splicemachine/spliceengine

- hbase_sql/src/main/java/com/splicemachine/stream/StreamListener.java
- pom.xml
There is a path where close() may not have been called which will leak Streams.
> SPLICE-696 Fixing Small Memory Leak in Spark Stream Processing

- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericStatementContext.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Row_IT.java
The code change is to fix two problems:
1) when a trigger throws an exception, we pop up all statement context for trigger on stack and clean them up. There could be more than one statement contexts because a trigger may fire another trigger for another table. Pop the stack until the parent statement is not in a trigger, which is the parent statement context(GenericStatementContext.java).
2) Always look at the context at the top of the stack(GenericLanguageConnectionContext.java).
> DB-5011: pop statement context properly when a trigger fails

- db-tools-ij/src/main/grammar/ij.jj
- db-tools-ij/src/main/resources/com/splicemachine/db/loc/toolsmessages.properties
- docs/architecture/ExplainTracePlan.tex
I removed the EXPLAINTRACE reference  from the ij.jj grammar , the reference in the help documentation, and messages properties.
Now when we type help in ij, there is no reference left to EXPLAINTRACE
> Bug Fixed SPLICE-701 : EXPLAINTRACE  obsolete when type help in ij.

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TableScanOperation.java
The issue was a simple issue of serialization. I just added the tableDisplayName in the readExternal and writeExternal in TableScanOperation
> Fixed SPLICE-703 : Null Name on UI for Query in the Dag Spark Visualizer

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/AggregateNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/RowIdIT.java
Throw an exception and return an error message to a client when an aggregate funciton is applied to a rowid column, instead of failing an assertion and dropping client connection.
> DB-4198:throw an exception when aggregate function is applied to rowid Column

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropTableConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/ConstraintConstantOperationIT.java
All objects defined on a table(such as indexes, constraints) are dropped before dropping a table. For any reasons, if an exception is thrown when dropping a table, the txn will be rolled back, and table definition is not changed on disk. However, the table object in cache may have been modified. This will cause erroneous behavior when the table is accessed again.
> SPLICE-114: clear table cache when dropping a table failed

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
Fixes two issues:
1) Pick up useSpark property in connection context
2) Serialize/deserialize explain plan when executing explain on spark, because it's stored in a ThreadLocal variable.
> SPLICE-136: fix explain for Spark

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/BadRecordsRecorder.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
Bad record accumulators create ".bad" files in <bad_record_directory>/.tmp directory but do not merge.
In the case where there's only one bad record accumulator, accumulator#addInPlace(BadRecordsRecorder r1, BadRecordsRecorder r2), which forwards to merge(), never gets called by spark.
Removed the merge. Now BadRecordRecorder writes to only its uniquely named file.
Tested on cluster with small (10 record) file and with TPCC 1000 where import date format was changed to force import errors.
See more details in https://splice.atlassian.net/browse/SPLICE-28
> SPLICE-28: bad file creation broken on hdfs

- db-engine/src/main/java/com/splicemachine/db/impl/ast/ColumnUtils.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_Join_IT.java
We weren't catching ColumnReference versions, assuming everything was a VirtualColumnNode instead. This corrects that and adds an IT to ensure the flattening works as desired.
> SPLICE-712: Adding additional source paths for ColumnReference

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
revert changes to spark.cleaner.ttl setting, because it did not fix DB-5252, but may cause long running job to fail.
> DB-5561: revert spark.cleaner.ttl setting

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/sequence/AbstractSequence.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/sequence/Sequence.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/sequence/SpliceSequenceIT.java
DataDictionaryImpl.peekAtSequence() tries to peek next sequence number from SequenceUpdater, which is obsolete. The code changes make it work by peeking SpliceSequence.
> SPLICE-128: Fix SYSCS_UTIL.SYSCS_PEEK_AT_SEQUENCE

- hbase_sql/src/main/java/com/splicemachine/hbase/BytesCopyTaskSplitter.java
- hbase_sql/src/main/java/com/splicemachine/hbase/RegionSizeEndpoint.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/AbstractSMInputFormat.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SubregionSplitter.java
- hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
- splice_protocol/src/main/protobuf/Splice.proto
This change makes sure we set start/stop keys properly on Spark scans when they are bounded, for instance when we have an inequality on an index access. Previously we would scan the whole region.
Furthermore, when computing cutpoints we didn't take into account the start/stop scan keys, so we could create more partitions than necessary that did no useful work.
> SPLICE-726 Set start/stop keys properly in Spark

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SortOperation.java
Should not return the operation if distinct is set to true but continue to traverse the execution tree.
> Fixed SPLICE-724 : ORDER BY with UNION ignored

- hbase_pipeline/pom.xml
- hbase_sql/pom.xml
- hbase_storage/pom.xml
Some exclusions were wrong (transposed artifactId/groupId) and some were missing. This caused the standalone version to sometimes fail to start, as reported on the user forum: http://community.splicemachine.com/community/forum/topic/getting-error-on-startup/
> SPLICE-731 Fix maven exclusions

- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PrimaryKeyIT.java
Modifying an IT to check for table and constraint names in error messages to avoid regressing in SPLICE-682.
> SPLICE-682: Adding IT check to make sure message is well formatted

- hbase_sql/hbase1.0.0.x/src/test/java/com/splicemachine/derby/impl/spark/WholeTextInputFormatTest.java
- hbase_sql/src/main/java/com/splicemachine/derby/impl/spark/WholeTextInputFormat.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/BadRecordsRecorder.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/FileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/StreamFileFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
- splice_machine/src/test/test-data/multiLineDirectory/mytable.dat
- splice_machine/src/test/test-data/multiLineDirectory/mytable1.dat
- splice_machine/src/test/test-data/multiLineDirectory/mytable2.dat
- splice_machine/src/test/test-data/multiLineDirectory/mytable3.dat
WholeTextInputFormat was only processing a single path out of a combined
list, which meant that multiple files were not being processed. This is
easily detected in a UT(WholeTextInputFormatTest), and corrected here.
It also includes an IT because why not.
I also included a few (minor) code cleanups, but it passes ITs on my box.
> SPLICE-739: Correcting WholeTextInputFormat.

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/ModifyColumnConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/DataDictionaryUtils.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Row_IT.java
Trying to drop a column with a trigger depending on that column will throw a error but behind the scene the column is effectively deleted and the table descriptor will become stall.
This fix makes sure we handling triggers and constraints before we effectively deleting the column.
> Fixed SPLICE-735

- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/hbase1.0.0.x/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
The current backup/restore is not efficient because it backup/restore one table a time. The code changes parallelize backup/restore by creating callables and submitting to ExecutorCompletionService.  This speeds up backup/restore by 3-4 times on bare splice db.
I include some other minor changes in the commit:
1) rename cancel_backup to syscs_cancel_backup for naming consistency.
2) Add an error message for backup cancelation.
2) code clean up.
**Note: please review code changes on both spliceengine and spliceengine_ee.
> DB-5595: Parallelize backup/restore

- splice_machine/src/test/java/com/splicemachine/derby/transactions/QueryTimeoutIT.java
Removing Ignore from test, making sure we can load the jar correctly,  adding to serial transactions since we are loading a jar.
> SPLICE-757 Removing Ignore from Timeout Test

- db-engine/pom.xml
- hbase_sql/pom.xml
- pom.xml
Removed hadoop-tools and hadoop-core, pulled in  hadoop-distcp and hadoop-common. Please also review https://github.com/splicemachine/spliceengine-ee/pull/3
> DB-5473: fix distcp dependencies

- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Limits.java
SPLICE-728: Making select column limit equal the table column limit. There isn't a test here because, well, it's a number change.
> SPLICE-728 Increasing limit for the max number of columns

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSparkKryoRegistrator.java
- hbase_sql/src/main/java/com/splicemachine/stream/KryoDecoder.java
- hbase_sql/src/main/java/com/splicemachine/stream/KryoEncoder.java
- hbase_sql/src/main/java/com/splicemachine/stream/ResultStreamer.java
- hbase_sql/src/main/java/com/splicemachine/stream/StreamListenerServer.java
- hbase_sql/src/main/java/com/splicemachine/stream/handlers/OpenHandler.java
- splice_encoding/src/main/java/com/splicemachine/utils/kryo/KryoPool.java
Use Kryo pools in result streamer   stream listener
Added Kryo Pool master
This version added  ThreadLocal to avoid race condition with multiple handlers used with Netty.
It should now use  different kryo objects by thread basis and then the kryo object will be return when the thread close and perform a clean of its ThreadLocal
>  SPLICE 741

- splice_encoding/src/main/java/com/splicemachine/storage/index/SparseBitIndex.java
- splice_encoding/src/test/java/com/splicemachine/storage/index/SparseBitIndexTest.java
It turns out that, in the (incredibly rare) situation where the bits in
a SparseBitIndex exactly line up with a byte boundary, SparseBitIndex
may end up over-estimating the number of bytes required by 1, which
results in a trailing 0. This trailing 0 can throw off deserialization
of that row, resulting in all kind of odd errors.
This ensures that the trailing zero is not present by dropping it if the
over-estimation happens, and adds a unit test to verify.
> SPLICE-816: Correcting error in SparseBitIndex

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/TableConstantOperationIT.java
Adding Text datatype so Spark JDBC lib works easily with Splice Machine.
> SPLICE-835 Mapping TEXT column creation to CLOB

- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
Add a parameter splice.backup.parallelism to allow a user to tune backup parallelism.
> DB-5620: add splice.backup.parallelism parameter

- hbase_sql/src/main/java/com/splicemachine/olap/AsyncOlapNIOLayer.java
- hbase_sql/src/main/java/com/splicemachine/olap/MappedJobRegistry.java
- hbase_sql/src/main/java/com/splicemachine/olap/OlapJobStatus.java
- hbase_sql/src/main/java/com/splicemachine/olap/OlapServer.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SIConfigurations.java
This makes the olap server tick time configurable, so that we can wait longer if we need to.
> SPLICE-838: Making olap server tick time configurable

- splice_machine/src/main/java/com/splicemachine/derby/stream/function/AntiJoinRestrictionFlatMapFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/CogroupAntiJoinRestrictionFlatMapFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/CogroupInnerJoinRestrictionFlatMapFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/CogroupOuterJoinRestrictionFlatMapFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ConcatenatedIterable.java
The implementation of cogrouping was (accidentally?) recursive: it
created a wrapper Iterable around each pair of iterables, resulting in a
wrapper Iterable around each row on the left-hand side. If you get
enough such rows, you'll blow off with a StackOverflowError
(SPLICE-836).
This removes the recursive implementation and uses an iterative approach
instead by flattening out the excess Iterables and using just a single
while() loop. This should have the added benefit of reducing extraneous
object creation, reducing memory overhead and improving performance (in
a pretty small way, to be sure, but still).
> SPLICE-836: Removing recursive cogroups.

- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/StatisticsAdminIT.java
This is the 2.0 version of SPLICE-856. 
Updates push multiple versions into a cell. When scanning, HBase
defaults to only scanning a single version of the cell. Thus, if you do
an update, you have to make sure that any subsequent scans are using
non-default hbase behavior (i.e. reading all versions). There is a
method on DataScan to provide this, but statistics collection was not
calling it. This resulted in statistics collections only reading the
updates, and not the underlying insertions (or past updates), instead of
constructing the entire row.
This corrects that issue, and adds an IT for verification. Note that the
IT would only fail in the HBase architecture, as the memory architecture
ignores version limits.
> 2.0 version of SPLICE-856 fix

- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/StatisticsAdminIT.java
Updates push multiple versions into a cell. When scanning, HBase
defaults to only scanning a single version of the cell. Thus, if you do
an update, you have to make sure that any subsequent scans are using
non-default hbase behavior (i.e. reading all versions). There is a
method on DataScan to provide this, but statistics collection was not
calling it. This resulted in statistics collections only reading the
updates, and not the underlying insertions (or past updates), instead of
constructing the entire row.
This corrects that issue, and adds an IT for verification. Note that the
IT would only fail in the HBase architecture, as the memory architecture
ignores version limits.
> SPLICE-856: Correcting version read issue.

- hbase_sql/src/main/java/com/splicemachine/hbase/BytesCopyTaskSplitter.java
- hbase_sql/src/main/java/com/splicemachine/hbase/RegionSizeEndpoint.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/AbstractSMInputFormat.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SubregionSplitter.java
- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
- splice_protocol/src/main/protobuf/Splice.proto
Currently, spark would scan the entire Region even on a small range scan.  Daniel worked on this a while back but introduced a bug by throwing exceptions where a retry was needed.  Nice work Daniel...
> Splice 726 - More Efficient Cutpoints for Spark

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
DB-5550 for branch-2.0, this config opting is for "cluster" mode we run in "client" mode.
> DB-5550 - removing unused parameter from SpliceSpark default config

- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HBasePipelineEnvironment.java
- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/SpliceIndexEndpoint.java
- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/SpliceIndexObserver.java
- hbase_pipeline/src/test/java/com/splicemachine/pipeline/testsetup/HPipelineTestEnv.java
- hbase_sql/src/main/java/com/splicemachine/compactions/PoolSlotBooker.java
- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/TxnLifecycleEndpoint.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/region/RegionServerControl.java
- mem_pipeline/src/main/java/com/splicemachine/pipeline/MPipelineEnv.java
- mem_storage/src/main/java/com/splicemachine/storage/MServerControl.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/MappedPipelineFactory.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/PipelineDriver.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/PipelineEnvironment.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/PipelineWriter.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/api/WritePipelineFactory.java
- splice_access_api/src/main/java/com/splicemachine/access/api/ServerControl.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/TxnRegion.java
- splice_si_api/src/test/java/com/splicemachine/si/testenv/TestServerControl.java
It turns out that a Region is not to be considered "available" until it
is added to the HBase RegionServerServices, instead of when a
coprocessor start() is called. For most operations this doesn't matter,
because RegionServerServices is where the HBase network layer determines
if the Region is present or not; if you sent an operation to that region
and it wasn't in RegionServerServices, you'd get a
NotServingRegionException instead of allowing through an operation.
However, in the Write Pipeline we send writes to multiple regions
simultaneously in a single network call (if there's a network call at
all--in some cases we send the data directly to the same JVM where we
are writing data). Therefore, we allow the possibility of bypassing the
network stack and its protections.
When operating …
> SPLICE-868: Correcting Race condition around splits.

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/HregionDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/SplitRegionScannerIT.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/SplitRegionScannerStressIT.java
- hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
Make sure we don't retry indefinitely looking for subpartitions and raise an exception if we ever construct a Scan that doesn't make sense in SMRecordReaderImpl.
> SPLICE-886 Don't wait indefinetely for subpartitions

- hbase_sql/hbase1.0.0.x/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.0.0/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
If the EngineDriver has not yet booted, then we can't use Spark for
compactions (because we don't know where the OlapServer is). This
ensures that we default back to HBase's default compaction strategy when
a compaction is requested during this time, rather than failing.
> SPLICE-892: Correcting NPE during boot compactions.

- hbase_sql/src/main/java/com/splicemachine/olap/AsyncOlapNIOLayer.java
- hbase_sql/src/main/java/com/splicemachine/olap/MappedJobRegistry.java
- hbase_sql/src/main/java/com/splicemachine/olap/OlapJobStatus.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SIConfigurations.java
Add logging when cancelling an Olap job
I've increased the Phi failure detector's threshold since 0.1 seems to be too conservative. 
As taken from http://doc.akka.io/docs/akka/snapshot/scala/remoting.html and http://fubica.lsd.ufcg.edu.br/hp/cursos/cfsc/papers/hayashibara04theaccrual.pdf a more reasonable threshold seems to be 10. We can revisit this based on the logged information when cancelling running jobs.
> SPLICE-838 Increase OlapClient timeout

- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
setting default password lifetime to 0, aka forever
> DB-4696 - setting default native pasword expiration to never

- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java
This fixes some test failures on the recent builds. The preconditions were wrong, sometimes we build scans with a startRow greater than a stopRow, for instance if we do
`create table a ( i int primary key);
select * from a where i > 3 and i < 1;`
We can't raise an exception in that case.
> SPLICE-909 Remove wrong preconditions

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/JoinOperation.java
Little nit, removing object creation on a per row basis.
> SPLICE-919 Remove Object Creation from Join Operation

- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLClob.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/sequence/SpliceSequence.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnOperationFactory.java
SQLClob.readExternal still uses read(), complicated code path
Should I try to fix SQLClob.readExternal too? I'm not so sure about the invariants there, or whether that method is used at all. If we assume the header will always have a 10.5 format we can just read 5 bytes and be done with it.
> SPLICE-915 Don't expect read() to return more than 1 byte

- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
The important change is line 95, previously if we had an unbounded scan we wouldn't bound the cutpoint search, meaning we could add cutpoints outside the region in case of a recent split, for instance.
> SPLICE-897 Limit cutpoints when scans are unbounded

- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/GenericQualifier.java
Removing the continued reflection calls.  This was there due to issues in our old task framework.
> SPLICE-923 Fixing GenericQualifier.getOrderable to be more performant

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/IndexConstantOperation.java
Spark was failing to access Accumulators because the SparkOperationContext wasn't being properly set up.
> SPLICE-869 Make sure operation context is properly setup on index job

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
Timestamp column for system tables is encoded by V1 serializer, but is decoded by v2 serializer. In general, you get incorrect values for a timestamp column if you do a select on the column. Fix this problem by using a V1 serializer to decode system tables.
> DB-5633: fix timestamp column for system tables

- hbase_sql/src/main/java/com/splicemachine/derby/impl/spark/WholeTextInputFormat.java
Files processed by WholeTextInputFormat should be handled as a whole, we can't split them into blocks.
>  SPLICE-932 Make WholeTextInputFormat never split a file

- hbase_sql/src/main/java/com/splicemachine/compactions/PlaceholderTask.java
Since we are cancelling the job anyway it goes directly to the Failed jobs list, no need to raise exceptions and pollute the logs.
> SPLICE-934 Remove exceptions from PoolSlotBooker

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ScanOperation.java
This is causing SelfInsertIT to add an extra row.  This could hit us on Batch NLJ...
> SPLICE-942 SmallScanners bug in HBase where they return extra row

- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLChar.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/JoinWithFunctionIT.java
In EntryPredicateFilter.java; line 79  we remove 1 to the limit.
When we build the Table Hash Key in a join , we end up with a hash key desalign between the left operand and the right operand.
> Fixed SPLICE-742

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/depend/BasicDependency.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/depend/BasicDependencyManager.java
Invalidate statements when pushed out of the statement cache and store
only weak references on the DependencyManager
I've tested this running a script similar to what Gene uploaded concurrently with an IT run. A test for it will be added to the QA runs.
Tested it against JDK 7 & 8.
> SPLICE-950 Make activation classes eligible for GC

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SetOpOperationIT.java
We do not currently support 
intersect all,
except all 
but we do support
intersect,
except.
This commit attempts to straighten that out.
> SPLICE-948 Intersect Not Implemented Error on the wrong case

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SetOpOperationIT.java
We do not currently support  
intersect all,
 except all  
but we do support
 intersect,
 except.
This commit attempts to straighten that out.  Branch-2.0 version.
> SPLICE-948 Intersect Error Not Implemented on the wrong case

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/batchonce/BatchOnceOperation.java
BatchOnceOperation pulls a batch of rows to a buffer until the buffer is full (by default 50000). There is a bug that caused the operation to lose one row for each batch, because it pulls a row first and then check whether the buffer is full. If the buffer is full, the row that it just pulled will be ignored. 
The fix is very straightforward: check whether the buffer is full first. If not full, pull a row and buffer it.
> SPLICE-954: fix an issue with BatchOnceOperation

- hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
We were leaking resources in StoreScanner, which MemStoreFlushAwareScanner inherits from. We must close it properly.
> SPLICE-960 close parent scanner

- hbase_storage/src/main/java/com/splicemachine/access/hbase/H10PartitionAdmin.java
- mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MEnginePartitionAdmin.java
- mem_storage/src/main/java/com/splicemachine/storage/MPartitionFactory.java
- splice_access_api/src/main/java/com/splicemachine/access/api/PartitionAdmin.java
Filter out temporary tables for backup.
Please also review https://github.com/splicemachine/spliceengine-ee/pull/9
> DB-5638: do not backup temporary tables

- assembly/pom.xml
- db-engine/pom.xml
- hbase_sql/pom.xml
- pom.xml
- utilities/pom.xml
- resolves some io.netty startup issues
- include akka-remote dependency in our assembly since it was pulled out of Spark 2.0.0
- make Scala binary version a property instead of hard-coding
> SPLICE-938 : Splice Machine 3.0 on a cluster with Spark 2.0.0

- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HBasePipelineEnvironment.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/PipelineDriver.java
- splice_machine/src/main/java/com/splicemachine/EngineDriver.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLDriver.java
I got an NPE while accessing these fields a couple of times during the boot process. We might be accessing the field before initializing it, but if we are sharing it across threads it has to be volatile or have a synchronized access, I opted for the former.
> SPLICE-993 Make shared INSTANCE fields volatile

- splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/load/SpliceCsvReader.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/load/SpliceCsvTokenizer.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/AbstractFileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/FileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/MutableCSVTokenizer.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/QuoteTrackingTokenizer.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/StreamFileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/BooleanList.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/ImportDefaultValueIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/ImportNullityIT.java
- splice_machine/src/test/java/com/splicemachine/derby/stream/function/QuoteTrackingTokenizerTest.java
- splice_machine/src/test/test-data/import/nullity.csv
It turns out, Imports are really just inserts over subselects; to
support default value during the import, we can just re-write the import
SQL clauses to include a case statement which replaces null entries with
default values.
However, in order to support this case statement effectively, we also
need to make sure that we properly treat NULL strings within the parsing
stage. Per customer request, we treat null, NULL, nUll, etc. as actually
being null; we treat "null" as the string 'null'.
An IT was added to confirm overall behavior.
> SPLICE-983: Carrying defaults through imports.

- splice_machine/src/main/java/com/splicemachine/derby/stream/function/MergeAllAggregatesFunction.java
Small optimization that removes a few seconds from TPCH1, query 1.  
aggregator.isInitialized(?) is a bit slow especially when the query has a decent number of aggregates.
> SPLICE-1034 Removing expensive checks when possible, incremental move

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
Pulling up hbase.regionserver.kerberos.principal and hbase.regionserver.keytab.file from HBase configuration
and set spark.yarn.keytab and spark.yarn.principal for Spark
I have tested manually the settings and it works.
>  fix DB-5653

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/AggregateDefinition.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/WindowFunctionVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/AggregateNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowResultSetNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WrappedAggregateFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/WindowFunctionInfo.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkPairDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkUtils.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkWindow.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/DataFrameIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/WindowOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregatorImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/OperationContext.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
Added a window method support in com.splicemachine.derby.stream.iapi.DataSet
and pushed down the execution implementation in both engines.
Ignored tests with a decimal precision difference between current implementation and Spark.
This is going to be fixed afterward.
> WIndow Functions on top of Dataset.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ScanSelectivityIT.java
The optimizer did not expect a scan qualifier may have a CastNode, so it did not look down to CastNode.
Fixed and added an IT.
> SPLICE-1081: calculate statistics correctly for scan qualifier with a cast

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WithStatementIT.java
Handles the "(" and ")" properly so with clauses can allow order bys...
> SPLICE-966 Fixing With Clause omissions

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/JoinIT.java
During subquery fattening, reference table map of the subquery was not propagated upwards. This information is needed for hash join with a function applied to join column. Missing this information will cause the result column of join  out of order.
> SPLICE-1072: propogate table referece map from subquery

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/JoinIT.java
During subquery fattening, reference table map of the subquery was not propagated upwards. This information is needed for hash join with a function applied to join column. Missing this information will cause the result column of join  out of order.
> SPLICE-1072: propogate table referece map from subquery(for 2.0)

- splice_encoding/src/main/java/com/splicemachine/storage/EntryDecoder.java
- splice_encoding/src/main/java/com/splicemachine/storage/index/SparseBitIndex.java
- splice_encoding/src/test/java/com/splicemachine/storage/EntryDecoderTest.java
- splice_encoding/src/test/java/com/splicemachine/storage/index/SparseBitIndexTest.java
2.0.x version of DB-5669 fix. Identical fix to master branch.
> DB-5669: Correcting SparseBitIndex correctness issues.

- db-engine/src/main/java/com/splicemachine/db/iapi/stats/FakePartitionStatisticsImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/actions/index/IndexIT.java
Default cardinality to row count will result in a very low selectivity for nested loop join predicate. Thus nestedloop join will be more likely picked than other join strategies. Reset cardinality to 0, the selectivity of join predicate will be 0.1. This was the behavior before John's code change to statistics.
> SPLICE-1101: set cardinality to 0 when there is no statistics

- db-engine/src/main/java/com/splicemachine/db/impl/ast/FindHashJoinColumns.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/RepeatedPredicateVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CastNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumn.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TableScanOperationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/JoinIT.java
Fixes two customer bugs:
DB-5671: correct the result column order for hash join whose join column is applied by a function. We used to rely on table number and table reference map to determine if a column is from left or right child result set, but these information can be missing. It's more reliable to lookup source result set of a result column from left/right subtree to determine whether the column is from left/right child result set.
DB-5672: an optimization to extract out duplicate predicates from where clause does not work in general. The query that can be optimized is rarely seen, but it can cause problem if there are duplicate predicates. Disable it for now.
> DB-5671 & DB-5672

- db-engine/src/main/java/com/splicemachine/db/impl/ast/FindHashJoinColumns.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/RepeatedPredicateVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CastNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumn.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TableScanOperationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/JoinIT.java
Fixes two customer bugs:
DB-5671: correct the result column order for hash join whose join column is applied by a function. We used to rely on table number and table reference map to determine if a column is from left or right child result set, but these information can be missing. It's more reliable to lookup source result set of a result column from left/right subtree to determine whether the column is from left/right child result set.
DB-5672: an optimization to extract out duplicate predicates from where clause does not work in general. The query that can be optimized is rarely seen, but it can cause problem if there are duplicate predicates. Disable it for now.
> DB-5671 & DB-5672 for 2.0

- assembly/pom.xml
Adding for assembly so Parquet can run on parcels.  We thought this was provided by Hadoop and we were wrong...
> SPLICE-1145 Adding logging required for parquet reading on a cluster.

- splice_machine/pom.xml
Attempting to remove this issue from HDP logs...
```
============= begin nested exception, level (1) ===========
java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.MethodVisitor, but class was expected
at com.esotericsoftware.reflectasm.ConstructorAccess.insertConstructor(ConstructorAccess.java:124)
at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:95)
at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1233)
at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1078)
at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1087)
at com.esotericsoftware.kryo.serializers.CollectionSerializer.create(CollectionSerializer.java:107)
at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(C …
```
> SPLICE-1146 Making sure we are only using shaded kryo

- hbase_sql/src/main/java/com/splicemachine/stream/output/SpliceOutputCommitter.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/writehandler/PartitionWriteHandler.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Row_IT.java
Import transaction should be additive, so that write-write conflicts between sibling transaction can be handled as primary key/unique constraints violations.
Report all constraint violations (per Daniel's comments)
I intended to add ITs similar to Daniel's except some more assertions. Since Daniel will check in IT, I will modify after his checkin.
> SPLICE-1129: make import transaction additive

- hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatform.java
Fix 'master not started after 30 seconds' errors when restarting standalone quickly.
> SPLICE-1186 Remove ZK nodes on standalone startup

- hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java
- hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java
- hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java
- hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java
- hbase_storage/src/main/java/com/splicemachine/access/HConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
Adding the ability to perform HBase block encoding via configuration.  Once we get results, good possibility FAST_DIFF becomes are default.
> SPLICE-1216 Block Coding Configurability

- db-engine/src/main/java/com/splicemachine/db/iapi/stats/StatsBoundaryDataValueDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/DataType.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/DataValueDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLClob.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLTime.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/ValueRow.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/test/java/com/splicemachine/homeless/TestUtils.java
Fix for Spark to handle time and clob data types with tests.
> SPLICE-1180 Fixing Time and Clob Data Types

- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
Increasing Default Table Cache Descriptor Size to make sure we have a bit of overhead over dictionary tables.
> SPLICE-1267

- hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
Increasing the ipc pool size under the covers in hbase for tests and the per region tasks.
> SPLICE-1268 Modifying Default Test Config

- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/ConglomerateController.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceController.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/hbase/HBaseRowLocation.java
Inside the dictionary (not query stack), we currently do our index lookups from an index scan serially .  This will perform a single batch multi-get to reduce RPC calls.
> SPLICE-1270 Fixing Dictionary Index Lookup Logic

- db-engine/src/main/java/com/splicemachine/db/iapi/stats/StatsBoundaryDataValueDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/DataType.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/DataValueDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLClob.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLSmallint.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLTime.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/ValueRow.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/test/java/com/splicemachine/homeless/TestUtils.java
Fixes places where the DataValueDescriptor#getObject() does not allign to Spark types.
> SPLICE-1180 Fixing Time, Small int, and Clob data types

- assembly/mapr5.1.0/src/main/resources/conf/hbase-env.sh.patch
- assembly/mapr5.1.0/src/main/resources/conf/hbase-env.sh.secure.patch
- assembly/mapr5.1.0/src/main/resources/conf/yarn-site.xml.patch
- assembly/mapr5.1.0/src/main/resources/conf/yarn-site.xml.secure.patch
- assembly/mapr5.2.0/src/main/resources/conf/hbase-env.sh.patch
- assembly/mapr5.2.0/src/main/resources/conf/hbase-env.sh.secure.patch
- assembly/mapr5.2.0/src/main/resources/conf/yarn-site.xml.patch
- assembly/mapr5.2.0/src/main/resources/conf/yarn-site.xml.secure.patch
- assembly/pom.xml
Changes shading so we're not picking up Spark 2.x; should fix codegen. I'll work on CDH/HDP/MapR cluster config changes and get docs tickets generated once this is in.
> SPLICE-1273

- hbase_storage/src/main/java/com/splicemachine/storage/HLock.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetWriter.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
Fix two issues that caused import to report wrong failed rows
1) Take a write row lock(instead of read lock) before writing. A read lock may fail to detect duplicate rows
2) For ControlDatasetWriter, report failed rows after flushing write buffer.
> SPLICE-1177: Correct failed rows for import

- hbase_sql/pom.xml
- splice_machine/src/test/java/com/splicemachine/test/RestoreTest.java
Fix hadoop-client dependencies for cdh5.8.0. Run RestoreIT at the end of ITs.
Please also review pull request at spliceengine-ee.
> DB-5678: get right version of hadoop-client-core

- db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java
- db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAProtocolException.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/DRDAConstants.java
- splice_machine/pom.xml
- splice_machine/src/test/java/com/splicemachine/derby/client/TestUnknownClient.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceNetConnection.java
Added a check for odbc driver so that only splice odbc driver is allowed to proceed. Tested with our odbc and jdbc app, and odbc app with Easysoft derby odbc driver which would now fail to connect.
**Note: the only new change is in DRDAConnThread
> Splice 976 v1

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java
Use per Kb in calculation instead of 100. 
FYI, I am also running tpcds explain workload plans to see if we are regressing anywhere far too much to ensure the sanity. There are bunch of small changes in planner related bugs that John has pointed out the changes.
> SPLICE-1209: pick up a remote cost per Kb

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectivityUtil.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/HalfMergeSortJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java
It seems since 1.5 release we were multiplying the mergeSortJoin cost by3x since it was being replicated three times. It does not make sense now to do so since that is not the case, so adjusting the cost by removing that factor.
Tested the plans with the tpcds workload query plan for sanity.
> SPLICE-1208: fix mergeSortJoin overestimate by 3x

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
By extra dup line, it was increasing the NLJ cost higher.
> SPLICE-1210: remove dup of setRemoteCost

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/TempGroupedAggregateCostController.java
> SPLICE-1295: remove the legacy costing that involvs hbase temp table strategy

- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/OperationConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
- splice_machine/src/main/java/com/splicemachine/EngineDriver.java
- splice_machine/src/main/java/com/splicemachine/derby/lifecycle/EngineLifecycleService.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJoinFunction.java
A global thread pool is created. The default maximum number of threads in the pool is 256.
The pool is used in NLJoinFunction to avoid new thread pool creation on every invocation.
> Splice 1325

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/CreateExternalTableJob.java
Creating External Table - ERROR EXT22: Cannot write at the location
Replaced this
SIDriver.driver().fileSystem().getPath(request.getLocation()).toFile().exists())
by this
SIDriver.driver().fileSystem().getInfo(request.getLocation()).isWritable()
There is no additional tests as the ones written before cover the use cases but this patch change the code to make sure it use the hadoop api instead of java library....
> Fix SPLICE-1333 : 

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDescriptorGenerator.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/TableDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSTABLESRowFactory.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CreateViewNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NewInvocationNode.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateAliasConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreatePinConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateViewConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropAliasConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
- Added a IS_PINNED column in sys tables descriptor.
- Added a job to un cache the pin table
- Remove the pin table from memory when drop table is the table is pinned.
It is difficult to add news IT because DROP TABLE doesn't return any meaningful information and it is difficult to do that in the scope of that jira. I will create a JIRA to add more meaningful informations which will help to add ITs.
> SPLICE-1122:	Deleting a table needs to remove the pin for the table.

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/batchonce/BatchOnceOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/BatchOnceOperationIT.java
serialize column positions for correlated subquery, so that BatchOnceOperation can initialize correctly.
> SPLICE-1349: serialize and initialize BatchOnceOperation correctly

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/SpliceCreateTableOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/CreateTableWithDataIT.java
Quote table names for CTAS to respect table/schema name case sensitivity.
> SPLICE-8: make CTAS work with case sensitive names

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeDerbyScanInformation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperatonIT.java
Need to fence the populateQualifier with more null checks on the probeValue. Tested with various tests manually on multiple size tables/indexes with IN clause combination.
> SPLICE-1323: Fix NPE for in-list caluse on spark side

- hbase_sql/src/main/java/com/splicemachine/stream/QueryJob.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/serialization/SpliceObserverInstructions.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
The proposed fix moves pushContext(statementContext) from SpliceObserverInstructions.ActivationContext.populateActivation() and the matching popContext() from QueryJob.call() to ActivationHolder so that they are either invoked or not invoked together.
The assumption is that ActivationHolder.reinitialize() must be matched by ActivationHolder.close() unlike ActivationHolder.init(), which closes underlying SpliceTransactionResourceImpl, and thus pops all contexts and context managers, itself.
> Splice-1329 Memory leak in SpliceObserverInstructions

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/stats/StatsCollectionJob.java
- re-implemented readTextFile in SparkDataSetProcessor to be consistent with the others methods of the class. 
I have a jira to clean that class and have that merged with SpliceFileVTI
- Added to test to make sure data and small datatype work with csv
> SPLICE-1169 : Fix External Table with Csv - Text FIles

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
Correct table number of a predicate's column reference, so that predicate can be pushed down from JoinNode to base table.
> DB-5743: fix table number to allow predicate push down

- splice_machine/src/main/java/com/splicemachine/derby/stream/control/BadRecordsRecorder.java
Change bad file name postfix from a hash code to a UUID, because hash code can collide for large number of import tasks.
> DB-5792: avoid bad file naming collision

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumn.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/OuterJoinIT.java
for the chained outer join queries, this was causing NPE, getTableNumber() should return -1 if it cannot determine the tablenumber.
> SPLICE-737: getTableNumber should return -1 if it cannot be determined

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDescriptorGenerator.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/TableDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSTABLESRowFactory.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CreateViewNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NewInvocationNode.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateAliasConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreatePinConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateViewConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropAliasConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
We need to do the following...
When a table is pinned in memory, the dictionary should be modified to say the table is in memory.  We should then remove the pin when we delete the table from the dictionary.
> SPLICE-1122 -backport

- hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
I'm changing two configuration properties in standalone setup:
hbase.regionserver.handler.count = 100 - number of threads (handlers) in the default executor;
hbase.regionserver.metahandler.count = 100 - number of threads in the priority executor.
> SPLICE-1379 The number of threads in the HBase priority executor is low

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DeleteNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InsertNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UpdateNode.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java
Fixed the issues :
INSERT INTO the pinned view reports success and inserts into the original table (but not the pinned view). This should not be allowed.
DELETE FROM the pinned view reports '0 rows inserted/updated/deleted', but does not display an error message, which is misleading
UPDATE on a pinned view generates a network protocol error and bombs Splice
> SPLICE-1370 ; INSERT, UPDATE, DELETE error message for pin tables

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DeleteNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InsertNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UpdateNode.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java
INSERT INTO the pinned view reports success and inserts into the original table (but not the pinned view). This should not be allowed.
DELETE FROM the pinned view reports '0 rows inserted/updated/deleted', but does not display an error message, which is misleading
UPDATE on a pinned view generates a network protocol error and bombs Splice
> SPLICE-1370 backport : Fixed the issues with INSERT, DELETE, UPDATE and pin table

- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextManager.java
- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
- splice_machine/src/main/java/com/splicemachine/derby/serialization/SpliceObserverInstructions.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
I undo all changes implemented for SPLICE-1329 (memory leak in internalConnection) and SPLICE-1362 (concurrent access to internalConnection) and provide a new fix for the original problem: nested connections are not created on Spark.
> DB-5789 redo nested connection on Spark fix

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DeleteNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InsertNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UpdateNode.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java
Fixed the issues :
INSERT INTO the pinned view reports success and inserts into the original table (but not the pinned view). This should not be allowed.
DELETE FROM the pinned view reports '0 rows inserted/updated/deleted', but does not display an error message, which is misleading
UPDATE on a pinned view generates a network protocol error and bombs Splice
> SPLICE-1370 ; INSERT, UPDATE, DELETE error message for pin tables -approved

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
re enabled :
com.splicemachine.derby.impl.sql.execute.operations.ExternalTableIT.testWriteReadFromPartitionedORCExternalTable	2.9 sec	2
com.splicemachine.derby.impl.sql.execute.operations.ExternalTableIT.testWriteReadFromSimpleORCExternalTable
The tests work just fine.
> SPLICE-1128 ; trivial - please merge

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectivityUtil.java
just taking out open/close latency cost which is already factored in transfer cost.
> SPLICE-1211: open and close latency calculated twice for NLJ

- db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java
Fixing a regular expression performance issue for Timestamp.  Just a quick one I saw while looking at encoding.  The fix is covered by anywhere Timestamps are returned in JDBC...
> SPLICE-1410 Make the compilation of the pattern static

- hbase_storage/src/main/java/com/splicemachine/access/hbase/H10PartitionAdmin.java
- mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MEnginePartitionAdmin.java
- mem_storage/src/main/java/com/splicemachine/storage/MPartitionFactory.java
- splice_access_api/src/main/java/com/splicemachine/access/api/PartitionAdmin.java
backport a fix to branch-2.0. It should be done a while ago, but I only found out today.
> DB-5638: do not backup temporary tables(backport to 2.0)

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/ExternalTableSystemProcedures.java
Corrected multiples issues:
1) remove 3th arg : CALL SYSCS_UTIL.SYSCS_REFRESH_EXTERNAL_TABLE('APP', 'myTable', rs);
2) check for table not found.
> SPLICE-1387 backport branch 2.5

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
This visitor does a lot of work especially on queries with many joins at the FromTable.  Not needed anymore.
> SPLICE-1424 Removing Unneeded Visitor from FromTable

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/CreateExternalTableJob.java
- Moved the logic of checking if a file exist outside of the job to avoid all the exception wrapping
> SPLICE-1258 : Move logic  outside of Spark Job

- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HBasePipelineEnvironment.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HBaseSIEnvironment.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- mem_pipeline/src/main/java/com/splicemachine/pipeline/MPipelineEnv.java
- mem_storage/src/main/java/com/splicemachine/si/MemSIEnvironment.java
- mem_storage/src/main/java/com/splicemachine/storage/MemFileSystem.java
- splice_access_api/src/main/java/com/splicemachine/access/api/DistributedFileSystem.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportFile.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/BadRecordsRecorder.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIDriver.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIEnvironment.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/TestingFileSystem.java
We were mixing APIs at different places, sometimes using the local filesystem and sometimes the correct filesystem.
I also removed a bunch of dangerous APIs such as SIDriver.driver().fileSystem() and made DistributedFilesystem not extend FileSystemProvider.
Tested this on a MapR cluster, the original test case passes, both running on control or Spark. I tested other filesystems (webhdfs) and exports. I didn't test backups/restores.
This fixes SPLICE-21 also which is the same issue.
> DB-5469 Fix filesystem code (master)

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropPinConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/DropPinJob.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/RemoteDropPinJob.java
Make sure the "unpinning" from spark happens on the OlapServer
Update system table when unpinning
I verified it on a cluster
> SPLICE-1433 Fix unpin feature

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
* SPLICE-1424 Removing Unneeded Visitor from FromTable
* SPLICE-1424 Deleted vs. commenting out
Already committed to master, backporting to 2.5.
> SPLICE-1424 Removing Unneeded Visitor from FromTable (#480)

- splice_machine/src/main/java/com/splicemachine/derby/serialization/SpliceObserverInstructions.java
- splice_machine/src/test/java/com/splicemachine/derby/serialization/ActivationSerializerTest.java
Allows for arbitrary statement length vs. putting a UTF serde limit on it.
> SPLICE-1478 Fixing Statement Limits

- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/InsertDataSetWriter.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/BadRecordsRecorder.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetWriter.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlOperationContext.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/OperationContext.java
Change the message for import bad file from some like:
ERROR SE009: Too many bad records in import, please check bad records file /data/import_test_data/bad/nulls4.csv.bad
to
ERROR SE009: Too many bad records in import, please check bad records in directory /data/import_test_data/bad
> SPLICE-1423: clean up import error messages for bad file

- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/StoreCostControllerImpl.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SelectivityIT.java
For a column with all null values, let its nullSelectivity slightly less than 1 to prevent nonnull selectivity from being 0.
> SPLICE-1098: prevent nonnull selectivity from being 0

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OrderByColumn.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumn.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Table_IT.java
Order by column in subquery being not projected in the subquery select list could get resolved during bind time for the outer query, which however is not in scope for the outer query and so it should be errored out. Compared the semantics with mysql which supports order by in the subquery, which does the similar error-out.
(Ran full cdh profile regression suite)
> SPLICE-77: order by column in subquery not projected should not be resolved

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
- hbase_sql/src/main/java/com/splicemachine/stream/StreamableRDD.java
- hbase_sql/src/test/java/com/splicemachine/derby/stream/spark/SMOutputFormatTest.java
- hbase_sql/src/test/java/com/splicemachine/derby/stream/spark/SparkDataSetTest.java
- hbase_sql/src/test/java/com/splicemachine/derby/stream/spark/SparkPairDataSetTest.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/DataFrameIT.java
- hbase_sql/src/test/java/com/splicemachine/stream/StreamableRDDTest.java
- hbase_sql/src/test/java/com/splicemachine/stream/StreamableRDDTest_Failures.java
Ignore DataFrameIT for now since it's creating a local SparkContext to convert a
resultset into a DF, and it breaks with these protections.
> SPLICE-1448 Make sure SpliceSpark.getContext/Session isn't misused (master)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/execute/ResultSetFactory.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InsertNode.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/SIObserver.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/PartitionWritePipeline.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/callbuffer/PartitionBuffer.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/callbuffer/PipingCallBuffer.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/client/BulkWrite.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/client/PipelineEncoding.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/config/BaseWriteConfiguration.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/config/ForwardingWriteConfiguration.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/config/WriteConfiguration.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/context/PipelineWriteContext.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/context/WriteContext.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/context/WriteNode.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/contextfactory/LocalWriteContextFactory.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/contextfactory/WriteContextFactory.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/writehandler/PartitionWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/SpliceKryoRegistry.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/SpliceGenericResultSetFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/output/PermissiveInsertWriteConfiguration.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/output/insert/InsertPipelineWriter.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsUnsafeImportIT.java
- splice_si_api/src/main/java/com/splicemachine/si/api/server/TransactionalRegion.java
- splice_si_api/src/main/java/com/splicemachine/si/api/server/Transactor.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/TxnRegion.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactor.java
Limitations:
- It only skips conflict detection on base table, support for indexes will be added later
- It skips PK check constraints
Added a new import procedure that uses this flag: IMPORT_DATA_UNSAFE() with the same parameters as the existing one.
> SPLICE-1497 Add flag for inserts to skip conflict detection 

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ScanSelectivityIT.java
This one old commit reverted due to intermittent IT failure, debugged and cleaned IT.
> SPLICE-1294: Poor Costing when first part of PK is not = (master)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ScanSelectivityIT.java
This one old commit reverted due to intermittent IT failure, debugged through and cleaned the test.
> SPLICE-1294: Poor Costing when first part of PK is not =

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ScanSelectivityIT.java
> SPLICE-1294: Poor Costing when first part of PK is not = (2.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNodeList.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/InListMultiprobeIT.java
Multi-probe index scan was giving wrong answer due to duplicates in the in list, we should have eliminated it before we move on.
> Splice-1533: eliminate duplicates in the IN list

- hbase_sql/hbase1.0.0.x/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.0.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
- splice_protocol/src/main/protobuf/Splice.proto
Address a couple of backup issues in this pull request.
Used wrong end key to probe if a region is ready for backup. This caused backup to hang in Cetera's cluster
When backup is done, marked wrong znode to indicate backup is complete. This can block flush, compaction and split.
Set correct hbase.rootdir for spark backup task. Otherwise, incorrect default hbase root dir may be used to create HFileLink to referenced parent file.
Fix an issue in BackupObserverEndpoint that can cause deadlock.
Add more tracing for diagnosis.
Moderator - Please remember to merge pull request from ee branch together with this one
> DB-5876: Fix a couple issues that cause backup to hang(2.5)

- hbase_sql/hbase1.0.0.x/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.0.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
- splice_protocol/src/main/protobuf/Splice.proto
Address a couple of backup issues in this pull request.
Used wrong end key to probe if a region is ready for backup. This caused backup to hang in Cetera's cluster
When backup is done, marked wrong znode to indicate backup is complete. This can block flush, compaction and split.
Set correct hbase.rootdir for spark backup task. Otherwise, incorrect default hbase root dir may be used to create HFileLink to referenced parent file.
Fix an issue in BackupObserverEndpoint that can cause deadlock.
Add more tracing for diagnosis.
**Moderator - Please remember to merge pull request from ee branch together with this one**
> DB-5876: Fix a couple of problems that can cause backup to hang(for 2.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNodeList.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/InListMultiprobeIT.java
Two fixes related to IN-list and multi-probe index scan:
- with dynamic binding prepared statement, the duplicates in the IN-list were not eliminated,
- with char column, there was no correct match happening, it was missing the right space padding in the probevalue list causing the wrong answer.
> SPLICE-1541,1543: fix IN-list issues with dynamic bindings and char column

- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/IndexRow.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/ValueRow.java
While a virtual method call requires only class vtable indexing, an interface method call involves a search for the right itable first and then indexing. For methods that are called many times the difference may become quite noticeable.
ValueRow provides setColumn() as part of ExecRow interface definition. However, the method is called in getClone() for objects returned by virtual cloneMe(), which always returns either ValueRow or its subclass but is declared to return ExecRow. The compiler can't optimize it and generates an interface call where a virtual one would suffice.
Profiler shows total time time spent in ValueRow.getClone(), which calls setColumn(), goes down from 118 sec to 102 sec after promoting cloneMe() to return ValueRow (workload is IMPORT of 2M rows with 600+ columns).
> SPLICE-1546 ValueRow.setColumn as an Interface method is more expensive to call than as a virtual one

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Level2OptimizerTrace.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceLevel2OptimizerImpl.java
modified:   db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Level2OptimizerTrace.java
modified:   db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
modified:   splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceLevel2OptimizerImpl.java
> SPLICE-1555 Enable optimizer trace info for costing - port to 2.5

- hbase_sql/hbase1.0.0.x/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.0.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
Make sure coprocessor hooks set and clear flags for flushing and split.
Please also review pull request on ee branch.
> DB-5912: fix incremental backup hang(2.5)

- hbase_sql/hbase1.0.0.x/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.0.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
Make sure coprocessor hooks set and clear flags for flushing and split.
Please also review pull request on ee branch.
> DB-5912: fix incremental backup hang(2.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/TableDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSTABLESRowFactory.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DeleteNode.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/olap/AsyncOlapNIOLayer.java
- hbase_sql/src/main/java/com/splicemachine/olap/OlapRequestHandler.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java
- hbase_sql/src/test/java/com/splicemachine/olap/OlapClientTest.java
- mem_sql/src/main/java/com/splicemachine/derby/impl/sql/ControlOnlyDataSetProcessorFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreatePinConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropPinConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/DistributedIsCachedJob.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/GetIsCachedResult.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/IsCachedJob.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
-Remove Pin from dictionary and use Spark instead
-Speedup OlapNIOLayer for very short tasks by scheduling the first status
-check just after receiving the confirmation.
> SPLICE 1430 : remove pin from dictionary and rely on spark cache to get the status of pins & Fix race condition on OlapNIOLayer

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
Spark use String Type by default for csv. This fix make sure what we convert the columns in the right format by using the execRow schema and the baseColumnMap
passed in readTextFIle
> SPLICE-1425 :  Fix data type inconsistencies with unary functions and  external table based on TEXT data format

- splice_si_api/src/main/java/com/splicemachine/si/impl/TxnUtils.java
This fix breaks compatibility with earlier 2.5. Justification is provided in JIRA.
> SPLICE-1589 All transactions are processed by pre-created region 0 (v2.5)

- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupJobStatus.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupRestoreConstants.java
Store backup job status in zookeeper and update its last active timestamp. If a thread(compaction or flush, etc) is blocked, check the last active timestamp. Clean up backup if it times out.
Please also review code changes in ee branch.
> DB-5898: clean up timeout backup

- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/broadcast/AbstractBroadcastJoinFlatMapFunction.java
Choose dynamically whether to use the RDD or the Dataset implementation
for Bcast joins
Initialize bcast joins asynchronously
> DB-5872 Bcast implementation dataset vs rdd

- hbase_sql/src/main/java/com/splicemachine/fs/s3/PrestoS3FileSystem.java
- hbase_sql/src/main/resources/core-site.xml
- hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
Rolling back a performance fix for preventing early aborts when reading ORC files from S3.
Increasing io.file.buffer.size from default 4K to 64K.
> DB-5946 Fixing S3 File System Implementation

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/serialization/SpliceObserverInstructions.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
This pull request backports an accumulated set of changes for:
- SPLICE-1329: Memory leak in SpliceObserverInstructions
- SPLICE-1362: IndexOOB exceptions loading TPCC data
- DB-5789: redo nested connection onSpark fix (most importantly)
from master to 2.0.
It will fix intermittent failures in Jenkins and a memory leak in 2.0.
> DB-5956 RestoreIT fails in Jenkins intermittently

- hbase_sql/src/main/java/com/splicemachine/derby/stream/function/BulkImportFunction.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkHBaseBulkImport.java
BulkImportFunction was missing the call to SpliceSpark.setupSpliceStaticComponents() That's usually taken care of by the operationContext, but we don't use one here so we have to be explicit.
> SPLICE-1639 Fix NPE due to Spark static initialization missing

- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextManager.java
- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
- splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/serialization/SpliceObserverInstructions.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
A fix for DB-5956 (RestoreIT fails in Jenkins intermittently), essentially backported 
DB-5789 (Redo SpliceUDTIT.testConnection fix) to 2.0.
This pull request ensures that all three branches, 2.0, 2.5, and master, are aligned with regard to DB-5789, which provided a better fix for:
- SPLICE-1329: Memory leak in SpliceObserverInstructions
- SPLICE-1362: IndexOOB exceptions loading TPCC data.
> Backport DB-5789 from master to 2.5

- splice_machine/src/main/java/com/splicemachine/derby/utils/Vacuum.java
Increase logging level if needed with
CALL SYSCS_UTIL.SYSCS_SET_LOGGER_LEVEL (
'com.splicemachine.derby.utils.Vacuum', 'TRACE');
> DB-5933 Add logging to Vacuum process (2.0)

- splice_machine/src/main/java/com/splicemachine/derby/utils/Vacuum.java
We should ignore the table, not stop the vacuum process
> DB-5933 Continue processing tables when one doesn't have a namespace (2.0)

- splice_machine/src/main/java/com/splicemachine/derby/utils/Vacuum.java
We should ignore the table, not stop the vacuum process
> DB-5933 Continue processing tables when one doesn't have a namespace (2.5)

- splice_machine/src/main/java/com/splicemachine/derby/utils/Vacuum.java
We should ignore the table, not stop the vacuum process
> DB-5933 Continue processing tables when one doesn't have a namespace

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BaseJoinStrategy.java
- hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinCache.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/broadcast/AbstractBroadcastJoinFlatMapFunction.java
Close broadcast tables after use for GC, disable broadcast prefetch
> DB-5992 Disable Spark block cache and fix broadcast costing

- hbase_sql/src/main/java/com/splicemachine/hbase/RegionServerLifecycleObserver.java
- hbase_sql/src/test/java/com/splicemachine/hbase/PhysicalDeletionIT.java
- splice_machine/src/main/java/com/splicemachine/client/SpliceClient.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
Disable dictionary cache to fix HFile loading and physical delete problems. For longer term, we should support dictionary cache invalidation for them.
> DB-5982: disable dictionary cache for hbase master and spark executor(2.5)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
Fix for stats collection where it was missing partition by info for orc file type, for text file the index was zero based but for stats collection it has tobe one based.
(2.5 back port to follow)
> DB-5832: fix stats collection on external table

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
It was a regression introduced when DataDistionary was reworked. Basically, I restore the original behavior. With the fix, prepared statement recompilations disappear from performance profiles for TPC-C.
> SPLICE-1611 TPC-C workload causes many prepared statement recompilations

- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
Add a hbase snapshot to a list after it is taken successfully. The list can be used to delete the snapshot if the txn needs to roll back.
> DB-6012: avoid deleting a nonexist snapshot

- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
In cluster environment, org.joda.time.DateTime is loaded from /opt/cloudera/parcels/CDH-5.8.3-1.cdh5.8.3.p0.2/lib/hbase/lib/jruby-cloudera-1.0.0.jar, where its implementation is outdated and does not have the now() method.
DateTime.now() is implemented as 'new DateTime()', so the fix is trivial.
> DB-6023 NoSuchMethodError: org.joda.time.DateTime.now()

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/TransactionController.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumn.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/SpliceTransactionManager.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/StatsUsageIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/StatisticsAdminIT.java
… to bypass fetching real stats from dictionary tables + fix IT related to sample stats and skipStats.
The same logic was in an earlier pull request #780, which was backed out due to non-deterministic result in IT. 
This pull request fixed the IT as well as the IT for sample stats test in StatististicsAdminIT.
> SPLICE-1681 Introduce query hint "skipStats" after a table identifier…(2.5)

- hbase_storage/src/main/java/com/splicemachine/si/impl/readresolve/SynchronousReadResolver.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/scanner/SITableScanner.java
- splice_si_api/src/main/java/com/splicemachine/si/api/readresolve/AsyncReadResolver.java
- splice_si_api/src/main/java/com/splicemachine/si/api/readresolve/ReadResolver.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnFilter.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/readresolve/NoOpReadResolver.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/SimpleTxnFilterTest.java
This change brings a significant performance improvement in TPC-C workload: https://splice.atlassian.net/browse/SPLICE-1397
The idea is to skip transaction resolution of KeyValues when they only contain columns for which we already have read a later version.
> SPLICE-1682 Perform accumulator check before txn resolution

- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
If the data stored in backup znode is not recognizable, the znode is created by a backup on an old build. It should be cleaned up.
> DB-6035: cleanup failed backup from old build(2.5)

- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
If the data stored in backup znode is not recognizable, the znode is created by a backup on an old build. It should be cleaned up.
> DB-6035: cleanup failed backup from old build(master)

- db-engine/src/main/java/com/splicemachine/db/iapi/services/io/StoredFormatIds.java
- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
- hbase_sql/src/main/java/com/splicemachine/hbase/RegionServerLifecycleObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceMasterObserver.java
- hbase_sql/src/main/resources/META-INF/services/com.splicemachine.derby.utils.UpgradeK2
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/ZkUpgradeK2.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/TxnLifecycleEndpoint.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/CoprocessorTxnStore.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/region/RegionTxnStore.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/region/TxnDecoder.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/region/V2TxnDecoder.java
- splice_access_api/src/main/java/com/splicemachine/access/api/DatabaseVersion.java
- splice_access_api/src/main/java/com/splicemachine/tools/version/SimpleDatabaseVersion.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/Splice_DD_Version.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/SpliceAccessManager.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/btree/IndexConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/hbase/HBaseConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/ConglomerateUtils.java
- splice_protocol/src/main/protobuf/Txn.proto
- splice_si_api/src/main/java/com/splicemachine/si/api/txn/TxnStore.java
- splice_si_api/src/main/java/com/splicemachine/si/api/txn/lifecycle/TxnLifecycleStore.java
- splice_si_api/src/main/java/com/splicemachine/si/api/txn/lifecycle/TxnPartition.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/TxnUtils.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/data/StripedTxnLifecycleStore.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/store/TestingTxnStore.java
- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampOracle.java
Support new conglomerate format, store  V1 transaction threshold in ZK and use it when resolving transactions.
> SPLICE-774 Support upgrade from K2 (2.5)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java
- hbase_sql/src/main/java/com/splicemachine/orc/input/SpliceOrcNewInputFormat.java
- hbase_sql/src/main/java/com/splicemachine/orc/predicate/SpliceORCPredicate.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsOperation.java
This is an issue in the master branch where new orc input format is being used. The basecolumn map indexes needed to be zero based than the one based indexes to match the expectation in the reader job. Other external table formats were also tested with the last column as a partitioning column, it was not having this array bounds problem while stats collection.
> DB-6018: keep the column indexes zero based for new orc stats collection job

- hbase_sql/src/test/java/com/splicemachine/olap/OlapClientTest.java
Ignore OlapClientTest to achieve -Pcdh5.8.3 build success
> SPLICE-1716 Ignore OlapClientTest

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropTableIT.java
We currently handle 'drop table if exists table_name'
This commit allows for 'drop table table_name if exists' to work as well
> SPLICE-1729 Handle 'drop table table_name if exists'

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/Aggregate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_machine/src/main/java/com/splicemachine/SpliceKryoRegistry.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemAggregatorGenerator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/K2UpgradeScript.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
Hopefully the last piece for the upgrade, this change drops and recreates the statistics tables (and views) plus recreates an aggregate definition that also changed.
> SPLICE-774 Reset statistics during upgrade

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/StatementType.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CreateSchemaNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/CreateSchemaIT.java
You can now run CREATE SCHEMA <schemaname> IF NOT EXISTS as well as 
CREATE SCHEMA IF NOT EXISTS <schemaname> 
A warning will throw if the schema exists, else it will create the schema.
> SPLICE-1739: Added CREATE SCHEMA IF NOT EXISTS functionality

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
Explain is not showing always what the plan executes on spark vs control, fixing those inconsistencies.
> SPLICE-1438: fix the explain plan issues

- hbase_sql/hbase1.0.0.x/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.0.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/compactions/SpliceCompactionRequest.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
- hbase_sql/src/main/java/com/splicemachine/hbase/MemstoreAwareObserver.java
- Cleaned up compaction, split and flush hook. Removed unnecessary ones, and make sure even compaction failed, isCompacting is cleared
- make isCompacting, isFlushing, and isSplitting flag atomic variable.
> DB-5998: clean up backup endpoint to avoid hang(2.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
Small Nit but the cache used optional to be a negative cache and the logic was slightly off.  The effect is that each connection performed an additional scan.
> SPLICE-1748 Fixing Role Cache Usage

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericPreparedStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/BaseDataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/AsynchronousDDLWatcher.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchRefresher.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatcher.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/SynchronousDDLWatcher.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateRoleConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/TruncateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_protocol/src/main/protobuf/DDL.proto
Fixing Read/Write Cache Mechanism.  Based on this fix, truncate dictionary calls were found to be in the wrong order.
> Splice 1748 v5

- hbase_storage/src/main/java/com/splicemachine/access/hbase/H10PartitionAdmin.java
- hbase_storage/src/main/java/com/splicemachine/access/hbase/HServer.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java
Avoid multiple getClusterStatus() calls.
Increase the default value for "splice.statistics.regionLoadUpdateInterval"
> SPLICE-1759 HBase Master generates 1.1GB/s of network bandwidth even when cluster is idle

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/execute/ExecRow.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/IndexValueRow.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/ValueRow.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/orc/OrcRecordReader.java
- hbase_sql/src/main/java/com/splicemachine/orc/StripeReader.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTablePartitionIT.java
previously, selecting columns from a partitioned orc table would throw an error if it was partitioned by any column other than the last. in ValueRow, createStructType() could return columns that weren't selected. OrcRecordReader had some index issues where the partitioned column would be listed last in the query results, and the true last column would be chopped off.
> SPLICE-1621 Fix select from partitioned orc table error

- hbase_storage/src/main/java/com/splicemachine/access/hbase/H10PartitionAdmin.java
- hbase_storage/src/main/java/com/splicemachine/access/hbase/HServer.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java
> SPLICE-1759-2.5 HBase Master generates 1.1GB/s of network bandwidth even when cluster is idle (#881)

- hbase_sql/src/main/java/com/splicemachine/olap/AbstractOlapHandler.java
- hbase_sql/src/main/java/com/splicemachine/olap/AsyncOlapNIOLayer.java
- hbase_sql/src/main/java/com/splicemachine/olap/OlapCancelHandler.java
- hbase_sql/src/main/java/com/splicemachine/olap/OlapJobStatus.java
- hbase_sql/src/main/java/com/splicemachine/olap/OlapPipelineFactory.java
- hbase_sql/src/main/java/com/splicemachine/olap/OlapRequestHandler.java
- hbase_sql/src/main/java/com/splicemachine/olap/OlapServer.java
- hbase_sql/src/main/java/com/splicemachine/olap/OlapStatusHandler.java
- hbase_sql/src/test/java/com/splicemachine/olap/OlapClientTest.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/olap/OlapStatus.java
- splice_protocol/src/main/protobuf/Olap.proto
Block on the server the first time we request the status of a job, if
it's short it will be available before we return to the client, lowering
latency for short jobs.
> SPLICE-1716 Reduce Olap job latency for short tasks

- hbase_sql/src/main/java/com/splicemachine/hbase/BytesCopyTaskSplitter.java
- hbase_sql/src/main/java/com/splicemachine/hbase/RegionSizeEndpoint.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java
- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
- splice_protocol/src/main/protobuf/Splice.proto
Makes cutpoint generation a regular coprocessor vs. a serial coprocessor call from cached regions.  Also, I found a resource leak where the HFile.Reader is not closed.
> SPLICE-1784 Fixing Serial Cutpoint Generation

- mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MemDatabase.java
Without this, memory database is worthless in understanding cache misses.
> SPLICE-1788 Mem Database should traverse the same cache as HBase

- db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/ResultSet.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedResultSet.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/BasicNoPutResultSetImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/IteratorNoPutResultSet.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/TemporaryRowHolderResultSet.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/HEngineSqlEnv.java
- hbase_sql/src/main/java/com/splicemachine/stream/RemoteQueryClientImpl.java
- mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MEngineSqlEnv.java
- splice_machine/src/main/java/com/splicemachine/EngineDriver.java
- splice_machine/src/main/java/com/splicemachine/SqlEnvironment.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/OperationManager.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/OperationManagerImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/SingleRowCursorResultSet.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/SpliceOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/CallStatementOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TemporaryRowHolderOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdmin_OperationsIT.java
- start-splice-cluster
This adds an OperationManager, when an operation is opened it registers itself on the OperationManager and unregisters when it is closed.
There's two new system procedures:
- SYSCS_UTIL.SYSCS_GET_RUNNING_OPERATIONS(): lists all running operations for the current user (or for all users if it is the db owner)
- SYSCS_UTIL.SYSCS_KILL_OPERATION(): kills an operation (either control-mode or spark)
The killing works by closing the operation and interrupting the DRDAConnThread associated with it.
The procedures are local to the region server, they only work on operations running on the given region server.
> SPLICE-1372 List and kill running operations

- assembly/cdh5.8.3/src/main/resources/bin/sqlshell.sh
- assembly/cdh5.9.0/src/main/resources/bin/sqlshell.sh
- assembly/hdp2.5.5/src/main/resources/bin/sqlshell.sh
- assembly/mapr5.2.0/src/main/resources/bin/sqlshell.sh
- hbase_sql/pom.xml
- sqlshell.sh
- start-splice-cluster
Added ssl mode args for sqlshell.sh and added a new ssl server profile for standalone server startup, please see SPLICE-1607 and DB-6021 comments for usage.
> DB-6021: enable JDBC client like sqlshell.sh for SSL/TLS

- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/hbase1.0.0.x/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupBaseRegionObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceHFileCleaner.java
- hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionState.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupRestoreConstants.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnFilter.java
- Given an incremental backup Id, find all of it parent backups and restore all of them.
- Added more logging
- pass hbase.mapreduce.bulkload.max.hfiles.perRegion.perFamily to restore job
- ignore unfound txn during compaction and txn filtering. From a restored database, some data may be wriiten by a txn that cannot be found in txn table.
Please also review ee branch.
> DB-5934: restore a chain of backup

- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/hbase1.0.0.x/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupBaseRegionObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceHFileCleaner.java
- hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionState.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupRestoreConstants.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnFilter.java
- Given an incremental backup Id, find all of it parent backups and restore all of them.
- Added more logging
- pass hbase.mapreduce.bulkload.max.hfiles.perRegion.perFamily to restore job
- ignore unfound txn during compaction and txn filtering. From a restored database, some data may be wriiten by a txn that cannot be found in txn table.
Please also review ee branch.
> DB-5934: restore a chain of backup(2.5)

- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/hbase1.0.0.x/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.0.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupBaseRegionObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceHFileCleaner.java
- hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionState.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupRestoreConstants.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnFilter.java
- Given an incremental backup Id, find all of it parent backups and restore all of them.
- Added more logging
- pass hbase.mapreduce.bulkload.max.hfiles.perRegion.perFamily to restore job
- ignore unfound txn during compaction and txn filtering. From a restored database, some data may be wriiten by a txn that cannot be found in txn table.
Please also review ee branch.
> DB-5934: restore a chain of backup(2.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
Fixes TPC/IP Timeouts from JDBC Client.
> SPLICE-1718 Fixes TCP/IP Timeout and Sets Default to 60 seconds

- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/SavepointConstantOperationIT.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/TransactionImpl.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/txn/AbstractTxn.java
- splice_si_api/src/test/java/com/splicemachine/si/SavepointsTest.java
Make sure we keep transactions around if needed for in memory
subtransactions
(This has already been merged into master.)
> SPLICE-1813 Remove transactions from the savepoint stack (2.5)

- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/SavepointConstantOperationIT.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/TransactionImpl.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/txn/AbstractTxn.java
- splice_si_api/src/test/java/com/splicemachine/si/SavepointsTest.java
Make sure we keep transactions around if needed for in memory
subtransactions
(This has already been merged into master)
> SPLICE-1813 Remove transactions from the savepoint stack (2.6)

- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/SavepointConstantOperationIT.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/TransactionImpl.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/txn/AbstractTxn.java
- splice_si_api/src/test/java/com/splicemachine/si/SavepointsTest.java
Make sure we keep transactions around if needed for in memory
subtransactions
> SPLICE-1813 Remove transactions from the savepoint stack

- RELEASE-NOTES.md
Updating the release notes for 2.5.0.1729 patch release (including changes since 2.5 GA version 2.5.0.1707).
> DB-6126: 2.5.0.1729 Patch Release Notes

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/BulkDataSetWriter.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/PipelineConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
Add a new parameter splice.region.toLoad.perTask to control the number of regions to load for each  spark task in the last stage of HFile bulk import.
> SPLICE-1785: load more regions per task in last stage of bulk import

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/BulkDataSetWriter.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/PipelineConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
Add a new parameter splice.region.toLoad.perTask to control the number of regions to load for each  spark task in the last stage of HFile bulk import.
> SPLICE-1785: load more regions per task in last stage of bulk import(2.5)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/BulkDataSetWriter.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/PipelineConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
Add a new parameter splice.region.toLoad.perTask to control the number of regions to load for each  spark task in the last stage of HFile bulk import.
> SPLICE-1785: load more regions per task in last stage of bulk import(2.6)

- hbase_sql/src/main/java/com/splicemachine/hbase/BytesCopyTaskSplitter.java
- hbase_sql/src/main/java/com/splicemachine/hbase/RegionSizeEndpoint.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java
- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
- splice_protocol/src/main/protobuf/Splice.proto
This was change was reverted earlier due to tpch1 regression, the problem appeared related when we close the fileReader in the HRegionUtil.getCutPoints(), it may close this FSDataInputStream for later operations. Ran tpch1 suite in 5+ attempts, no regressions found.
> Splice-1784: query does not scale on 4000 regions

- db-client/src/main/java/com/splicemachine/db/client/net/ClientJDBCObjectFactoryImpl.java
- db-client/src/main/java/com/splicemachine/db/client/net/ClientJDBCObjectFactoryImpl40.java
- db-client/src/main/java/com/splicemachine/db/client/net/NetConfiguration.java
- db-client/src/main/java/com/splicemachine/db/client/net/NetConnection.java
- db-client/src/main/java/com/splicemachine/db/client/net/NetConnection40.java
- db-client/src/main/java/com/splicemachine/db/jdbc/ClientDriver.java
Making jdbc driver compatible for 2.0 server build. Without doing any server side changes, here the driver would connect in two attempts to connect to 2.0 server. If it gets connection exception first time, it would retry with the 2.0 product Id and see it can connect.
Tested on standalone with simple jdbc app for both 2.5 and 2.0, will need more testing on cluster with 2.5 db-client.jar
Needs to apply this PR only for special branch "shared-2.5" since its a one off case.
> DB-6171: Implement retry for jdbc driver to connect to 2.0 and 2.5 (shared-2.5)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/IndexColumnOrder.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/DerbyWindowContext.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregatorImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowContext.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/ColumnComparator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/MergeWindowFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/OrderByIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
…Spark and Control path for Window function
by reverting commit 0966e6479abad15ddd9ff0428b05113d191c2aee.
> DB-6164 re-apply DB-6164's fix: honor Null ordering specification in …(2.5)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/IndexColumnOrder.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/DerbyWindowContext.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregatorImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowContext.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/ColumnComparator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/MergeWindowFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/OrderByIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
…Spark and Control path for Window function
by reverting commit 817a09dfe3560ac71b9f2cf74eec7d6782c699d8.
> DB-6164 re-apply DB-6164's fix: honor Null ordering specification in …(2.6)

- hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
Clean up rpc for backup, so it won't accidentally trying to prob a missing region and gets stuck.
> DB-6183: clean up rpc for backup

- hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
Clean up rpc for backup, so it won't accidentally trying to prob a missing region and gets stuck.
> DB-6183: clean up rpc for backup(2.6)

- hbase_sql/src/main/java/com/splicemachine/hbase/BytesCopyTaskSplitter.java
- hbase_sql/src/main/java/com/splicemachine/hbase/RegionSizeEndpoint.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/AbstractSMInputFormat.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java
- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
- splice_protocol/src/main/protobuf/Splice.proto
Earlier reverted due to tpc1g intermittent regressions. Now added the retry coprocessor while getting subsplits for the region during that interval. Tested with tpch1g 15 runs consecutively, and more manual testing.
> SPLICE-1784: Fixing cutpoint generation

- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
The KeyBy piece is not correct.  I modified it to behave more like a map call to transform V to PairDataSet<K,V>.
> SPLICE-1879 Modify Key By function to look more like map()

- assembly/pom.xml
- hbase_sql/pom.xml
- pom.xml
There are three changes here, these worked:
change io.netty shading to match the shading which 'vanilla spark' provides
force netty version to be a perfect match for the version packaged with mapr5.2
modify zookeeper.version to match perfectly mapr5.2 (but zookeeper.version is unused...? )
Its possibly we only need the shading change.
I have *only* tested on mapr5.2 on one setup with secure mapr, splice 2.5 branch.
> DB-6066: build changes for mapr5.2/vanilla yarn support

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSparkKryoRegistrator.java
- splice_machine/src/main/java/com/splicemachine/SpliceKryoRegistry.java
We were seeing a lot of object creation on the Spark side and it seems like we are spilling to disk.  The serde I think was missing for the base class...
> DB-6226 Adding Serde for Serialization registration with Kryo

- splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
- Make sure there is always a valid backup chain with a full backup after purging old backups.
- When there is no valid backup chain, and a user is requesting an incremental backup, promote it to a full backup.
> DB-6214: reserve a valid backup chain when deleting old backups

- splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
- Make sure there is always a valid backup chain with a full backup after purging old backups.
- When there is no valid backup chain, and a user is requesting an incremental backup, promote it to a full backup.
> DB-6214: reserve a valid backup chain when deleting old backups (2.6)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CostEstimate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CostEstimateImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SimpleCostEstimate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/StoreCostControllerImpl.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/IndexSelectivityIT.java
…cost to prune join plan search space
This is a replacement of PR #1062 to fix intermittent IT failure. More details please see PR #1078 .
> DB-6124 fix conglomerate average row width estimation, also use local…(2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CostEstimate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CostEstimateImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RowOrderingImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SimpleCostEstimate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/StoreCostControllerImpl.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/IndexSelectivityIT.java
…cost to prune join plan search space
Port the change to 2.6.1 also.
> DB-6124 fix conglomerate average row width estimation, also use local…(2.6.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BasicPrivilegesNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
Add the column list from table as column level privileges so that users can revoke few columns later. Also see spliceengine-ee for ITs
> DB-6217: make table level select privileges to column level (2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BasicPrivilegesNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
Add the column list from table as column level privileges so that users can revoke few columns later. Also see spliceengine-ee for ITs.
> DB-6217: make table level select privileges to column level (2.6)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BasicPrivilegesNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
Add the column list from table as column level privileges so that users can revoke few columns later. Also see spliceengine-ee for ITs
> DB-6217: make table level select privileges to column level

- assembly/pom.xml
keep master, 2.6 branch in sync with v2.0 and v2.5 for Cloudera certification
> DB-6275: exclude flatten and restart scripts (2.6)

- hbase_sql/src/main/resources/info-log4j.properties
- hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.2.0_cdh5.12/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.2.0_cdh5.12/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/src/main/java/com/splicemachine/access/client/CountingRegionScanner.java
- hbase_storage/src/main/java/com/splicemachine/access/client/SkeletonClientSideRegionScanner.java
This is a temporary addition of logging information meant to debug DB-6274, it should be reverted once the problem is fixed.
> DB-6274 Add more logging on Spark scanners close()

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
restrictionList has always been initialized as "null" instant with empty list. It should check whether it's empty before printing the restriction list.
> SPLICE-1913: NullPointerException happen when DumpOptimizedTree

- db-engine/pom.xml
This is a backport of SPLICE-1351 to 2.5.
> SPLICE-1351 Upgrade Sketching Library from 0.8.1 - 0.8.4 (2.5)

- hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
- hbase_storage/hbase1.2.0_cdh5.12/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.2.0_cdh5.12/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.2.0_cdh5.12/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
Previous merge had some IT failures
Now we make sure we don't close the MemstoreFlushAwareScanner if it reaches the scan's stopRow
> DB-6274 Re-init SplitRegionScanner if MemstoreKVScanner returns null

- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/src/main/java/com/splicemachine/storage/HScan.java
- mem_storage/src/main/java/com/splicemachine/storage/MScan.java
- splice_access_api/src/main/java/com/splicemachine/storage/DataScan.java
- splice_access_api/src/main/java/com/splicemachine/storage/Partition.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/SpliceRegionAdmin.java
If a region start/end key cannot be decoded, fetch the first/last row of the region and decode it.
> SPLICE-1928: decode region start/end key by fetching actual rowkey

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/TempTableIT.java
ITs already existed for the feature but were ignored, I'm reenabling them.
> DB-6354 Fix automatic DROP of temp tables

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CheckCorrelatedSubqueryVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CountWhereSubqueryVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DMLStatementNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultSetNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/TPCHIT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Table_IT.java
…… (#1124)
This is a backport of DB-4300 to 2.6.1. Code has already been merged to master.
> DB-4300 enhance subquery processing logic to convert eligible where s…(2.6.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CheckCorrelatedSubqueryVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CountWhereSubqueryVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DMLStatementNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultSetNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/TPCHIT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Table_IT.java
…… (#1124)
This is a back port of DB-4300 to 2.5. The code has already been merged to master.
> DB-4300 enhance subquery processing logic to convert eligible where s…(2.5)

- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampOracle.java
Previous behavior, when "splice.timestamp_server.blocksize" was interpreted as roughly the number of transactions, is restored. The default value for "splice.timestamp_server.blocksize" remains intact (32768).
> DB-6362 Large variance in simple select query execution time

- pom.xml
- splice_protocol/pom.xml
[ERROR] protoc failed error: [libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: Backup.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: Txn.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: Derby.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for …
> SPLICE-1930: Fixes an issue where maven uses platform installed protobuf to compile proto2 files.

- GETTING-STARTED.md
Protobuf installation instructions should be removed from GETTING-STARTED as it's not needed anymore. Fixed by SPLICE-1930
> SPLICE-1951: Remove protobuf installation instructions from GETTING-STARTED

- hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/CostChoosingDataSetProcessorFactory.java
If Splice.isClient is true, allow execution go to spark. This is needed if splice spark adapter is launched from a spark task with a thread name of "Executor task launch worker"
> DB-6349: allow distributed execution for splice client

- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/test/java/com/splicemachine/hbase/SpliceRegionAdminIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/SpliceRegionAdmin.java
If table name or split key is null, return a meaningful error message rather than a null pointer exception.
If schema name is null, use the current schema.
> DB-6367: null checking for region operations

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/SparkStreamingTest.scala
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/TestStreamingContext.scala
The ITs from the previous PR had some issues that were resolved when backporting to 2.5, I fix them here.
I've also made SpliceSpark.setContext() synchronized to guarantee correctness under concurrency.
> SPLICE-1948 Resolve conflicts and some IT bugs

- platforms/cdh5.12.0/pom.xml
- platforms/cdh5.8.3/pom.xml
Added missing module to cdh5.8.3 and cdh5.12.0
> SPLICE-1961 Missing splice_spark module in pom.xml

- db-engine/src/main/java/com/splicemachine/db/impl/ast/RowLocationColumnVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/VirtualColumnNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/UpdateFromSubqueryIT.java
Note, compared to the commit to branch-2.5 and branch-2.6, the commit to the master's UpdateFromSubqueryIT has the merge join path commented out due to wrong result tracked in DB-6320.
> DB-6411 fix column misalignment for join update through mergesort join

- pom.xml
Fixes importing from S3 in standalone environment.
> DB-6445 Upgrade joda-time to 2.8.2 (2.6)

- pom.xml
Fixes importing from S3 in standalone environment.
> DB-6445 Upgrade joda-time to 2.8.2

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/stats/ColumnStatisticsImpl.java
- db-engine/src/main/java/com/splicemachine/db/iapi/stats/EffectivePartitionStatisticsImpl.java
- db-engine/src/main/java/com/splicemachine/db/iapi/stats/FakePartitionStatisticsImpl.java
- db-engine/src/main/java/com/splicemachine/db/iapi/stats/ItemStatistics.java
- db-engine/src/main/java/com/splicemachine/db/iapi/stats/NonUniqueKeyStatisticsImpl.java
- db-engine/src/main/java/com/splicemachine/db/iapi/stats/PartitionStatistics.java
- db-engine/src/main/java/com/splicemachine/db/iapi/stats/PartitionStatisticsImpl.java
- db-engine/src/main/java/com/splicemachine/db/iapi/stats/PrimaryKeyStatisticsImpl.java
- db-engine/src/main/java/com/splicemachine/db/iapi/stats/TableStatistics.java
- db-engine/src/main/java/com/splicemachine/db/iapi/stats/TableStatisticsImpl.java
- db-engine/src/main/java/com/splicemachine/db/iapi/stats/UniqueKeyStatisticsImpl.java
- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/StoreCostController.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/test/java/com/splicemachine/db/iapi/types/SQLBooleanTest.java
- db-engine/src/test/java/com/splicemachine/db/iapi/types/SQLCharTest.java
- db-engine/src/test/java/com/splicemachine/db/iapi/types/SQLDecimalTest.java
- db-engine/src/test/java/com/splicemachine/db/iapi/types/SQLDoubleTest.java
- db-engine/src/test/java/com/splicemachine/db/iapi/types/SQLIntegerTest.java
- db-engine/src/test/java/com/splicemachine/db/iapi/types/SQLLongIntTest.java
- db-engine/src/test/java/com/splicemachine/db/iapi/types/SQLRealTest.java
- db-engine/src/test/java/com/splicemachine/db/iapi/types/SQLSmallIntTest.java
- db-engine/src/test/java/com/splicemachine/db/iapi/types/SQLTimestampTest.java
- db-engine/src/test/java/com/splicemachine/db/iapi/types/SQLTinyIntTest.java
- db-engine/src/test/java/com/splicemachine/db/iapi/types/SQLVarcharTest.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/StoreCostControllerImpl.java
Please see [DB-6428](https://splicemachine.atlassian.net/browse/DB-6428) for description of the fix.
> DB-6428 adjust selectivity estimation by excluding skewed default values(2.5)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/batchonce/BatchOnceOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/BatchOnceOperationIT.java
This is a port of SpLICE-1349 to 2.5. The code is already in branch-2.0, branch-2.6 and master.
Also see [DB-6462](https://splicemachine.atlassian.net/browse/DB-6461).
> SPLICE-1349: serialize and initialize BatchOnceOperation correctly(2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Optimizer.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/RowOrdering.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HalfOuterJoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RowOrderingImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJoinFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/OrderByEliminationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/OuterJoinOrderByEliminationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/NestedLoopJoinOperationIT.java
and DB-6453 preserve left row order for batched nestedloop join. 
Summary of solution could be found in [DB-6453](https://splicemachine.atlassian.net/browse/DB-6453)
> DB-6453 avoid sort for outer join when applicable(2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Optimizer.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/RowOrdering.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HalfOuterJoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RowOrderingImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJoinFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/OrderByEliminationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/OuterJoinOrderByEliminationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/NestedLoopJoinOperationIT.java
DB-6453 preserve left row order for batched nestedloop join
> DB-6453 avoid sort for outer join when applicable(2.6.1)

- start-splice-cluster
I would like to be able to continue to watch zookeeper when I run the startup script. The script looks for "zoo" and kills associated processes. I think that looking for "zookeeper" is a more specific termination directive.
> The startup script kills 'tail -f zoo.log' too.

- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
SMRecordReaderImpl not closing activationHolder was causing the memory leak.
However, closing it created more problems that it solved - triggers wouldn't work in Spark for one thing (this is likely the reason why it was commented out). It appears removing ActivationHolder altogether is a better solution as there is now another scope of ActivationHolder handling in ResultStreamer (probably not a perfect solution either).
Another memory leak was caused by ActivationHolder.reinitialize() not closing the currently opened SpliceTransactionResourceImpl when called repeatedly (this may not be an immediate issue any more after removing this call from SMRecordReaderImpl).
> SPLICE-1983 OOM in Spark executors while running TPCH1 repeatedly

- start-splice-cluster
This script just needed to be updated to use the right Cloudera version. @MurrayBrown mentioned that we use `5.8.3` now.
@MurrayBrown Who should merge this?
> DB-6515: Upgrade the version number in start-splice-cluster

- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HBasePipelineEnvironment.java
- hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java
- hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java
- hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java
- hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java
- hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java
- hbase_storage/src/main/java/com/splicemachine/access/hbase/H10PartitionAdmin.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HBaseSIEnvironment.java
- mem_pipeline/src/main/java/com/splicemachine/pipeline/MPipelineEnv.java
- mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MEnginePartitionAdmin.java
- mem_storage/src/main/java/com/splicemachine/si/MemSIEnvironment.java
- mem_storage/src/main/java/com/splicemachine/storage/MPartitionFactory.java
- splice_access_api/src/main/java/com/splicemachine/access/api/PartitionAdmin.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyChildInterceptWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyParentInterceptWriteHandler.java
- splice_si_api/src/main/java/com/splicemachine/si/api/server/TransactionalRegionFactory.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnFilter.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/TxnRegion.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIDriver.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIEnvironment.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactor.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/store/IgnoreTxnSupplier.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/txn/SITransactionReadController.java
Add an ignore txn cache to filter out txns that are committed during backup. The ignore txn cache entry is a pair of long [backup begin txnId, backup end TxnId]
> DB-6284: add ignore txn cache (2.5)

- hbase_sql/src/main/resources/hbase-log4j.properties
- hbase_sql/src/main/resources/info-log4j.properties
- hbase_sql/src/main/resources/log4j.properties
- hbase_sql/src/main/resources/trace-log4j.properties
- hbase_sql/src/test/resources/log4j.properties
- hbase_storage/src/test/resources/log4j.properties
- mem_sql/src/main/resources/log4j.properties
- splice_machine/src/test/resources/log4j.properties
- splice_si_api/src/test/resources/log4j.properties
- splice_spark/src/test/resources/log4j.properties
- utilities/src/test/resources/log4j.properties
Modified the log4j default timestamp format for standalone version. The cluster version, the timestamp format of log file could be set in Cloudera Manager (CDH), Ambari (HDP) and file /opt/mapr/hbase/hbase-1.1.1/conf/log4j.properties (MapR in default).
> SPLICE-1974 Splice derby timestamp format not compliant with Hadoop

- pom.xml
Fixed DB-6511. Open source builds will be published to external and internal nexus. In pom.xml, added profiles for distributionManagement. Added two IDs splicemachine-internal and splicemachine-external. DB-6511-2.5 branched off from branch-2.5. Suggest to merge it to branch-2.5 first. Then, branch-2.6 and master. The Jenkins projects configurations need to be changed as well.
In Jenkins:
spliceengine-platform -> Configuration Matrix, add hdp2.5.5
Build -> Invoke top-level Maven targets, replace "-P ${platform},ee" with
-P ${platform},ee,installer,splicemachine-internal,splicemachine-external
Remove lines below
-DaltReleaseDeploymentRepository=splicemachine-public::default::http://repository.splicemachine.com/nexus/content/repositories/releases/ …
> DB-6511 Discrepancy between internal and external Nexus repos (2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/services/property/PropertyUtil.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/PropertyConglomerate.java
I have tested on the cluster. The # of read requests for splice:16 does not increase if I keep running SQL queries
> DB-6558: cache more database properties

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
Removing checking if already closed fixes memory leak.
It may cause multiple logging of statement processing finish, though.
I'm going to file another JIRA for redoing closing of SpliceBaseOperation.
> SPLICE-2006 TPC-C run fails to complete, Region Servers die

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
Removing checking if already closed fixes memory leak.
This fix has already been integrated in master.
> SPLICE-2006 TPC-C run fails to complete, Region Servers die (2.6)

- splice_machine/src/main/java/com/splicemachine/pipeline/IndexWriteHandler.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/UpportIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/TPCHIT.java
Fix to DB-4165 missed a corner case when a tombstone is added to write buffer, the buffer gets flushed immediately, so the next insert cannot replace it. Here is a description of the original problem 
/*
* DB-4165: When we do an update to the base table, that translates to a delete
* and then an insert in the index. For situations where we update the indexed fields
* to different values, this is fine because the delete will go to one HBase row, and the
* insert to another. However, if you update an indexed field by setting it to the same value
* (i.e. update foo set bar = bar), then the insert and the delete will end up going to the same
* location, and the result is an insert and a delete on the same row with the same transaction.
* The SI module treats this as a delete (because there is …
> DB-6537: fix upsert index(2.6)

- pom.xml
… Open source builds will be published to external and internal nexus. In pom.xml, added profiles for distributionManagement. Added two IDs splicemachine-internal and splicemachine-external. The Jenkins projects configurations need to be changed after code is merged.
In Jenkins:
Build -> Invoke top-level Maven targets, replace "-P ${platform},ee" with
-P ${platform},ee,installer,splicemachine-internal,splicemachine-external
Remove lines below
-DaltReleaseDeploymentRepository=splicemachine-public::default::http://repository.splicemachine.com/nexus/content/repositories/releases/
-DaltSnapshotDeploymentRepository=splicemachine-public::default::http://repository.splicemachine.com/nexus/content/repositories/snapshots/
> DB-6511. Fixed Discrepancy between internal and external Nexus repos (2.6)

- build-tools/checkBuildNumber.sh
This script is used to check mismatched build numbers in pom.xml files. Type ./checkBuildNumber.sh to learn usage.
> DB-6595: Script to check mismatched build numbers in pom.xml files. 

- build-tools/checkBuildNumber.sh
DB-6595: Script to check mismatched build numbers in pom.xml files. Type ./checkBuildNumber.sh to learn usages.
> DB-6595: Script to check mismatched build numbers in pom.xml files (2.5)

- build-tools/checkBuildNumber.sh
DB-6595: Script to check mismatched build numbers in pom.xml files.
> DB-6595: Script to check mismatched build numbers in pom.xml files (2.7)

- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceHFileCleaner.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupRestoreConstants.java
During the first full backup, some incremental changes were produced right after a region finishes backup. SpliceHFileCleaner should keep incremental changes either it finds there was successful backup in the system, or there is an ongoing backup.
> DB-6603: prevent incremental backup from losing changes(2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextService.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
SPLICE-1983 is undone to restore UDF functionality. ActivationHolder.close() is uncommented in SMRecordReaderImpl to avoid memory leaks. Trigger ITs are fixed by guarding against out-of-order  activationHolder.close() called from SMRecordReaderImpl and SMRecordWriter (violated nesting or push/pop semantics) whether sharing the same activationHolder or using different instances.
> DB-6541 User defined function does not work on spark

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/depend/BasicDependencyManager.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
Disable dependency manager for splice adapter because it caused memory leak
> DB-6516: disable dependency manager for spark(2.5)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/security/SchemaPrivilegeIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
- splice_protocol/src/main/protobuf/DDL.proto
Please see problem description and solution in [DB-6685](https://splicemachine.atlassian.net/browse/DB-6685?focusedCommentId=53176&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-53176)
> DB-6685 invalidate dictionary cache after update schema owner

- hbase_sql/pom.xml
Fixes log4h inclusion which causes issues for log files on the cluster.
> DB-6722 Fixing Log4j inclusion in hbase_sql jar

- splice_spark/src/main/spark2.2/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
@jleach4 This was missed in spark2.2 in the recent merge.
> SPLICE-2066: Duplicate create connection in Splicemachinecontext(2.5)

- assembly/pom.xml
The hdp2.6.3 rpm package names do not match our naming conventions. It places "1" at end of the name for release build, places timestamps at the end of the name for SNAPSHOT build. The release scripts cannot find the packages and upload to S3 bucket. Added build number at the end of package name.
> DB-6754 Add build number for hdp2.6.3

- assembly/pom.xml
The hdp2.6.3 rpm package names do not match our naming conventions. It places "1" at end of the name for release build, places timestamps at the end of the name for SNAPSHOT build. The release scripts cannot find the packages and upload to S3 bucket. Added build number at the end of package name.
> DB-6754 Add build number for hdp2.6.3 (2.5)

- assembly/pom.xml
The hdp2.6.3 rpm package names do not match our naming conventions. It places "1" at end of the name for release build, places timestamps at the end of the name for SNAPSHOT build. The release scripts cannot find the packages and upload to S3 bucket. Added build number at the end of package name.
> DB-6754 Add build number for hdp2.6.3 (2.7)

- hbase_pipeline/src/main/java/com/splicemachine/pipeline/SnappyPipelineCompressor.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/utils/PipelineCompressor.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/utils/SimplePipelineCompressor.java
Removed unused methods from the PipelineCompressor interface and its implementations.
Reimplemented SnappyPipelineCompressor with org.xerial.snappy.Snappy already used by Splice in db-drda.
Mean TPMC for TPC-C went up from 14675.4 to 15999 (practically the limit for the 200 rate used in the test). GC looks normal, SnappyPipelineCompressor is off the radar screen.
> SPLICE-2107 SnappyPipelineCompressor generates too much garbage

- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceScan.java
already merged in branch-2.5 but missing in master/2.7 branch
> SPLICE-2104: Dictionary Scans Should Use HBase Small Scans vs. the network heavy regular scan (2.7)

- db-drda/pom.xml
- db-drda/src/main/java/com/splicemachine/db/impl/drda/DDMWriter.java
- hbase_pipeline/src/main/java/com/splicemachine/pipeline/SnappyPipelineCompressor.java
- utilities/pom.xml
- utilities/src/main/java/com/splicemachine/compression/SpliceSnappy.java
A wrapper, SpliceSnappy, is introduced. It sets "org.xerial.snappy.tempdir" to control Snappy native library extraction and provides robustness in case Snappy is not loaded.
Snappy version is downgraded to 1.0.4.1 to match the one provided in cluster environment.
> SPLICE-2112 Configure org.xerial.snappy.Snappy to avoid extracting its native library to /tmp

- assembly/hdp2.6.3/src/main/resources/common-services/SPLICEMACHINE/2.5.1/service_advisor.py
Add HBASE_REGIONSERVER_OPTS configuration in hbase-env.
Also deleted a duplicated line "hbase.htable.threads.max" : "96".
> DB-6817 Add Information to HBASE_REGIONSERVER_OPTS (2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/RoutinePermsDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/Procedure.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSROUTINEPERMSRowFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptForModifySchemaPermissionAndDefaultRole.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptForSysTables.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptToCleanSysRoutinePerms.java
also clean obsolete rows in sysroutineperms if any
Please see [SPLICE-2120](https://splice.atlassian.net/browse/SPLICE-2120) for analysis and solution.
Since the fix is in the upgrade logic, no automatic test is added to IT. I've manually tested with the upgrade from 2.5.1810T to 2.5.1812, 2.5.1810 to 2.5.1812.
> SPLICE-2120 update SYS.SYSROUTINEPERMS when upgrading system procedures (2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/RoutinePermsDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/Procedure.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSROUTINEPERMSRowFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptForModifySchemaPermissionAndDefaultRole.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptToCleanSysRoutinePerms.java
also clean obsolete rows in sysroutineperms if any
Port change to branch-2.7. a minor difference from 2.5 is that: there is no call of upgradeSystables() in SpliceDataDictionary.upgradeIfNecessary(), so no need to add a UpgradeScriptForSysTables.java.
> SPLICE-2120 update SYS.SYSROUTINEPERMS when upgrading system procedures (2.7)

- hbase_sql/pom.xml
- mem_sql/pom.xml
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
This change adds logging to intercept System.exit() calls during the ITs execution, which could be the cause of the "VM crashed" messages on jenkins.
This will cause jenkins output to be less readable, we can switch back once the issue is fixed or if this doesn't help diagnose it.
> SPLICE-2064 Add logging on System.exit() calls

- db-tools-ij/pom.xml
- db-tools-ij/src/main/grammar/ij.jj
- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/utilMain.java
Switched to db-shared, removed what I believe was unused code.
> SPLICE-1348 remove dependency on db-engine from db-tools-ij

- hbase_storage/pom.xml
- mem_pipeline/pom.xml
- mem_sql/pom.xml
- mem_storage/pom.xml
- pipeline_api/pom.xml
- pom.xml
- splice_machine/pom.xml
- splice_si_api/pom.xml
The "VM crashed" failure might be related to https://issues.apache.org/jira/browse/SUREFIRE-1302
Upgrading to surefire 2.21.0 might solve it
> SPLICE-2064 Upgrade surefire plugin

- pipeline_api/src/main/java/com/splicemachine/pipeline/PipelineDriver.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/PipelineConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
Set the configuration manually since there are issues between different HBase versions.  This should leave 50% of the threads open based on our default implementation.
> DB-6833 Set Max Dependent and Independent write threads directly (2.5)

- hbase_sql/src/test/java/com/splicemachine/hbase/DefaultIndexBulkLoadIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateIndexConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/index/IndexTransformer.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/CreateIndexConstantOperationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DefaultIndexIT.java
This PR contains fixes for two tickets:
[SPLICE-2136](https://splice.atlassian.net/browse/SPLICE-2136) fix issue with index exclude default keys feature not correctly suppressing rows with default values if leading index column is in descending order
[SPLICE-2138](https://splice.atlassian.net/browse/SPLICE-2138) set the defaultValue for the leading column of an index excluding default key correctly
> SPLICE-2136 SPLICE-2138 fix issues related to index excluding default keys

- hbase_sql/src/test/java/com/splicemachine/hbase/DefaultIndexBulkLoadIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateIndexConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/index/IndexTransformer.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/CreateIndexConstantOperationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DefaultIndexIT.java
This PR contains fixes for two tickets:
[SPLICE-2136](https://splice.atlassian.net/browse/SPLICE-2136) fix issue with index exclude default keys feature not correctly suppressing rows with default values if leading index column is in descending order
[SPLICE-2138](https://splice.atlassian.net/browse/SPLICE-2138) set the defaultValue for the leading column of an index excluding default key correctly
> SPLICE-2136 SPLICE-2138 fix issues related to index excluding default keys (2.5)

- hbase_sql/src/test/java/com/splicemachine/hbase/DefaultIndexBulkLoadIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateIndexConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/index/IndexTransformer.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/CreateIndexConstantOperationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DefaultIndexIT.java
This PR contains fixes for two tickets:
[SPLICE-2136](https://splice.atlassian.net/browse/SPLICE-2136) fix issue with index exclude default keys feature not correctly suppressing rows with default values if leading index column is in descending order
[SPLICE-2138](https://splice.atlassian.net/browse/SPLICE-2138) set the defaultValue for the leading column of an index excluding default key correctly
> SPLICE-2136 SPLICE-2138 fix issues related to index excluding default keys (2.7)

- splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/PropertyConglomerate.java
A new fix checking for system property "derby.language.logStatementText", config property "splice.debug.logStatementContext" and passing them down via startParams to PropertyConglomerate.
> SPLICE-2108 Can't disable logging statements

- assembly/pom.xml
> DB-6964 Missing io.airlift dependencies in cluster deployment

- hbase_storage/src/main/java/org/apache/hadoop/hdfs/ProxiedFilesystem.java
LocalFileSystem can support close but a HDFS File System will fail after closed.
> DB-6984 Remove the close of the file system

- hbase_sql/src/main/java/com/splicemachine/derby/stream/function/HFileGenerationFunction.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/BulkInsertDataSetWriter.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/client/BulkWriteAction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetWriter.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/output/delete/DeletePipelineWriter.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/output/insert/InsertPipelineWriter.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/output/update/UpdatePipelineWriter.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
- splice_machine/src/test/test-data/rows_count.csv
This is the first patch to fix one of the bugs in DB-6431.
`AbstractPipelineWriter` already write the rows count to `operationContext` based on `writeStats`. But there are some problems:
1. The `writeStats` returned from `BulkWriteAction` is not correct.
2. `SparkOperationContext` record the written rows to `pipelineRowsWritten`, which seems to be not used in anywhere.
3. Because of 2, `AbstractPipelineWriter` didn't write the row count into `rowsWritten`. Thus some pipeline writer re-add these counters. And when they add these counters, the data is still in buffer which may fail in later writes.
This patch fix these issues.
> DB-6431: Fix imported rows count and bad records count for IMPORT_DATA and HFILE_BULK_LOAD

- hbase_sql/pom.xml
- mem_sql/pom.xml
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
This reverts commit e49d0c6ada5f23c09fba123f942b2f9cc51966d3.
Upgrading the surefire plugin seems to have fixed the "VM crashed" errors on master, so we can remove this extra logging from master
> Revert "SPLICE-2064 Add logging on System.exit() calls (#1633)"

- platforms/std/docs/STD-installation.md
You should also probably fix the https://s3.amazonaws.com/splice-releases/2.7.0.1815/standalone/splicemachine-2.7.0.1815.tar.gz link at the bottom of the page, because 1) it doesn't work and 2) it's outdated
> Fixed anchor link and paths to shell scripts (included 'bin')

- hbase_sql/pom.xml
java.lang.NoSuchMethodError: org.apache.http.HttpHost.getAddress()Ljava/net/InetAddress;
is caused by malformed splice-uber.jar. Two incompatible jars are included:
> [INFO] Including org.apache.httpcomponents:httpcore:jar:4.2.4 in the shaded jar.
> [INFO] Including org.apache.httpcomponents:httpclient:jar:4.5.2 in the shaded jar.
> 
The former is a transitive dependency of
> [DEBUG]       org.apache.spark:spark-hive_2.11:jar:2.1.0:compile
> [DEBUG]          org.apache.thrift:libthrift:jar:0.9.2:compile
> [DEBUG]             org.apache.httpcomponents:httpcore:jar:4.2.4:compile
> 
spark_hive already excludes org.apache.httpcomponents:httpclient but not org.apache.httpcomponents:httpcore.
> DB-6931 Import from S3 failed on HDP 2.5.5 (2.5)

- .lgtm.yml
As mentioned here: https://github.com/splicemachine/spliceengine/pull/1857#issuecomment-391106700
This PR introduces a configuration file that instructs LGTM how to build the Java code for spliceengine.
Alert results are currently available here: https://lgtm.com/projects/g/splicemachine/spliceengine/alerts/?mode=tree
(Full disclosure: I work at Semmle, on the team responsible for LGTM.com)
cc @sjvs
> add lgtm.yml file for analysis of splicemachine/spliceengine on LGTM.com

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/JoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BaseJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/BroadcastJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/sequence/AbstractSequence.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/GeneratedColumnIT.java
[DB-7040](https://splicemachine.atlassian.net/browse/DB-7040):   Fix race condition in multi-row insert into identity column table which caused a duplicate primary key error.  Also, fix data corruption of insert into identity column table with a negative increment.
[SPLICE-2186](https://splice.atlassian.net/browse/SPLICE-2186):  Remove class variable missingHashKeyOK from JoinStrategy since multiple references to JoinStrategy are used in the code and updating missingHashKeyOK in a shared reference may be the cause of sporadic hash join related errors (possible regression of DB-6930).
>  DB-7040 + SPLICE-2186

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/JoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BaseJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/BroadcastJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/sequence/AbstractSequence.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/GeneratedColumnIT.java
[DB-7040](https://splicemachine.atlassian.net/browse/DB-7040):   Fix race condition in multi-row insert into identity column table which caused a duplicate primary key error.  Also, fix data corruption of insert into identity column table with a negative increment.
[SPLICE-2186](https://splice.atlassian.net/browse/SPLICE-2186):  Remove class variable missingHashKeyOK from JoinStrategy since multiple references to JoinStrategy are used in the code and updating missingHashKeyOK in a shared reference may be the cause of sporadic hash join related errors (possible regression of DB-6930).
> DB-7040 + SPLICE-2186 (2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/JoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BaseJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/BroadcastJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/sequence/AbstractSequence.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/GeneratedColumnIT.java
[DB-7040](https://splicemachine.atlassian.net/browse/DB-7040):   Fix race condition in multi-row insert into identity column table which caused a duplicate primary key error.  Also, fix data corruption of insert into identity column table with a negative increment.
[SPLICE-2186](https://splice.atlassian.net/browse/SPLICE-2186):  Remove class variable missingHashKeyOK from JoinStrategy since multiple references to JoinStrategy are used in the code and updating missingHashKeyOK in a shared reference may be the cause of sporadic hash join related errors (possible regression of DB-6930).
> DB-7040 + SPLICE-2186  (2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
…y cache for database property "derby.language.maxStatementLogLen"
> DB-7134 call getCachedDatabaseProperty() to take advantage of propert…(2.5)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
…y cache for database property "derby.language.maxStatementLogLen"
> DB-7134 call getCachedDatabaseProperty() to take advantage of propert…(2.7)

- hbase_sql/src/test/java/com/splicemachine/hbase/CheckTableIT.java
- mem_sql/src/main/java/com/splicemachine/derby/impl/sql/NoOpBackupManager.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupManager.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceTableAdmin.java
Adding a system procedure syscs_util.validate_backup to detect backup corruption caused by file transfer or media corruption, etc. The system procedure makes sure all files for the backup are in place and verifies their checksums.
Please also review ee branch.
> DB-6419: add validate_backup system procedure

- assembly/hdp2.6.3/build/var/lib/ambari-server/resources/common-services/SPLICEMACHINE/2.5.1/metainfo.xml
- assembly/hdp2.6.3/src/main/resources/common-services/SPLICEMACHINE/2.5.1/metainfo.xml
- assembly/hdp2.6.3/src/main/resources/common-services/SPLICEMACHINE/2.5.1/package/scripts/params.py
remove zeppelin and dependency when installing splicemachine using ambari service:
splicemachine doesn't need hive and zeppelin to function correctly, it is best it doesn't check their presence when installing.
> DB-7171:remove zeppelin and hive dependency when installing splicemachine using ambari service

- assembly/pom.xml
- hbase_sql/pom.xml
Apache Spark doesn't include spark-arvo jar, we need to package it in parcel and rpm.
Modified lines are 171, 592 in assembly/pom.xml and 55 in hbase_sql/pom.xml, other differences are spaces generated by editor for breaking lines.
> SPLICE-2116 Include spark-arvo in parcel/rpm

- assembly/common/src/main/resources/bin/sqlshell.sh
make username quoting the default, to be more friendly with ldap usernames like first.last@company.com
> DB-7214 (2.7) - always quote usernames

- assembly/common/src/main/resources/bin/sqlshell.sh
add an option '-U' to encapsulate a new feature to quote usernames
> DB-7296: remove the behavior to always quote usernames

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/test/resources/core-site.xml
- platforms/mapr6.0.0/pom.xml
Restored core-site.xml for testing. It selects LocalFileSystem instead of MapRFS, which is not ready to be used in ITs/standalone.
Removed _ from the name of a temporary directory used to infer avro schema. All such names are filtered out in PartitioningAwareFileIndex.shouldFilterOut() (spark-sql).
Fixed version in platforms/mapr6.0.0/pom.xml.
Tested with SPLICE-2219_v2 on centos7 (required for MapR6.0.0)
> DB-7302 MapR 6.0.0 ITs fixed

- assembly/standalone/template/bin/functions.sh
- assembly/standalone/template/bin/start-splice.sh
- start-splice-cluster
* In all of the scripts, fixed capture of ZooKeeper PID to be more
specific so as not to mistakenly capture non-ZooKeeper PIDs (this was
causing the Kafka PID to be captured, so no "Found Kafka" message was
ever shown since the Kafka process was already killed)
* In `start-splice.sh`, added OlapServerMaster to Splice PID capture
pattern to be consistent with the other scripts
* In `start-splice-cluster`, added `SpliceTestYarnPattern` to YARN PID
capture to be consistent with the other scripts
* Changed all occurrences of `Yarn` to `YARN` in messages for
consistency with existing occurrences
* Changed some punctuation in messages for consistency
> SPLICE-2231 Fix inconsistencies in start/stop scripts

- platforms/std/docs/STD-installation.md
Correct a number of errors in the instructions for installing Standalone
Splice Machine on Ubuntu Linux, such as:
* garbled commands due to missing newlines
* missing `sudo` in several commands
* incorrect packages (`openssh-client` and `openssh-server`, which
cannot be installed directly, instead of meta-package `ssh`, which
installs them)
* inconsistent use of `$` to represent the command prompt
* incorrect output redirection with commmand that requires `sudo`
Also, performed a bit of markdown format simplification and cleanup to
make the file more readable while editing, without affecting the
rendering.
> SPLICE-2230 Correct errors in Ubuntu instructions

- pom.xml
The following mvn commands are supported:
% mvn -Pcore clean install
% mvn -Pcore,ee clean install
% mvn -P`<platform>` clean install
% mvn -P`<platform>`,ee clean install
% mvn -P`<platform>`,`<assemble>` clean install
% mvn -P`<platform>`,ee,`<assemble>` clean install
% mvn -Pcore,`<platform>`,`<assemble>` clean install
% mvn -Pcore,`<platform>`,ee,`<assemble>` clean install
`<platform>`=mem|cdh5.12.0|hdp2.6.4|mapr6.0.0|...
`<assemble>`=parcel|installer|hdp_service.
> DB-7399 Make Splice fully buildable from spliceengine/pom.xml

- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
This is on branch 2.5. See #2214 and #2215 .
> DB-7393 Change Sentry related SQLState to keep it the same with branch master/2.7 (2.5)

- hbase_sql/pom.xml
The `commons-dbutils` test scope dependency is not transitively propagated from the `splice_machine` project.
Has to be explicitly specified where used.
> DB-7404 CheckTableIT fails to run in IDE

- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TimestampIT.java
This fixes the failing IT test point from SPLICE-1212, and re-enables its execution.
The fix is to reset autoCommit to false after the rollback.  Rollback has a side effect of setting autoCommit to true.
I also changed the IT to execute serially, since SpliceWatcher is not thread safe.
> DB-7377 Fix updateTest in TimestampIT.

- db-engine/src/main/java/com/splicemachine/db/iapi/services/loader/ClassInspector.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/MethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/StaticMethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/pyprocedure/PyCodeUtil.java
- hbase_sql/src/test/java/com/splicemachine/derby/transactions/PyFunctionIT.java
- hbase_sql/src/test/java/com/splicemachine/derby/transactions/PyProcedureIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/PyRoutineWrapper.java
Pull Request Message:
Added support for Python user-defined function that returns a single value.
This Branch is based on SPLICE-2029 and has rebased on build 2.8.0.1832.
For more detailed documentation please look at the google doc: https://docs.google.com/document/d/1KiEkLw3YKfoY6J3WKRYefVxE5uGhu3993rBKY3ZZrYk/edit?usp=sharing
The files that have been modified based on SPLICE-2029 by Ao are:
1. .../java/com/splicemachine/db/iapi/services/loader/ClassInspector.java
2. .../main/java/com/splicemachine/db/impl/sql/compile/MethodCallNode.java
3. .../java/com/splicemachine/db/impl/sql/compile/StaticMethodCallNode.java
4. .../main/java/com/splicemachine/db/impl/sql/pyprocedure/PyCodeUtil.java
5. .../src/test/java/com/splicemachine/derby/transactions/PyFunctionIT.java
6. …
> SPLICE-2204: Added support for Python user-defined function that returns

- platforms/std/docs/STD-installation.md
Tarball in the installation markdown returns a access denied code. The standalone tarball is updated to the new standalone link provided in the email/website.
> DB-7471 Update standalone tarball link

- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLDate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSTABLESRowFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/BatchOnceFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/marshall/dvd/DateV4DescriptorSerializer.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/marshall/dvd/V4SerializerMap.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/marshall/dvd/VersionedSerializers.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/FixedSITableScannerTest.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/marshall/BareKeyHashTest.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/marshall/dvd/DateV4DescriptorSerializerTest.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/test/TestingDataType.java
This changes the Date encoding from storing milliseconds to:
(year << 9) + (month << 5) + day
Which changes what's stored from a point in DateTime, to simply a pure date.
See [SPLICE-2239](https://splice.atlassian.net/browse/SPLICE-2239?focusedCommentId=27567&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-27567)
> SPLICE-2239 Version 4.0 Date serializer. Store year, month and day only, not time.

- splice_spark/src/main/spark2.1/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark2.2/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
Replace getCurrentUserCredentials(), which has been removed in Spark 2.3, with its effective implementation.
> DB-7495 Forward compatibility with Spark 2.3

- hbase_sql/src/main/java/com/splicemachine/fs/s3/PrestoS3FileSystem.java
Uses the AnonymousAWSCredentials() to create credentials if none is given. Allows S3A to download from public buckets.
> DBAAS-1817 Add Anonymous Login Creds for S3 

- pipeline_api/src/main/java/com/splicemachine/pipeline/PipelineDriver.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/traffic/AtomicSpliceWriteControl.java
- pipeline_api/src/test/java/com/splicemachine/pipeline/traffic/SpliceWriteControlTest.java
Use java.util.concurrent.atomic.LongAdder to update individual counters. Don't use WriteStatus as simultaneous updates of two counters don't have to be "transactional": f.e. it's OK to read dependentWriteThreads == 0 and dependentWriteCount != 0.
> DB-7545 SynchronousWriteControl creates contention

- platforms/std/docs/STD-installation.md
Eliminates the need to maintain the link along with stopping people from bypassing our main website download.
> DB-7572 Remove link in standalone install docs

- platforms/std/docs/STD-installation.md
Eliminates the need to maintain the link along with stopping people from bypassing our main website download.
> DB-7572 Remove link in standalone install docs (2.5)

- platforms/std/docs/STD-installation.md
Eliminates the need to maintain the link along with stopping people from bypassing our main website download.
> DB-7572 Remove link in standalone install docs (2.7)

- splice_spark/src/main/spark2.1/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark2.2/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark2.3/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
This is a new iteration on the same issue, the first PR was https://github.com/splicemachine/spliceengine/pull/2342
In this case I'm only making the broadcastCredentials a singleton, rather than the connection, and that should simplify things considerably
> DB-7566 Broadcast credentials for Spark adapter once per app

- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/SpliceRegionAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/AbstractFileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceDateFormatter.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceDateFunctions.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceDateFunctionsIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceDateFunctionsTest.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/test/DecoderIT.java
Import of dates which have a transition to daylight savings time at midnight in the Korean time zone fails.  See [SPLICE-2264](https://splice.atlassian.net/browse/SPLICE-2264?focusedCommentId=27629&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-27629).
> SPLICE-2264 Correctly import dates with a TZ transition at midnight.

- splice_machine/src/main/java/com/splicemachine/derby/stream/function/merge/AbstractMergeJoinFlatMapFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/MergeJoinIT.java
This is a performance enhancement for merge join to adjust the right table start key using the values from the first read row of the left table when there is a range term like join_col > 5.  
Without the range term present, we currently use the left table key value as the right table start key.
With the range term, this doesn't happen even though the left table value could be much greater than the constant value in the range term.  This fix will use the greater of the two start keys.
See [DB-7583](https://splicemachine.atlassian.net/browse/DB-7583?focusedCommentId=58106&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-58106) for more info.
> DB-7583 Adjust right start key of merge join based on first read left row.

- assembly/pom.xml
After discussing how to add the spark adapter, I added the spark adapter to the binary distributions since we currently already have the jars on nexus and having them on S3 would cause more issues with documentation/use.
> DB-7499 Add spark adapter to release package

- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextService.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMSQLUtil.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlOperationContext.java
- splice_machine/src/test/java/com/splicemachine/customer/Price.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceUDTIT.java
Ensure ContextManager is always setup after ActivationHolder deserialization (affects Control, OlapServer, Spark executors).
Tested: ITs (mem, cdh), TPC-H 100g, HTAP-25 in cluster.
Monitored RS, OlapServer, Spark executors for memory leaks (number of alive ContextManagers).
> DB-6913 Query fails when output of CONVERT_TO_DATE is used in GROUP BY clause

- assembly/mapr6.0.1/build/Makefile
- assembly/mapr6.0.1/build/sample.spec
- assembly/mapr6.0.1/build/splicemachine-mapr-hbase-bin.spec
- assembly/mapr6.0.1/build/splicemachine-mapr-hbase-conf.spec
- assembly/mapr6.0.1/build/splicemachine-mapr-master.spec
- assembly/mapr6.0.1/build/splicemachine-mapr-region.spec
- assembly/mapr6.0.1/templates/hbase-daemon.sh
- assembly/mapr6.0.1/templates/hbase-env.sh
- assembly/mapr6.0.1/templates/hbase-site.xml
- assembly/mapr6.0.1/templates/mapr-splice-hbase-config.sh
- assembly/mapr6.0.1/templates/splice-init-script
this initial set of files built rpms that worked on mapr 6.0.1, based on the same binary files compiled for mapr 6.0.0 and tested there. I think this structure therefore works on both versions of mapr 6
> DB-7553: Checking in initial working copies of rpm spec files (2.7)

- platforms/std/docs/STD-installation.md
changed from ```$ echo 'vm.swappiness = 0' &gt;&gt; /etc/sysctl.conf``` to ```$ sudo /bin/su -c "echo 'vm.swappiness = 0' >> /etc/sysctl.conf"```
> fixes vm.swappiness bash update syntax (2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UpdateNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UpdateOperationIT.java
If update target table has correlation name, set result columns (column.updated() is false) expression table name as target table's correlation name. 
Resolved the previous PR's UpportIT failed test case.
> SPLICE-1958 Fix reference column matching when update target table has alias

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
Set _spark.sql.broadcastTimeout_ to "infinity" by default
> DB-7647 query timed out after 300 seconds, Spark job finished successfully

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
Set _spark.sql.broadcastTimeout_ to "infinity" by default
> DB-7647 query timed out after 300 seconds, Spark job finished successfully (2.5)

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
Set _spark.sql.broadcastTimeout_ to "infinity" by default
> DB-7647 query timed out after 300 seconds, Spark job finished successfully (2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryComparisonOperatorNode.java
Remove the else block to postpone exception raise out. It addresses the failed RowId test in the previous PR.
> DB-7570 Handle RowId and String type compare

- platform_it/pom.xml
- pom.xml
- splice_spark/pom.xml
Set doclint to None since it would fail the build on Jenkins due to not every java function having the correct format. The doclint reduces the errors to warnings, thus letting the build on Jenkins to succeed. The javadoc jar would correctly be generated and the docs are similar to what is currently public.
> DB-7601 Add Profile to generate Scala and Javadoc

- platform_it/pom.xml
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatform.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
Don't copy 'test' scope artifacts to target/dependency (used by Yarn, Spark).
Minimize dependencies.
> SPLICE-2251 platform_it/pom.xml cleanup

- splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactor.java
- splice_si_api/src/test/java/com/splicemachine/si/SITransactorTest.java
Use effective begin timestamp when checking conflicts against rolled
back transactions
> DB-7779 Prevent rolled back txns from masking WW conflicts

- splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactor.java
- splice_si_api/src/test/java/com/splicemachine/si/SITransactorTest.java
Use effective begin timestamp when checking conflicts against rolled
back transactions
> DB-7779 Prevent rolled back txns from masking WW conflicts (2.7)

- splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactor.java
- splice_si_api/src/test/java/com/splicemachine/si/SITransactorTest.java
Use effective begin timestamp when checking conflicts against rolled
back transactions
> DB-7779 Prevent rolled back txns from masking WW conflicts (2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/services/io/AccessibleByteArrayOutputStream.java
A bug in the original Derby code.
> SPLICE-2288 IndexOutOfBoundsException while loading a resource from a jar file

- db-engine/src/main/java/com/splicemachine/db/iapi/services/io/AccessibleByteArrayOutputStream.java
A bug in the original Derby code.
> SPLICE-2288 IndexOutOfBoundsException while loading a resource from a jar file (2.7)

- assembly/hdp2.6.4/build/var/lib/ambari-server/resources/common-services/SPLICEMACHINE/2.5.1/service_advisor.py
- assembly/hdp2.6.4/src/main/resources/common-services/SPLICEMACHINE/2.5.1/service_advisor.py
fix hdp version and add props for backup functions:
1.fixed hdp version for hdp2.6.4
2.added props for backup functions to work
3.remove ranger coprocessor from "hbase.coprocessor.regionserver.classes"
> DB-7646: fix properties issues in custom ambari service in hdp2.6.4 of branch-2.7

- platform_it/pom.xml
hdp2.6.5 on standalone is broken by version conflict of com.fasterxml.jackson.core:jackson-databind,this fixes it by excluding from kafka's dependency.
> DB-7918: fix hdp2.6.5 on standalone by excluding kafka dependency

- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLArray.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLReal.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/ValueRow.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinCache.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ValueRowMapTableLoader.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ValueRowMappedJoinTable.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/BroadcastJoinIT.java
This fixes broadcast join on the control path when the join columns are both numeric, but different data types, e.g.  decimal = real, double = float.
See [SPLICE-2304](https://splice.atlassian.net/browse/SPLICE-2304?oldIssueView=true) for more details.
> SPLICE-2304 Wrong results in broadcast join with numeric data types.

- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedPreparedStatement.java
Refactor to avoid an endless loop in a critical section.
> DB-7854 Deadlock in EmbedPreparedStatement.getMetaData()

- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedPreparedStatement.java
Refactor to avoid an endless loop in a critical section.
> DB-7854 Deadlock in EmbedPreparedStatement.getMetaData() (2.7)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/IndexRowReader.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/IndexRowReaderBuilder.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/IndexRowToBaseRowOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/IndexRowReaderTest.java
This fix decouples the selected max concurrency of index row lookups from optimizer row count estimates.  For large number of rows, we should still allow concurrency, even if the optimizer predicted we have less rows.
More info in: [SPLICE-2291](https://splice.atlassian.net/browse/SPLICE-2291?oldIssueView=true)
> SPLICE-2291 Avoid slow IndexLookups when row count estimates are bad.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OrNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/InListMultiprobeIT.java
There are some problems with the part of DB-7621 which converts predicates like (a = 1 and b = 2) or (a = 3 and b = 4) into (a,b) in ((1,2), (3,4)):
1. There was no checking in canConvertToInList that we found at least one column in the OR'ed predicate.
2. There was no checking that we have IN list probe predicates when more than one column is in the predicates. Predicates such as "a in (1,2) or a in (3,4)" can be combined, but the code wasn't meant to handle terms such as "a1 in (1,2) and b1 in (10,20) or a1 in (1,3) and b1 in (30,40)"
3. There was no checking that a column had already been added to the columnNumbers list and columns HashMap, and so we get duplicates sometimes, when each unique column is only supposed to be added once.
I have added the above checks plus some more test …
> SPLICE-2306 NPE in query with multiple AND'ed and OR'ed IN lists.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowResultSetNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/AggregateAndArithmeticOverflowIT.java
Fixes an incorrect result regression from DB-7960, caused by adding a CAST operator in a window function.
The root cause is poor support for expressions in aggregate functions of complex window function queries.
For details, please see [DB-8082](https://splicemachine.atlassian.net/browse/DB-8082?focusedCommentId=60300&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-60300).
> DB-8082 Fix DB-7960 regression

- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampClient.java
- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampServer.java
Disable Nagle's algorithm responsible for delays obtaining timestamps (transaction IDs) from the oracle.
> DB-8155 set tcpNoDelay to true in TimestampClient

- splice_machine/src/main/java/com/splicemachine/SpliceKryoRegistry.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictSparkExpressionIT.java
Kryo changes prevented timestamps stored in stats in serialized form to no longer be readable, so DROP TABLE on a table with stats before SPLICE-2301 is failing.  The Kryo changes were added to fix incorrect results.  DB-8206 is opened to re-do this fix.
> DB-8205 Undo Kryo change from SPLICE-2301.

- db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/RSUtils.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BaseTableNumbersVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SetOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/NestedLoopJoinOperationIT.java
A second submission for DB-8200. This has the additional fix to address the intermittent wrong result exposed in the IT. For more details of the problem and fix, please see [this comment in DB-8200](https://splicemachine.atlassian.net/browse/DB-8200?focusedCommentId=61038&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-61038).
> DB-8200 fix NPE and wrong result for nested loop join with UNION operation as right table

- mem_sql/pom.xml
- splice_machine/pom.xml
- sqlj-it-procs/pom.xml
- txn-it-procs/pom.xml
Use `scala.binary.version` (not a hardcoded Scala version)
> [MINOR][BUILD] Use scala.binary.version (not a hardcoded Scala version)

- db-shared/src/main/resources/com/splicemachine/db/info/DBMS.properties
- db-shared/src/main/resources/com/splicemachine/db/info/dnc.properties
- db-shared/src/main/resources/com/splicemachine/db/info/net.properties
- db-shared/src/main/resources/com/splicemachine/db/info/tools.properties
roll back changes to DRDA maintenance code
Rolling this back as just a temporary measure in the 2.7 branch only just to resolve the current ODBC issue. Will investigate a long term approach in the next couple of weeks.
> DB-8296 Roll back changes to DRDA maintenance code to re-enable ODBC

- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/TxnLifecycleEndpoint.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/region/RegionTxnStore.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
Use try-with-resources to ensure underlying scanners are closed and associated memory is released (when MemStoreLAB is enabled).
Reduce splice.txn.completedTxns.cacheSize for ITs to ease memory pressure.
> SPLICE-2364 Properly close internal region scanners

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/CrossJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/CrossJoinIT.java
Fixes wrong results due to a filter predicate getting lost when using cross join strategy for a single-table scan.
See [DB-8492](https://splicemachine.atlassian.net/browse/DB-8492)
> DB-8492 Wrong results when cross join strategy is used for TableScan.

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/JoinOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MergeSortJoinOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/BroadcastJoinIT.java
Wrong results can occur when executing joining on columns of the Real data type and the join is done natively on spark.  Execute the join via Splice functions in this case.
[DB-8204](https://splicemachine.atlassian.net/browse/DB-8204)
> DB-8204 Avoid native spark SortMergeJoin involving the Real data type.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/subquery/aggregate/AggregateSubqueryPredicate.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIndexIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/TPCHIT.java
- splice_machine/src/test/java/com/splicemachine/subquery/SubqueryITUtil.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_Aggregate_IT.java
Please see [DB-8480](https://splicemachine.atlassian.net/browse/DB-8480) for details.
There is an IT update in ee branch, please review the corresponding [PR#378](https://github.com/splicemachine/spliceengine-ee/pull/378)
> DB-8480 do not flatten non-correlated scalar aggregate subquery

- splice_machine/src/main/java/com/splicemachine/derby/lifecycle/EngineLifecycleService.java
Closing an internal connection needs to get a timestamp to start a txn. However, timestamp server may have shutdown. This will cause retry and prevent region server to shutdown within graceful shutdown timeout
> DB-DB-8536: No need to close internal connections during shutdown

- splice_machine/src/main/java/com/splicemachine/derby/lifecycle/EngineLifecycleService.java
Closing an internal connection needs to get a timestamp to start a txn. However, timestamp server may have shutdown. This will cause retry and prevent region server to shutdown within graceful shutdown timeout
> DB-DB-8536: No need to close internal connections during shutdown (2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/CreateTableWithDataIT.java
A comment in CREATE TABLE ... AS, such as the following:
```
create table mws.t2 as
select * from mws.t1 --comment
where a = 1;
```
... masks out the rest of the SELECT.  In this case, it would mask out the WHERE clause, leading to an incorrect table definition.  The fix is in sqlgrammar.jj, to use a newline separator instead of single space.
[DB-8193](https://splicemachine.atlassian.net/browse/DB-8193)
> DB-8193 Comments in CTAS mask the rest of the SELECT statement.

- splice_machine/src/main/java/com/splicemachine/derby/stream/function/AbstractFileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceDateFunctions.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceDateTimeFormatter.java
Fixes a performance regression in IMPORT_DATA due to DateTime formatters not being built when AbstractFileFunction is deserialized, causing a new SpliceDateTimeFormatter object to be built for every row which is imported.
I also added static formatters, which can be used if TO_DATE, TO_TIME or TO_TIMESTAMP are called with no format specified (which may help performance if these functions are used in a SELECT query reading many rows).
> DB-8604 Deserialize SpliceDateTimeFormatters in AbstractFileFunction.

- splice_machine/src/test/java/com/splicemachine/test/SpliceTestPlatformWait.java
ITs run in Jenkins sporadically fail when multiple tests are run. It's worse now that we have 4 releases to build.  Increasing the timeout will give enough time for splice to come up.
> DB-8655 Increase time allowed for splice to come up when running ITs.

- platform_it/src/test/jmeter/tpch1.jmx
tested on against splice standalone master 3.1.0.1928-SNAPSHOT, attempting to fix the following build pipeline error:
http://nexus.splicemachine.com:8080/job/spliceengine-master/job/test-tpch1-spliceengine-master/1418/platform=cdh5.12.2/artifact/platform_it/src/test/jmeter/logs/tpch1/assertion-results.html
> DB-8579: fixed false positives in tpch1 on account of the rounding changes in SPLICE-2302

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinOperation.java
Reverts splicemachine/spliceengine#2845
Causes a regression on HBase 2.0, documented in [DB-8660](https://splicemachine.atlassian.net/browse/DB-8660)
> Revert "SPLICE-2377 Always use native spark broadcast join, if possible (3.0)"

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CostEstimate.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Optimizable.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/LimitOffsetVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CostEstimateImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DistinctNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromVTI.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OrderByList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RowResultSetNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectivityUtil.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnionNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/BroadcastJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/CrossJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/HalfMergeSortJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SimpleCostEstimate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/StoreCostControllerImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/TempGroupedAggregateCostController.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/TempScalarAggregateCostController.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/TempSortController.java
This PR addresses join costing issues which prevent merge join from being selected by the join planner in queries with many join tables with large data sets.
Fixes:
1. Give localCost and remoteCost consistent units when costing joins.
2. Add sort cost estimates to the MergeSortJoin cost formula.
3. Update nested loop join costing to reflect the network bottleneck of retrieving inner table rows via RPC requests.
See [SPLICE-2369](https://splice.atlassian.net/browse/SPLICE-2369?focusedCommentId=27871&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-27871)
I will remove the changes in platform_it/pom.xml, SpliceTestPlatformConfig.java and SpliceTestYarnPlatform.java before merging.
> SPLICE-2369 Fix join costing involving large data sets.

- platform_it/pom.xml
Zookeeper fails to start during some IT runs, causing failures.
The following was seen in the logs: 
> Listening for transport dt_socket at address: 4002
Sometimes this situation causes the process to suspend until the debugger is attached, even though "suspend=n" is specified.
> DB-8677 Comment out ZK maven debugging option to avoid IT hangs.

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
Calling SYSCS_PERFORM_MAJOR_COMPACTION_ON_SCHEMA attempts to perform major compaction on the all tables in the schema, including external tables, which errors out since external tables aren't backed by HBase tables.  This causes compaction to not run on all tables in the schema.
`create external table t1 (a int, b int)
STORED AS PARQUET
LOCATION '/tmp/t1';
CALL SYSCS_UTIL.SYSCS_PERFORM_MAJOR_COMPACTION_ON_SCHEMA('MWS');
splice> ERROR SE001: Splice Engine exception: unexpected exception
ERROR XJ001: Java exception: 'splice:3536: org.apache.hadoop.hbase.TableNotFoundException'.
`
> SPLICE-1504 Skip compaction of external tables.

- splice_encoding/src/main/java/com/splicemachine/encoding/BigDecimalEncoding.java
- splice_encoding/src/main/java/com/splicemachine/encoding/ScalarEncoding.java
Eliminated extra copying. Took advantage of _new BigDecimal(long)_.
> DB-8718  BigDecimalEncoding.toBigDecimal() is expensive

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorToString.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictSparkExpressionIT.java
Fixes a regression of SPLICE-2301.  The BETWEEN clause in a native spark projection is translated to Spark SQL as: BETWEEN (_expr1_,_expr2_)   ...  but should be:   BETWEEN _expr1_ AND _expr2_.
> SPLICE-2385 Fix BETWEEN clause in native Spark projections.

- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/SpliceRegionAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/AbstractFileFunction.java
Initialize _calendar_ in the default constructor.
> SPLICE-2387 AbstractFileFunction.getRow() instantiates too many Calendar (3.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/SpliceRegionAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/AbstractFileFunction.java
Initialize _calendar_ in the default constructor.
> SPLICE-2387 AbstractFileFunction.getRow() instantiates too many Calendars

- hbase_storage/src/main/java/com/splicemachine/access/HConfiguration.java
_StripedTxnLifecycleStore_ requires a lock for each transaction. _LongStripedSynchronizer_ provides a pre-created set of read-write locks which are reused for multiple transactions  based on their id hash. It, thus, becomes possible to use the same lock by totally unrelated transactions.
The number of locks is tied to _hbase.regionserver.handler.count_ - the number of threads processing RPCs in the default thread pool. Due to hash collision, many threads will be using the same lock even if they are processing unrelated transactions.
Implement a new splice property to configure the number of locks independently. Define the default value of that property to be a multiple of _hbase.regionserver.handler.count_.
> DB-8821 Read-write lock contention in StripedTxnLifecycleStore

- db-client/src/main/java/com/splicemachine/db/client/am/PreparedStatement.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DecimalIT.java
JDBC programs that use  "void setObject(int parameterIndex, Object x, int targetSqlType)"
to specify a Decimal input parameter to a prepared statement end up getting Decimal values with the  fractional digits truncated.
The spec says a scale of 0 is implied:
https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#setObject(int,%20java.lang.Object,%20int)
This should probably be a default for data types that have no scale (such as Double).
This Jira changes the behavior to retain the scale from the Decimal source object, e.g.
BigDecimal bd = new BigDecimal("14.51");
statement.setObject(1, bd, Types.DECIMAL);
... will create a Decimal input parameter of 14.51, where previously the value 14 was created.
Source data types such as Double, which have no specific scale, still …
> DB-8770 Inherit decimal scale from the input parameter in PreparedStatement.setObject

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/UnionOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/NonOrderPreservingFutureIterator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DecimalIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/actions/index/IndexIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/OuterJoinOrderByEliminationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/complextypes/SQLArrayIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/RecursiveWithStatementIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TernaryOperationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UnionOperationIT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_Exists_IT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_NotExists_IT.java
- splice_machine/src/test/test-data/expressions/SparkExpressionTables.sql
For union-all operation that takes control execution, instead of always returning rows from the first union branch, return from the branch whose rows become available first.
> DB-8132 return first available union branch first

- hbase_sql/src/main/java/com/splicemachine/hbase/HBaseRegionLoads.java
My previous PR had a problem because the cache wasn't initialized for a long time, functions like tableLoad() could try to .put() values into a null map.
Now I initialize the cache to an empty Map and schedule the first update right away, the rest will continue to be staggered.
> DB-8167 Stagger region load refreshes

- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- platforms/cdh6.3.0/docs/CDH-installation.md
_hbase.rowlock.wait.duration = 0_ is no longer supported. The default value, 30 sec, appears adequate.
> DB-8841 HMaster fails to initialize after Splice installation on CDH 6.3.1 (3.0)

- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceTest.scala
the failure would happen in avg once every 5! (120) execution.
It now would happen once every 20! (2,432902008E18).
> DB-8921 Make sporadic failure in test much less likely

- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceTest.scala
the failure would happen in avg once every 5! (120) execution.
It now would happen once every 20! (2,432902008E18).
> DB-8921 Make sporadic failure in test much less likely (2.7)

- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceTest.scala
the failure would happen in avg once every 5! (120) execution.
It now would happen once every 20! (2,432902008E18).
> DB-8921 Make sporadic failure in test much less likely (2.8)

- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceTest.scala
the failure would happen in avg once every 5! (120) execution.
It now would happen once every 20! (2,432902008E18).
> DB-8921 Make sporadic failure in test much less likely (3.0)

- hbase_storage/src/main/java/com/splicemachine/hbase/SpliceRpcSchedulerFactory.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/SkeletonTxnNetworkLayer.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SIConfigurations.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnFilter.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactor.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/store/CompletedTxnCacheSupplier.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/txn/AbstractTxn.java
DB-8796 High GC overhead during OLTP workload
DB-8806 CompletedTxnCache is expensive
DB-8789 Apparent deadlock during OLTP workload
Greatly reduces overhead from getTransaction() RPCs - a bottleneck for OLTP workloads like TPC-C and HTAP.
Introduces RPC priorities and a new _SpliceRpcSchedulerFactory_ to enable them (but not a Splice scheduler yet).
> DB-8806 and oth.: improve OLTP performance

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TableScanOperationIT.java
Note:
DB2 supports the syntax for ROW and ROWS both and does not care n (n > 0) is singular or plural.
> DB-8933 Support Syntax OPTIMIZE FOR n ROWS

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/TriggerExecutionContext.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_When_Clause_IT.java
Fixes a trigger execution bug when the trigger table is altered and the trigger action statement it a SET statement, e.g.  'SET new.col1 = 1'.
[DB-8974](https://splicemachine.atlassian.net/browse/DB-8974)
> DB-8974 Recompilation of "SET" trigger fails with syntax error.

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/AggregateAndArithmeticOverflowIT.java
The Derby optimizer projects inner table columns of semijoin or antijoin sometimes.
When using native Spark execution, the inner table columns are not included in the data frame, so attempting to project out nonexistent inner table columns results in an AnalysisException.
The fix is to modify the join data frame to add nulls for the inner table columns when we have a subquery.  
See description in [DB-9024](https://splicemachine.atlassian.net/browse/DB-9024).
> DB-9024 Subquery with IN or NOT IN hits AnalysisException when native spark execution is used.

- hbase_storage/src/main/java/com/splicemachine/storage/ClientPartition.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/callbuffer/PipingCallBuffer.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/writehandler/PartitionWriteHandler.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/writehandler/RoutingWriteHandler.java
Extensively tested in bespoke/AWS with TPC-C. Runs are much cleaner and there is also some noticeable performance improvement (up to 10%; tpmC ~= 32K in a 4 node cluster).
> SPLICE-1806 NullPointerException in PipingCallBuffer (3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextManager.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionFactory.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
Reverts a couple last-minute changes to DB-8883 which cause ITs to fail in mem.
The changes were:
1. Addition of synchronization in ContextManager.
2. Sharing the same session number between all LanguageConnectionContexts used by parallel triggers (so the logs would nicely show all triggers for a given SQL fired in the same "session".
> DB-8883 Fix IT failures on mem platform.

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/MergeJoinCostingIT.java
Merge join is driven from the left table, and we read all qualified rows from the beginning of that table.
When the left table is large and the right table is small (e.g. 1 row), we may need to read, on average, half of the large table before we find a matching row in the right table.  If we made the small table the left table, we could read the 1 row quickly, then jump immediately to the matching row in the large table.
The problem is that the right table read costs assume that the entire table is read, so when the cost of joining rows is small, this read cost may dominate and favor selection of the large table as the left table.
Merge join costing already calculates the selectivities of scanning the right (inner) table during the merge join, and join selectivity in computing total rows: …
> DB-9101 Reduce merge join right table scan costs when left table is small.

- assembly/mapr/src/main/resources/scripts/splice/hbase-env.sh
One line change to switch the order of how the jars are located for MapR 6.1 executors.
> DB-9228 Fix MapR executor configuration (2.8)

- hbase_storage/src/main/java/com/splicemachine/access/client/SkeletonClientSideRegionScanner.java
Workaround for HBase issue where HFile scanners are opened but not
closed for Memstore-only scans, PREAD scanners don't hold any resources
so it's fine not to close them, but STREAM scanners do and leak
resources in this case.
> DB-9265 Make memstore-only scanners PREAD instead of STREAM

- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/OperationManagerImpl.java
Use ThreadLocalRandom when secure random is not a strong requirement.
> DB-9326 java.util.UUID.randomUUID() creates thread contention

- platform_it/pom.xml
Restore dependency on _splice_sentry_.
See corresponding PR for spliceengine-ee.
> DB-9347 Fix sentry dependency in platform_it/pom.xml

- platform_it/pom.xml
Make dependency on _splice_sentry_ conditional (when _ee_ profile is enabled).
See corresponding PR for spliceengine-ee.
> DB-9347 Fix sentry dependency in platform_it/pom.xml (3.0)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkTableChecker.java
- hbase_sql/src/test/java/com/splicemachine/hbase/CheckTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/CheckTableJob.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/DistributedCheckTableJob.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/KeyByRowIdFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlTableChecker.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/IndexTransformFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/TableChecker.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceTableAdmin.java
Implement syscs_util.fix_table to make base table and index consistent.
> DB-6542: create missing index rows

- hbase_storage/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/src/main/java/com/splicemachine/storage/HScan.java
Set default caching for HBase scans to avoid very large scans causing
memory pressure on RegionServers
> DB-9408 Harmonize peek() and next() on MemStoreFlushAwareScanner

- hbase_storage/hbase1.1.1/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.2.2.6-129/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.2.2.6/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.8/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/src/main/java/com/splicemachine/storage/HScan.java
Set default caching for HBase scans to avoid very large scans causing
memory pressure on RegionServers
> DB-9408 Harmonize peek() and next() on MemStoreFlushAwareScanner (2.8)

- hbase_storage/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/src/main/java/com/splicemachine/storage/HScan.java
Set default caching for HBase scans to avoid very large scans causing
memory pressure on RegionServers
> DB-9408 Harmonize peek() and next() on MemStoreFlushAwareScanner (3.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
also executed field has been removed as nowhere used to clean up
> DB-9156 3.0 startTime, badRecords, returnedRows added to reset()

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTablePartitionIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/catalog/ViewsInSysIbmIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ShowCreateTableIT.java
in the previous version the temporary directory gets deleted after every test,
however the table gets only deleted after the whole class shuts down,
so e.g. analyze schema fails as it can't access those tables anymore
what will happen now:
- before instantiating a test class like, e.g. ExternalTableIT would go to /platform_it/target/external + /SCHEMA_NAME,
e.g. /platform_it/target/external/EXTERNALTABLEIT, wipe that directory (with @BeforeClass)
- we then run all tests, create external tables in that subdirectory (e.g. .../external/EXTNERALTABLEIT/avro_simple_file_test etc.)
- at the end of the whole class @AfterClass, delete the temporary directory (target/external/EXTERNALTABLEIT), but not all of target/external
with this
- allows parallel runs of ExternalTableIT while running …
> DB-9109 fix jenkins problem with testCollectStats

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumnList.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/OrderByIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
e.g. as in
select C as C2+1 from A order by -C2;
> DB-9434 ORDER BY can use the aliases defined in SELECT AS

- hbase_sql/src/main/java/com/splicemachine/stream/StreamListener.java
NPE could occur because we used putIfAbsent that can return null no
value was found
ComputeIfAbsent returns the computed value or the present value.
Additionally, we do not create a new object if not necessary
> DB-9511 Fix NPE in StreamListener

- hbase_sql/src/main/java/com/splicemachine/stream/StreamListener.java
NPE could occur because we used putIfAbsent that can return null no
value was found
ComputeIfAbsent returns the computed value or the present value.
Additionally, we do not create a new object if not necessary
> DB-9511 Fix NPE in StreamListener (2.8)

- hbase_sql/src/main/java/com/splicemachine/stream/StreamListener.java
NPE could occur because we used putIfAbsent that can return null no
value was found
ComputeIfAbsent returns the computed value or the present value.
Additionally, we do not create a new object if not necessary
> DB-9511 Fix NPE in StreamListener (3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/error/ExceptionUtil.java
- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/SpliceIndexEndpoint.java
- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/SpliceIndexObserver.java
This fix prevents use of HRegion before it's fully opened.
> DB-9437 Register writePipeline only after region is fully open

- hbase_sql/src/main/java/com/splicemachine/compactions/SpliceCompactionRequest.java
- hbase_sql/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactionPolicy.java
- hbase_sql/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/src/main/java/com/splicemachine/hbase/RegionSizeEndpoint.java
- hbase_storage/src/main/java/com/splicemachine/access/client/MemstoreAware.java
- hbase_storage/src/main/java/com/splicemachine/access/client/SkeletonClientSideRegionScanner.java
- hbase_storage/src/main/java/com/splicemachine/access/client/SpliceHRegion.java
- hbase_storage/src/main/java/com/splicemachine/storage/AdapterPartition.java
- hbase_storage/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/src/main/java/com/splicemachine/storage/SkeletonHBaseClientPartition.java
- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
- platform_it/src/main/resources/info-log4j.properties
- splice_protocol/src/main/protobuf/Splice.proto
Migration to hbase2.0 created two issues:
1. We did not use memStoreAware's lock properly anymore
2. We did not know about compacted files when creating a HRegion from
Spark's side
This commit addresses these two issues in the following way:
1.
SpliceCompactionRequest.setOffPeak is now hijacked to properly
release the lock on memStoreAware once a compaction has completed.
Short of modifying HBase's code to be able to use a custom
CompactionLifeCycleTracker (only DUMMY is used outside of their tests),
this seems to be the only reliable solution.
2.
Spark side now RPC calls the relevant region to get a list of compacted
files so that regions created on Spark side can properly exclude
compacted store files that pertains to a specific region.
> DB-9448 Fix resurfacing rows issue in Spark

- hbase_sql/src/main/java/com/splicemachine/hbase/HBaseRegionLoads.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/AbstractSMInputFormat.java
- hbase_sql/src/test/java/com/splicemachine/hbase/SpliceRegionAdminIT.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/RegionSplitsIT.java
- hbase_storage/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/src/main/java/com/splicemachine/storage/HPartitionLoad.java
- hbase_storage/src/main/java/com/splicemachine/storage/HServerLoad.java
- mem_storage/src/main/java/com/splicemachine/storage/MPartitionLoad.java
- splice_access_api/src/main/java/com/splicemachine/storage/PartitionLoad.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/IndexConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/RegionLoadStatistics.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/CheckTableJob.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
Fix RegionSplitsIT and don't require /BAD directory to exist for
SpliceRegionAdminIT
> DB-9540 Make RegionLoads use bytes instead of MBs

- hbase_sql/src/main/java/com/splicemachine/hbase/HBaseRegionLoads.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/AbstractSMInputFormat.java
- hbase_sql/src/test/java/com/splicemachine/hbase/SpliceRegionAdminIT.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/RegionSplitsIT.java
- hbase_storage/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/src/main/java/com/splicemachine/storage/HPartitionLoad.java
- hbase_storage/src/main/java/com/splicemachine/storage/HServerLoad.java
- mem_storage/src/main/java/com/splicemachine/storage/MPartitionLoad.java
- splice_access_api/src/main/java/com/splicemachine/storage/PartitionLoad.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/IndexConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/RegionLoadStatistics.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/CheckTableJob.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
Fix RegionSplitsIT and don't require /BAD directory to exist for
SpliceRegionAdminIT
> DB-9540 Make RegionLoads use bytes instead of MBs (3.0)

- hbase_sql/src/main/java/com/splicemachine/hbase/HBaseRegionLoads.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/AbstractSMInputFormat.java
- hbase_sql/src/test/java/com/splicemachine/hbase/SpliceRegionAdminIT.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/RegionSplitsIT.java
- hbase_storage/hbase1.1.1/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/hbase1.1.2.2.6-129/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/hbase1.1.2.2.6/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/hbase1.1.8/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/src/main/java/com/splicemachine/storage/HPartitionLoad.java
- hbase_storage/src/main/java/com/splicemachine/storage/HServerLoad.java
- mem_storage/src/main/java/com/splicemachine/storage/MPartitionLoad.java
- splice_access_api/src/main/java/com/splicemachine/storage/PartitionLoad.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/IndexConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/RegionLoadStatistics.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/CheckTableJob.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
Fix RegionSplitsIT and don't require /BAD directory to exist for
SpliceRegionAdminIT
> DB-9540 Make RegionLoads use bytes instead of MBs (2.8)

- hbase_sql/src/test/java/com/splicemachine/hbase/SnapshotIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/Vacuum.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SimpleDateArithmeticIT.java
Explicitly close connection in an @AfterClass method.
> DB-9590 SnapshotIT leaves an active transaction, breaks vacuuming during ITs

- platform_it/src/test/bin/start-splice-its
The reason is a leftover OlapServerMaster process that is not recognized by the start-splice-its script. If there are no other Splice related processes, the stop-splice-its script is not invoked and the already running OlapServerMaster process is not killed. The new OlapServerMaster process tries to bind to the same debugging port and fails.
> DB-9605 OlapServerMaster fails to start during ITs 

- platform_it/src/test/bin/stop-splice-its
Integration tests appear to get stuck for hours on the first test (BackupManagerLoaderIT).
The reason is SpliceTestYarnPlatform failed to start. The error in platform_it/target/yarn_it.log indicates that the failure occurred when binding to spark.shuffle.service.port, 8061.
The port is owned by the previous SpliceTestYarnPlatform process, which was missed by the stop-splice-its script.
Incidentally, the start-splice-cluster script has been fixed in that regard.
> DB-9609 SpliceTestYarnPlatform fails to start during ITs 

- hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/HEngineSqlEnv.java
- hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/OlapServerProviderImpl.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/OlapConfigurations.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
New config: "splice.olap_server.maxRetries" = 30
Set "hbase.client.retries.number" to 35 for ITs (as in 2.8).
> DB-9645 OlapServerIT.testKillOlapServer fails with OlapServerNotReadyException

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SparkFlushMissingRowsIT.java
- hbase_storage/hbase1.1.1/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.1/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.1.13/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.13/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.1.2.2.6-129/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.2.2.6-129/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.1.2.2.6/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.2.2.6/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.1.8/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.1.8/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/src/main/java/com/splicemachine/access/client/CountingRegionScanner.java
- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
If a flush happened during a Spark scan, the flush token that is
returned by MemStoreFlushAwareScanner would be marked with timestamp 0
and would therefore be read before any other cell.
However, when the scanner fetches a row, it first reads from the mem
store, then from hfiles. The flush token would prevent us from reading
from hfiles for that row and we would resume the scan at the next row.
We addressed the issue by making sure that the flush token will be
sorted exactly after the last row that was being scanned, so that we can
properly merge data from MemStore and HFiles before addressing the flush
and resetting scanners
> DB-9449 Fix spark scan issue that missed a row during flush (2.8)

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SparkFlushMissingRowsIT.java
- hbase_storage/src/main/java/com/splicemachine/access/client/CountingRegionScanner.java
- hbase_storage/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/src/main/java/com/splicemachine/access/client/SkeletonClientSideRegionScanner.java
- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
- platform_it/src/main/resources/info-log4j.properties
If a flush happened during a Spark scan, the flush token that is
returned by MemStoreFlushAwareScanner would be marked with timestamp 0
and would therefore be read before any other cell.
However, when the scanner fetches a row, it first reads from the mem
store, then from hfiles. The flush token would prevent us from reading
from hfiles for that row and we would resume the scan at the next row.
We addressed the issue by making sure that the flush token will be
sorted exactly after the last row that was being scanned, so that we can
properly merge data from MemStore and HFiles before addressing the flush
and resetting scanners
> DB-9449 Fix spark scan issue that missed a row during flush (3.0)

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SparkFlushMissingRowsIT.java
- hbase_storage/src/main/java/com/splicemachine/access/client/CountingRegionScanner.java
- hbase_storage/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
- hbase_storage/src/main/java/com/splicemachine/access/client/SkeletonClientSideRegionScanner.java
- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
- platform_it/src/main/resources/info-log4j.properties
If a flush happened during a Spark scan, the flush token that is
returned by MemStoreFlushAwareScanner would be marked with timestamp 0
and would therefore be read before any other cell.
However, when the scanner fetches a row, it first reads from the mem
store, then from hfiles. The flush token would prevent us from reading
from hfiles for that row and we would resume the scan at the next row.
We addressed the issue by making sure that the flush token will be
sorted exactly after the last row that was being scanned, so that we can
properly merge data from MemStore and HFiles before addressing the flush
and resetting scanners
> DB-9449 Fix spark scan issue that missed a row during flush

- splice_spark/pom.xml
- splice_spark2/pom.xml
Requires -Dnsds2jar to be added to the mvn command so that the jar will be built.
Example: mvn -P core,cdh6.3.0,ee -DskipTests -Dnsds2jar clean install
The jar will be at splice_spark2/target/splice_spark2-3.1.0.1959-SNAPSHOT-shaded.jar
The jar size in my env was about 120 MB.
> DB-9597 NSDS v2 Build Jar

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DMLStatementNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/FlattenedOuterJoinIT.java
…pass costing for control and spark.
> DB-9593 reset the variable optimized for JoinNode in-between the two-…(2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DMLStatementNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/FlattenedOuterJoinIT.java
…pass costing for control and spark.
> DB-9593 reset the variable optimized for JoinNode in-between the two-…(3.0)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
SparkDataSetProcessor.getExternalFileSchema was copying one file out of the location so that the schema infer is only looking at one file (performance optimization). In the case that we can't access that file, we fall back to the normal behavior.
> DB-9465 external tables shouldn't write when only reading

- docker/Dockerfile
- docker/entrypoint.sh
- docker/start.sh
- docker_run.sh
- docker_start-splice_cluster.sh
- start-splice-cluster
- fixed issue with nc in start-splice-cluster on linux
used base image for docker is maven:3.6.3-jdk-8 .
both docker_run.sh and docker_start-splice-cluster.sh do:
- to be able to sqlshell.sh into the container, we are exposing the containers' port 1527
as port 2527 for the host, so you can connect from host e.g. with
./sqlshell.sh -h localhost -p 2527
- to re-use the $HOME/.m2/settings.xml and the already downloaded
maven dependencies, we map the path $HOME/.m2 of host to
/root/.m2 inside of the container (since $HOME=/root, this mimicks $HOME/.m2 in the container)
- to have access to the source, we map $(pwd) to /usr/src/
- we cd into /usr/src in the container.
With these preparation steps, you can then just instantiate mvn,
short scripts are:
build:
./docker_run.sh mvn install …
> DB-9610 fix start-splice-cluster on linux, add docker build&start scripts

- db-client/src/main/java/com/splicemachine/db/client/am/ResultSet.java
Move explicit release of CLOB locators in _ResultSet.closeX()_ after a call to _flowCloseAndAutoCommitIfNotAutoCommitted()_, which invokes _completeLocalCommit() -> LOBStateTracker.discardState()_ making a call to _checkCurrentRow()_ a no-op. Retain the call in case _discardState()_ is bypassed.
> DB-9329 Client makes many unnecessary CLOBRELEASELOCATOR() calls

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/SessionProperties.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InsertNode.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SessionPropertyIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
Note that useOLAP is added. useSpark=X still works.
> DB-9572 add useOLAP=X as query and session config/hint (2.8)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/fs/s3/PrestoS3FileSystem.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- mem_storage/src/main/java/com/splicemachine/storage/MemFileSystem.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- splice_access_api/src/main/java/com/splicemachine/access/api/DistributedFileSystem.java
- splice_access_api/src/main/java/com/splicemachine/access/api/FileInfo.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/TestingFileSystem.java
- standalone/pom.xml
- standalone/src/test/java/com/splicemachine/test/SpliceTestYarnPlatform.java
- start-splice-cluster
- some cleanup in SparkDataSetProcessor.write{X}
- HNIOFileSystem.getInfo will return a FileInfo which is calculating expensive (recursive) size() and fileCount() only on demand.
- added FileInfo.isEmptyDirectory to avoid scanning the whole directory tree for this
- modified SpliceTestPlatformConfig and SpliceTestYarnPlatform so that standalone spliceengine can use s3 access keys from ~/.aws/credentials or environment (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY).
- start-splice-cluster: don't start splice cluster if build failed.
> DB-9756 reduce filesystem metadata calls for external tables

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/fs/s3/PrestoS3FileSystem.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- mem_storage/src/main/java/com/splicemachine/storage/MemFileSystem.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestYarnPlatform.java
- splice_access_api/src/main/java/com/splicemachine/access/api/DistributedFileSystem.java
- splice_access_api/src/main/java/com/splicemachine/access/api/FileInfo.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/TestingFileSystem.java
- standalone/pom.xml
- start-splice-cluster
- some cleanup in SparkDataSetProcessor.write{X}
- HNIOFileSystem.getInfo will return a FileInfo which is calculating expensive (recursive) size() and fileCount() only on demand.
- added FileInfo.isEmptyDirectory to avoid scanning the whole directory tree for this
- modified SpliceTestPlatformConfig and SpliceTestYarnPlatform so that standalone spliceengine can use s3 access keys from ~/.aws/credentials or environment (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY).
- start-splice-cluster: don't start splice cluster if build failed.
> DB-9756 reduce filesystem metadata calls for external tables (2.8)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/fs/s3/PrestoS3FileSystem.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- mem_storage/src/main/java/com/splicemachine/storage/MemFileSystem.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- splice_access_api/src/main/java/com/splicemachine/access/api/DistributedFileSystem.java
- splice_access_api/src/main/java/com/splicemachine/access/api/FileInfo.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/TestingFileSystem.java
- standalone/pom.xml
- standalone/src/test/java/com/splicemachine/test/SpliceTestYarnPlatform.java
- start-splice-cluster
- some cleanup in SparkDataSetProcessor.write{X}
- HNIOFileSystem.getInfo will return a FileInfo which is calculating expensive (recursive) size() and fileCount() only on demand.
- added FileInfo.isEmptyDirectory to avoid scanning the whole directory tree for this
- modified SpliceTestPlatformConfig and SpliceTestYarnPlatform so that standalone spliceengine can use s3 access keys from ~/.aws/credentials or environment (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY).
- start-splice-cluster: don't start splice cluster if build failed.
> DB-9756 reduce filesystem metadata calls for external tables (3.0)

- platform_it/pom.xml
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceIT.scala
Setting hbase.rpc.timeout to avoid rpc timeouts in Jenkins.
The reason for setting hbase.rootdir as a system property: the sqlContext.read calls returning the dataframes are implemented as calls to SplicemachineContext.df() in SpliceRelation.buildScan().  The df function uses an EmbeddedConnection to query the data from the db.  Somewhere in the call stack, SplitRegionScanner.createAndRegisterClientSideRegionScanner() is called and it looks for hbase.rootdir in config files or in system properties.  It wasn’t getting the correct value for hbase.rootdir.  So the code was probably reading rows from the memstore, but didn’t have the right path to HBase to be able to read the additional rows stored in HFiles, and so it wasn't returning all of the rows.  The solution for DefaultSourceIT was to …
> DB-9613 DefaultSourceIT Insertion with Sampling Fix

- docker/Dockerfile
- docker/entrypoint.sh
- docker/start.sh
- docker_run.sh
- docker_start-splice_cluster.sh
- start-splice-cluster
used base image for docker is maven:3.6.3-jdk-8 .
both docker_run.sh and docker_start-splice-cluster.sh do:
- to be able to sqlshell.sh into the container, we are exposing the containers' port 1527
as port 2527 for the host, so you can connect from host e.g. with
./sqlshell.sh -h localhost -p 2527
- to re-use the $HOME/.m2/settings.xml and the already downloaded
maven dependencies, we map the path $HOME/.m2 of host to
/root/.m2 inside of the container (since $HOME=/root, this mimicks $HOME/.m2 in the container)
- to have access to the source, we map $(pwd) to /usr/src/
- we cd into /usr/src in the container.
With these preparation steps, you can then just instantiate mvn,
short scripts are:
build:
./docker_run.sh mvn install -Pcdh6.3.0 -DskipTests
start splice cluster + sqlshell: …
> DB-9610 fix start-splice-cluster on linux, add docker build&start scripts (2.8)

- docker/Dockerfile
- docker/entrypoint.sh
- docker/start.sh
- docker_run.sh
- docker_start-splice_cluster.sh
- start-splice-cluster
used base image for docker is maven:3.6.3-jdk-8 .
both docker_run.sh and docker_start-splice-cluster.sh do:
- to be able to sqlshell.sh into the container, we are exposing the containers' port 1527
as port 2527 for the host, so you can connect from host e.g. with
./sqlshell.sh -h localhost -p 2527
- to re-use the $HOME/.m2/settings.xml and the already downloaded
maven dependencies, we map the path $HOME/.m2 of host to
/root/.m2 inside of the container (since $HOME=/root, this mimicks $HOME/.m2 in the container)
- to have access to the source, we map $(pwd) to /usr/src/
- we cd into /usr/src in the container.
With these preparation steps, you can then just instantiate mvn,
short scripts are:
build:
./docker_run.sh mvn install -Pcdh6.3.0 -DskipTests
start splice cluster + sqlshell: …
> DB-9610 fix start-splice-cluster on linux, add docker build&start scripts (3.0)

- hbase_sql/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/src/main/java/com/splicemachine/fs/s3/PrestoS3FileSystem.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- HNIOFileSystem's FileInfo, will use FileSystem.listFiles(path, recursive) to calculate (recursive) size() and fileCount() (FileInfo.size/fileCount is used in StoreCostController)
- PrestoS3FileSystem will now implement FileSystem.listFiles(Path path, boolean recursive) directly.
(On Cloud Storage systems like s3/adl/gcp etc. metadata requests are limited not by bandwidth, but by ping, so reducing the number of metadata requests is very important. For directories with a lot of subdirectories, this means we should do ONE request asking for "give me that directory tree" instead of listing the root, then listing each subdirectory etc. E.g. for a directory with 100 subdirectories, this can make a difference of 300ms (one request) to (1+100)*300ms = 30.3 s (1 = list root, then 100 lists in …
> DB-9783 use recursive listdir (3.0)

- hbase_sql/src/main/java/com/splicemachine/fs/s3/PrestoS3FileSystem.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- HNIOFileSystem's FileInfo, will use FileSystem.listFiles(path, recursive) to calculate (recursive) size() and fileCount() (FileInfo.size/fileCount is used in StoreCostController)
- PrestoS3FileSystem will now implement FileSystem.listFiles(Path path, boolean recursive) directly.
(On Cloud Storage systems like s3/adl/gcp etc. metadata requests are limited not by bandwidth, but by ping, so reducing the number of metadata requests is very important. For directories with a lot of subdirectories, this means we should do ONE request asking for "give me that directory tree" instead of listing the root, then listing each subdirectory etc. E.g. for a directory with 100 subdirectories, this can make a difference of 300ms (one request) to (1+100)*300ms = 30.3 s (1 = list root, then 100 lists in …
> DB-9783 use recursive listdir (2.8)

- hbase_sql/src/main/java/com/splicemachine/fs/s3/PrestoS3FileSystem.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- HNIOFileSystem's FileInfo, will use FileSystem.listFiles(path, recursive) to calculate (recursive) size() and fileCount() (FileInfo.size/fileCount is used in StoreCostController)
- PrestoS3FileSystem will now implement FileSystem.listFiles(Path path, boolean recursive) directly.
(On Cloud Storage systems like s3/adl/gcp etc. metadata requests are limited not by bandwidth, but by ping, so reducing the number of metadata requests is very important. For directories with a lot of subdirectories, this means we should do ONE request asking for "give me that directory tree" instead of listing the root, then listing each subdirectory etc. E.g. for a directory with 100 subdirectories, this can make a difference of 300ms (one request) to (1+100)*300ms = 30.3 s (1 = list root, then 100 lists in …
> DB-9783 use recursive listdir

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/CreateTableTypeHelper.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTablePartitionIT.java
- tests like testAbcParquet, testAbcORC, testAbcAvro have been unified to  testAbc.
- removed code duplication, especially in tests for syntax error handling
- testWriteReadFromSimpleExternalTable will now tests ALL available column types
- added CreateTableTypeHelper to make testing multiple column, values and null values types easier, even if Parquet, ORC and Avro sometimes support different types.
> DB-9782 improve ExternalTableIT to handle more column types / unify tests

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/CreateTableTypeHelper.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTablePartitionIT.java
- tests like testAbcParquet, testAbcORC, testAbcAvro have been unified to  testAbc.
- removed code duplication, especially in tests for syntax error handling
- testWriteReadFromSimpleExternalTable will now tests ALL available column types
- added CreateTableTypeHelper to make testing multiple column, values and null values types easier, even if Parquet, ORC and Avro sometimes support different types.
> DB-9782 improve ExternalTableIT to handle more column types / unify tests (2.8)

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/CreateTableTypeHelper.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTablePartitionIT.java
- tests like testAbcParquet, testAbcORC, testAbcAvro have been unified to  testAbc.
- removed code duplication, especially in tests for syntax error handling
- testWriteReadFromSimpleExternalTable will now tests ALL available column types
- added CreateTableTypeHelper to make testing multiple column, values and null values types easier, even if Parquet, ORC and Avro sometimes support different types.
> DB-9782 improve ExternalTableIT to handle more column types / unify tests (3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/test/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImplTest.java
- previously, the conglomerate ID was used to check whether a table
is a system table being smaller than FIRST_USER_TABLE_NUMBER.
- this assumption becomes invalid after upgrade where sys tables
are recreated with potentially larger conglomerate ID than
FIRST_USER_TABLE_NUMBER.
- since the check fails, the wrong serializer is used with TIMESTAMP
columns causing incorrect data to be shown.
- the fix makes the check look at the schema of the table, if it is
"SYS" then we know for sure this is a system table regardless of
its conglomerate ID.
- add unit test.
> DB-9589 rely on schema name for checking sys tables (2.8)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/test/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImplTest.java
- previously, the conglomerate ID was used to check whether a table
is a system table being smaller than FIRST_USER_TABLE_NUMBER.
- this assumption becomes invalid after upgrade where sys tables
are recreated with potentially larger conglomerate ID than
FIRST_USER_TABLE_NUMBER.
- since the check fails, the wrong serializer is used with TIMESTAMP
columns causing incorrect data to be shown.
- the fix makes the check look at the schema of the table, if it is
"SYS" then we know for sure this is a system table regardless of
its conglomerate ID.
- add unit test.
> DB-9589 rely on schema name for checking sys tables. (3.0)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TableScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- avoid to check for empty directory if spark does it
- dont use recursive listdir for isEmptyDirectory if FileSystem doesnt implement efficiently
> DB-9835 reduce time spent in listdirs for isEmptyDirectory

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TableScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- avoid to check for empty directory if spark does it
- dont use recursive listdir for isEmptyDirectory if FileSystem doesnt implement efficiently
> DB-9835 reduce time spent in listdirs for isEmptyDirectory (2.8)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TableScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- avoid to check for empty directory if spark does it
- dont use recursive listdir for isEmptyDirectory if FileSystem doesnt implement efficiently
> DB-9835 reduce time spent in listdirs for isEmptyDirectory (3.0)

- hbase_sql/src/main/java/com/splicemachine/hbase/MemstoreAwareObserver.java
MemstoreAwareObserver.postScannerOpenAction() does not close the passed RegionScanner when it returns a new MemStoreFlushAwareScanner. The dropped scanner gets leaked via HRegion.scannerReadPoints.
> DB-9939 Memory leak caused by unclosed scanners

- hbase_sql/src/main/java/com/splicemachine/hbase/MemstoreAwareObserver.java
MemstoreAwareObserver.postScannerOpenAction() does not close the passed RegionScanner when it returns a new MemStoreFlushAwareScanner. The dropped scanner gets leaked via HRegion.scannerReadPoints.
> DB-9939 Memory leak caused by unclosed scanners (3.0)

- hbase_sql/src/main/java/com/splicemachine/hbase/MemstoreAwareObserver.java
MemstoreAwareObserver.postScannerOpenAction() does not close the passed RegionScanner when it returns a new MemStoreFlushAwareScanner. The dropped scanner gets leaked via HRegion.scannerReadPoints.
> DB-9939 Memory leak caused by unclosed scanners (2.8)

- start-splice-cluster
there's two versions of nc: GNU and OpenBSD
OpenBSD supports -z (only check port), but GNU not.
GNU would work with 'exit', OpenBSD needs 'exit\n'
this one works in both and on mac
> DB-9931 fix start-splice-cluster when netcat is GNU version, not OpenBSD

- start-splice-cluster
there's two versions of nc: GNU and OpenBSD
OpenBSD supports -z (only check port), but GNU not.
GNU would work with 'exit', OpenBSD needs 'exit\n'
this one works in both and on mac
> DB-9931 fix start-splice-cluster when netcat is GNU version, not OpenBSD (3.0)

- start-splice-cluster
there's two versions of nc: GNU and OpenBSD
OpenBSD supports -z (only check port), but GNU not.
GNU would work with 'exit', OpenBSD needs 'exit\n'
this one works in both and on mac
> DB-9931 fix start-splice-cluster when netcat is GNU version, not OpenBSD (2.8)

- splice_machine/pom.xml
The dependency is used in TestUnknownClient only and should be in the _test_ scope.
> DB-10026 Make derbyclient dependency test only

- splice_machine/pom.xml
Reverts splicemachine/spliceengine#4000
Mem profile build in Jenkins has failed twice with:
com.splicemachine.derby.client.TestUnknownClient.testDerbyDriverFails
Error Details
Unexpected exception, expected<java.sql.SQLNonTransientConnectionException> but was<java.lang.ClassNotFoundException>
> Revert "DB-10026 Make derbyclient dependency test only"

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- hbase_sql/src/main/java/com/splicemachine/stream/RemoteQueryClientImpl.java
Previously, certain code paths that run remote jobs such as ASQ where getting the user roles as-is from the current SQL session context. Problem is, the retrieved list of roles is not kept up to date, meaning if the DBA revoked some roles from the user running ASQ, it wouldn't have any effect since the list of roles is not updated and the revoked role is not removed from it.
With this fix, we always refresh the list of roles before retrieving it.
I chose not to make refresh logic part of `LanguageConnectionContext.getCurrentRoles` as it might affect performance since it is used in many other locations that does proper cleansing of the role list already.
> DB-9749 sync user roles before running remote queries.

- mem_sql/pom.xml
- splice_machine/pom.xml
Don’t rerun splice_machine unit tests from mem_sql: that is redundant and the classpath is not right.
> DB-10026 Make derbyclient dependency test only (redux)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsOperation.java
- INSERT into CSV external table now also respects ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' ESCAPED BY '#' (DB-10231) . See NativeSparkDataSet::writeTextFile and SparkDataSetProcessor::getCsvOptions .
> DB-10231 better CSV format support in external tables

- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceIT.scala
- Adding too many rows seems to cause memory pressure in Jenkins environment
causing builds to fail sporadically.
- We should move this test to a performance benchmark where we have more
suitable infrastructure.
> DB-9705 reduce the amount of self-inserted rows in DefaultSourceIT.

- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceIT.scala
- Adding too many rows seems to cause memory pressure in Jenkins environment
causing builds to fail sporadically.
- We should move this test to a performance benchmark where we have more
suitable infrastructure.
> DB-9705 reduce the amount of self-inserted rows in DefaultSourceIT (3.0)

- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceIT.scala
- Adding too many rows seems to cause memory pressure in Jenkins environment
causing builds to fail sporadically.
- We should move this test to a performance benchmark where we have more
suitable infrastructure.
> DB-9705 reduce the amount of self-inserted rows in DefaultSourceIT (2.8)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsOperation.java
INSERT into CSV external table now also respects ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' ESCAPED BY '#' (DB-10231) . See NativeSparkDataSet::writeTextFile and SparkDataSetProcessor::getCsvOptions .
This is a revert-revert of https://github.com/splicemachine/spliceengine/pull/4111 .
This reverts commit dc7736bf19f0b36177ab9f5b180d29c271365f42, which reverted https://github.com/splicemachine/spliceengine/pull/4111.
> Redo DB-10231 better CSV format support in external tables

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsOperation.java
INSERT into CSV external table now also respects ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' ESCAPED BY '#' (DB-10231) . See NativeSparkDataSet::writeTextFile and SparkDataSetProcessor::getCsvOptions .
This reverts commit 3cd2d846cb663109538e9be4d28ff87e11d35a98, which reverted 56ce82c9ff1bac7ab2c5b58b42a4bb5254fd75fe .
> Redo DB-10231 better CSV format support in external tables (2.8)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsOperation.java
INSERT into CSV external table now also respects ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' ESCAPED BY '#' (DB-10231) . See NativeSparkDataSet::writeTextFile and SparkDataSetProcessor::getCsvOptions .
This reverts commit dc7736bf19f0b36177ab9f5b180d29c271365f42, which reverted 61966fc855f0598e34ca7ccdf83c3cfa4f730ef6 .
> Redo DB-10231 better CSV format support in external tables (3.0)

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
There seems to be a bug in Spark 2.8 when writing "#," with escape=#,
wrongly writes "#," instead of "##,". Spark 3.0 does it correctly.
> DB-10339 fix ExternalTableIT for CSV

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
There seems to be a bug in Spark 2.8 when writing "#," with escape=#,
wrongly writes "#," instead of "##,". Spark 3.0 does it correctly.
> DB-10339 fix ExternalTableIT for CSV (3.0)

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
There is a bug in Spark 2.8 when writing "#," with escape=#,
wrongly writes "#," instead of "##,". Spark 3.0 does it correctly.
> DB-10339 fix ExternalTableIT for CSV (2.8)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
consisting of changes DB-9770 (fix) and DB-10267 (speed improvement)
> DB-9770/DB-10267 Fix External Table Row Counts after cross-join insert (2.8)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
consisting of changes DB-9770 (fix) and DB-10267 (speed improvement)
> DB-9770/DB-10267 Fix External Table Row Counts after cross-join insert (3.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/AlterTableConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/TruncateTableIT.java
> DB-10351 fix columnOrdering array for unique index when truncating a …(2.8)

- db-client/src/main/java/com/splicemachine/db/client/net/NetConnection40.java
After checking `ClientInfo` properties, the driver looks up the environment variable `SPLICEMACHINE_JDBC_IGNORE_UNSUPPORTED_PROPERTIES` and checks whether it is set to `true`. If so, any unrecognized properties in `ClientInfo` will be ignored instead of throwing a `SQLClientInfoException` exception.
This allows JDBC programs that targets other database systems such as DB2, potentially with many properties set in `ClientInfo` that are not supported by SpliceMachine, to run without modification and recompilation against SpliceMachine.
> DB-10359 allow JDBC driver to ignore unrecognized ClientInfo properties.

- assembly/standalone/template/bin/sqlshell.sh
Runs into an error with spark queries if JAVA_HOME is not set. We should check if it is correctly set before sqlshell starts in standalone.
> DB-10385 Add JAVA_HOME check to standalone sqlshell

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/LastIndexKeyOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ScanOperation.java
fixes a problems caused by DB-10328 -> DB-10253 -> REVERT DB-10328
> DB-10544 fix missing serialization items in LastIndexKeyOperation / ScanOperation (3.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/LastIndexKeyOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ScanOperation.java
fixes a problems caused by DB-10328 -> DB-10253 -> REVERT DB-10328
> DB-10544 fix missing serialization items in LastIndexKeyOperation / ScanOperation (3.1)

- hbase_sql/src/test/java/com/splicemachine/derby/utils/VacuumIT.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/SMInputFormatIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/OrderByIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceUDTIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TimestampIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WithStatementIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
- splice_machine/src/test/java/com/splicemachine/homeless/TestUtils.java
- splice_machine/src/test/java/com/splicemachine/subquery/SubqueryITUtil.java
This fixes the issues because of un-closed Transactions which are preventing VacuumIT from running correctly.
It also introduces a @AfterClass function for each tests that logs messages of the following form:
`WARNING: Test failed to close all transactions. This might be due to multiple tests running in parallel.`
in case it finds left open transactions.
However, this message might be also caused by multiple tests running in parallel (that's why it's not Assert.fail).
To check if these Warnings are actually issues (especially if you see multiple of these messages), you can turn `failOnError=true` in SpliceUnitTest.waitForStaleTransactions() and check the tests that reported issues one by one (forcing Serial mode).
Also, SYSCS_GET_OLDEST_ACTIVE_TRANSACTION will now return same oldest …
> DB-10534 fix VacuumIT / unclosed Transactions in Tests

- hbase_sql/src/test/java/com/splicemachine/derby/utils/VacuumIT.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/SMInputFormatIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/OrderByIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceUDTIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TimestampIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WithStatementIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
- splice_machine/src/test/java/com/splicemachine/homeless/TestUtils.java
- splice_machine/src/test/java/com/splicemachine/subquery/SubqueryITUtil.java
This fixes the issues because of un-closed Transactions which are preventing VacuumIT from running correctly.
It also introduces a @AfterClass function for each tests that logs messages of the following form:
`WARNING: Test failed to close all transactions. This might be due to multiple tests running in parallel.`
in case it finds left open transactions.
However, this message might be also caused by multiple tests running in parallel (that's why it's not Assert.fail).
To check if these Warnings are actually issues (especially if you see multiple of these messages), you can turn `failOnError=true` in SpliceUnitTest.waitForStaleTransactions() and check the tests that reported issues one by one (forcing Serial mode).
Also, SYSCS_GET_OLDEST_ACTIVE_TRANSACTION will now return same oldest …
> DB-10534 fix VacuumIT / unclosed Transactions in Tests (2.8)

- hbase_sql/src/test/java/com/splicemachine/derby/utils/VacuumIT.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/SMInputFormatIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/OrderByIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceUDTIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TimestampIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WithStatementIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
- splice_machine/src/test/java/com/splicemachine/homeless/TestUtils.java
- splice_machine/src/test/java/com/splicemachine/subquery/SubqueryITUtil.java
This fixes the issues because of un-closed Transactions which are preventing VacuumIT from running correctly.
It also introduces a @AfterClass function for each tests that logs messages of the following form:
`WARNING: Test failed to close all transactions. This might be due to multiple tests running in parallel.`
in case it finds left open transactions.
However, this message might be also caused by multiple tests running in parallel (that's why it's not Assert.fail).
To check if these Warnings are actually issues (especially if you see multiple of these messages), you can turn `failOnError=true` in SpliceUnitTest.waitForStaleTransactions() and check the tests that reported issues one by one (forcing Serial mode).
Also, SYSCS_GET_OLDEST_ACTIVE_TRANSACTION will now return same oldest …
> DB-10534 fix VacuumIT / unclosed Transactions in Tests (3.0)

- hbase_sql/src/test/java/com/splicemachine/derby/utils/VacuumIT.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/SMInputFormatIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/OrderByIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceUDTIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TimestampIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WithStatementIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
- splice_machine/src/test/java/com/splicemachine/homeless/TestUtils.java
- splice_machine/src/test/java/com/splicemachine/subquery/SubqueryITUtil.java
This fixes the issues because of un-closed Transactions which are preventing VacuumIT from running correctly.
It also introduces a @AfterClass function for each tests that logs messages of the following form:
`WARNING: Test failed to close all transactions. This might be due to multiple tests running in parallel.`
in case it finds left open transactions.
However, this message might be also caused by multiple tests running in parallel (that's why it's not Assert.fail).
To check if these Warnings are actually issues (especially if you see multiple of these messages), you can turn `failOnError=true` in SpliceUnitTest.waitForStaleTransactions() and check the tests that reported issues one by one (forcing Serial mode).
Also, SYSCS_GET_OLDEST_ACTIVE_TRANSACTION will now return same oldest …
> DB-10534 fix VacuumIT / unclosed Transactions in Tests (3.1)

- hbase_storage/src/main/java/com/splicemachine/si/impl/SkeletonTxnNetworkLayer.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/region/HBaseTxnFinder.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/PurgeConfigBuilder.java
This PR addresses TPC-C performance regressions reported recently, the root cause was [DB-10084](https://github.com/splicemachine/spliceengine/pull/4163) PR, in that PR we made our purge-during-flush logic play nicely with time travel's minimum retention period (MRP) such that if we want to flush we check whether the involved transaction is within MRP, if so, we skip the purging preserving as a result the validity of past transactions within MRP.
The new check leverages the `getTxnAt` RPC which we introduced a while ago with time travel. This method performs HBase scans in a very inefficient way potentially causing a full scan of Splice txn table. That is maybe OK if the system is not under heavy load.
The TPC-C benchmark is intentionally putting the system under a heavy transnational …
> DB-10558 Improve getTxnAt performance

- hbase_storage/src/main/java/com/splicemachine/si/impl/SkeletonTxnNetworkLayer.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/region/HBaseTxnFinder.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/PurgeConfigBuilder.java
This PR addresses TPC-C performance regressions reported recently, the root cause was [DB-10084](https://github.com/splicemachine/spliceengine/pull/4163) PR, in that PR we made our purge-during-flush logic play nicely with time travel's minimum retention period (MRP) such that if we want to flush we check whether the involved transaction is within MRP, if so, we skip the purging preserving as a result the validity of past transactions within MRP.
The new check leverages the `getTxnAt` RPC which we introduced a while ago with time travel. This method performs HBase scans in a very inefficient way potentially causing a full scan of Splice txn table. That is maybe OK if the system is not under heavy load.
The TPC-C benchmark is intentionally putting the system under a heavy transnational …
> DB-10558 Improve getTxnAt performance (3.0)

- hbase_storage/src/main/java/com/splicemachine/si/impl/SkeletonTxnNetworkLayer.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/region/HBaseTxnFinder.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/PurgeConfigBuilder.java
This PR addresses TPC-C performance regressions reported recently, the root cause was [DB-10084](https://github.com/splicemachine/spliceengine/pull/4163) PR, in that PR we made our purge-during-flush logic play nicely with time travel's minimum retention period (MRP) such that if we want to flush we check whether the involved transaction is within MRP, if so, we skip the purging preserving as a result the validity of past transactions within MRP.
The new check leverages the `getTxnAt` RPC which we introduced a while ago with time travel. This method performs HBase scans in a very inefficient way potentially causing a full scan of Splice txn table. That is maybe OK if the system is not under heavy load.
The TPC-C benchmark is intentionally putting the system under a heavy transnational …
> DB-10558 Improve getTxnAt performance (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/catalog/TriggerNewTransitionRows.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Statement_IT.java
This fixes a ClassCastException Ben was seeing when a DML statement runs in control but a trigger it fires runs in Spark.
Test case:
> create table t1 (a int, b int);
> create table t2 (a int, b int);
> 
> create trigger trig2
> after insert on t1
> referencing new_table as NT
> for each statement
> insert into t2 --splice-properties useSpark=true
> select * from NT;
> 
> insert into t1 values(1,2);
> ERROR SE001: Splice Engine exception: unexpected exception
> ERROR XJ001: Java exception: 'java.lang.ClassCastException: com.splicemachine.derby.stream.control.ControlDataSet cannot be cast to com.splicemachine.derby.stream.spark.SparkDataSet: java.io.IOException'.
> ERROR XJ001: Java exception: 'com.splicemachine.derby.stream.control.ControlDataSet cannot be cast to …
> DB-10578 Use proper DataSet type for trigger rows.

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CharTypeCompiler.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumn.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/QualifierUtils.java
ITs on the mem platform are taking twice as long after DB-10597 merged.
Fix:
Introduced a thread local variable to avoid doing many costly cached database property lookups.
> DB-10662 Fix DB-10597 Performance regression.

- hbase_storage/src/main/java/com/splicemachine/si/impl/region/HBaseTxnFinder.java
Ensure the iterator is closed, which also closes the underlying scanner.
> DB-10703 HBaseTxnFinder.find() does not close RegionScanner

- db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DB2VarcharCompatibilityIT.java
The SYSCS_INVALIDATE_STORED_STATEMENTS procedure should clear stored statements from the dictionary cache so that they will be recompiled the next time they are executed.  Currently it does not, it only invalidates stored statements on disk.
> DB-10685 Fix SYSCS_INVALIDATE_STORED_STATEMENTS

- hbase_storage/src/main/java/com/splicemachine/si/impl/SkeletonTxnNetworkLayer.java
Set transaction RPC priority to HIGH to dispatch such RPCs to the priority thread pool.
> DB-10320 execute transaction RPCs in the priority thread pool

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/AlterTableConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/foreignkeys/ForeignKey_AlterDropTable_IT.java
We do not allow tables to be created with a foreign key that has a delete action (`on delete cascade` and `on delete set null`) since they these actions are not supported. However we still incorrectly allow the user to add such foreign keys via the `alter` statement.
In this PR we fix this behavior disallowing the user to add a foreign key with delete action via `alter` statement.
> DB-10514-2.8 Reject adding foreign key with delete actions via ALTER statement

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSparkKryoRegistrator.java
Kryo increments a class registration id for each new class added.  TriggerDescriptorV4 should have been added at the end to avoid messing up the registration ids.
> DB-10752 Move TriggerDescriptorV4 to the end of SpliceSparkKryoRegistrator.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericPreparedStatement.java
- splice_machine/src/test/java/com/splicemachine/homeless/SerializationTest.java
when constructing GenericPreparedStatement from a unit test (without running DB) we need to ignore not available uuid factory
> DB-10745 fix uuidFactory null (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericPreparedStatement.java
- splice_machine/src/test/java/com/splicemachine/homeless/SerializationTest.java
when constructing GenericPreparedStatement from a unit test (without running DB) we need to ignore not available uuid factory
> DB-10745 fix uuidFactory null (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DMLModStatementNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UpdateOperationIT.java
The logic in IndexTransformer and elsewhere to avoid updating an index on an UPDATE statement which doesn't modify any index columns is broken.  If an index shares any columns with some other index that is getting updated, then it will also be updated.  UpdateNode.getXAffectedIndexes() detects which indexes shouldn't get updates, and skips adding their columns to the update, meaning they will be inaccessible.  Any attempt to rebuild an index row with missing columns will corrupt the index (produce columns with bad data, possibly a base rowid which cannot be properly read).   Attempting to read the bad index row will return incorrect results or throw an error.  Deleted the corresponding base table row may fail to delete the index row.
The fix is to add all indexes to the update for now, so …
> DB-10746 Fix UPDATE statement index corruption.

- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/SIObserver.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyChildInterceptWriteHandler.java
- splice_machine/src/test/java/com/splicemachine/foreignkeys/ForeignKeyCheckIT.java
- splice_si_api/src/main/java/com/splicemachine/si/constants/SIConstants.java
When adding a row in the child table, the child-interceptor logic was making decisions about the existence of the foreign key in the parent table using latest rows' latest versions from HBase which could lead to true negatives. This behavior is corrected by letting the child-interceptor examine the entire row history of the parent keys.
> DB-10734 expose entire row history to foreign key child interceptor

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DDLStatementNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropTableIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
Regression of DB-10525.
> drop table cjpsplat;
> ERROR 42Y55: 'CJPSPLAT' cannot be performed on '{1}' because it does not exist.
> 
> ... should be:
> 
> drop table cjpsplat;
> ERROR 42Y55: 'DROP TABLE' cannot be performed on 'CJPSPLAT' because it does not exist.
> DB-10790 Fix missing parameter in DROP TABLE error.

- splice_ck/src/main/java/com/splicemachine/ck/ConnectionCache.java
- splice_ck/src/main/java/com/splicemachine/ck/ConnectionSingleton.java
- splice_ck/src/main/java/com/splicemachine/ck/HBaseInspector.java
- splice_ck/src/main/java/com/splicemachine/ck/Utils.java
- splice_ck/src/main/java/com/splicemachine/ck/command/RGetCommand.java
- splice_ck/src/main/java/com/splicemachine/ck/command/RPutCommand.java
- splice_ck/src/main/java/com/splicemachine/ck/command/RootCommand.java
- splice_ck/src/main/java/com/splicemachine/ck/command/TListCommand.java
- splice_ck/src/main/java/com/splicemachine/ck/command/TxListCommand.java
- splice_ck/src/main/java/com/splicemachine/ck/command/common/TableNameGroup.java
- splice_ck/src/main/java/com/splicemachine/ck/hwrap/ConnectionWrapper.java
- splice_ck/src/main/java/com/splicemachine/ck/visitor/TableCellPrinter.java
- splice_ck/src/main/java/com/splicemachine/ck/visitor/TableRowPrinter.java
- spliceck.sh
- `./spliceck.sh interactive` starts spliceck in "interactive shell" `spliceck>` mode. Commands stay the same, however since -we're caching the hbase connection, it's much faster. exit with `exit`
- rget can now also get all rows (use `all` instead of rowid)
- since this can be quite a lot, `--limit X` limits the number of rows to X. Default is 100.
- rget can limit the version it prints with e.g. `-V 1` (like default for hbase shell)
- rget can print additional cells like hbase (`--hbase`)
- tlist can accept filters e.g. `tlist *DUMMY` list all schema.table that end with DUMMY
- txlist also limits output by default to 100 (change with --limit)
- both rget and txlist notify when they cut off results due to --limit.
> DB-10708 SpliceCK interactive mode and other improvements

- splice_ck/src/main/java/com/splicemachine/ck/ConnectionCache.java
- splice_ck/src/main/java/com/splicemachine/ck/ConnectionSingleton.java
- splice_ck/src/main/java/com/splicemachine/ck/HBaseInspector.java
- splice_ck/src/main/java/com/splicemachine/ck/Utils.java
- splice_ck/src/main/java/com/splicemachine/ck/command/RGetCommand.java
- splice_ck/src/main/java/com/splicemachine/ck/command/RPutCommand.java
- splice_ck/src/main/java/com/splicemachine/ck/command/RootCommand.java
- splice_ck/src/main/java/com/splicemachine/ck/command/TListCommand.java
- splice_ck/src/main/java/com/splicemachine/ck/command/TxListCommand.java
- splice_ck/src/main/java/com/splicemachine/ck/command/common/TableNameGroup.java
- splice_ck/src/main/java/com/splicemachine/ck/hwrap/ConnectionWrapper.java
- splice_ck/src/main/java/com/splicemachine/ck/visitor/TableCellPrinter.java
- splice_ck/src/main/java/com/splicemachine/ck/visitor/TableRowPrinter.java
- spliceck.sh
- `./spliceck.sh interactive` starts spliceck in "interactive shell" `spliceck>` mode. Commands stay the same, however since -we're caching the hbase connection, it's much faster. exit with `exit`
- rget can now also get all rows (use `all` instead of rowid)
- since this can be quite a lot, `--limit X` limits the number of rows to X. Default is 100.
- rget can limit the version it prints with e.g. `-V 1` (like default for hbase shell)
- rget can print additional cells like hbase (`--hbase`)
- tlist can accept filters e.g. `tlist *DUMMY` list all schema.table that end with DUMMY
- txlist also limits output by default to 100 (change with --limit)
- both rget and txlist notify when they cut off results due to --limit.
> DB-10708 SpliceCK interactive mode and other improvements (3.1)

- findbugs-exclude-filter.xml
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkExternalTableUtil.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkUtils.java
- hbase_sql/src/main/java/com/splicemachine/fs/s3/PrestoS3FileSystem.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTablePartitionIT.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableUnitTests.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- mem_sql/src/main/java/com/splicemachine/derby/impl/sql/ControlOnlyDataSetProcessorFactory.java
- mem_storage/src/main/java/com/splicemachine/storage/MemFileSystem.java
- scala_util/src/main/scala/com/splicemachine/spark/splicemachine/SplicePartitioningUtils.scala
- splice_access_api/src/main/java/com/splicemachine/access/api/FileInfo.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/DistributedGetSchemaExternalJob.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/GetSchemaExternalJob.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/GetSchemaExternalResult.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/TestingFileSystem.java
fixing issues:
- DB-9843: Don't copy files for schema infer, but also don't check all files for schema -> overall faster
- DB-10568 Partitioned by using VARCHAR but value is 1 will be infered as INT and can't be read
currently we copy one file out of the directory to another directory, keeping the subdirectories like path/col1=22/col2=ABC/file.parquet . The idea behind this was that Spark should only have to look at ONE file, not ALL. However, we would still need directory partitioning information, so we had to COPY the file (couldn't just point at one file).
Now we can do directory partitioning ourselfs, we can skip the copy part.
> DB-9843 External Tables: Own directory partition parsing

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/TableDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DeleteNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromVTI.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InsertNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TriggerReferencingStruct.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UpdateNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DMLWriteOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ScrollInsensitiveOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TriggerHandler.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/VTIOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/FromFinalTableIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
- With autocommit off, the transaction stack would get pushed for every FROM FINAL TABLE statement, but never popped.
This is due to a missing needsSavepoint flag in the outermost prepared statement plus code from SPLICE-1625 that's no longer needed (trigger logic has added an extra transaction wrapping the statement since then) which caused the transaction to be elevated when the operation was closed (elevating it upon close causes it never to get popped).
- The cleanup code in TriggerHandler was too convoluted and not kicking in, so it's been simplified.
- I also moved the ThreadLocals added by DB-10525 from DataDictionaryCache to TriggerReferencingStruct per [DB-10738](https://splicemachine.atlassian.net/browse/DB-10738).
> DB-10854 Fix txn leak in FROM FINAL TABLE.

- hbase_sql/src/test/java/com/splicemachine/derby/utils/VacuumIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
No remote_it in 2.8.
Fixed SpliceUnitTest.getOldestActiveTransaction() to return long.
> DB-10786 Remote ITs are broken (2.8)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/foreignkey/Graph.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/foreignkey/GraphAnnotator.java
- db-engine/src/test/java/com/splicemachine/db/iapi/sql/dictionary/foreignkey/GraphTest.java
- db-engine/src/test/java/com/splicemachine/db/iapi/sql/dictionary/foreignkey/GraphvizParser.java
In this PR we add few hundreds of positive and negative unit tests to the foreign key dependency graph. the sheer amount of unit tests comes from constructing each graph in the test cases using all possible edge permutations. This brute-force test uncovered one bug in graph construction mechanism causing the checker to construct an incorrect graph and ultimately causing it to accept an incorrect foreign key dependency graph. The generation of the permutations is done using [Heap's algorithm](https://en.wikipedia.org/wiki/Heap%27s_algorithm).
> DB-10719 add unit tests for foreign key dependency checker.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SetOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_InList_IT.java
This wraps a UNION/INTERSECT/EXCEPT subquery in a derived table so that it can be flattened and participate in join planning, e.g.
> explain
> select a1,a2 from A
>                 WHERE -a1 in (select -a1 from A
>                             WHERE -a1 in (
>                             SELECT b1*2 FROM B
>                             UNION ALL
>                             SELECT -b1 FROM B
>                             EXCEPT
>                             SELECT b1 FROM B where b1 in (10,20,30,40,50)
>                             INTERSECT
>                             SELECT b1 FROM B ));
> 
> Cursor(n=29,rows=23,updateMode=READ_ONLY (1),engine=OLTP (default))
>   ->  ScrollInsensitive(n=29,totalCost=57.712,outputRows=23,outputHeapSize=69 B,partitions=1,parallelTasks=1)
>     -> …
> DB-10774 Wrap SetOp subquery in a derived table so it can be flattened.

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/SPSDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromVTI.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SetOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/AnyOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DMLWriteOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/GenericAggregateOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/NormalizeOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/RowCountOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SortOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/VTIOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/WindowOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/FromFinalTableIT.java
FROM FINAL Table must elevate the transaction to writeable via a call to getCurrentTransaction() in VTIOperation, but not all flavors of SpliceOperation were calling getCurrentTransaction on its source result set, so we ended up deferring the elevation of the transaction, which leaks it.
All operations that could have a VTIOperation as its source are now modified with a version of getCurrentTransaction that checks the source operation.  A new error is returned if we try to use FROM TABLE in a SetOp query.
Also, compiling the temporary trigger prepared statement caused a new transaction to be created in preparation for a write to the data dictionary, which caused in our case transactions to go to the transaction table instead of using subtransactions.  FROM TABLE does not write the …
> DB-10885 Fix FINAL TABLE txn leak in all paths.

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/Activation.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/ResultSet.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericPreparedStatement.java
The Activation that executes the INSERT/UPDATE/DELETE of a FROM TABLE query (VTIOperation.executeFromTableDML -> fromTableDML_SPS.executeSubStatement) is never saved off anywhere so that it can be closed.  So, all of the resources that it references are leaked until the LanguageConnectionContext is cleared, which may be until the sqlshell session ends.
The solution is to register the Activation as a closeable item of the SpliceOperation that's executing, so that when it closes, the Activation will automatically be closed.
> DB-10911 Fix Activation leak in FINAL TABLE query.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/subquery/aggregate/AggregateSubqueryPredicate.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_Aggregate_IT.java
Avoid flattening correlated subqueries with value-producing aggregates such as `count` and `coalesce` as that might lead to having missing rows on LHS on the resulting inner join.
> DB-10889 avoid flattening subqueries with value-producing aggregates

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SetOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnionNode.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_InList_IT.java
Please review the latest commit of this PR.  This is a redo of https://github.com/splicemachine/spliceengine/pull/4689.
Set operations in a subquery that contain correlated predicates (referencing columns from the outer table) cannot be wrapped in a derived table because such correlations are not legal in SQL, and result in an error.
At the time we try the rewrite, we don't yet know if the subquery is correlated or not, as that is detected much later, in the optimizer phase.  It may be risky to delay the rewrite to this late phase as some other parts of the query tree may already have called preprocess() and expect the variables set during binding to be complete and not changing any more.  Therefore we'll indirectly detect correlation by attempting the rewrite still during binding, and if …
> Redo DB-10774 Wrap SetOp subquery in a derived table so it can be flattened.

- db-engine/src/main/java/com/splicemachine/db/iapi/util/DecimalUtil.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/ValueRow.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DecimalFunctionIT.java
DecimalUtil.getDecimalDb2 needs to return a SQL null, not a Java null.
The projection (and therefore also the getDecimalDb2 function) will be called once from Olap Server with
a"null" row from getExecRowDefinition to get the types in the result rows.
Then later, the Spark Executor will get the correct results and insert the correct values.
> DB-10919 fix DEC conversion null in Spark for getExecRowDefinition

- db-engine/src/main/java/com/splicemachine/db/iapi/util/DecimalUtil.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/ValueRow.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DecimalFunctionIT.java
DecimalUtil.getDecimalDb2 needs to return a SQL null, not a Java null.
The projection (and therefore also the getDecimalDb2 function) will be called once from Olap Server with
a"null" row from getExecRowDefinition to get the types in the result rows.
Then later, the Spark Executor will get the correct results and insert the correct values.
> DB-10919 fix DEC conversion null in Spark for getExecRowDefinition (3.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/util/DecimalUtil.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/ValueRow.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DecimalFunctionIT.java
DecimalUtil.getDecimalDb2 needs to return a SQL null, not a Java null.
The projection (and therefore also the getDecimalDb2 function) will be called once from Olap Server with
a"null" row from getExecRowDefinition to get the types in the result rows.
Then later, the Spark Executor will get the correct results and insert the correct values.
> DB-10919 fix DEC conversion null in Spark for getExecRowDefinition (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MemDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeDerbyScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/QualifierUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/Scans.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DB2VarcharCompatibilityIT.java
This completes the work to support DB2 varchar compatibility mode for queries using MultiProbeScan.
Trailing spaces are ignored when comparing a varchar with any other string.  Normally in Splice, comparisons of varchars do not ignore trailing spaces.  The original work was done by DB-10597, which utilizes a new SQLVarcharDB2Compatible DataValueDescriptor in place of SQLVarchar, where required.  This follow-on work uses the same approach.
> call syscs_util.syscs_set_global_database_property('splice.db2.varchar.compatible', true);
> create table t (v varchar(14), c char(2));
> create index ti on t (v,c);
> insert into t values ('ABC','A ');
> /* Should return one row. */
> select * from t --splice-properties index=ti
>                      WHERE v in ( ' ', 'ABC      ');
> DB-10895 Complete DB2 varchar compatibility for MultiProbeScan.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromVTI.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/TriggerExecutionContext.java
- hbase_storage/src/main/java/com/splicemachine/access/hbase/HBasePartitionAdmin.java
- mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MEnginePartitionAdmin.java
- mem_storage/src/main/java/com/splicemachine/storage/MPartitionFactory.java
- splice_access_api/src/main/java/com/splicemachine/access/api/PartitionAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/catalog/TriggerNewTransitionRows.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/TriggerRowHolderImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/VTIOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/FromFinalTableIT.java
Example of query this PR adds support for:
> prepare ps as 'select * from old table (update t1 set a = ?) where a >= ?';
> execute ps using 'values (2, 1)';
The parameter list is normally one per activation, but FROM TABLE queries use two activations, so this change makes sure both activations can access the same parameter list.
Two new system procedures are also added: SYSCS_GET_TABLE_COUNT and SYSCS_IS_MEM_PLATFORM
**SYSCS_GET_TABLE_COUNT** 
Returns the number of HBase user tables, or on mem, the number of tables allocated in MPartitionFactory.Admin.partitionMap.
**SYSCS_IS_MEM_PLATFORM**
Returns true if splice is running on the mem platform, otherwise false.
> splice> CALL SYSCS_UTIL.SYSCS_GET_TABLE_COUNT();
> NumTables  
> //-----------
> 111        
> 
> 1 row selected
> ELAPSED TIME …
> DB-10949 Support parameterized FROM FINAL TABLE queries.

- pom.xml
Hadoop version 3.1.1.3.1.0.61-1 is not available anymore from hortonworks repo.
https://repo.hortonworks.com/content/repositories/releases/org/apache/hadoop/hadoop-common/
Set it to match the versions already referenced for hdp3.1.0.
> DB-10770 Fix SSDS pipeline

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/Procedure.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/replication/ReplicationSystemProcedure.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ProcedureUnitTest.java
removes the following functions since they are not existent:
- SYSCS_GET_AUTO_INCREMENT_ROW_LOCATIONS
- PARTITION_EXISTS
- CLOBGETPROSITIONFROMSTRING
re-adding GET_REPLICATION_PROGRESS as it was removed accidentally in DB-8990
> DB-10952 use reflection to ensure created system procedures are correct

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/Procedure.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ProcedureUnitTest.java
removes the following functions since they are not existent:
- SYSCS_GET_AUTO_INCREMENT_ROW_LOCATIONS
- PARTITION_EXISTS
- CLOBGETPROSITIONFROMSTRING
- GET_REPLICATION_PROGRESS
> DB-10952 use reflection to ensure created system procedures are correct (2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/Procedure.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/replication/ReplicationSystemProcedure.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ProcedureUnitTest.java
removes the following functions since they are not existent:
- SYSCS_GET_AUTO_INCREMENT_ROW_LOCATIONS
- PARTITION_EXISTS
- CLOBGETPROSITIONFROMSTRING
re-adding GET_REPLICATION_PROGRESS as it was removed accidentally in DB-8990
> DB-10952 use reflection to ensure created system procedures are correct (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/Procedure.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/replication/ReplicationSystemProcedure.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ProcedureUnitTest.java
removes the following functions since they are not existent:
- SYSCS_GET_AUTO_INCREMENT_ROW_LOCATIONS
- PARTITION_EXISTS
- CLOBGETPROSITIONFROMSTRING
re-adding GET_REPLICATION_PROGRESS as it was removed accidentally in DB-8990
> DB-10952 use reflection to ensure created system procedures are correct (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
This allows joinStragegy query hints to be applied to the target table of an UPDATE, for example, if there is a join predicate on the primary key and you'd like to use nested loop join to avoid scanning the entire table:
```
explain update t4 --splice-properties joinStrategy=nestedloop
set (a4,b4) = (select 1,1 from t1 where c1 = a4);
```
Sometimes such hints may be inside a trigger, but often the optimizer cost estimates are so low on triggers that the parsing time limit is set to less than a millisecond, and the query planner gives up before even considering the hinted join.  In general prepared statements such as triggers are recompiled infrequently, so it is OK if parsing uses a little extra time, especially if it means that will allow more optimal plans and plans including all query …
> DB-10773 Honor joinStrategy hints on the target table of an UPDATE.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/BroadcastJoinIT.java
Currently the Splice optimizer only allows nested loop join to perform left outer join with join predicates that don't reference left table columns, for example:
> select * from t1 left outer join t2  
> on t2.b = 1;
This Jira adds support for left outer join to use broadcast join when each join predicate only references columns from a single table (or perhaps from neither table).
> DB-11063 Left outer broadcast join for more cases.

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- hbase_sql/src/main/java/com/splicemachine/derby/vti/KafkaVTI.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/load/SpliceCsvReader.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateIndexConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/SpliceRegionAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/AbstractFileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/AbstractTokenizerCR.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/CsvLineReaderCR.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/CsvParserConfig.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/FileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/MutableCSVTokenizer.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/QuoteTrackingTokenizer.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/StreamFileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/FromFinalTableIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/CsvLineReaderCRTest.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
- splice_machine/src/test/java/com/splicemachine/derby/stream/function/csv/QuoteTrackingTokenizerTest.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
- splice_machine/src/test/test-data/newline.csv
if splice.function.preserveLineEndings = true, multiline strings imported into the database will contain the `\r`, `\r\n`, `\n` exactly like in file. Otherwise (current default) all these will be replaced by `\n`.
> DB-11047 add option splice.function.preserveLineEndings

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- hbase_sql/src/main/java/com/splicemachine/derby/vti/KafkaVTI.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/load/SpliceCsvReader.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateIndexConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/SpliceRegionAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/AbstractFileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/AbstractTokenizerCR.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/CsvLineReaderCR.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/CsvParserConfig.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/FileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/MutableCSVTokenizer.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/QuoteTrackingTokenizer.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/StreamFileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/FromFinalTableIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/CsvLineReaderCRTest.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
- splice_machine/src/test/java/com/splicemachine/derby/stream/function/csv/QuoteTrackingTokenizerTest.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
- splice_machine/src/test/test-data/newline.csv
if splice.function.preserveLineEndings = true, multiline strings imported into the database will contain the `\r`, `\r\n`, `\n` exactly like in file. Otherwise (current default) all these will be replaced by `\n`.
> DB-11047 add option splice.function.preserveLineEndings (3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- hbase_sql/src/main/java/com/splicemachine/derby/vti/KafkaVTI.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/load/SpliceCsvReader.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateIndexConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/SpliceRegionAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/AbstractFileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/AbstractTokenizerCR.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/CsvLineReaderCR.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/CsvParserConfig.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/FileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/MutableCSVTokenizer.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/QuoteTrackingTokenizer.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/StreamFileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/FromFinalTableIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/CsvLineReaderCRTest.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
- splice_machine/src/test/java/com/splicemachine/derby/stream/function/csv/QuoteTrackingTokenizerTest.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
- splice_machine/src/test/test-data/newline.csv
if splice.function.preserveLineEndings = true, multiline strings imported into the database will contain the `\r`, `\r\n`, `\n` exactly like in file. Otherwise (current default) all these will be replaced by `\n`.
> DB-11047 add option splice.function.preserveLineEndings (3.1)

- assembly/hdp3.1.0/build/var/lib/ambari-server/resources/scripts/restart.sh
- assembly/hdp3.1.5/build/var/lib/ambari-server/resources/scripts/restart.sh
Fix logic for Hbase resart. Also the omission of `hbase.SpliceDriver:` from the grep makes it consistent to the flatten.sh script.
> DB-11069 Fix HDP restart script for Hbase

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SelectivityIT.java
Only unconditionally record a hinted join as best cost if the previous best cost join is not a hinted join.
> DB-11084:  Fix DB-10773 join plan performance regression.

- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextService.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/broadcast/AbstractBroadcastJoinFlatMapFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
Create a delegating ContextManager. No need to push LCC using initCurrentLCC() (will be available from the parent ContextManager). Cleanup must be done on the same thread. Newly created ContextManager must be destroyed.
I'm also fixing memory leak warnings in ContextService.
> DB-11117 NPE in getPreserveLineEndings/SpliceFileVTI

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/Splice_DD_Version.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceCatalogUpgradeScriptsTest.java
- SpliceCatalogUpgradeScripts can run multiple scripts for one version 
- fix UpgradeScriptForTablePriorities not running
- added some sort of tests for SpliceCatalogUpgradeScripts
- aligned master/3.0/3.1 code
- cleaned up upgrade scripts (see DB-11111)
> DB-11067/DB-11111 SpliceCatalogUpgradeScripts UpgradeScriptForTablePriorities fix, cleanup, tests

- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextService.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/broadcast/AbstractBroadcastJoinFlatMapFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
Create a delegating ContextManager. No need to push LCC using initCurrentLCC() (will be available from the parent ContextManager). Cleanup must be done on the same thread. Newly created ContextManager must be destroyed.
I'm also fixing memory leak warnings in ContextService.
> DB-11117 NPE in getPreserveLineEndings/SpliceFileVTI (3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextService.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/broadcast/AbstractBroadcastJoinFlatMapFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
Create a delegating ContextManager. No need to push LCC using initCurrentLCC() (will be available from the parent ContextManager). Cleanup must be done on the same thread. Newly created ContextManager must be destroyed.
I'm also fixing memory leak warnings in ContextService.
> DB-11117 NPE in getPreserveLineEndings/SpliceFileVTI (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/Splice_DD_Version.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceCatalogUpgradeScriptsTest.java
- SpliceCatalogUpgradeScripts can run multiple scripts for one version 
- fix UpgradeScriptForTablePriorities not running
- added some sort of tests for SpliceCatalogUpgradeScripts
- aligned master/3.0/3.1 code
- cleaned up upgrade scripts (see DB-11111)
> DB-11067/DB-11111 SpliceCatalogUpgradeScripts UpgradeScriptForTablePriorities fix, cleanup, tests (3.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/Splice_DD_Version.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceCatalogUpgradeScriptsTest.java
- SpliceCatalogUpgradeScripts can run multiple scripts for one version 
- fix UpgradeScriptForTablePriorities not running
- added some sort of tests for SpliceCatalogUpgradeScripts
- aligned master/3.0/3.1 code
- cleaned up upgrade scripts (see DB-11111)
> DB-11067/DB-11111 SpliceCatalogUpgradeScripts UpgradeScriptForTablePriorities fix, cleanup, tests (3.1)

- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SparkExplainIT.java
Spark explain has slightly different text in spark 3.0, so need to fix up this IT.
http://nexus.splicemachine.com:8080/job/spliceengine-3.0/job/spliceengine-platform/platform=dbaas3.0/727/testReport/junit/com.splicemachine.derby.impl.sql.execute.operations/SparkExplainIT/testCrossJoinBroadcastRightNoHint_0_/
> DB-11140 Fix testCrossJoinBroadcastRightNoHint

- pipelines/spliceengine-branch/Jenkinsfile
- pipelines/spliceengine-core/Jenkinsfile
- pipelines/spliceengine-jdbc/Jenkinsfile
- pipelines/spliceengine-platform/Jenkinsfile
- pipelines/standalone/Jenkinsfile
Fix settings.xml location in Jenkinsfile that moved the template file from spot-bugs folder to one level higher. This fixes errors in the pipeline related to not being able to find the settings.xml
> DB-11103 Fix Jenkins pipeline for scm pull

- platform_it/pom.xml
ASYNC_WAL doesn't eventually force a SYNC as I thought, so we need to
use SYNC_WAL if we want durability for standalone. See
https://issues.apache.org/jira/browse/HBASE-16689 for details
> DB-11136 Use SYNC_WAL in standalone

- platform_it/pom.xml
ASYNC_WAL doesn't eventually force a SYNC as I thought, so we need to
use SYNC_WAL if we want durability for standalone. See
https://issues.apache.org/jira/browse/HBASE-16689 for details
> DB-11136 Use SYNC_WAL in standalone (3.1)

- platform_it/pom.xml
ASYNC_WAL doesn't eventually force a SYNC as I thought, so we need to
use SYNC_WAL if we want durability for standalone. See
https://issues.apache.org/jira/browse/HBASE-16689 for details
> DB-11136 Use SYNC_WAL in standalone (3.0)

- mem_storage/src/main/java/com/splicemachine/si/impl/TxnPartition.java
Fixes a malformed list of Cell iterators that may happen when running concurrent triggers.  A null Cell iterator should not be added to the list. 
> ============= begin nested exception, level (2) ===========
> java.lang.NullPointerException
>         at com.splicemachine.derby.impl.store.access.base.SpliceController.batchFetch(SpliceController.java:197)
>         at com.splicemachine.derby.impl.store.access.base.SpliceController.fetch(SpliceController.java:164)
>         at com.splicemachine.derby.impl.store.access.base.SpliceController.fetch(SpliceController.java:160)
>         at com.splicemachine.db.impl.sql.catalog.TabInfoImpl.deleteRows(TabInfoImpl.java:782)
>         at com.splicemachine.db.impl.sql.catalog.TabInfoImpl.deleteRow(TabInfoImpl.java:640)
>         at …
> DB-11186 Don't add null cell iterator to TxnPartition batchGet results.

- pom.xml
Currently we have a proxy for these repositories in our nexus repository (splicemachine). After removing my local maven cache and the repositories, my instance is able to successfully build. Therefore this PR removes the redundant endpoints since if maven is not able to find the jars in our repository, then it wouldn't find it in the other repositories either.
Also took out the mapr repo since we also mirror that repository
> DB-11176 Remove cdh/hdp repository from pom.xml

- mem_storage/src/main/java/com/splicemachine/si/impl/TxnPartition.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceController.java
This reimplements DB-11186 by ignoring the null cell entries instead of not adding them to the list of found entries.  Some interfaces rely on checking whether a base row exists by checking the ordinal position of the results list for a null or empty cell.
> DB-11220 Re-do DB-11186.

- db-engine/src/main/java/com/splicemachine/db/impl/services/reflect/UpdateLoader.java
- platform_it/pom.xml
For splice in the cloud (both standalone and cluster), the path names of application jar files in the UpdateLoader do not start with file:/// or hdfs:/// as expected by SparkContext.addJar.  This fix adds them, if missing, so that the fix for DB-10759 functions properly in the cloud.
See [DB-11225](https://splicemachine.atlassian.net/browse/DB-11225?focusedCommentId=73427)
> DB-11225 Prepend hdfs or file URI tag when adding jars to SparkContext.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateSimplificationVisitor.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/NullPredicateIT.java
In this PR we fix an issue with evaluating `null` expressions with `NOT` operator, during simplification, we simplify expressions like `NOT <NullExpr>` to `<NullExpr>` which will be simplified further later on as in e.g. join-condition expressions where we simply replace `<NullExpr>` with `false`.
Please have a look `NullPredicateIT.java` for example cases.
> DB-11091 fix null expr. evluation with NOT.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryArithmeticOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/C_NodeNames.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConcatenationOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DecimalFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DeleteNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DenseRankFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DropAliasNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JavaToSQLValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/LikeEscapeOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NonStaticMethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NumericConstantNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ParameterNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLGrammarImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SetOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/StaticMethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TimeSpanNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TypeofOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UpdateNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceNodeFactoryImpl.java
This is a first part of starting to remove the NodeFactory (spliceengine/db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/NodeFactory.java) that is currently used by our SQL Parser to create the nodes from the Syntax Tree (sqlfgrammar.jj).
We want to remove NodeFactory and replace with simple, strongly typed constructors, because:
1. Node Factory is quite complicated code
2. we don't have safety when constructing the nodes. Potential errors that will ONLY be detected at run time include
1. calling getNode with wrong number of parameters. will result (at run time) in a throw in SanityManager.DEBUG, otherwise “nothing”, so Node will not be initialized)
2. calling getNode with wrong TYPE of parameters: will result (at run time) in java.lang.ClassCastException.
3. calling …
> DB-10961 remove node factory part 1

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryArithmeticOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/C_NodeNames.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConcatenationOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DecimalFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DeleteNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DenseRankFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DropAliasNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JavaToSQLValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/LikeEscapeOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NonStaticMethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NumericConstantNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ParameterNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLGrammarImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SetOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/StaticMethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TimeSpanNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TypeofOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UpdateNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceNodeFactoryImpl.java
This is a first part of starting to remove the NodeFactory (spliceengine/db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/NodeFactory.java) that is currently used by our SQL Parser to create the nodes from the Syntax Tree (sqlfgrammar.jj).
We want to remove NodeFactory and replace with simple, strongly typed constructors, because:
1. Node Factory is quite complicated code
2. we don't have safety when constructing the nodes. Potential errors that will ONLY be detected at run time include
1. calling getNode with wrong number of parameters. will result (at run time) in a throw in SanityManager.DEBUG, otherwise “nothing”, so Node will not be initialized)
2. calling getNode with wrong TYPE of parameters: will result (at run time) in java.lang.ClassCastException.
3. calling …
> DB-10961 remove node factory part 1 (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryArithmeticOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/C_NodeNames.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConcatenationOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DecimalFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DeleteNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DenseRankFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DropAliasNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JavaToSQLValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/LikeEscapeOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NonStaticMethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NumericConstantNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ParameterNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLGrammarImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SetOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/StaticMethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TimeSpanNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TypeofOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UpdateNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceNodeFactoryImpl.java
This is a first part of starting to remove the NodeFactory (spliceengine/db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/NodeFactory.java) that is currently used by our SQL Parser to create the nodes from the Syntax Tree (sqlfgrammar.jj).
We want to remove NodeFactory and replace with simple, strongly typed constructors, because:
1. Node Factory is quite complicated code
2. we don't have safety when constructing the nodes. Potential errors that will ONLY be detected at run time include
1. calling getNode with wrong number of parameters. will result (at run time) in a throw in SanityManager.DEBUG, otherwise “nothing”, so Node will not be initialized)
2. calling getNode with wrong TYPE of parameters: will result (at run time) in java.lang.ClassCastException.
3. calling …
> DB-10961 remove node factory part 1 (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryArithmeticOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CurrentDatetimeOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ExpressionClassBuilder.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/CurrentDatetime.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceDateFunctions.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TimestampIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceDateFunctionsTest.java
In this PR we provide support to [DB2's CURRENT TIMEZONE](https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0005887.html?pos=2).
According to the documentation, `CURRENT TIMEZONE` (or `CURRENT_TIMEZONE`) returns the server's timezone offset as `DEC(6,0)`. We can also use with a timestamp expression to return it in UTC (GMT).
Some example how this works (all examples assume that the server is running in IST (05:30+GMT)
```
splice> select current_timezone from t1;
1
-------
53000 -- decimal(6,0)
splice> select current_timestamp from  t1;
1
-----------------------------
2021-01-20 20:23:10.516897
splice> select current_timestamp - current_timezone from t1;
1
-----------------------------
2021-01-20 14:53:02.12 -- we shift 5:30 hours …
```
> DB-11126 support CURRENT TIMEZONE.

- db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Statement_IT.java
Fixes VALUES clause queries or triggers that use multiple joins and/or subqueries, e.g.
> CREATE TRIGGER FeatureTable_History_UPDATE_PREHISTORIC
> AFTER UPDATE ON FeatureTable
> REFERENCING OLD_TABLE AS OLDW NEW_TABLE AS NEWW
> FOR EACH STATEMENT
> WHEN (
>      (NOT EXISTS (SELECT 1 FROM FeatureTable_History H,NEWW N WHERE H.ENTITY_KEY=N.ENTITY_KEY AND N.LAST_UPDATE_TS >= H.ASOF_TS AND N.LAST_UPDATE_TS < H.UNTIL_TS))
>      AND
>      (EXISTS (SELECT 1 FROM OLDW,NEWW WHERE OLDW.ENTITY_KEY=NEWW.ENTITY_KEY AND OLDW.LAST_UPDATE_TS < NEWW.LAST_UPDATE_TS))
> )
> ...
The WHEN clause is converted to a VALUES clause internally.  Since the JoinConditionVisitor doesn't scan the entire RowResultSetNode tree for ResultColumns, an incomplete joinChainMap may be built leading to some column references …
> DB-11252 Fix JoinConditionVisitor childParentMap for VALUES clauses with subqueries.

- pipelines/spliceengine-PR/Jenkinsfile
- pipelines/spliceengine-branch/Jenkinsfile
- pipelines/spliceengine-jdbc/Jenkinsfile
- pipelines/spliceengine-platform/Jenkinsfile
Create a debugging node option for spliceengine-branch. 
-  Creates a non-spot instanced node that can be ssh'd into and debugged for issues. The ordinary standalone spot instances is under an internal VPC and will randomly get killed if the spot capacity is low (Possibly won't stay up long)
Switch spliceengine-platform pod to small ec2 node. 
- The spliceengine-platform flyweight pod currently dies after about an hour of idle time. The platform_it's take about 3ish hours to complete currently. While the tests still run, the flyweight job is killed, so even if the platform_it's all complete, the overall job will fail.
Remove ** from spliceengine-PR and spliceengine-platform
- There is not enough space in the disk to archive the entire workspace on jenkins master, since all job workspace …
> Add parameter, fix archiving and regex

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/SessionProperties.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/SessionPropertiesImpl.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SessionPropertyIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceNetConnection.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
Adds support for:
> set session_property minPlanTimeout=5000;
or
> connect ‘jdbc:splice://localhost:1527/splicedb;user=splice;password=admin;minPlanTimeout=3000’;
To allow queries at least the specified number of milliseconds in join planning.
> DB-11256 Session property minPlanTimeout

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceCatalogUpgradeScriptsTest.java
DB-8897 introduced a system table with conglomerate `SPLICE_CONGLOMERATE_SI`, and also an upgrade script `UpgradeConglomerateTable` to create this table. This table is used when other tables are created. However, that means it is are also used in some other upgrade scripts, specifically `UpgradeScriptToAddSysNaturalNumbersTable` from 1985. Since `UpgradeScriptToAddSysNaturalNumbersTable` runs before `UpgradeConglomerateTable`, this would fail.
Solution is to move `UpgradeConglomerateTable` script before `UpgradeScriptToAddSysNaturalNumbersTable` script.
See also DB-11134 for some scripts.
Basic idea:
PROFILE=cdh6.3.0,core
1. create a "snapshot" of a standalone 1980 cluster:
a. `git checkout tags/3.1.0.1980`
b. `./start-splice-cluster -p${PROFILE}`
c. `./start-splice-cluster -k` # stop …
> DB-11296 fix upgrades from 1985 to 1996

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Optimizer.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/SPSDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
This Jira replaces the problematic prepared statement check of DB-10773 with the following:
1. A check if a stored prepared statement is currently being compiled.  If so, the join planning time limit lower bound is set to 10 ms.
2. A check if a joinStrategy hint is present in the SQL.  If so, the join planning time limit lower bound is set to 2 ms.
Also fixed as part of this Jira:
1. A bug in DB-11256, where the max timeout setting when using Level2OptimizerImpl is set to zero, which could cause queries to time out too early and use a suboptimal join plan.
2. The join planner is updated to only consider nested loop join when planning a single table.  Nested loop join is a special "join strategy" which also knows how to handle single-table access paths.  The planner should never pick a …
> DB-11278 More join planning time for triggers and hinted joinStrategy

- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLChar.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/StringDataValue.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLGrammarImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceStringFunctions.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceStringFunctionsIT.java
Adds support for:
1. System function SYSFUN.RTRIM, which trims all trailing whitespaces off a string expression, e.g.
> values(sysfun.rtrim('abc   ') || sysfun.rtrim('abc   '));
> 1                                                                                                                                                                                                                                                               
> //----------------------------------------------------------------
> abcabc     
2. An extra parameter to the RTRIM operator/function which supports stripping multiple occurrences of a trim string from the end of an expression, e.g.
> values (rtrim('abcdefdef','def'));
> 1        
> //---------
> abc
> DB-11118 Add DB2-like RTRIM functionality

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DeleteOperationIT.java
This makes the FROM keyword in a DELETE FROM _tableName_  statement optional.
These statements are recognized as being identical:
DELETE T1;
DELETE FROM T1;
> DB-11312 Make the FROM clause of a DELETE statement optional.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ShowCreateTableIT.java
While doing 8 streams of  "create alias" at the same time (to speed up schema_create), all on different tables, there are write conflicts such as:
During ERROR SE014: Write Conflict detected between transactions 97147649 and 97147393.
The conflict happened when two txns were writing to unique index SYSALIASES_INDEX3(SCHEMAID, SPECIFICNAME).
The two create alias DDL were executed from different region servers, and got same specificname, which were generated according to timestamp and total number of generated SQL names. DataDictionaryImpl.getSystemSQLName() is guaranteed to be unique for a single server, but not cluster-wise. 
Scripts to create tables and aliases are attached in https://splicemachine.atlassian.net/browse/DB-10756. It should be tested on the cluster with more than 2 region …
> DB-10756 CREATE ALIAS - Write conflict detected

- pom.xml
Add the missing splice_ck modules to the hdp profiles
The jenkins build will fail at the end of the assembly module since it is looking for the splice_ck artifacts, which were never built since they were included in the list of required modules to be built in the hdp profile. 
Running a maven build should succeed successfully after the module is added
`mvn clean install -Pcore,hdp2.6.3 -DskipTests -Denv=hdp2.6.3`
You should also see the splice_ck module in the list of completed modules built
`[INFO] splice_ck .......................................... SUCCESS [  3.108 s]`
> add missing splice_ck modules to hdp profiles

- hbase_sql/src/main/java/com/splicemachine/olap/OlapServerMaster.java
Also avoids an unrunnable query situation if registering maxExecutorCores should cause an error in the future.  The error is logged, but not thrown.
> DB-11361 Avoid NPE on cloud clusters when registering maxExecutorCores.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TriggerHandler.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/txn/AbstractTxn.java
Fixes issues with concurrent row triggers:
1. Aborts other running trigger threads when one thread errors out, so the main thread doesn't try to clean up resources actively being used by running triggers.
2. Increase the size of the stored prepared statement cache, to decrease likelihood two threads are trying to recompile the same trigger simultaneously.
3. Use a ConcurrentHashMap-backed HashSet for the "children" Set of transactions in AbstractTxn, to avoid ConcurrentModificationException errors.
Part 3 will alleviate customer issues in the interim until DB-10276 is complete.  In that Jira I'm working on an issue where the LanguageConnectionContext used to get the transaction to elevate when compiling a trigger may sometimes be the wrong one (is gotten from the ContextService instead of …
> DB-11266 Fix trigger concurrency issues.

- db-engine/src/main/java/com/splicemachine/db/catalog/types/RoutineAliasInfo.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/StaticMethodCallNode.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
Adding better error output for when users try to call functions with wrong parameters.
Users can make various mistakes when calling a function, and the error message should help solving those.
Examples of current behavior:
```
splice> call SYSCS_UTIL.SYSCS_SET_GLOBAL_DATABASE_PROPERTY( 'a', 'b', 'c');
ERROR 42Y03: 'SYSCS_UTIL.SYSCS_SET_GLOBAL_DATABASE_PROPERTY' is not recognized as a function or procedure.
```
This is misleading, as there IS a function, however the parameter count is wrong.
```
splice> call SYSCS_UTIL.SYSCS_SET_GLOBAL_DATABASE_PROPERTY( 123, 123 );
ERROR 42846: Cannot convert types 'INTEGER' to 'VARCHAR'.
```
This is better than the behavior when having wrong parameter count. However, when calling a function with multiple parameters, it might not be clear which one of the …
> DB-9656 better error output for nonmatching parameters in CALL

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/LikeEscapeOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/LikeBitDataIT.java
In this PR we extend `LIKE` predicate to support operations on `for bit data` data types such as `varchar for bit data`.
To do this, we check in `LIKE` operator's binding phase whether we have any `for bit data` operand, if so, then we add an implicit cast to `VARCHAR` in Single Byte Character Set (SBCS) mode so we can parse the characters back if necessary which is important for processing escapes correctly in later generation and execution phases.
As an example, in this PR the following queries work:
```
create table t(c long varchar for bit data)
insert into t values 'a';
select * from t where c like 'a';
C
-
61
```
We added quite many tests (240) in this PR to address different possibilities of using `LIKE` operator with different types in LIKE operands, also to test prepared vs. …
> DB-11124 LIKE predicate support for [long] [var]char for bit data

- assembly/common/src/main/resources/bin/sqlshell.sh
- assembly/common/src/main/resources/bin/winsqlshell.cmd
- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/util.java
- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/utilMain.java
You can now run `sqlshell.sh` or `winsqlshell.cmd` (on windows) with `-x` mode, which is the same as starting sqlshell and then do `WITHOUT HEADER;`.
Run any query, e.g. `show tables`. In WITH HEADER mode, you get
```
splice> show tables;
TABLE_SCHEM         |TABLE_NAME                                        |CONGLOM_ID|REMARKS             
-------------------------------------------------------------------------------------------------------
SYS                 |SYSALIASES                                        |288       |                    
...
```
In WITHOUT HEADER mode you get
```
splice> show tables;
SYS                 |SYSALIASES                                        |288       |                    
...
```
By default (on startup of sqlshell, if no WITH or WITHOUT HEADER is …
> DB-11409 Add command line option -x to specify no headers for sqlshell

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceStringFunctionsIT.java
LTRIM with a 2nd parameter is not supported and should throw a syntax error.
Regression of DB-11118.
> DB-11400 Fix LTRIM grammar

- db-engine/src/main/java/com/splicemachine/db/iapi/types/DataTypeDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromVTI.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NewInvocationNode.java
- db-engine/src/main/java/com/splicemachine/db/vti/CompileTimeSchema.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/main/java/com/splicemachine/derby/vti/KafkaVTI.java
- hbase_sql/src/main/java/com/splicemachine/derby/vti/SpliceDatasetVTI.java
- hbase_sql/src/main/java/com/splicemachine/derby/vti/SpliceRDDVTI.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/hive/SMHiveRecordWriter.java
- splice_machine/src/main/java/com/splicemachine/derby/catalog/TriggerNewTransitionRows.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SchemaFilterVTI.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceAllRolesVTI.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceGroupUserVTI.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceIteratorVTI.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceJDBCVTI.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/iapi/DatasetProvider.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/VTIOperationIT.java
- sqlj-it-procs/src/main/java/org/splicetest/sqlj/PropertiesFileVTI.java
In this PR we allow querying a VTI without explicitly specifying the output result set provided the VTI class implements the newly introduced interface `CompileTimeSchema`.
The rationale behind this PR is that we want to be able to introduce a monitoring table-valued function called `MON_GET_CONNECTION`, which, [similar to DB2](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.sql.rtn.doc/doc/r0053938.html), has hundreds of columns, VTIs provide a way to implement table-valued functions as [documented in Derby](https://db.apache.org/derby/docs/10.11/publishedapi/org/apache/derby/vti/package-summary.html), however with this limitation (having to explicitly specify the output schema) it becomes very difficult to expose `MON_GET_CONNECTION` as a table-valued function. …
> DB-11401 allow querying VTI without specifying the schema.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNodeVector.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_Exists_IT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_InList_IT.java
DB-10774 modified the binding code to only add a SubqueryNode once to a subqueryList in an effort to bind the subquery only once in a given subtree.  The problem is there could be different subtrees that maintain their own subqueryList and they reference that SubqueryNode as well.  The SubqueryNode should be added to those other subqueryLists as well, but since the new flag thisSubqueryAddedToSubqueryList is now false, we fail to do so.
example query:
> insert into B values (
>     nullif(
>         case when
>             EXISTS (select C1 from C where EXISTS (select A1 from A))
>         then 14 end,
>         4)
> );
ERROR 42Z50: INTERNAL ERROR: Unable to generate code for
com.splicemachine.db.impl.sql.compile.SelectNode@45eb0df
The fix is to add the SubqueryNode to subqueryList, but …
> DB-11405 Fix 'Unable to generate code' error with multiple subqueries

- db-engine/src/main/java/com/splicemachine/db/iapi/ast/ISpliceVisitor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/C_NodeTypes.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/ConcatableDataValue.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLBinary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLChar.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/AbstractSpliceVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TranslateFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceStringFunctionsIT.java
This PR introduces TRANSLATE as a new SQL function. It is inspired from the DB2 implementation of translate that can be found here:
https://www.ibm.com/support/knowledgecenter/SSEPEK_10.0.0/sqlref/src/tpc/db2z_bif_translate.html
Usage:
`TRANSLATE(string_expression, outputTranslationTable, inputTranslationTable [, pad])
`
This function returns a new string, of type TYPEOF(string_expression)
If any operand is null, we return null
This new string is constructed the following way:
for each character c in string_expression:
if c is present in inputTranslationTable (position n), use outputTranslationTable[n]
else use c
For example:
```
translate('ABC', 'b', 'B') = 'AbC'
translate('ABC', 'ba', 'BA') = 'abC'
```
If outputTranslationTable is longer than inputTranslationTable, we ignore the excess …
> DB-11119 Support TRANSLATE function

- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/ijCommands.java
- splice_machine/src/test/java/com/splicemachine/derby/test/DatabaseMetaDataTestIT.java
Fix issues discovered by @dyang-splice in QA of DB-10890.
QA showed that if a table name contained escape or placeholder characters such as `\`, `_`, or `%` then `DESCRIBE` wasn't working as expected. The issue was not in `DESCRIBE` itself but in sqlshell's usage of a method that verifies the table exists, this method wasn't escaping the table name properly, now this is fixed.
Some test cases that were not working but now working (thanks @dyang-splice for providing those):
```
create table "TEMP  _TABLE"(j int);
create table "TEMP ESCAPE '\\' TABLE"(k int);
create table "\'TEMPTABLE\'"(p int);
create table "TEMP\TABLE"(q int);
create table "tee%sss"(X int);
create table "TEE%SSS"(Y int);
create table "TEE%SSSS"(z int);
describe  "TEMP  _TABLE"(j int);
describe  "TEMP ESCAPE '\\' TABLE"; …
```
> DB-11434 fix escaping table name in DESCRIBE (redux)

- db-engine/src/main/java/com/splicemachine/db/iapi/ast/ISpliceVisitor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/C_NodeTypes.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLChar.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/StringDataValue.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/AbstractSpliceVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/C_NodeNames.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorToString.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PosStrOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceNodeFactoryImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceStringFunctionsIT.java
Implement the POSSTR function, which finds the position of a search string in an expression.
Example:
> values posstr('abc','bc');
> 1          
> //-----------
> 2
> DB-11129 Implement POSSTR function

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportCSVWriterBuilder.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportOperationIT.java
`QUOTE_MODE` was ignored when running `EXPORT` on `[VAR]CHAR FOR BIT DATA` fields. We now properly surround those fields with `QUOTE_CHARACTER` when `QUOTE_MODE` is set to `ALWAYS`
Example:
```
DROP TABLE foo if exists;
CREATE TABLE foo (a int, b varchar(5) , c varchar(5) for bit data, d char(5) for bit data );
insert into foo values (4, 'abcde', 'abcde', 'abcde');
insert into foo values (0, '', '', '');
insert into foo values (null, null, null, null);
EXPORT to '/tmp/DB-10872'
AS CSV
FIELD_SEPARATOR ','
QUOTE_CHARACTER '"'
QUOTE_MODE ALWAYS
```
```
$ cat /tmp/DB-10872/part-r-00000.csv
,,,
4,"abcde","6162636465","6162636465"
0,"","","2020202020"
``` 
Tests were added to ExportOperationIT . We now test that properly for BIT DATA columns. We also added empty strings and NULL tests.
> DB-10872 consider QUOTE_ALWAYS when exporting FOR BIT DATA field 

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConstraintDefinitionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CreateTableNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLGrammarImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TableElementList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/DeclareLikeIT.java
This ticket introduces a new way to create tables:
```
create table base (a INT);
CREATE TABLE T1 LIKE base; 
show create table t1;
DDL
---
CREATE TABLE "SPLICE"."T1" (
"A" INTEGER
) ;
```
The newly created table will have the same column structure as the original one. Nullability and default values will also be the same as for the original one.
As DB2, we do not reproduce constraints, primary keys, etc. Only the column structure is ported to the new table
This is also supported when creating temporary tables:
```
DECLARE GLOBAL TEMPORARY TABLE T2 LIKE base;
show create table t2;
DDL
---
CREATE LOCAL TEMPORARY TABLE "SPLICE"."T2" (
"A" INTEGER
) ;
```
This was tested with temporary and non-temporary tables, with nullable and non nullable columns, with default (empty or not) values for …
> DB-11207 Support creation of table LIKE other table

- assembly/standalone/template/bin/functions.sh
- assembly/standalone/template/bin/start-splice.sh
This fixes nc hangs on Ubuntu 18.04 with the BSD version of nc.
We are using the same code we added in DB-9930 to ./start-splice-cluster. This runs on Mac, BSD and GNU versions of netcat (nc).
> DB-11433 fix start-splice.sh use of BSD nc (3.1)

- assembly/standalone/template/bin/functions.sh
- assembly/standalone/template/bin/start-splice.sh
This fixes nc hangs on Ubuntu 18.04 with the BSD version of nc.
We are using the same code we added in DB-9930 to ./start-splice-cluster. This runs on Mac, BSD and GNU versions of netcat (nc).
> DB-11433 fix start-splice.sh use of BSD nc (3.0)

- assembly/standalone/template/bin/functions.sh
- assembly/standalone/template/bin/start-splice.sh
This fixes nc hangs on Ubuntu 18.04 with the BSD version of nc.
We are using the same code we added in DB-9930 to ./start-splice-cluster. This runs on Mac, BSD and GNU versions of netcat (nc).
> DB-11433 fix start-splice.sh use of BSD nc

- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Performance_IT.java
Trigger_Performance_IT is failing on control, maybe due to slow Jenkins servers.  The target of DB-10276 is trigger performance on spark, so disable this test on control
> DB-11507 Skip tests on control in Trigger_Performance_IT

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Optimizer.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceLevel2OptimizerImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/JoinOrderJumpModeIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/JoinSelectionIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/BroadcastJoinIT.java
This effectively disables nested loop join on Spark by adding a huge cost penalty in the join planner.
Initially the idea was to only apply the penalty if no join predicates with low cardinality that enabled index access were present.
But due to underestimated join cardinality, documented in [DB-11521](https://splicemachine.atlassian.net/browse/DB-11521), bad nested loop joins could still get picked.  So for now we just avoid nested loop join whenever possible on Spark.
> DB-11006 Don't pick NestedLoopJoin on Spark unless there's no alternative

- start-splice-cluster
In this PR we enable JMX for running in mem-profile, this helps reproducing mem-profile tests which was passing on Jenkins but failing locally because in Jenkins we set the JMX when running these ITs under mem-profile, but when starting a local mem-profile cluster we do not.
> DB-11498 enable JMX for mem profile.

- hbase_sql/pom.xml
- mem_sql/pom.xml
- pom.xml
- splice_access_api/src/main/java/com/splicemachine/tools/version/ManifestFinder.java
Include MANIFEST only on top modules (hbase_sql or mem_sql)
`getSparkVersion()` reads the Spark version used to compile the Splice build from a MANIFEST file. We include MANIFEST files for all jars though, even those that don't depend on a specific Spark version, if we read the version from one of those we end up with the wrong one.
This fix only generates MANIFEST files for the top modules (hbase_sql and mem_sql)
Run Spark version-dependent code on platforms with different Spark versions, e.g. hdp3.1.5 (Spark 2.3) and dbaas3.0 (Spark 3.0)
> DB-11145 Set MANIFEST only for hbase/mem_sql modules

- platforms/hdp3.1.0/docs/HDP-installation.md
Documentation update to match Cloudera documentation. 
Encountered this issue with olapserver not starting up in HDP due to these steps missing from the HDP documentation. The steps are currently in the CDH documentation. The main important part of the documentation is the HDFS commands to add the user and splice directories with the correct permission.
New clusters should be able to startup and run OlapServer queries. A simple hinted query should run
```
SELECT * FROM SYS.SYSTABLES --splice-properties useSpark=true
;
```
> DB-11504 Add instructions for startup for hdp

- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
Previously, collection of table statistics of a schema was done lazily during streaming of results, i.e. whenever DRDA requests a new row of `analyze` result set we return a row pertaining one of the analyzed tables so far and we might trigger analyzing a new table assuming as long as we do not exceed `splice.statistics.collectSchemaStatisticsMaximumConcurrent` concurrent operations.
This is probably fine since the user normally wait for the results to arrive to consider the statement's execution complete, however if the user monitors active operations using `SYSCS_UTIL.SYSCS_GET_RUNNING_OPERATIONS` then some inconsistencies will be noticed, the reason is that `SYSCS_GET_RUNNING_OPERATIONS` reads information about running operation from a `OperationManager`, this manager has certain hooks …
> DB-10865 force statistics collection during analyze execution.

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DB2VarcharCompatibilityIT.java
This change fixes distinct operation when result set contains varchar columns on native Spark. According to SQL standard, character string comparison are done by padding the shorter string to the longer string's length according to collation in use. On native Spark, however, there is no such padding. 'abc' and 'abc  ' are different strings. Method `distinct()` or `dropDuplicates()` do not remove any of them since they are different.
To make Spark's `distinct()` and `dropDuplicates()` work as SQL standard defines, all StringType columns are rtrimmed before running the distinct operation. rtrimmed columns are added as extra columns to the data frame so that in the end we return a row from original data for each group, not a row with rtrimmed values.
This fix is currently guarded under DB2 …
> DB-11517 DB2 compatible varchar for (Native)SparkDataSet.distinct()

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/TriggerDescriptor.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Performance_IT.java
DB-10276 improved the performance of parallel row triggers on spark, but performance of serial row triggers on control got worse.
DB-10276 added a shallow clone of the SPSDescriptor on trigger compilation because when a table has multiple triggers, compiling one trigger invalidates the other triggers because they are dependent objects.  The SPSDescriptors are pre-compiled before statement execution and added to a local cache before being shipped off to the spark executors.  The shallow clone assures that compiling more triggers as part of the statement doesn't invalidate what is in the local cache.  However, DB-10276 also added code to do a shallow clone for statements run on control.  This prevented the dictionary cache from getting updated with the valid version of the SPSDescriptor …
> DB-11535 Fix trigger performance regression from DB-10276

- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Exec_Stored_Proc_IT.java
fixing IT failure in Trigger_Exec_Stored_Proc_IT
1. fixing IT failure in Trigger_Exec_Stored_Proc_IT
2. `SYSCS_SET_LOGGER_LEVEL` is now set to only allow admins to change this - normal user shouldn't set log level to DEBUG and slow down the system. Execution prevention is currently implemented with  `RoutineAliasInfo.MODIFIES_SQL_DATA` (we should change this, see DB-11542), which also prevents this function then to be used in BEFORE triggers (`java.sql.SQLSyntaxErrorException: Procedures that modify SQL data are not allowed in BEFORE triggers`). Therefore we're now using .after() in `Trigger_Exec_Stored_Proc_IT.testStatementTriggerSysStoredProc`.
(fix for IT)
> DB-10968 fix Trigger_Exec_Stored_Proc_IT

- db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAStatement.java
- db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java
- db-engine/src/main/java/com/splicemachine/db/iapi/error/PublicAPI.java
- db-engine/src/main/java/com/splicemachine/db/iapi/error/StandardException.java
- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextManager.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementPermission.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchRefresher.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/NormalizeOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
Under some circumstances, the Server Connection gets in an erroneous state, and the connection to the client is dropped. Symptoms are one of the following:
When executing a query through sqlshell (or other JDBC shells):
- `ERROR 08006: Insufficient data while reading from the network - expected a minimum of 6 bytes and received only 0 bytes.  The connection has been terminated.`
- `ERROR 08006: A network protocol error was encountered and the connection has been terminated: the requested command encountered an unarchitected and implementation-specific condition for which there was no architected message (additional information may be available in the derby.log file on the server)`
- `ERROR 08003: DERBY SQL error: SQLCODE: -1, SQLSTATE: 08003, SQLERRMC: No current connection.`
This fix …
> DB-10382/DB-11470 fix exception paths

- db-engine/src/main/java/com/splicemachine/db/iapi/stats/ColumnStatisticsImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CastNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNode.java
This change improves conglomerate cost estimation performance.
After frequency sketch size is increased to 8192, some queries get slower on first run. The time spent in optimizer is increased drastically.
There are three issues:
1. String literals representing date/time/timestamp are used to compare with column statistics values directly. The string literals are converted to date/time/timestamp values over and over again. Example predicate is `DATE_COL > '2010-11-05'
`.
2. `frequenciesSketch.getFrequentItems(ErrorType.NO_FALSE_POSITIVES)` sorts items internally. With sketch size increased to 8192, this sort involves a lot of `DataType.compare()`, making it slow.
3. `ColumnStatisticsImpl.getSkewedRowCountInRange()` compares every skewed value to start value and stop value. With sketch size …
> DB-11559 Improve conglomerate cost estimation performance

- db-engine/src/main/java/com/splicemachine/db/iapi/services/io/StoredFormatIds.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/ColumnDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/DataTypeDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/DataValueFactoryImpl.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/TypeId.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ParameterNode.java
- db-engine/src/main/protobuf/Derby.proto
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DB2VarcharCompatibilityIT.java
Queries involving a varchar index and IndexLookup step return wrong results with database property splice.db2.varchar.compatible = true.
In non-parameterized queries, a SQLVarcharDB2Compatible object is created in the gen phase (query compilation) for the value used in an index lookup (as opposed to the normal SQLVarchar).  For parameterized queries, we built an array of DataTypeDescriptors and end up calling DataTypeDescriptor.getNull() which checks the column data type and builds a null SQLVarchar.  
The fix is to introduce a new data type, VARCHAR_DB2_COMPATIBLE_TYPE_ID, to be used in place of VARCHAR_TYPE_ID in the parameter row data types array.  It will be used for internal purposes only.  The only usage of the parameter data types is to get a new null, so it should not require …
> DB-11552 Fix DB2VarcharCompatibility mode for parameterized queries

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
This change fixes a performance issue of `Predicate.scanSelectivity()`.
`Predicate.scanSelectivity()` has been working well. The problem occurs, however, when frequency sketch size is increased to 8192. In optimizing query hash `SsPX#UKs`, JProfiler shows that over 30% of the time is spent on doing `ReversePurgeItemHashMap.hashProbe()`, indicating that `ReversePurgeItemHashMap` in sketch library may have a performance issue when map size is big (although 8192 is not very big...). 
A solution on our side is to cache scan selectivity of a predicate so that `scanSelectivity()` doesn't always ask statistics and calculates over and over again. Given a predicate, its scan selectivity should stay the same for a given table. With that in mind, we can have a HashMap<Optimizable, Double> to cache …
> DB-11541 Cache predicate scan selectivity

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/UserDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/AccessFactory.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedConnection.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/BaseDataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/test/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImplTest.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateDatabaseConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/SpliceAccessManager.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/MultiDatabaseIT.java
This disables multidatabase as a default and introduces a new system procedure to enable it.
This introduces two new system procedures: 
```
SYSCS_UTIL.SYSCS_ENABLE_MULTIDATABASE()
SYSCS_UTIL.SYSCS_DISABLE_MULTIDATABASE()
```
Creating a new database is forbidden if multidatabase is disabled. Disabling multidatabase after the creation of a new database does not destroy that database, but only prevents the creation of new ones.
This parameter is persisted in zookeeper, because we need to be able to access during connection time.
```
splice> show databases;
DATABASENAME
------------------------------------
SPLICEDB
splice> connect 'jdbc:splice://localhost:1527/splicedb3;user=foo;password=pass;create=true';
ERROR 42Y19: DERBY SQL error: SQLCODE: -1, SQLSTATE: 42Y19, SQLERRMC: Multidatabase is …
```
> DB-10258 Create parameter to disallow multidatabase creation

- db-engine/src/main/java/com/splicemachine/db/impl/ast/PredicateUtils.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DefaultPredicateSelectivity.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectivityUtil.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SelectivityIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/CrossJoinIT.java
A cross join of two tables is picking the large table as the right table and broadcasting it, leading to out of memory errors or query execution that runs seemingly forever.
Broadcast costs are dominating the execution of cross join when the broadcast table is large, but the cost formula estimates that the join costs are 3 orders of magnitude larger than remote cost of doing the broadcast.  
Remote cost formula:
> remoteCost = openLatency + closeLatency + totalRowCount * totalSelectivity * remoteLatency * (1+colSizeFactor/1024d)
remoteLatency is 10.0.
Join row cost formula:
> joiningRowCost = numOfJoinedRows * localLatency;
localLatency is 1.0, but the number of joined rows is so high that joiningRowCost dominates.
For a query of the form:
> select count(*) from
>        t1 BH, t1 BU
> …
> DB-11476 Apply computeSqrtLevel selectivity to the correct level

- db-engine/src/main/java/com/splicemachine/db/iapi/error/StandardException.java
- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextManager.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementPermission.java
Under some circumstances, the Server Connection gets in an erroneous state, and the connection to the client is dropped. Symptoms are one of the following:
When executing a query through sqlshell (or other JDBC shells):
- `ERROR 08006: Insufficient data while reading from the network - expected a minimum of 6 bytes and received only 0 bytes.  The connection has been terminated.`
- `ERROR 08006: A network protocol error was encountered and the connection has been terminated: the requested command encountered an unarchitected and implementation-specific condition for which there was no architected message (additional information may be available in the derby.log file on the server)`
- `ERROR 08003: DERBY SQL error: SQLCODE: -1, SQLSTATE: 08003, SQLERRMC: No current connection.`
This fix …
> DB-10382 fix exception paths (3.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/error/StandardException.java
- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextManager.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementPermission.java
Under some circumstances, the Server Connection gets in an erroneous state, and the connection to the client is dropped. Symptoms are one of the following:
When executing a query through sqlshell (or other JDBC shells):
- `ERROR 08006: Insufficient data while reading from the network - expected a minimum of 6 bytes and received only 0 bytes.  The connection has been terminated.`
- `ERROR 08006: A network protocol error was encountered and the connection has been terminated: the requested command encountered an unarchitected and implementation-specific condition for which there was no architected message (additional information may be available in the derby.log file on the server)`
- `ERROR 08003: DERBY SQL error: SQLCODE: -1, SQLSTATE: 08003, SQLERRMC: No current connection.`
This fix …
> DB-10382 fix exception paths (3.0)

- hbase_storage/src/main/java/com/splicemachine/storage/HLock.java
Get out of infinite loop if we hit timeout taking a lock
In SIObserver.prePut() there's a chance we enter an infinite loop if we hit a lock timeout. We'll report NOT_RUN for the affected rows and we'll retry again thinking we failed to take the lock due to a concurrent write, but since we hit a timeout we'll always return NOT_RUN. 
The change raises an exception in this case so that we can deal with it at a different layer.
I tested it manually with breakpoints, this is almost impossible to test programatically.
I tested:
* Conflict case, two concurrent transactions try to modify the same row, one takes the lock the other retries a few times
* Timeout case, operation expires and lock times out, we raise an exception to the user
> DB-9588 Get out of infinite loop if we hit timeout

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSFOREIGNKEYSRowFactory.java
- db-engine/src/main/resources/com/splicemachine/db/impl/sql/catalog/syscat_references_view.sql
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceCatalogUpgradeScriptsTest.java
- splice_machine/src/test/java/com/splicemachine/foreignkeys/ForeignKeyMetadataIT.java
This change adds `FK_COLNAMES` and `PK_COLNAMES` columns to system view `SYSCAT.REFERENCES`.
DB2 drops columns `FK_COLNAMES` and `PK_COLNAMES` in the latest version. However, customer has queries that rely on these columns. For compatibility, we want to add them to the view, too.
The column data types are `VARCHAR(640)` as of DB2 LUW 9.7.0.
Values in these columns are:
`FK_COLNAMES`: foreign key column names of a foreign key constraint concatenated with comma as separator.
`PK_COLNAMES`: primary key column names of a primary key constraint concatenated with comma as separator.
`ForeignKeyMetadataIT.testReferencesAndSysKeyColUseViews` is updated to reflect this change.
> DB-11567 Add FK_COLNAMES and PK_COLNAMES to SYSCAT.REFERENCES

- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLChar.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/StringDataValue.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TranslateFunctionNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DB2VarcharCompatibilityIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceStringFunctionsIT.java
When `splice.db2.varchar.compatible` is set to true, SQLChar.{replace,strip,etc.} should return a `SQLDB2Varchar`
Functions in SQLChar (substring, split_part, right, left, replace, translate, ansiTrim, db2Trim) need to create a new `SQLVarchar` to store the result. If `splice.db2.varchar.compatible` is set to true, we should make sure that the result will be stored in a `SQLVarcharDB2Compatible` instead.
Comparisons done on `replace(SQLChar)` would not behave according to that parameter before that change.
```
call syscs_util.syscs_set_global_database_property('splice.db2.varchar.compatible', false);
values 'abcdefgh            '=strip(replace(TRANSLATE('abcdefgh            ',' ',X'00'),' ',''));
1
-----
false
call syscs_util.syscs_set_global_database_property('splice.db2.varchar.compatibl …
```
> DB-11570 Use SQLDB2Varchar in SQLChar.getNewVarchar when applicable

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CastNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLGrammarImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/NullPredicateIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
> DB-11605 fix using NULL in case when/else

- splice_machine/src/test/java/com/splicemachine/benchmark/TriggerBenchmark.java
- splice_machine/src/test/java/com/splicemachine/test/Benchmark.java
New _@Category(Benchmark.class)_.
New _TriggerBenchmark_ is not included in the default IT run (by naming convention).
The benchmark is runnable from IDE against standalone Splice or a remote cluster.
> DB-11579 Convert a trigger microbenchmark to a performance IT

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SimpleStringOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TranslateFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceStringFunctionsIT.java
TRANSLATE('abc') should parse properly and return 'ABC'
We now supports TRANSLATE with only one parameter. It should be equivalent to UPPER and return a new uppercased string.
We currently do not support TRANSLATE on BIT DATA TYPES.
Running TRANSLATE on any other type will cast the first operand to VARCHAR.
```
splice> select translate('abc');
1
---
ABC
1 row selected
ELAPSED TIME = 4 milliseconds
splice> select translate(1E1);
1
------------------------------------------------------
10.0
1 row selected
ELAPSED TIME = 4 milliseconds
splice> select translate(1.0976);
1
-------
1.0976
1 row selected
ELAPSED TIME = 6 milliseconds
splice> select translate(cast('test translate' as varchar(30)))
> ;
1
------------------------------
TEST TRANSLATE
1 row selected
ELAPSED TIME = 16 milliseconds …
```
> DB-11119 Support TRANSLATE with one parameter

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CursorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumn.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumnList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultSetNode.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PreparedStatementIT.java
Introduced `splice.bind.cursorUntypedExpressionType` to hint `select ?`'s type.
This PR introduces a new global database property: `splice.bind.cursorUntypedExpressionType`.
As of now, the only supported value (beside null) for that parameter is `'varchar'`.
If that parameter is set, we assume the type of a '?' at top select level to be `VARCHAR(254)`.
This is a workaround introduced until we provide proper deferred prepare statement support, at which point, this parameter can be discontinued once DB-11582 is addressed.
```
splice> call syscs_util.syscs_set_global_database_property('splice.bind.cursorUntypedExpressionType', null);
name                |value
--------------------------------------------------------------------------------------------------- …
```
> DB-11564 Support hinting cursor '?' 

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CastNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLGrammarImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/NullPredicateIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
> DB-11605 fix using NULL in case when/else (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CastNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLGrammarImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/NullPredicateIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
> DB-11605 fix using NULL in case when/else (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSCONGLOMERATESRowFactory.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ViewIT.java
DB-11610 broke SYSCAT.INDEXCOLUSE, this fixes it.
`select * from syscat.indexcoluse` should execute normally (added IT now).
> DB-11610 fix broken SYSCAT.INDEXCOLUSE

- hbase_sql/src/main/java/com/splicemachine/ddl/ZooKeeperDDLWatchChecker.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/AsynchronousDDLWatcher.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchChecker.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchRefresher.java
This PR fixes an issue only happens if a region server restarts and lost most recent DDL demarcation point. The workload initiated(from a different region server) before  most recent DDL demarcation point may try to use data dictionary cache and read data that's not supposed to be visible to it.
For every DDL, we set a DDL demarcation point(transaction id) in DDL refresher. Any txns started earlier than this demarcation point is forbidden from reading/writing data dictionary cache, because the DDL may have changed data dictionary. The data dictionary cache can only contain data that's visible after demarcation point. However, demarcation point is not persisted. If a region server restarts, it loses the most recent DDL transaction id.
We have found in a rare case, a truncated, insert and …
> DB-11133: persist DDL demarcation point to zookeeper

- db-engine/src/main/java/com/splicemachine/db/iapi/types/ProtobufUtils.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/AvgAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/DecimalBufferedSumAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/DoubleBufferedSumAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/LongBufferedSumAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/MaxMinAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/SumAggregator.java
- db-engine/src/main/protobuf/Derby.proto
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DB2VarcharCompatibilityIT.java
A regression due to serialization changes to avg aggregator
The SumAggregator included in a AvgAggregator can be one of LongBufferedSumAggregator, DecimalBufferedSumAggregator, or DoubleBufferedSumAggregator. When it is deserialized, we should find out its correct data type and construct the right aggregator.
This is only reproducible if a grouped aggregation is executed a normal spark processor (not native spark). To disable native spark, set the following database property
```
call syscs_util.syscs_set_global_database_property('splice.execution.nativeSparkAggregationMode', 'off');
create table AG (a int, b real, c bigint, d decimal(15,2));
insert into AG values(1, 1, 2, 3);
insert into AG values(2, 1, 2, 3);
insert into AG values(3, 1, 2, 3);
insert into AG select a, b+1, c+1, d+1 from …
```
> DB-11636: fix avg aggregator regression

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeStoredObjects.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/ConglomerateUtils.java
The PR improves data dictionary upgrade(DB-10410)
DB-10410 under-estimate the size of data dictionary tables. It rewrites a table by first reading all its descriptors in memory and write each of them back using new serialization format. For tables with many rows(sys.syscolumns), it takes a long time to upgrade. For tables whose column size is very big(sys.syscolumnstats), upgrade may run OOM and fail.
This PR solve this problem by
1. cloning system tables that are to be upgraded. This is done using HBase snapshot and does not move data
2. reading a batch of rows from cloned table, and batch write to original table using new serialization format. Only a batch of rows are stored in memory, so upgrade will never run OOM. Batch write improves upgrade performance.
Build a pre-2003 cluster and …
>  DB-11644: improve dictionary serialization upgrade

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/CrossJoinOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DB2VarcharCompatibilityIT.java
Implements native spark cross join for DB2 varchar compatibility mode.
When cross join cannot run natively in spark it has a broadcast join implementation to fill the gap.  This implementation does not honor the flag indicating the right table should not be cached.  Previously, when splice.db2.varchar.compatible is set to true, a cross join selected by the optimizer does not qualify for native spark, so if the join planner ever mistakenly picks the large table as the right table of cross join we can hit an out of memory condition if the table is too large to be broadcast.
Fix:
Implement native spark cross join for DB2 mode by adding trimmed join columns so trailing spaces are ignored.  Also add IS NOT NULL conditions on the left and right join keys.  The remaining case that can't use …
> DB-11639 Native spark cross join for DB2 mode

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/SessionProperties.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/SessionPropertiesImpl.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/IndexPrefixIterationIT.java
- splice_machine/src/test/test-data/subquery/IndexPrefixIterationTestTables.sql
During index lookup the wrong base table field is used to locate the column side of the predicate and no matching column is found, leading to NPE.
In `PredicateList.orderUsefulPredicates`, when an index access is identified as not using the first index column AccessPath.numUnusedLeadingIndexFields is set to 1.  The logic should only kick in when examining the first column position of an index, but it sometimes gets invoked after the first index column is already found:
>                     if (indexPrefixIterationAllowed &&
>                         (!thisPred.isHashableJoinPredicate() || considerJoinPredicateAsKey) &&
>                          (thisIndexPosition-currentStartPosition) == numColsInStartPred + 1) {
>                         accessPath.setNumUnusedLeadingIndexFields(1);
> …
> DB-11675 Fix NPE in IndexLookup: SPLICE-2399 regression

- hbase_sql/src/main/java/com/splicemachine/compactions/SpliceDefaultFlusher.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/StressSparkIT.java
- hbase_sql/src/test/java/com/splicemachine/hbase/FlushDeadlockWhenRegionInClosingStateIT.java
- hbase_sql/src/test/java/com/splicemachine/test/HBaseTestUtils.java
We should not try to purge any data when flushing the memstore if the region being flushed is closing
When flushing the memstore to disk, we call `getTxnLowWatermark` to understand what can be purged. 
If a region that is necessary for `getTxnLowWatermark` is closing, we will hang until that region is back online. However, if that region is the very one we try to flush, this will result in a deadlock.
We now make sure that a region isn't closing before trying to call `getTxnLowWatermark`
An easy way to reproduce in standalone is:
```
create table a(i int); -- add some data to SYSTABLES
CALL SYSCS_UTIL.INVALIDATE_GLOBAL_DICTIONARY_CACHE(); -- invalidate caches so we have to go to HBase to retrieve TableDescriptor
```
then from hbase shell
```
disable 'splice:48' # SYSTABLE conglomerate, …
```
> DB-11693 Skip purging in memstore flushes if region is closing 

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RankFunctionNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
This improves the error message if RANK is used without an ORDER BY clause.
```
DROP TABLE WINDOW_RANK_BI_S.RANK_BIGINT_table;
CREATE TABLE WINDOW_RANK_BI_S.RANK_BIGINT_table (column_1 BIGINT, column_2 BIGINT);
INSERT INTO WINDOW_RANK_BI_S.RANK_BIGINT_table (column_2, column_1) values (-1820363457914885439, 2365922364770649437);
SELECT column_1, RANK() OVER () from WINDOW_RANK_BI_S.RANK_BIGINT_table ORDER BY 1 NULLS FIRST, 2 NULLS FIRST;
```
This should return an error like `ERROR 42X01: Syntax error: RANK requires an ORDER BY clause`
> DB-11620 improve error message for missing ORDER BY in RANK

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RankFunctionNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
> DB-11620 improve error message for missing ORDER BY in RANK (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RankFunctionNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
> DB-11620 improve error message for missing ORDER BY in RANK (3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/ast/ISpliceVisitor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Visitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/AggregateVectorCleaner.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/RepeatedPredicateVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/SpliceDerbyVisitorAdapter.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/GroupedAggregateOperationIT.java
Fixes NullPointerException in aggregate queries with repeated predicates;
For a query such as:
```
EXPLAIN SELECT
A.C1, SUM(A.DIFFERENZ)
FROM ( SELECT A1.C1,C2+1 AS "DIFFERENZ" FROM A1 WHERE A1.C1 = '' ) A, A1 B
WHERE A.C1 = B.C1
GROUP BY A.C1
HAVING ((SUM(DIFFERENZ) <= 4999 AND A.C1 <> '') OR
(SUM(DIFFERENZ) <= 4999 AND A.C1 = '' AND '10' = '10') OR
(SUM(DIFFERENZ) <= 1000 AND A.C1 = '' AND '10' <> '10'));
```
The predicate SUM(DIFFERENZ) <= 4999 is repeated, and ends up getting factored out of the OR'ed predicates by RepeatedPredicateVisitor and replaced with a new predicate instance in a top-level AND.  
Root cause:
When processing a SelectNode we pass aggregate vector "havingAggregates" to bindExpression in the binding phase: …
> DB-11613 Fix NPE in aggregate queries with repeated predicates

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryComparisonOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConcatenationOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PreparedStatementIT.java
Assume operands types of `? || ?` to be VARCHAR
Two things are introduced by this PR:
1. We assume both operands of the concatenation operator to be VARCHAR if they are both unkwnon
2. We cast LONG VARCHAR back to VARCHAR when trying to compare LONG VARCHAR to another string type
The second point is necessary because the result of `? || ?` is of type LONG VARCHAR
```
prepare foo as 'select ? || ?';
execute foo using 'values (''abc'', ''def'')';
1
-
abcdef
prepare foo as 'select ''abcdef'' = ? || ?';
execute foo using 'values (''abc'', ''def'')';
1
-
true
```
> DB-11625 Support both operands of concat to be parameters

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/scanner/SITableScanner.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/filter/PackedTxnFilter.java
Skip checking older versions of a row once accumulating its columns finishes
When we do an index scan, we do two things:
1. Scan hbase index conglomerate to identify affected index row(s).
2. For each index row, we look it up in the base table to add any missing columns.
In the second step, we were unnecessarily scanning all base table user_data versions, if the number of updates is relatively small, this is OK since the user_data versions is not too big, however if we are doing too many updates in a table with min. retention period (MRP) defined -effectively preventing flushes- it could become very costly to go through previous versions.
Create a table with a large amount of updates:
```
call SYSCS_UTIL.SET_MIN_RETENTION_PERIOD('SPLICE',null, 604800);
drop table t2 if exists;
create …
```
> DB-11445 skip checking older versions once row accumulation is complete.

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/ResultSet.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/StatementContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedResultSet.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericStatementContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/BasicNoPutResultSetImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlUtils.java
- splice_machine/src/test/java/com/splicemachine/derby/transactions/QueryTimeoutIT.java
JDBC timeout is not respected by some queries.
JDBC query timeout is not respected by a query with many stages, because the timeout applies for a stage, not for the whole query. One example is select * query that runs on spark. If each spark task can complete within timeout, the query will succeed, even though it runs much longer than JDBC query timeout.
Write a JDBC program and set query timeout to a small number. Run select * SQL on a big table. If the query runtime is expected to longer than timeout, it should fail.
> DB-11677:fix JDBC timeout

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/ResultSet.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/StatementContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedResultSet.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericStatementContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/BasicNoPutResultSetImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlUtils.java
- splice_machine/src/test/java/com/splicemachine/derby/transactions/QueryTimeoutIT.java
JDBC timeout is not respected by some queries.
JDBC query timeout is not respected by a query with many stages, because the timeout applies for a stage, not for the whole query. One example is select * query that runs on spark. If each spark task can complete within timeout, the query will succeed, even though it runs much longer than JDBC query timeout.
Write a JDBC program and set query timeout to a small number. Run select * SQL on a big table. If the query runtime is expected to longer than timeout, it should fail.
> DB-11677:fix JDBC timeout(3.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/ResultSet.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/StatementContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedResultSet.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericStatementContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/BasicNoPutResultSetImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlUtils.java
- splice_machine/src/test/java/com/splicemachine/derby/transactions/QueryTimeoutIT.java
JDBC timeout is not respected by some queries.
JDBC query timeout is not respected by a query with many stages, because the timeout applies for a stage, not for the whole query. One example is select * query that runs on spark. If each spark task can complete within timeout, the query will succeed, even though it runs much longer than JDBC query timeout.
Write a JDBC program and set query timeout to a small number. Run select * SQL on a big table. If the query runtime is expected to longer than timeout, it should fail.
> DB-11677:fix JDBC timeout(3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
Force creating a new CC when generating code for explain plan
We noticed that when running explain on some SQL statements and the same CC (which we use to generate the activation of the statement) is used again to generate the activation of the explain we might end up with an incorrect activation since the CC contains some state that belongs to other activation.
This was noticed by the QA team when running some regression tests, please refer to their test plan for more information, what's interesting is that this error does not show up with sqlshell but only through JDBC driver.
> DB-11695 force creating a new CC for generating code of explain plan.

- db-client/src/main/java/com/splicemachine/db/client/am/ClientConnection.java
- db-client/src/main/java/com/splicemachine/db/client/am/ColumnMetaData.java
- db-client/src/main/java/com/splicemachine/db/client/am/Cursor.java
- db-client/src/main/java/com/splicemachine/db/client/net/NetStatementReply.java
- db-client/src/main/java/com/splicemachine/db/jdbc/ClientBaseDataSource.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedConnection40.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/Attribute.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceNetConnection.java
- splice_machine/src/test/java/com/splicemachine/jdbc/JdbcApiIT.java
This change makes JDBC `getColumnDisplayWidth` method returns the same value as DB2 for decimal and numeric type columns.
Comparison of return values of `getColumnDisplayWidth` between splice and DB2:
|  | splice | splice example | DB2 | DB2 example |
|------|-------|-------|-------|-------|
| precision > scale > 0 | precision + 2 | -11.12 | precision + 2 | -11.12 |
| precision == scale | precision + 3 | -0.13 | precision + 2 | -.13 |
| scale == 0 | precision + 1 | -12 | precision + 2 | -12. |
Examples above show why `precision + 2` is always sufficient in DB2.
This change introduces a new JDBC connection attribute `jdbcDb2CompatibleMode=[true|false]` to set the JDBC `getColumnDisplayWidth` method.
Note that the string representation is purely a client thing. `getString()` of `SQLDecimal` …
> DB-10772 DB2-compatible getColumnDisplaySize() for decimals

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinCache.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinNoCacheLoader.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ValueRowMapTableLoader.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/IteratorUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/broadcast/AbstractBroadcastJoinFlatMapFunction.java
If a broadcast join task is killed when it is loading the inner table to a cache, it does not terminate immediately. 
If a broadcast join task is killed when it is loading the inner table to a cache, it does not terminate immediately. Broadcast join does not check whether the task has been killed until it has completed cache loading. If the inner table is big, it will waste time and resources executing cache loading.
To fix the issue, the inner table rows are transformed to an InterruptibleIterator. When each row is read from the iterator, a task context is checked to find out whether the task has been killed. If so, an exception will be raised to terminate cache loading.
Run TPCH1 query without using native spark dataset. Cancel the job during the 1st stage. The task should be terminated …
> DB-11637: abort broadcast join cache loading if spark task has been killed

- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java
fix NPE that may prevent txn from committing
Backport a fix by @jpanko1 from master to branch-3.0. The NPE can cause a txn never commit or abort, preventing vacuum from cleaning up unused tables for ITs. ITs will eventually run out of memory and crash.
This should improve ITs stability
> DB-11742: fix NPE that may prevent txn from committing

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinCache.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinNoCacheLoader.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ValueRowMapTableLoader.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/IteratorUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/broadcast/AbstractBroadcastJoinFlatMapFunction.java
> DB-11637: abort broadcast join cache loading if spark task has been killed(3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinCache.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinNoCacheLoader.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ValueRowMapTableLoader.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/IteratorUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/broadcast/AbstractBroadcastJoinFlatMapFunction.java
> DB-11637: abort broadcast join cache loading if spark task has been killed(3.0)

- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Performance_IT.java
Increase statement trigger IT timeout
Increase the timeout of testStatementTriggersRuntimeUnderLimit from 10 seconds to 15 seconds.  ITs run much slower on colo clusters, and testStatementTriggersRuntimeUnderLimit runs well under 10 seconds on a laptop often takes 11 or 12 seconds on a colo system.
Run testStatementTriggersRuntimeUnderLimit on a colo system and verify it passes.
> DB-11666 Timeout of testStatementTriggersRuntimeUnderLimit: 10s -> 15s

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSALIASESRowFactory.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSTRIGGERSRowFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/ViewDefinitions.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/CreateAliasIT.java
- splice_machine/src/test/java/com/splicemachine/derby/security/MetaDataAccessControlIT.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Create_IT.java
- DB-11267 added SYSVW.SYSTRIGGERSVIEW
- DB-11267 added SYSVW.SYSALIASESVIEW
- DB-11688 fix SYSINDEXCOLUSE in SYSALIASES
added SYSVW.SYSTRIGGERSVIEW and SYSVW.SYSALIASESVIEW since SYS.SYSTRIGGERS and SYS.SYSALIASES can not be directly queried over JDBC due to marshal problems.
Execute this query without error (with sqlshell from spliceengine)
```
select * from SYS.SYSALIASES WHERE ALIAS = 'SYSINDEXCOLUSE';
```
Execute this query without error (with ext. sqlshell)
```
select * from SYSVW.SYSALIASESVIEW WHERE ALIAS = 'SYSINDEXCOLUSE';
```
make sure `SYSVW.SYSTRIGGERSVIEW` would return at least one line by creating an example table+trigger:
```
CREATE TABLE T1(A VARCHAR(5), B VARCHAR(5));
CREATE TRIGGER mytrigger BEFORE INSERT
ON t1 REFERENCING NEW AS N
FOR EACH ROW
BEGIN ATOMIC
SET N.a = …
```
> DB-11267 add SYSVW.SYSTRIGGERSVIEW

- pipelines/spliceengine-branch/Jenkinsfile
- pipelines/spliceengine-core/Jenkinsfile
- pipelines/spliceengine-hdp/Jenkinsfile
- pipelines/spliceengine-jdbc/Jenkinsfile
- pipelines/spliceengine-mapr/Jenkinsfile
- pipelines/spliceengine-nsds/Jenkinsfile
- pipelines/spliceengine-parcel/Jenkinsfile
- pipelines/spliceengine-platform/Jenkinsfile
- pipelines/spliceengine-sqlshell/Jenkinsfile
- pipelines/spot-bugs/Jenkinsfile
Update pipelines to reference main instead of master
The PR updates the source branch references in the main branch to main instead of master. There also is some work needed to point to main in Jenkins whenever we cutover along with the other pipelines in the other repos, such as the weekly-build script.
> DB-11697 Update pipeline source branch to main

- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/TransactionController.java
- db-engine/src/main/java/com/splicemachine/db/impl/db/BasicDatabase.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_access_api/src/main/java/com/splicemachine/access/api/PartitionAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeConglomerateTable.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeStoredObjects.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/PropertyConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/SpliceTransactionManager.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/ConglomerateUtils.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceCatalogUpgradeScriptsTest.java
If upgrade from pre-2003 to post-2003 aborts abruptly, system tables are left in an inconsistent state. This PR roll back previous upgrade in next startup
If upgrade from pre-2003 to post-2003 aborts abruptly, system tables are left in an inconsistent state - some system tables are encoded in new serialization format, while others are still in old format. For next restart, master server will have problem reading objects from system tables.
This PR address this problem by rolling back the previous failed upgrade. All tables that has been rewritten using new serialization format are truncated. The backup tables that are still in old serialization format are restored. The upgrade process will start from scratch.
During an upgrade from pre-2003 to post-2003 release, tail master server log. …
> DB-11684: recover from data dictionary serialization upgrade failure

- splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/IndexPrefixIterationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/JoinOrderJumpModeIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
This change increases `DEFAULT_DETERMINE_SPARK_ROW_THRESHOLD` to 80000.
20000 seems to be a small number for determining if a query should go to OLTP or OLAP. Several cases (`SVqKB1=#`, `S6IvIPML`, `SuOpWcwG`, ) indicate that scanning more than 20K rows and do joins on OLTP are actually still faster than in OLAP.
The query hashes described above should now get a OLTP plan and run faster than before. Example:
`SuOpWcwG` should now run on OLTP and finish under 1 second. The same plan executed on OLAP would cost about 20 seconds.
> DB-11717 Increase default Spark row threshold to 80K

- splice_spark/src/main/spark2.2/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark2.3/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark2.4/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark3.0/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceIT.scala
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/SplicemachineContextIT.scala
- splice_spark2/src/main/scala/com/splicemachine/spark2/splicemachine/SplicemachineContext.scala
- splice_spark2/src/test/scala/com/splicemachine/spark2/splicemachine/SplicemachineContextIT.scala
NSDS bulk import function will now return the count of imported records.  It was previously not returning anything.
It now returns the count returned from the JDBC Statement executeUpdate() call.
In the DB, set up a table:
`splice> create table abc.cars(number int primary key,
make  varchar(20),
model varchar(20) );`
In Spark, bulk import a dataframe and check that bulk import returns the number of records imported.
`scala> val carsdfi = Seq(
(1, "Toyota", "Camry"),
(2, "Honda", "Accord"),
(3, "Subaru", "Impreza"),
(4, "Chevy", "Volt")
).toDF("NUMBER", "MAKE", "MODEL")`
`scala> spc.bulkImportHFile(carsdfi, "abc.cars", collection.mutable.Map("bulkImportDirectory" -> "/tmp/bi"))`
`res0: Long = 4`
> DB-11789 NSDS Bulk Import to Return Count of Imported Rows

- splice_spark/src/main/spark2.2/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark2.3/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark2.4/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark3.0/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceIT.scala
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/SplicemachineContextIT.scala
- splice_spark2/src/main/scala/com/splicemachine/spark2/splicemachine/SplicemachineContext.scala
- splice_spark2/src/test/scala/com/splicemachine/spark2/splicemachine/SplicemachineContextIT.scala
NSDS bulk import function will now return the count of imported records.  It was previously not returning anything.
It now returns the count returned from the JDBC Statement executeUpdate() call.
In the DB, set up a table:
`splice> create table abc.cars(number int primary key,
make  varchar(20),
model varchar(20) );`
In Spark, bulk import a dataframe and check that bulk import returns the number of records imported.
`scala> val carsdfi = Seq(
(1, "Toyota", "Camry"),
(2, "Honda", "Accord"),
(3, "Subaru", "Impreza"),
(4, "Chevy", "Volt")
).toDF("NUMBER", "MAKE", "MODEL")`
`scala> spc.bulkImportHFile(carsdfi, "abc.cars", collection.mutable.Map("bulkImportDirectory" -> "/tmp/bi"))`
`res0: Long = 4`
> DB-11789 NSDS Bulk Import to Return Count of Imported Rows (3.1)

- splice_spark/src/main/spark2.2/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark2.3/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark2.4/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark3.0/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceIT.scala
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/SplicemachineContextIT.scala
- splice_spark2/src/main/scala/com/splicemachine/spark2/splicemachine/SplicemachineContext.scala
- splice_spark2/src/test/scala/com/splicemachine/spark2/splicemachine/SplicemachineContextIT.scala
NSDS bulk import function will now return the count of imported records.  It was previously not returning anything.
It now returns the count returned from the JDBC Statement executeUpdate() call.
In the DB, set up a table:
`splice> create table abc.cars(number int primary key,
make  varchar(20),
model varchar(20) );`
In Spark, bulk import a dataframe and check that bulk import returns the number of records imported.
`scala> val carsdfi = Seq(
(1, "Toyota", "Camry"),
(2, "Honda", "Accord"),
(3, "Subaru", "Impreza"),
(4, "Chevy", "Volt")
).toDF("NUMBER", "MAKE", "MODEL")`
`scala> spc.bulkImportHFile(carsdfi, "abc.cars", collection.mutable.Map("bulkImportDirectory" -> "/tmp/bi"))`
`res0: Long = 4`
> DB-11789 NSDS Bulk Import to Return Count of Imported Rows (3.0)

- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- hbase_sql/src/main/java/com/splicemachine/stream/RemoteQueryClientImpl.java
So far, number of OLAP parallel partitions can be changed with a session or query property olapParallelPartitions. This also adds a global database property `'splice.olapParallelPartitions'` that can be set by e.g.
```
SYSCS_UTIL.SYSCS_SET_GLOBAL_DATABASE_PROPERTY('splice.olapParallelPartitions', '16')
```
Priority of settings is
- session setting (highest prio): `olapParallelPartitions` session parameter
- global setting                : `SYSCS_SET_GLOBAL_DATABASE_PROPERTY('splice.parallelPartitions', '20');`
- default setting (lowest prio) : DEFAULT_PARALLEL_PARTITIONS = 4;
currently only implicitly by setting the property, then running a olap query like
```
SELECT * FROM A --splice-properties useOlap=true
;
```
> DB-11793 global 'splice.olapParallelPartitions' property

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NotEqualsSelectivity.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SelectivityIT.java
This change boost the performance of query with hash `SGgiYFr5`.
Three issues:
* Index XPFVEZUASERLZP is not picked up probably because high number of estimated output rows. Currently working on this.
* Join between VE and VZ is not NLJ probably due to the same issue above.
* We don’t have bitmap IXAND.
To improve the first two points, this change improves the following:
* A not equal predicate and a range predicate are combined if the not equal value equals to an inclusive boundary value of the range predicate.
`SGgiYFr5` should have plan on OLTP after this change. It's execution time should below 30 seconds on a k8s cluster. Before this change, the plan is on OLAP and takes at least 350 seconds.
> DB-11687 Improve NE+Range estimates

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeSystemProcedures.java
https://splicemachine.atlassian.net/browse/DB-11806
In UpgradeSystemProcedures.restartOlapServer() append the port to the zookeeper address only if it's not there.
UpgradeSystemProcedures.restartOlapServer() was appending the port to the zookeeper address.  This was apparently needed in standalone and in on-prem envs, but the zookeeper address shown in a log from k8s has the port duplicated.  The config param `hbase.zookeeper.quorum` in k8s has the port but in the other envs it apparently doesn't.
Changed the code to check if the port is already on the end of the zookeeper quorum address before appending it.
Before the fix, calling SYSCS_UTIL.SYSCS_ROLLBACK_DATABASE_TO_TRANSACTION() in k8s gave the error:
`KeeperErrorCode = ConnectionLoss for /splice/olapServer/restart`
To test, be sure …
> DB-11806 RestartOlapServer Zookeeper Port

- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
Schema statistic by tables is calculated in parallel
DB-10592 is changing the behavior of spark execution. Schema statistic is calculated sequentially, which can be blocked if some executors not ready, see more details in jira DB-10592. It can cause the timeout in COLLECT_SCHEMA_STATISTICS.  Changed to calculate in parallel.
Execute ExportOperationIT, StatisticsAdminIT
> DB-10592 StatisticsAdmin schema statistic in parallel 

- assembly/pom.xml
Add JWT jars to common dependencies to enable deployment of SSO to either onto an on-prem or cloud deployment
JWT jars are not currently available in a cluster, but a standalone cluster which uses maven to resolve dependencies pulls down the needed jars. This PR adds the needed JWT jars in order to add the dependencies needed to get SSO running with just the parcel.
Was deployed on a cloud cluster and tested
> DB-11815 Add JWT jars to common dependencies to enable deployment

- pipelines/hbck/Jenkinsfile
- platforms/hbck/README.md
Add README.md and add build pipeline to build hbck2.
Add a small readme with how to build and some quick usage. Also built a build pipeline to deploy the hbck2 at a location that we can use. Set the version to STABLE (RELEASE and LATEST is deprecated and thus can't be deployed), so that our docker images can have a static location that can pull down the jar.
https://jenkins.build.splicemachine-dev.io/job/spliceengine-master/job/hbck/
> DB-11739 Add Hbck2 pipeline/Update Instructions

- db-engine/src/main/java/com/splicemachine/db/iapi/services/io/DataInputUtil.java
On a post-2003 build, restoring a backup from pre-2003 build failed
Build 2003 changes serialization of statistics. However, older backup still stores statistics in old serialization format. To fix this issue, bump up backup version number. For pre-2009 backup, its stats will be read using old format first. If that does not work, read using newer format. For post-2009 backup, its stats will be always stored and read using new format.
Make table/schema backup on a pre-2003 build. Table/schema and their stats should be restored successfully.
> DB-11818: fix table/schema backup stats backward compatibility

- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/main/java/com/splicemachine/backup/BackupManager.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_protocol/src/main/protobuf/Backup.proto
Backup/restore data base except user data
This is a new feature to backup/restore splice system tables.
```
describe procedure syscs_util.syscs_backup_metadata;
COLUMN_NAME    |TYPE_NAME    |ORDINAL_POSITION
directory      |VARCHAR      |1               
describe procedure syscs_util.syscs_restore_metadata;
COLUMN_NAME    |TYPE_NAME    |ORDINAL_POSITION
directory      |VARCHAR      |1
backupId       |BIGINT       |2
validate       |BOOLEAN      |3           
```
Usage of `syscs_util.syscs_backup_metadata` and `syscs_util.syscs_restore_metadata` is very similar to database backup/restore system procedures.
Run `syscs_util.syscs_backup_metadata` and check the backup. User data should not be included.
Run `syscs_util.syscs_backup_metadata` for a backup, Restart splice machine and check user …
> DB-11690: backup metadata

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/execute/ResultSetFactory.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/SpliceGenericResultSetFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperationIT.java
The too complex query can cause a java.io.UTFDataFormatException.
if DataOutputStream.writeUTF is used, the length of the parameter cannot exceed 65535. This is due to the fact, that writeUTF uses the first two bytes to code the length of the byte array and has a check for this:
```
if (utflen > 65535)
throw new UTFDataFormatException(
"encoded string too long: " + utflen + " bytes");
```
In particular, in this case, the problem is with ProjectRestrictOperation.filterPred, when the query has too many values in 'in' clause, for example. CONSTANT_Utf8_info.put cannot serialize a value to ClassFormatOutput.
Use many values for in clause in the query, like select * from [TABLE] where id in('id1','id2', .... 'idn'), that the length of the string 
```
in('id1','id2', .... 'idn')
```
is greater …
> DB-11764 TOSCA rich client test - query complexity

- db-engine/src/main/java/com/splicemachine/db/iapi/util/StringUtil.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TranslateFunctionNode.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/ClassName.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DB2VarcharCompatibilityIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
In this PR we provide a fix for queries that fail to select `VARBIT` (`VARCHAR FOR BIT DATA`) when  the database is running in `splice.db2.varchar.compatible` mode.
A previous PR brought some fixes to trailing spaces for string types, basically a flag to set comparison with or without ignoring trailing whitespaces is added to string types, this flag is used to create either a `SQLVarchar` or a `SQLVarcharDB2Compatible`.
During code generation for some operators, e.g. `substring` the flag is always set as shown here:
```
if (getCompilerContext().getVarcharDB2CompatibilityMode()) {
mb.dup();
mb.push(true);
mb.callMethod(VMOpcode.INVOKEINTERFACE, ClassName.StringDataValue,
"setIgnoreTrailingWhitespacesInVarcharComparison", "void", 1);
}
```
There is a mistake in this logic, before pushing …
> DB-11766 fix VARBIT projection in db2.varchar.compatible mode

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/Procedure.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/test/java/com/splicemachine/derby/security/PermissionIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ProcedureUnitTest.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Exec_Stored_Proc_IT.java
SYSCS_SET_GLOBAL_DATABASE_PROPERTY should be callable in functions
create a function, call SYSCS_SET_GLOBAL_DATABASE_PROPERTY.
This was wrongly fixed in DB-10968 before because of a misunderstanding of the permissions architecture.
> DB-10968 SYSCS_SET_GLOBAL_DATABASE_PROPERTY should be callable in functions

- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/ijImpl.java
- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/utilMain.java
Currently, when in hitting Ctrl+C in sqlshell, it directly terminates, without cancelling the current running query. With this fix, we don’t terminate sqlshell, but cancel the current query.
On Mac and Linux, If no query is running, Ctrl+C does nothing. You can quit with Ctrl+D.
On Windows, Ctrl+C still terminates the application if no query is running.
General, execute a long query and try to terminate with Ctrl+C. Note that before this fix, a CTRL+C would cause the sqlshell to get closed, but the query still to run (check with call `SYSCS_UTIL.SYSCS_GET_RUNNING_OPERATIONS();`).
Detailed test description with testdata in https://splicemachine.atlassian.net/browse/DB-11845 .
> DB-11845 sqlshell cancel queries with CTRL+C

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/OptimizablePredicateList.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Optimizer.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/IntersectOrExceptNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TableOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnionNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/HashableJoinIT.java
This change fixes an issue that some irrelevant equijoin predicates could make optimizer believes that a hashable join strategy (broadcast, merge sort, merge) is feasible but later before code generation, no hash key columns can actually be found for such a join.
The problem can be described using the following query:
```
select D.c1, D.c2, G.c2 
from D, G
where G.c2 = D.c2
and D.ts <= '2000-01-01'
and not (exists(select * from D_LZ, L
where D_LZ.c1 = D.c1
and L.c2 = D.c2
and L.e = 'X'));
```
Let's focus on the subquery. It has three predicates, but none of them is for the join between `D_LZ` and `L`. Also note that these predicates belong to the subquery at the very beginning. They are not pushed down from outer block. Also, note that the subquery cannot be flattened and `L` can only be …
> DB-11738 Fix feasible() of HashableJoinStrategy

- db-engine/src/main/java/com/splicemachine/db/iapi/stats/TableStatisticsImpl.java
- db-engine/src/test/java/com/splicemachine/db/iapi/stats/TableStatisticsImplTest.java
In this PR we fix wrong selectivity estimation of prepared predicates when we have empty stats.
This bug was observed when comparing the generated plans of a statement in two flavors: prepared and non-prepared. In the prepared version, the estimates where completely off and a table scan was chosen in the RHS of NLJ instead of a much more efficient index lookup.
I thought at the beginning this is related to falling back to default selectivity estimates of prepared predicates, but even with default estimates, we should not end up with infinity selectivity / cost for any predicate / operation, which we can see clearly in the plan (the weird looking question marks in the plan, which is basically a U+FFFD REPLACEMENT CHARACTER for the non-displayable infinity character U+221E INFINITY (∞) as …
> DB-11839 fix selectivity estimate in case of empty stats

- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/hbase/HBaseConglomerate.java
Redirect `HBaseConglomerate.readExternal` to `readExternalNew` once the engine has started to skip slow `getCatalogVersion`
3.2.0.2003 introduced a new serialization mechanism for HBaseConglomerate. On a version >= 2003, we will need the old serialization logic to upgrade, but never after that. Since `SIDriver.engineStarted` is set to true only after upgrade has completed, we don't need to check catalogVersion once `SIDriver.engineStarted == true`.
```
git checkout 3.2.0.2000
./start-splice-cluster -k
mvn -T 4 -B clean install -Pcore,cdh6.3.0 -DskipTests
./start-splice-cluster -b -p cdh6.3.0
git checkout DB-11857
./start-splice-cluster -l -p cdh6.3.0
```
> DB-11857 Short-circuit HBaseConglomerate.readExternal once the engine has started

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MergeSortJoinOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DB2VarcharCompatibilityIT.java
Run broadcast joins and merge sort joins natively in spark when using db2 varchar compatibility mode
Up until now, broadcast joins and merge sort joins could not run natively in spark when `'splice.db2.varchar.compatible'` was set to true.
With that parameter enabled, `'a'` and `'a      '` should be evaluated to be the same varchar in a join.
If a join key is a varchar, we now rtrim it before evaluating the join predicate.
```
create table A (a1 varchar(20), a2 varchar(20));
create table B (b1 varchar(20), b2 varchar(20));
insert into A values ('1  ', '2          '), ('1', '-2  ');
insert into B values ('1    ', '3    '), ('1 ', '-3 ');
call syscs_util.INVALIDATE_GLOBAL_DICTIONARY_CACHE();
call syscs_util.syscs_set_global_database_property('splice.db2.varchar.compatible', 'true');
> …
```
> DB-11796 Use native Spark broadcast/merge sort joins when DB2 compatibility mode is enabled

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/IndexPrefixIterationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/JoinOrderJumpModeIT.java
This change fixes performance regression of the query reported in DB-11622.
Before this change, we have two issues in cost estimation:
1. Cost accumulation is generally done as per parallel task except for the first table access, from which total cost is accumulated.
2. NLJ cost function always multiply outer rows by inner total cost. Essentially, this means we believe inner table access can be perfectly parallelized in case of broadcast join, sort merge join, and merge join, but not NLJ and cross join. When inner table access cost is high and number of parallelism is also high, this difference makes NLJ lose immediately.
In this change, 1 is fixed by accumulating per task cost for the first table access. 2 is improved by making NLJ uses inner table per task cost so that its cost is …
> DB-11622 Fix cost accumulation and NLJ cost function

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/AccessPath.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/AccessPathImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- hbase_sql/src/test/java/com/splicemachine/hbase/CostEstimationIT.java
This change provides a temporary fix for DB-11860.
Main reason is again that statistics are collected when the table is empty. Long-term solution would be again automatically updated statistics.
Check `testPreferIndexOnSpecialColumns` for details.
> DB-11860 Prefer indexes with more selective predicates

- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/btree/IndexConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/hbase/HBaseConglomerate.java
Redirect `IndexConglomerate.readExternal` to `readExternalNew` once the engine has started to skip slow `getCatalogVersion`
3.2.0.2003 introduced a new serialization mechanism for IndexConglomerate. On a version >= 2003, we will need the old serialization logic to upgrade, but never after that. Since `SIDriver.engineStarted` is set to true only after upgrade has completed, we don't need to check catalogVersion once `SIDriver.engineStarted == true`.
This is a clone of [DB-11857](https://github.com/splicemachine/spliceengine/pull/5387) for IndexConglomerate
```
git checkout 3.2.0.2000
./start-splice-cluster -k
mvn -T 4 -B clean install -Pcore,cdh6.3.0 -DskipTests
./start-splice-cluster -b -p cdh6.3.0
git checkout DB-11857
./start-splice-cluster -l -p cdh6.3.0
```
> DB-11890 Short-circuit IndexConglomerate.readExternal once the engine has started

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CreateIndexNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/actions/index/IndexIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DefaultIndexIT.java
This change improves the logic of setting `exclude null/default keys` flags of an index.
From splice SQL reference:
> Excluding NULL and Default Values
>
> You can include the optional EXCLUDE clause to specify that you want to exclude from the index either default values or NULL values for the column. This can be desirable for a large table in which the index column is largely populated with the same (default or NULL) value.
> Note: For an index with multiple columns, only rows with NULL or default values on the leading index column are excluded.
For the NPE issue described in Jira, root cause is that an index with `exclude default keys` clause is defined on a set of columns but the leading column has no default value defined. When optimizer checks if this index is eligible for a certain …
> DB-11224 Don't set exclude null/default flags of an index when they have no effect

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnDefinitionNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/ModifyColumnConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/AddColumnWithDefaultIT.java
In this PR we fix two issues:
* DB-11895 NPE when adding a column with a foreign key reference.
* DB-11899 Incorrectly allowing `null` default value even if the newly added column is not-nullable.
The first issue was related to having a code path that attempts to add a foreign key when a new column is added without initializing the FK graph properly before starting the FK validation process. The code path was not tested correctly, now it is fixed and new ITs were added to cover it.
The second issue was related to a missing check when validating a default value for a newly added column, a check was added and an IT.
For DB-11895:
```
create table p(c1 int primary key);
create table c(c1 int);
insert into p values 1,2,3;
insert into c values 100;
alter table c add column c2 int references …
```
> DB-11895 DB-11899 fixes for add column behavior

- hbase_sql/src/test/java/com/splicemachine/hbase/CheckTableIT.java
Previous DB-11224 PR causes two tests in `CheckTableIT` to fail. They were uncaught because the ITs are disabled for mem platform and longer than two minutes.
n/a
n/a
> DB-11224 Fix failing ITs in CheckTableIT

- splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJAntiJoinFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJInnerJoinFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJOneRowInnerJoinFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJOuterJoinFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJoinFunction.java
Avoid expensive clone operation for NestedLoopJoins that have only 1 row on the left side
Currently we clone the operationContext (expensive operation) in order to execute nestedLoopJoin lookups concurrently into the right table. When we only have 1 row on the left table we can avoid the expensive clone and use the operationContext directly as in any other normal operation.
> DB-11892 Avoid ctx clone on NLJ when there's only 1 row

- db-engine/src/main/java/com/splicemachine/db/iapi/stats/FakeColumnStatisticsImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/JoinOrderJumpModeIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/StatisticsProceduresIT.java
FakeColumnStats were wrong in some cases, specifically for selectivity of columns with a default value
- Create a table with a column with default value
- Set fake column statistics with some rowsPerValue
- Prepare statement with equality predicate on that column, the estimated scanned rows should be rowsPerValue
> DB-11907 Make FakeColumnStats selectivity should return rowsPerValue

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
SPLICE-2399's IndexPrefixIteratorMode does not kick in for large tables.
The check that the special IndexPrefixIteratorMode index access is not iterating through an excessive number of leading column values was checking the rows per value statistic instead of number of values.  Fix the code to use the correct method call.  Also, there is another check which limits the first column number of values to 20000 on OLTP.  For large tables, this may be too limiting since we often hint OLTP mode for faster scans.  This limit is increased to 200000.
Create a table with a 2-column PK and more than 20000 rows per value in the first PK column but less than 200000 values, with stats collected. EXPLAIN SELECT * FROM table WHERE 2nd_PK_Column = val;  should indicate IndexPrefixIteratorMode in the …
> DB-11928 Fix maxPrefixIteratorValues check of SPLICE-2399

- splice_si_api/src/main/java/com/splicemachine/si/impl/txn/WritableTxn.java
- splice_si_api/src/test/java/com/splicemachine/si/TransactionInteractionTest.java
When committing transactions we can update the global commit cache
When committing transactions we can update the global commit cache
This is specially useful for use cases where there's a single connection doing a lot of work, and most of the work happens locally on that RS
> DB-11904 Cache transactions on commit

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/AggregateNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CountAggregateDefinition.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/SPSPropertyCountReturnType.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/SPSPropertyRegistry.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/GlobalDatabasePropertyIT.java
This introduces a new parameter `splice.bind.countReturnType` to toggle the return type of COUNT from big int to int.
```
select typeof(count(*)) from sysibm.sysdummy1;
1
----------------------------------------
BIGINT
call syscs_util.syscs_set_global_database_property('splice.bind.countReturnType', 'integer');
select typeof(count(*)) from sysibm.sysdummy1;
1
----------------------------------------
INTEGER
call syscs_util.syscs_set_global_database_property('splice.bind.countReturnType', 'bigint');
select typeof(count(*)) from sysibm.sysdummy1;
1
----------------------------------------
BIGINT
> DB-11533 Introduce parameter to change return type of count

- hbase_sql/src/test/java/com/splicemachine/hbase/SpliceRegionAdminIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/SpliceRegionAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ProcedureUnitTest.java
Implemented system procedures to move index to the same region as base table. Currently only support table with a single region.
Please checkout DB-11926 for system procedure interface and use cases.
> DB-11926: add system procedures to move region

- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/ijCommands.java
- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/ijImpl.java
- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/utilMain.java
- hbase_sql/src/test/java/com/splicemachine/derby/utils/SqlshellIT.java
CTRL+C now exits sqlshell if no query is running.
open sqlshell, enter some characters, hit Ctrl+C. sqlshell should terminate.
> DB-11897 CTRL+C exit sqlshell if no query running

- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/StoreCostController.java
- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/TransactionController.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLChar.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/AbstractSelectivityHolder.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListSelectivity.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/StoreCostControllerImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/SpliceTransactionManager.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DB2VarcharCompatibilityIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
This PR fixes two selectivity issues with db2 compatible SQLVarchar
1. DB2 strings lookup in sketches:
To estimate selectivity, we lookup the key from a predicate in statistics sketches. If that key is Varchar and DB2 strings compatibility mode is enabled, we should not search for that precise key in the sketches, but for a range of equivalent keys. Luckily, we already support a startKey and a stopKey when probing sketches, so instead of passing the same value twice, we need to pass a trimmed version of the key as a startKey, and a padded version of the key as a stopKey
2. Multi-column indexes cannot be used beyond a DB2 varchar column with startKey/stopKey
Say we have an index on three columns (VARCHAR, INT, INT)
If DB2 strings are not used, the first three predicates of that index can …
> DB-11941 Fix optimizer selectivity issues with db2varchars

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ExportNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLGrammarImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportParams.java
- splice_machine/src/main/java/com/splicemachine/derby/procedures/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/csv/AbstractFileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/ImportNullityIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportBuilder.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportOperationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
- splice_machine/src/test/java/com/splicemachine/test_tools/TableCreator.java
This changes does
- DB-11784: Add feature that IMPORT_DATA can now read from parquet
- DB-11539: fix EXPORT so that EXPORT uses DEFAULT_TIMESTAMP_FORMAT if timestamp_format is not set
- DB-11784: We can already EXPORT to parquet, now we can also IMPORT. Since we can import from a directory, we will use PARQUET import once we have one `.parquet` file in the directory. If we have .orc, we use orc. Otherwise, we use .csv .
- DB-11539: Before this, a change in global database property `splice.function.timestampFormat` would change the behavior of EXPORT when not timestamp_format was given and the "default" value should be taken.  Since only the EXPORT would use that default value, but not IMPORT, we had a mismatch between these two, so we aligned now both so that default EXPORT can be read by …
> DB-11539/DB-11784 EXPORT fixes

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryArithmeticOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceDateFunctionsIT.java
Fix regression introduced by DB-11668
DB-11668 moved SpliceDateFunctions to another package without changing the reference in BinaryArithmeticOperatorNode. This PR fixes that.
select timestamp(trim('2016-08-05-07.12.59.000000')) + current timezone from sysibm.sysdummy1;
does not fail anymore
> DB-11973 Fix bindTimezoneOperation's static call to SpliceDateFunctions

- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
ddl notifications are partitioned during COLLECT_SCHEMA_STATISTICS. Previously, a large list of table descriptor ids was sent in one call. 
When COLLECT_SCHEMA_STATISTICS analyzes a big schema with many tables, it could cause a DDL coordination timeout. The problem happens when the massage with ddlChangeType: ALTER_STATS has many table descriptor ids. To avoid this issue, the new method ddlNotificationInPartitions splits the list of table descriptors into smaller partitions with the size given in partitionSize.
Create a schema with big amount of tables, some thousands, and call  COLLECT_SCHEMA_STATISTICS. It's also possible to decrease the environment variable splice.ddl.maxWaitSeconds to have a higher probability to get a timeout.
> DB-10494 DDL coordination timed out when analyze schema with many tables (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
ddl notifications are partitioned during COLLECT_SCHEMA_STATISTICS. Previously, a large list of table descriptor ids was sent in one call. 
When COLLECT_SCHEMA_STATISTICS analyzes a big schema with many tables, it could cause a DDL coordination timeout. The problem happens when the massage with ddlChangeType: ALTER_STATS has many table descriptor ids. To avoid this issue, the new method ddlNotificationInPartitions splits the list of table descriptors into smaller partitions with the size given in partitionSize.
Create a schema with big amount of tables, some thousands, and call  COLLECT_SCHEMA_STATISTICS. It's also possible to decrease the environment variable splice.ddl.maxWaitSeconds to have a higher probability to get a timeout.
> DB-10494 DDL coordination timed out when analyze schema with many tables (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/ast/QueryRewriteVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/AndNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/MethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateSimplificationVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumnList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SetOperatorNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/QueryRewriteIT.java
- splice_machine/src/test/test-data/subquery/QueryRewriteIT.sql
Move tables with unreferenced columns from the FROM clause into EXISTS WHERE clause conditions.
This feature does a query rewrite of SetOp queries of the form:
> select t1.* from t1, t2 union
> select t3.* from t3;
to:
> select t1.* from t1 where exists (select 1 from t2) union
> select t3.* from t3;
This eliminates a potentially costly join if t2 is large.  This works because duplicates are removed from the final result set and if no new values are added from the table due to no referenced columns, it does not impact the values in the final set.
For SetOp queries of the form:
> select 1,2,3 from t1 union
> select t2.a, t2.b, t2,c from t2;
They are rewritten as:
> select TOP 1 1,2,3 from t1 union
> select t2.a, t2.b, t2,c from t2;
This reduces the rows read from t1.
The presence of …
> DB-11858 Query rewrite for UNION queries

- hbase_sql/src/main/java/com/splicemachine/ddl/ZooKeeperDDLWatchChecker.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/AsynchronousDDLController.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchRefresher.java
The log improvements are done to have better understanding of issues, described in DB-11505.
Improve log statements in classes, which are responsible for ddl synchronisation between nodes, adding information about change id, when problem occuers.
For example, currently when max waiting time is reached, the log statement has no information for which change id it happens: 
2021-02-18 18:19:01,636 ERROR [DRDAConnThread_418] ddl.AsynchronousDDLController: Maximum wait for all servers exceeded. Missing response from [pjx-bml-hdpw032.clearsense.local,16020,1613665268935]
new format will be
Maximum wait for change with id spliceconnection0000000000 for all servers exceeded. Missing response from spliceconnection0000000000
Change id is added also to other log statements.
The log statements will …
> DB-11985 Improve ZK DDL Refresh logging

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/BaseDataDictionary.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/FailuresSparkIT.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/RollbackTxnFilter.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/SIFilterPacked.java
- hbase_storage/src/main/java/com/splicemachine/storage/RangedClientPartition.java
- hbase_storage/src/main/java/com/splicemachine/storage/RegionPartition.java
- hbase_storage/src/main/java/com/splicemachine/storage/SkeletonHBaseClientPartition.java
- hbase_storage/src/test/java/com/splicemachine/si/impl/SynchronousReadResolverTest.java
- mem_storage/src/main/java/com/splicemachine/si/impl/TxnPartition.java
- mem_storage/src/main/java/com/splicemachine/storage/MPartition.java
- mem_storage/src/test/java/com/splicemachine/si/MemSITestEnv.java
- splice_access_api/src/main/java/com/splicemachine/storage/Partition.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyChildInterceptWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/actions/OnDeleteAbstractAction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/WriteWriteRollbackIT.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnFilter.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/TxnRegion.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/server/ConflictRollForward.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactor.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/txn/SITransactionReadController.java
- splice_si_api/src/test/java/com/splicemachine/si/SITransactorTest.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/SimpleTxnFilterTest.java
We only check WW-conflict with latest version. In case 
We only check WW-conflict with latest version. In case latest version is rolled back, WW-conflict check can miss a conflict or constraint violation with previous version. 
Here is an example.
Session 0                                               Session 1
autocommit off;                                    autocommit off;
create table a(i int primary key, j int);   
insert into a values (1,1);                        
commit;                                                   
update a set j= j+ 1;                                
(sleep 20s)                                              
rollback;                                                 commit;
insert into a values (1,5);
commit;
For row (1,5), splice checks WW-conflict with …
> DB-11534: Filter out rolled back txn during WW-conflict detection

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/ScanController.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/TabInfoImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/sequence/SpliceSequence.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceScan.java
Identity column value reset to sequence start value after upgrading to a build later than 2003.
Splice stores identity column value as a sequence in SPLICE_SEQUENCES table. The row address of the sequence is the same as the address of the column descriptor stored in sys.syscolumns. DB-10410 rewrites sys.syscolumns table, which changes row address of all column descriptors. However, it does not update the address in SPLICE_SEQUENCES. If a build upgrades to 2003 or later, the relationship between sys.syscolumns and SPLICE_SEQUENCES table is lost, and all identity column's next value are reset to the sequence start value.
To test, create a table with identity column and insert rows into it. Upgrade to a build later than 2003. Insert a couple of rows and inspect identity column value. The …
> DB-11856: upgrade SPLICE_SEQUENCE table

- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
Fixed DataDictionaryCache.statementCache to do atomic "computeIfAbsent".
Multiple connections compiling identical statements would check DataDictionaryCache.statementCache to see if a prepared statement is already available, create new prepared statements if not and  add them to the cache. Only one wins, others would continue with compiling the statement to eventually throw away the result.
Also fixed unnecessarily complicated synchronization around prepared statements that reference session schema.
Run TPC-C, verify if there are multiple compilations of identical SELECT/UPDATE/DELETE statements in the same region server.
> DB-12033 Multiple compilations of a prepared statement due to poor cache synchronization

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLGrammarImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UpdateOperationIT.java
This change improves the error message when an invalid update syntax `set (a,b)=(c,d)` is used.
We currently have three update statement syntax:
1. `update T set a = c, b = d where ...`
2. `update T set (a, b) = (select c, d from ...)`
3. `update T set a = c, b = d from ... where ...`
When the left-hand side of a set clause is surrounded with a pair of parenthesis, right-hand side must be a subquery. This is syntax 2. Before syntax 3 is implemented, it's splice's way of allowing multi-column update from a subquery.
Currently, we don't generally have tuple assignment except for a few cases. In update statement, `set (a, b) = (c, d)` is equivalent to `set a = c, b = d`. For this reason, there is no real need at the moment to implement tuple assignment in update.
A proper error message is …
> DB-11969 Throw properly for invalid update syntax set(a,b)=(c,d).

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLGrammarImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UpdateOperationIT.java
Please see https://github.com/splicemachine/spliceengine/pull/5459.
> DB-11969 Throw properly for invalid update syntax set(a,b)=(c,d). (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLGrammarImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UpdateOperationIT.java
Please see https://github.com/splicemachine/spliceengine/pull/5459.
> DB-11969 Throw properly for invalid update syntax set(a,b)=(c,d). (3.0)

- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
BackupEndpointObserver.postFlush crashes region server if the namespace of a table is null
From hbase shell, create an hbase table with default namespace, insert data to it and flush the table
create 'guru99', {NAME=>'Edu', VERSIONS=>213423443}
put 'guru99', 'r1', 'Edu:c1', 'value', 10
put 'guru99', 'r1', 'Edu:c1', 'value', 15
put 'guru99', 'r1', 'Edu:c1', 'value', 30
flush 'guru99'
> DB-12075: null check for namespace

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/AbstractSparkExpressionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BaseJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorToString.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SparkColumnReference.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SparkExpressionNode.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/costing/V1NestedLoopJoinCostEstimationModel.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SparkExplainIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/CrossJoinIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/FullOuterJoinIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceDateFunctionsIT.java
Enable native spark broadcast join with non-equijoin predicates.
[SPLICE-2362](https://splice.atlassian.net/browse/SPLICE-2362) added support for general expressions in native spark join predicates.  It was enabled for combinations of equijoin plus non-equijoin predicates, but not non-equijoin predicates by themselves.  This Jira enables the latter by removing the check in BroadcastJoinOperation which checks that we have at least one left hash key before choosing native spark join.
A test case such as the following should indicate BroadcastNestedLoopJoin in the sparkexplain output:
> create table t1(a1 int not null, b1 int, c1 int, primary key(c1));
> create table t2 (a2 int not null, b2 int, c2 int, primary key(c2));
> sparkexplain select * from t1 a, t2 b --splice-properties …
> DB-11865 Enable native spark broadcast join with non-equijoin predicates

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/IndexPrefixIterationIT.java
- splice_machine/src/test/test-data/subquery/IndexPrefixIterationTestTables.sql
This change fixes a NPE in code generation related to index prefix iteration mode.
This is a bug happens in generating code in index prefix iteration mode when an equality predicate and a ranged predicate are both used as scan keys.
In code generation of a `FromBaseTable`, `getScanArguments()` is called with an assumption that the predicates pushed down to this table must be sorted in index column order (for PK or index conglomerates). If this is not the case, code generation is simply wrong.
However, `getScanArguments()` eventually calls `PredicateList.generateProbeQualifiers()`. This call sorts predicates according to a heuristic on selectivity:
```
if(numberOfQualifiers>0){
orderQualifiers();
}
```
This step is fine previously because when we are here, the logic relying on the order of …
> DB-12064 Fix NPE in code generation for index prefix iteration mode

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BooleanConstantNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateSimplificationVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicateSimplificationIT.java
Evaluate in-list condition at compile time if possible
When the in-list condition is constant, we should evaluate it at compile time to avoid doing a table scan for a predicate that we know to be false anyway
```
splice> explain select * from a where 'abc' in ('abcd', 'def', 'ghi');
Plan
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Cursor(n=3,rows=1,updateMode=READ_ONLY (1),engine=OLTP (default))
->  ScrollInsensitive(n=3,totalCost=0,outputRows=1,outputHeapSize=0 B,partitions=1,parallelTasks=1)
->  ProjectRestrict(n=2,totalCost=0,outputRows=1,outputHeapSize=0 …
```
> DB-11960 Check constant in-list condition in predicates (3.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DMLStatementNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNodeList.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- pom.xml
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/NullPredicateIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicateSimplificationIT.java
Fix issue with null constant restriction during execution
We try to remove nulls during constant folding & predicate simplification phase. However, if a folding or a simplification is missing, we would end up with a null constant restriction, which was evaluated to true during the execution. 
This PR fixes the execution problem, and introduces tests that enable/disable constant folding and predicate simplification, so that they do not hide null predicate problems in the future.
We also introduce a new parameter: `splice.database.disableConstantFolding` that echoes `derby.database.disablePredicateSimplification`. Both those parameters are database level parameters for now, but they we should introduce them as session parameters as well.
We bumped junit's version to 4.13.1 in in order to …
> DB-12077 Evaluate null constant restriction to false during execution 

- db-engine/src/main/java/com/splicemachine/db/iapi/services/property/PropertyUtil.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- hbase_sql/src/main/java/com/splicemachine/derby/impl/sql/ZkPropertyManager.java
- mem_sql/src/main/java/com/splicemachine/derby/impl/sql/DirectPropertyManager.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/PropertyManager.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/PropertyManagerService.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/SpliceService.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/PropertyConglomerate.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/GlobalDatabasePropertyIT.java
`selectivityEstimationIncludingSkewedDefault` was defined as a service property, which cannot be set globally by `syscs_set_global_database_property`.
`selectivityEstimationIncludingSkewedDefault` was defined as a service property, which cannot be set globally by `syscs_set_global_database_property`. To fix it, remove it from service properties, and fix the code to retrieve it from service property.
Run 
`call syscs_util.syscs_set_global_database_property('derby.database.selectivityEstimationIncludingSkewedDefault', 'true');`
to set it to true. Verify it is set for all servers
```
call syscs_util.syscs_get_global_database_property('derby.database.selectivityEstimationIncludingSkewedDefault');
HOST_NAME                     |PROPERTY_VALUE
----------------------------------------------- …
```
> DB-11966: set selectivityEstimationIncludingSkewedDefault for all servers

- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/NullPredicateIT.java
The cherry-pick from main of DB-12077 introduced new tests for NullPredicateIT. One of those tests relied on the `DAYS` function that does not exist in 3.1, so we should remove that from the test.
> DB-12077 Remove test with DAYS as DAYS does not exist in 3.1

- splice_machine/src/main/java/com/splicemachine/derby/utils/Vacuum.java
Flush dropped tables which can't be removed during VACUUM.
Currently, any old client connections which have an active transaction can prevent table conglomerates from getting removed upon VACUUM because dropped tables must be older than the oldest active transaction.  This issue can also occur due to connections which are left open in ITs.  The long-term solution would be to implement a more robust method of identifying tables which can't be dropped, for example by associating each active transaction with tables which it may write to.  
For now, this PR does an HBase flush of any dropped tables which can't be removed during VACUUM, so the memory used up by those tables in memstore can be recovered.
Run the full suite of ITs and track memory of the main master+regionserver task with a …
> DB-12111 Flush dropped tables which can't be removed during VACUUM

- splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Referencing_Clause_IT.java
Back out part of DB-11580 which may be causing IT failures on Jenkins colo servers.
> DB-12108 Back out the increase of default value of splice.controlExecution.rowsLimit

- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/AvgAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/CountAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/DecimalBufferedSumAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/DoubleBufferedSumAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/LongBufferedSumAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/MaxMinAggregator.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/GroupedAggregateOperationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UnionOperationIT.java
`MaxMinAggregator.toProtobufBuilder` used to call `value.toProtobuf()` without checking whether `value` is null or not. 
This PR makes `MaxMinAggregator.toProbufBuilder` behave like `SumAggregator.toProtobufBuilder` and checks for `value != null`
```
drop table t0;
drop table t2;
CREATE TABLE t0(c0 boolean , c1 TIMESTAMP);
CREATE TABLE t2(c0 TIMESTAMP not null);
INSERT INTO T0(C0) VALUES (FALSE);
INSERT INTO T0(C0, C1) VALUES (TRUE, '1970-01-13 04:08:02'), (TRUE, '1969-12-12 03:20:09');
INSERT INTO T0(C1) VALUES ('1969-12-12 03:20:09');
INSERT INTO T0(C1) VALUES ('1970-01-13 08:53:47');
SELECT MAX(agg0) FROM (SELECT MAX(T2.C0)  as agg0 FROM T0 LEFT OUTER JOIN T2 ON ((T0.C1)!=(T2.C0)) WHERE T0.C0 UNION ALL SELECT MAX(T2.C0)  as agg0 FROM T0 LEFT OUTER JOIN T2 ON ((T0.C1)!=(T2.C0)) WHERE …
```
> DB-12106 Fix NPE in MaxMinAggregator 

- hbase_sql/src/main/java/com/splicemachine/stream/RemoteQueryClientImpl.java
- hbase_sql/src/main/java/com/splicemachine/stream/StreamListener.java
- mem_sql/src/main/java/com/splicemachine/derby/impl/sql/ControlOnlyDataSetProcessorFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/RemoteQueryClient.java
This change fixes an exception propagation issue that causes test `ProjectRestrictSparkExpressionIT.testBugs` to be sporadic.
Submitting a job to OLAP is asynchronous in our system. On the very top level, this is done in `stmt.execute()` call in `DRDAConnThread.java`, around line 947. When submitting an OLAP job, we also register an handler in case the job's status is changed. This happens at `RemoteQueryClientImpl.java`, around line 132.
After submitting the OLAP job, execution in DRDA thread continues. Eventually, it blocks inside `writeQRYDTA(stmt)` (`DRDAConnThread.java`, around line 986). At this point, we need to block and wait because we are about to read the result set through the iterator. This happens at `getNextRowCore()` in `SpliceBaseOperation.java`.
When we are blocking at …
> DB-10980 Wait for real exception when an OLAP job fails

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/IndexRowGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RelationalOperator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryComparisonOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/HashableJoinIT.java
This change prevents predicates that cannot be used to limit a table scan from being pushed down to base table wrongly and used a scan qualifier.
Before this fix, `isQualifier()` (`RelationalOperator` interface method) implementations simply checks if the column reference operand of this relational operator refers to a column of `optTable`. Depending on the type of relational operator, there might be other checks. But this is a necessary part of all implementations.
However, this check is not sufficient in case we want to push this predicate down to scan. For an index conglomerate, the column reference must refer to one of the index columns, too. This check is currently missing.
Note that `isQualifier()` is used in two cases, which have slightly different semantics:
1. check if a …
> DB-12085 Fix isQualifier() for index conglomerates

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/OptimizablePredicate.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Optimizer.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FullOuterJoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HalfOuterJoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/IntersectOrExceptNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TableOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnionNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/OuterJoinIT.java
In this PR the sort merge join strategy is restricted from handling left and full outer joins containing a non-flattened correlated sub-query in the join condition for OLAP.
To understand the root cause of this issue, we should have a look at the generated code logic and the actual execution model of sort merge join in Spark.
The generated code for evaluating a non-flattened correlated subquery constructs a `ScalarAggregateOperation` which performs a `ScalarAggregateFlatMapFunction` on `TableScannerIterator`, the table scanner itself defines a set of row qualifiers that filters in the rows the satisfy the correlation. For example, if the query is:
```
SELECT * FROM t1 ALPHA LEFT OUTER JOIN 
t2 BETA --splice-properties useSpark=True, joinStrategy=sortmerge
ON ALPHA.b=BETA.b AND BETA.a = …
```
> DB-11523 sort merge join infeasible for correlated subq. join condition (redux + fix)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorToString.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicateWithSpecialCharactersIT.java
When sending predicates to spark, we need to escape ' and \ properly. Predicates such as `World's` would cause a ParserException on spark's side.
```
set session_property useOlap=true;
drop schema foo cascade;
create schema foo;
set schema foo;
call SYSCS_UTIL.SYSCS_EMPTY_GLOBAL_STATEMENT_CACHE();
CREATE TABLE ITEM_CODES ( ITEMTEXT VARCHAR (50) NOT NULL);
CREATE VIEW VERBOSE_INV AS SELECT * FROM item_codes UNION SELECT * FROM item_codes;
INSERT INTO ITEM_CODES VALUES ('a''b');
INSERT INTO ITEM_CODES VALUES ('a\b');
INSERT INTO ITEM_CODES VALUES ('a"b');
SELECT COUNT(*) FROM VERBOSE_INV WHERE ITEMTEXT = 'a''b';
SELECT COUNT(*) FROM VERBOSE_INV WHERE ITEMTEXT = 'a\b';
SELECT COUNT(*) FROM VERBOSE_INV WHERE ITEMTEXT = 'a"b';
```
All three select should return 1
> DB-12102 Properly escape ' and \ when sending a query to spark 

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/costing/v2/V2SelectivityEstimator.java
- splice_machine/src/test/java/com/splicemachine/benchmark/JoinSelectivityBenchmark.java
The PR fixes the join selectivity and gives a much better estimate of join cardinality.
Before this PR, the inner join selectivity is not exactly correct, it is given in the following formula:
((1 - NullSelectivity(L))*(1 - NullSelectivity(R)) / Min(Cardinality(L), Cardinality(R))
This could cause the join cardinality to give the wrong result, e.g. assume we have two tables `A` and `B` with join condition `A.a = B.b`. a has a cardinality of 800 with RPV=1 and `b` is a key has a cardinality of 10 also with RPV=1, both have no null values.
In this case, the join selectivity will be: 1 / Min(800, 10) = 0.1 which is incorrect, to see why, let’s calculate the join cardinality:
jc = 0.1 * 800 * 10 = 800
This is wrong, if we choose Max instead of Min we will have a much more conservative join …
> DB-12039 Calibrate join selectivity

- db-engine/src/main/java/com/splicemachine/db/iapi/types/NumberDataValue.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConcatenationOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConditionalNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConstantNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NotNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NumericConstantNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryArithmeticOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UntypedNullConstantNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ConstantFoldingIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicateSimplificationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
Support NOT, unary minus, conditional and binary relational operator constant folding
- **DB-12145** NOT: Support for constant folding added for null and non null operands
- **DB-12148** Conditional node: Support for constant folding added for null and non null operands. If the condition is constant but then or else isn't, remove the condition and return the correct underlying operand
- **DB-12146** Unary plus / minus: Support for constant folding added for nulls and non null number operand.
- **DB-12147** BinaryRelationalOperatorNode: Support added for null operands. Non null operand constant folding was already implemented.
This can be tested via an explain on a simple select: 
```
explain select * from sysibm.sysdummy1 where 1 = -(1)
```
will return a plan without a table scan because …
> DB-12051 Add support for additional constant folding

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DMLStatementNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ExecutorChoiceIT.java
This change fixes execution engine decision when RHS of a join is not a base table.
In `shouldRunSpark()`, `determineSpark()` is called under a guard that `obj instanceof FromBaseTable`. However, for the following query, join cost is not stored in any `FromBaseTable`:
```
select * from --splice-properties joinOrder=fixed
t1, (select distinct c2 from t2);
```
This is because the RHS of the join is a derived table. The join cost is stored in the `ProjectRestrictNode` on top of the `SelectNode` of the derived table. Since we check `obj instanceof FromBaseTable`, effectively join cost is not considered in deciding execution engine of this query.
The fix is to move `determineSpark()` to `FromTable` and remove the `FromBaseTable` check. Now we call `determineSpark()` on all `FromTable`s …
> DB-11095 Fix shouldRunSpark() for DT as RHS of a join

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/OptimizableList.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/OptimizerFactory.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Level2OptimizerFactoryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Level2OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerFactoryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultSetNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TableOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceLevel2OptimizerFactoryImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceLevel2OptimizerImpl.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SessionPropertyIT.java
This change adds a database property and a query hint for setting cost model.
- Database property:
```
CALL SYSCS_UTIL.SYSCS_SET_GLOBAL_DATABASE_PROPERTY('costModel', 'v2');
CALL SYSCS_UTIL.SYSCS_GET_GLOBAL_DATABASE_PROPERTY('costModel');
```
- Session property:
```
set session_property costModel='v1';
values current session_property;
```
- Query hint:
```
explain select * from --splice-properties costModel='v2'
sys.systables;
```
```
CALL SYSCS_UTIL.SYSCS_SET_GLOBAL_DATABASE_PROPERTY('costModel', 'v2');
name                |value
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PROPERTY_NAME       |costModel
NEW VALUE           |v2
PREVIOUS VALUE      |NULL
INFO …
```
> DB-12120 Database property and hint for cost model

- db-engine/src/main/java/com/splicemachine/db/catalog/types/IndexDescriptorImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/IndexExpressionBindingVisitor.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/costing/V1ScanCostEstimator.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/actions/index/IndexIT.java
This change fixes two problems:
1. An index created based on expressions using `UnaryDateTimestampOperatorNode` is not treated as an covering index even when an query refers to exactly the same expression.
2. An index on expression is not chosen based on cost if index expressions do not occur in any predicates.
For the first problem, root cause is that `bindExpression` of `UnaryDateTimestampOperatorNode` modifies the subtree in some cases. If this happens, the stored AST for index expression at index creation time is different than the AST parsed in query time. Solution is to bind `UnaryDateTimestampOperatorNode` nodes in index expression ASTs in query time, too.
Since we currently do this to `JavaToSQLValueNode` already, I refactor the code to have a new visitor doing this binding job …
> DB-12140 Fix index on expressions logic for UnaryDateTimestampOperatorNode

- db-engine/src/main/java/com/splicemachine/db/catalog/types/IndexDescriptorImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/IndexExpressionBindingVisitor.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/costing/v1/V1ScanCostEstimator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/costing/v2/V2ScanCostEstimator.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/actions/index/IndexIT.java
See https://github.com/splicemachine/spliceengine/pull/5535.
Note that the same change made to V1 cost model is applied to V2 cost model in this change, too.
> DB-12140 Fix index on expressions logic for UnaryDateTimestampOperatorNode (optimizer)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeUtils.java
Copying all conglomerates from SPLICE_CONGLOMERATE to SPLICE_CONGLOMERATE_SI is slow if there are a large amount of conglomerates.
It is slow because conglomerates are copied one at a time, each invoking an RPC. To speed up, conglomerates are batched to write to SPLICE_CONGLOMERATE_SI.
> DB-12116: batch write to SPLICE_CONGLOMERATE_SI during upgrade

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/BaseActivation.java
- hbase_storage/pom.xml
- hbase_storage/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
- hbase_storage/src/main/java/com/splicemachine/access/client/SkeletonClientSideRegionScanner.java
- hbase_storage/src/main/java/com/splicemachine/derby/hbase/KeyPrefixProbingFilter.java
- hbase_storage/src/main/java/com/splicemachine/derby/hbase/SpliceMultiRowRangeFilter.java
- hbase_storage/src/main/java/com/splicemachine/storage/HScan.java
- mem_storage/src/main/java/com/splicemachine/storage/MScan.java
- splice_access_api/src/main/java/com/splicemachine/storage/DataScan.java
- splice_encoding/src/main/java/com/splicemachine/encoding/Encoding.java
- splice_machine/src/main/java/com/splicemachine/derby/catalog/TriggerNewTransitionRows.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/costing/V1ScanCostEstimator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DerbyScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/IndexPrefixIteratorOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeDerbyScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TableScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/iapi/ScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/DerbyBytesUtil.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/Scans.java
- splice_machine/src/test/java/com/splicemachine/benchmark/IndexPrefixIterationBenchmark.java
- splice_machine/src/test/java/com/splicemachine/test/Benchmark.java
- splice_protocol/src/main/protobuf/Splice.proto
Improve performance of Index Prefix Iteration with a large number of values in the first index column.
[SPLICE-2399](https://github.com/splicemachine/spliceengine/pull/5013) Added index key lookups with no predicates on the leading index column, improving query performance.  When the number of values in that column is high, the time taken to discover the values to probe is excessive.  For example, on a table with 130K values, it takes roughly 2 minutes to collect those 130K values.  The problem is that there is no way to dynamically alter a scan from the SpliceOperation side of execution (the SpliceOperation is converted to an HBase scan and fulfilled via a connection to a Region Server).  Once the first value is found, we can't modify the start key value (search key) of the scan, or …
> DB-11930 Custom HBase Filter for Index Prefix Iteration

- hbase_sql/src/test/java/com/splicemachine/hbase/CheckTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/procedures/SpliceTableAdmin.java
System procedure syscs_util.check_table has problem with quoted schema or table name.
System procedure syscs_util.check_table has problem with quoted schema or table name. This was caused by a query that does not quote schema and table name.
Run this test case
create table "t"(i int);
insert into "t" values 1,2,3;
create index ti on "t"(i);
call syscs_util.check_table('SPLICE', null, null, 1, '/path/to/report');
> DB-12130: quote schema and table names for check_table

- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/TriggerExecutionContext.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/TriggerRowHolderImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TriggerHandler.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Referencing_Clause_IT.java
TriggerHandler does not clean up the trigger rows result sets properly for prepared statements.
TriggerHandler -> triggerActivator -> tec (TriggerExecutionContext) may accumulate ResultSets in the resultSetVector of TriggerExecutionContext because TriggerHandler.cleanup() skips calling triggerActivator.cleanup when cleanup1Done is true. The specialized cleanup logic was originally added to avoid calling cleanup code repetitively in case it's called through different code flows.  When prepared statements are used, the same TriggerHandler may be used over and over again.  cleanup1Done doesn't get reset in between uses of the TriggerHandler, so any subsequent executions of the prepared statement may skip cleanup of the ResultSet which holds the trigger rows that were …
> DB-12094 Fix TriggerHandler cleanup

- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/TriggerExecutionContext.java
- splice_machine/src/main/java/com/splicemachine/derby/catalog/TriggerNewTransitionRows.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/costing/V1NestedLoopJoinCostEstimationModel.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/TriggerRowHolderImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TriggerHandler.java
- splice_machine/src/test/java/com/splicemachine/benchmark/FeatureStoreTriggerBenchmark.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Referencing_Clause_IT.java
Improve performance of joins between NEW TABLE or OLD TABLE and a splice internal table in a statement trigger.
A join between a single-row NEW TABLE and a base table on the primary key chose broadcast join instead of nested loop join, resulting in poor throughput.  Triggers are precompiled, so we have no way of knowing how many rows will be updated/inserted/deleted in the triggering statement, so no way to cost joins accurately.  The feature store use cases may involve single row inserts/updates or batch updates of thousands of rows.  We need to handle both efficiently and hopefully also avoid trigger recompilation.  The solution in this case is to adjust the DUMMY_ROWCOUNT_ESTIMATE in TriggerNewTransitionRows from 1000 down to 1 and also scale the join cost of nested loop join by a …
> DB-12109 Favor NLJ for PK joins with the trigger VTI

- hbase_storage/src/main/java/com/splicemachine/derby/hbase/SpliceMultiRowRangeFilter.java
Fix for DB-11930 that is necessary because we cannot use `getComparisonData` and `isSearchRowInclusive` since they were introduced in hbase 2.1
> DB-11930 Fix SpliceMultiRowRangeFilter for hdp3.1.0

- hbase_storage/src/main/java/com/splicemachine/derby/hbase/SpliceMultiRowRangeFilter.java
Fix for DB-11930 that is necessary because we cannot use getComparisonData and isSearchRowInclusive since they were introduced in hbase 2.1
> DB-11930 Fix SpliceMultiRowRangeFilter for hdp3.1.0 (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/procedures/ShowCreateTableProcedure.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ShowCreateTableIT.java
In the generated DDL, constraints can be in different order. This makes ITs that expect a DDL string match to fail.
In the generated DDL, constraints can be in different order. This makes ITs that expect a DDL string match to fail. This PR orders constraints by constraint columns.
create table p1(a int, b real, primary key(a));
create table p2(c int, d real, primary key(c));
create table c(i int, j int, CONSTRAINT fk1 FOREIGN KEY (j) REFERENCES p1(a) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT fk2 FOREIGN KEY (i) REFERENCES p2(c) ON UPDATE NO ACTION ON DELETE RESTRICT) ;
Run show create table c, the constraint should appear in a deterministic order
show create table c;
CREATE TABLE "SPLICE"."C" (
"I" INTEGER
,"J" INTEGER
, CONSTRAINT FK2 FOREIGN KEY ("I") REFERENCES …
> DB-12159: generate constraints in a deterministic order

- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/GlobalDBProperties.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/GlobalDatabasePropertyIT.java
This PR refactors `costModel` database property to be part of `GlobalDBProperties` class, using its capability of having a validator. Also, an IT `testCostModel()` is added to `GlobalDatabasePropertyIT`.
No long description needed for this PR.
```
call syscs_util.syscs_set_global_database_property('costModel', 'v2');
call syscs_util.syscs_get_global_database_property('costModel');  -- should see v2 as the value
explain select * from sys.systables;  -- should see costModel=v2 in plan, no need to drop current session
call syscs_util.syscs_set_global_database_property('costModel', 'NULL');
call syscs_util.syscs_get_global_database_property('costModel');  -- should see NULL as the value
explain select * from sys.systables;  -- should see costModel=v1 in plan since v1 is the default value, no …
```
> DB-12132 Put cost model property into GlobalDBProperties, add an IT

- pipeline_api/src/main/java/com/splicemachine/pipeline/PipelineWriter.java
- splice_encoding/src/main/java/com/splicemachine/kvpair/KVPair.java
- splice_encoding/src/main/java/com/splicemachine/storage/Utils.java
- splice_encoding/src/test/java/com/splicemachine/encoding/TestType.java
- splice_encoding/src/test/java/com/splicemachine/storage/EntryEncoderTest.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/index/IndexTransformer.java
- splice_machine/src/main/java/com/splicemachine/pipeline/IndexWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyChildInterceptWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/actions/OnDeleteSetNullOrCascade.java
- splice_machine/src/test/java/com/splicemachine/foreignkeys/ForeignKeyActionIT.java
In this PR an index corruption caused by foreign key action on the child table is fixed.
Let us say we have a parent table `p` and child table `c` have a foreign key relationship with `on delete set null action`. If we delete a row from the parent the is referenced by row(s) in the child, then we generate an `UPDATE` mutation on the child table and its indices to set all referenced columns to `null`.
However, while doing so, we incorrectly set all other columns in the child indices to null as well! this is because the generated `update` mutation does not have the values of the non-fk index columns and we simply set them to `null`.
To fix this problem, a new mutation type is added `0x09` under the name `BLIND_UPDATE`. This mutation type is leveraged in situations where we don't have the …
> DB-11855 Fix index corruption caused by foreign key on delete set null action (3.0)

- pipeline_api/src/main/java/com/splicemachine/pipeline/PipelineWriter.java
- splice_encoding/src/main/java/com/splicemachine/kvpair/KVPair.java
- splice_encoding/src/main/java/com/splicemachine/storage/Utils.java
- splice_encoding/src/test/java/com/splicemachine/encoding/TestType.java
- splice_encoding/src/test/java/com/splicemachine/storage/EntryEncoderTest.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/index/IndexTransformer.java
- splice_machine/src/main/java/com/splicemachine/pipeline/IndexWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyChildInterceptWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/actions/OnDeleteSetNullOrCascade.java
- splice_machine/src/test/java/com/splicemachine/foreignkeys/ForeignKeyActionIT.java
In this PR an index corruption caused by foreign key action on the child table is fixed.
Let us say we have a parent table `p` and child table `c` have a foreign key relationship with `on delete set null action`. If we delete a row from the parent the is referenced by row(s) in the child, then we generate an `UPDATE` mutation on the child table and its indices to set all referenced columns to `null`.
However, while doing so, we incorrectly set all other columns in the child indices to null as well! this is because the generated `update` mutation does not have the values of the non-fk index columns and we simply set them to `null`.
To fix this problem, a new mutation type is added `0x09` under the name `BLIND_UPDATE`. This mutation type is leveraged in situations where we don't have the …
> DB-11855 Fix index corruption caused by foreign key on delete set null action (3.1)

- splice_machine/src/test/java/com/splicemachine/benchmark/FeatureStoreTriggerBenchmark.java
A pre-populated staging table is used in batch updates of FeatureTable or FeatureHistoryTable. How the table is generated is crucial for batch update performance.
The staging table is populated by batched inserts from multiple concurrent connections. It's important to turn autocommit off in those connections in order to avoid generating a large number of small transactions which will need to be resolved when the table is queried.
TRUNCATE does not preserve pre-split points specified at table creation time. Had to replace with DROP and re-CREATE.
ANALYZE the staging table to get better load balance for Spark tasks scanning the table. 
Run FeatureStoreTriggerBenchmark as an integration test either in standalone or cluster environment.
> DB-12032 FeatureStoreTriggerBenchmark: improve performance of batch updates 

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryListOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumnList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueTupleNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ValueTupleIT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_InList_IT.java
This change fixes two NPEs occur in queries with multi-column IN subquery predicates. Also, this change fixes join predicate generation for multi-column NOT IN subquery case to handle NULL data. Queries in this case should return correct results after this fix.
The reported NPEs happen in invalid syntax of using tuple in a query. This change fixes the following two cases:
- `select ... from ... where (a, b) in (1, 2)`
Currently, we support only multi-column IN subquery. IN tuple list is not supported. Instead of having an NPE, an syntax error exception is now thrown.
- `select (a, b) from ...`
We do not support tuple as a column type. Note that `select (a, b)` is not semantically equal to `select a, b`. The former results in a single column with tuple in it, while the latter results in …
> DB-11420 DB-10555 Fix multi-column IN subquery issues

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SQLWarningIT.java
This PR fixes a problem that `Activation.resultSet` is `null` when a `SQLChar.setWidth()` needs to set a SQL warning. 
Currently, SQL warnings in execution are propagated to client by setting the warnings in the result set in current activation. However, sometimes the result set is `null`, causing an NPE when setting a warning. DB-11089 suppresses the problem by not propagating a warning if result set is null. But the question is then whether the result set can be null and if yes, how should we propagate a warning properly.
My current understanding of the DRDA connection workflow based on debugging is the following.
Sending a select statement through a DRDA connection always contains two steps:
1. Client send a `PRPSQLSTT` code point (prepare SQL statement?) first. In this step, server …
> DB-11106 Defer executing code that could cause a warning in ProjectRestrictOperation

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ExplainNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/GroupByNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
This change fixes an issue in explain statement output that missing statistics objects may have duplicates and inconsistent names due to aliases.
The issue is mainly due to `FromBaseTable.getExposedTable()` method. It returns alias as the table name if a table has an alias.
The fix is to call `FromBaseTable.getTableDescriptor().getQualifiedName()` instead. This guarantees to use always the original table name with correct spelling.
Note that there is also a method `FromBaseTable.getOrigTableName()` which is not sufficient in this case because the `origTableName` field could have `schemaName == null` and code in `isTransitionTable()` in `CreateTriggerNode.java` relies on that...
Setup:
```
create table if not exists t1 (a int, b int, c int);
create table if not exists t2 (a int, b int, c …
```
> DB-10439 Improve no stats report from explain statement

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ParseException.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ParserImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Token.java
- findbugs-exclude-filter.xml
- hbase_sql/src/test/java/com/splicemachine/derby/utils/SqlshellIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropTableIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropViewIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TruncateFunctionIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
improve error messages with more detailed description what's wrong with the SQL
SQL with errors:
```
CREATE TABLE MY_TABLE (
L_ORDERKEY BIGINT NOT NULL,
L_PARTKEY INTEGER NOT DECIMAL,
L_SUPPKEY INTEGER NOT NULL,
L_LINENUMBER INTEGER NOT NULL,
L_QUANTITY DECIMAL(15,2),
L_EXTENDEDPRICE DECIMAL(15,2),
L_DISCOUNT DECIMAL(15,2)
);
```
Error Message before
```
ERROR 42X01: Syntax error: Encountered "DECIMAL" at line 3, column 23.
```
New Error Message
```
ERROR 42X01: Syntax error: Encountered "DECIMAL" at line 3, column 23.
Was expecting:
    "null" ...
    
1: CREATE TABLE MY_TABLE (
2: L_ORDERKEY BIGINT NOT NULL,
3: L_PARTKEY INTEGER NOT DECIMAL,
                         ^^^^^^^---------
4: L_SUPPKEY INTEGER NOT NULL,
5: L_LINENUMBER INTEGER NOT NULL,
6:L_QUANTITY DECIMAL(15,2),
```
> DB-12097 better SQL errors (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryArithmeticOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ConstantFoldingIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicateTransitiveClosureIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperatonIT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_InList_IT.java
Support plus, minus, times, divide, mod constant folding for numeric operands
This can be tested via an explain on simple selects:
```
explain select * from sysibm.sysdummy1 where 1 = 1 + 1
```
will return a plan without a table scan because 1 = 1 + 1 is evaluated to be false at compile time
The same principle will apply to the other operators supported in that ticket.
> DB-12225 Implement constant folding for numeric binary +-*/% 

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/SpliceGenericResultSetFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DerbyScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/IndexPrefixIteratorOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/iapi/ScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/Scans.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/IndexPrefixIterationIT.java
Avoid incorrect results on queries flagged as IndexPrefixIteratorMode in the EXPLAIN with predicates of the form _2nd_index_column_ < _constant_.
Scans.attachScanKeys was updated by [SPLICE-2399](https://github.com/splicemachine/spliceengine/pull/5013) to combine a list of key values on the first index column (firstIndexColumnKeys) with key values on the remaining index columns from predicates.  However this path always passed the stopSearchOperator parameter of buildStartAndStopKeys as hard-coded GT, which causes the stop key to be appended with an extra byte of value 1, causing the stop key to be inclusive, even if we are using a less than operator in the predicate.  The range was made wider in an attempt to never exclude necessary values with the assumption that the scan qualifier …
> DB-12280 Stop key for Index Prefix Iteration should not override stopSearchOperator

- splice_spark2/pom.xml
- splice_spark2/src/main/scala/com/splicemachine/nsds/kafka/KafkaTopics.scala
- splice_spark2/src/main/scala/com/splicemachine/spark2/splicemachine/SplicemachineContext.scala
NSDS now deletes used topics during processing instead of at shutdown.
NSDS v2 (eNSDS) uses a new Kafka topic for each transaction, for both transactions to and from the DB.  After the call to the DB returns (which should mean the transaction is completed), NSDS puts the used topic name on a queue to be deleted.  A separate thread now checks the deletion queue and sends the topic names to Kafka to delete the topics.  The thread sleeps for a minute between checks of the deletion queue.
The code was previously queueing the used topic names after each transaction and sending them for deletion when NSDS shut down.  For a long running process like streaming, a large number of topics accumulate and fill disk and memory in Kafka.  Now NSDS performs continual cleanup.
Use NSDS v2 (eNSDS) …
> DB-12210 NSDSv2 Continuous Topic Deletion

- db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/costing/V1BroadcastJoinCostEstimation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/BroadcastJoinIT.java
This PR fixes two issues:
- broadcast join is feasible but not costed in case of left outer join + missing hash key
- hash join predicates are not pulled up properly when the predicate is under a hash join which is in turn nested inside a non-flattenable subquery
Broadcast join is not costed in some cases. When it’s not costed, its cost is set to `Double.MAX`, thus losing the comparison to other join strategies.
The current condition is the following:
```
boolean costIt = isHinted ||
estimatedMemoryMB<regionThreshold &&
estimatedRowCount<rowCountThreshold &&
(!currentAccessPath.isMissingHashKeyOK() ||
// allow outer join without equality join condition
outerCost.getJoinType() == JoinNode.FULLOUTERJOIN ||
// allow left or inner join with non-equality broadcast join only if using spark …
```
> DB-12057 Cost broadcast join for left outer join with no hash key

- db-engine/src/main/java/com/splicemachine/db/iapi/ast/ISpliceVisitor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Visitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/SpliceDerbyVisitorAdapter.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/BroadcastJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/BroadcastJoinIT.java
See https://github.com/splicemachine/spliceengine/pull/5610.
There is a second commit in this PR only for 3.0 branch. It introduces some visitor utility methods that are in master and 3.1 but not 3.0.
> DB-12057 Cost broadcast join for left outer join with no hash key (3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/db/InternalDatabase.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedConnection.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/AdapterPipelineEnvironment.java
- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HBasePipelineEnvironment.java
- hbase_storage/src/main/java/com/splicemachine/hbase/SessionsWatcherImpl.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/AdapterSIEnvironment.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HActiveSessionsTaskFactory.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HBaseSIEnvironment.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HGetActiveSessionsTask.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/SpliceRSRpcServices.java
- mem_pipeline/src/main/java/com/splicemachine/pipeline/MPipelineEnv.java
- mem_storage/src/main/java/com/splicemachine/si/MemSIEnvironment.java
- mem_storage/src/main/java/com/splicemachine/storage/MSessionsWatcherImpl.java
- splice_access_api/src/main/java/com/splicemachine/access/api/ActiveSessionsTaskFactory.java
- splice_access_api/src/main/java/com/splicemachine/access/api/GetActiveSessionsTask.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceLevel2OptimizerImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/procedures/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ProcedureUnitTest.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdmin_GetActiveSessionsIT.java
- splice_protocol/src/main/protobuf/Splice.proto
- splice_si_api/src/main/java/com/splicemachine/si/api/session/SessionsWatcher.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIDriver.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIEnvironment.java
This PR implements a new admin system procedure `syscs_util.syscs_get_active_sessions()`, which lists all active sessions on all region servers.
This is the first step of cleaning up obsolete local temporary tables.
Each region server has a singleton instance of `SessionsWatcherImpl`. Internally, it maintains a concurrent hash set recording active sessions on this region server. Each session registers itself in setting up the connection and unregisters itself when disconnected from the region server.
When calling `syscs_util.syscs_get_active_sessions()` on a region server, `SessionWatcherImpl.getAllActiveSessions()` sends a request via protobuf to all region servers and merge returned active sessions from all region servers into a single list.
On mem platform, there is no region server …
> DB-12222 Track all active sessions

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromList.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropColumnIT.java
Fix regression introduced by DB-9898 after switching `ColumnReference.columnNumber` from logical column number to storage number.
DB-9898 started using storage columns in `ColumnReference`.
`FromList.returnsAtMostSingleRow` creates a column map to be passed to `recordColumnReferences`. This column map should be initialized with the `getNumberOfStorageColumns` (i.e. the max id of a storage column) instead of `getNumberOfColumns`
```
drop table ADVANCED_TEST001_S.employees;
CREATE TABLE ADVANCED_TEST001_S.employees (emplid INTEGER NOT NULL, firstname VARCHAR(25) NOT NULL, reportsto INTEGER);
insert into ADVANCED_TEST001_S.employees values (7725070,'Kottapalli',8852090);
insert into ADVANCED_TEST001_S.employees values (6825081,'Anderson',8852090);
insert into ADVANCED_TEST001_S.employees …
```
> DB-12305 Fix DB-9898 regression after using storage cols in ColRefs 

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/KafkaReadFunction.java
> DB-12291: close consumer when reading from Kafka fails(3.1)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/KafkaReadFunction.java
> DB-12291: close consumer when reading from Kafka fails(3.0)

- db-engine/src/main/java/com/splicemachine/db/catalog/IndexDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/catalog/types/IndexDescriptorImpl.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/IndexRowGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeFixIndexDescriptors.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/btree/IndexConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/hbase/HBaseConglomerate.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceCatalogUpgradeScriptsTest.java
Fix upgrade regression introduced by DB-9898 causing upgrades from 2021 to 2022 to fail.
DB-9898 introduced a new field in `IndexDescriptorImpl`: `baseStorageColumnPositions`. From 2022 onward,  IndexDescriptorImpl contains both `baseStorageColumnPositions` and `baseColumnPosition`.
The protobuf message was also extended: on top of the already present `repeat baseColumnPositions`, DB-9898 introduced `repeat baseColumnLogicalPositions`.
This is already somewhat confusing and the mapping between `IndexDescriptorImpl` and the protobuf message should be as follow:
| Protobuf message          | IndexDescriptorImpl       |
|---------------------------|---------------------------|
| baseLogicalColumnPosition | baseColumnPosition        |
| baseColumnPosition        | baseStorageColumnPosition | …
> DB-12323 Fix upgrade regression introduced by DB-9898 

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/execute/ResultSetFactory.java
- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/TransactionController.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryDateTimestampOperatorNode.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/sql/Utils.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/main/java/com/splicemachine/derby/stream/function/BulkImportFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/SpliceGenericResultSetFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DistinctScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/IndexPrefixIteratorOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/LastIndexKeyOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TableScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/SpliceTransactionManager.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SelectTimeTravelIT.java
In this PR, we target a subtle inconsistency caused by time-travel allowing the optimizer to choose a temporal-inconsistent index, causing wrong results to be returned.
With time-travel, the user view the historical data of a table within a min. retention period. It could happen that the optimizer prefers an AccessPath involving an index conglomerate that is created _after_ the past transaction ID which is dangerous, because the base table could have changed between the past transaction ID and the index creation time (e.g. some rows are deleted before the index was created), if the optimizer chooses that index conglomerate we will get empty results because the index does not have any data at the past transaction ID since it was created after it.
To fix this issue we make sure, during …
> DB-11826 DB-12226 Fix time-travel returning incorrect results due to using temporal-inconsistent index (3.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/execute/ResultSetFactory.java
- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/TransactionController.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryDateTimestampOperatorNode.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/sql/Utils.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/main/java/com/splicemachine/derby/stream/function/BulkImportFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/SpliceGenericResultSetFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DistinctScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/LastIndexKeyOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TableScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/SpliceTransactionManager.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SelectTimeTravelIT.java
In this PR, we target a subtle inconsistency caused by time-travel allowing the optimizer to choose a temporal-inconsistent index, causing wrong results to be returned.
With time-travel, the user view the historical data of a table within a min. retention period. It could happen that the optimizer prefers an AccessPath involving an index conglomerate that is created _after_ the past transaction ID which is dangerous, because the base table could have changed between the past transaction ID and the index creation time (e.g. some rows are deleted before the index was created), if the optimizer chooses that index conglomerate we will get empty results because the index does not have any data at the past transaction ID since it was created after it.
To fix this issue we make sure, during …
> DB-11826 DB-12226 Fix time-travel returning incorrect results due to using temporal-inconsistent index (3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/depend/DependencyManager.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/ViewDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CreateViewNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/depend/BasicDependencyManager.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/GlobalDBProperties.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/ModifyColumnConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropAddColumnIT.java
This change introduces a new automatic view refreshing mode for alter table add/drop column.
3.1 PR: https://github.com/splicemachine/spliceengine/pull/5660.
3.0 PR: https://github.com/splicemachine/spliceengine/pull/5662.
This change introduces a new automatic view refreshing mode for alter table add/drop column.
When this mode is turned on, an `ALTER TABLE T ADD/DROP COLUMN ...` statement automatically refreshes all views defined both directly and indirectly on `T` whose top-level select list is a `SELECT *`. Other views are not refreshed.
This mode is off by default. To turn it on, run the following:
```
call syscs_util.syscs_set_global_database_property('splice.execution.alterTable.autoViewRefreshing', true)
```
To turn it off, run the following:
```
call …
```
> DB-12158 Automatic view refreshing for alter table add/drop column

- splice_spark2/src/main/scala/com/splicemachine/nsds/kafka/KafkaTopics.scala
- splice_spark2/src/main/scala/com/splicemachine/spark2/splicemachine/SplicemachineContext.scala
Some changes made during work on streaming resampling.
1. Continuous topic cleanup default value set to false to reduce traffic on Kafka.
2. Support for upsert added in the setTable method so that streaming code can do upsert.
3. Some logging updates.
1. Run eNSDS and note that topics are not automatically cleaned up in Kafka when transactions are completed.
2. Run streaming in upsert mode and note upsert behavior with the incoming records.
3. Note sendData log as an info instead of debug.  Note insert topicCount logs are gone.
> DB-12324 NSDS v2 Changes for Streaming Resampling

- splice_spark2/src/main/scala/com/splicemachine/nsds/kafka/KafkaTopics.scala
- splice_spark2/src/main/scala/com/splicemachine/spark2/splicemachine/SplicemachineContext.scala
Some changes made during work on streaming resampling.
1. Continuous topic cleanup default value set to false to reduce traffic on Kafka.
2. Support for upsert added in the setTable method so that streaming code can do upsert.
3. Some logging updates.
1. Run eNSDS and note that topics are not automatically cleaned up in Kafka when transactions are completed.
2. Run streaming in upsert mode and note upsert behavior with the incoming records.
3. Note sendData log as an info instead of debug.  Note insert topicCount logs are gone.
> DB-12324 NSDS v2 Changes for Streaming Resampling (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/ModifyColumnConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropColumnIT.java
Fix a regression caused by DB-9898
DB-9898 incorrectly tries to find out whether column is referenced by a trigger by using storage position. The reference column number is a relative position and being updated if other columns are dropped. This PR reverts previous change and use relative position instead.
create table m(id int, col1 int, col2 int, col3 int, col4 char(50), col5 varchar(100));
create table s(id int ,description varchar(100),tm_time timestamp);
CREATE TRIGGER tr1 AFTER UPDATE of col1,col2 ON m FOR EACH STATEMENT insert into s values(7,'TR1',CURRENT_TIMESTAMP);
CREATE TRIGGER tr2 AFTER UPDATE of col2 ON m FOR EACH STATEMENT insert into s values(6,'TR2',CURRENT_TIMESTAMP);
alter table m drop col1;
alter table m drop col2;
-- Verify the above two DDL drops triggers
select …
> DB-12306: fix a drop column regression - drop columns doesn't drop related trigger

- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/procedures/SpliceAdmin.java
This change adds a new administrative system procedure which cleans up obsolete temporary tables.
Currently, local temporary tables are not dropped properly when region servers crash because the happy path in disconnecting a session is not executed.
Once the cluster is up again, there is no way to remove the obsolete local temporary tables because they were created by previous sessions, thus not visible to new sessions. Over time, there could be more and more obsolete temporary tables in system, wasting space and causing troubles in fixing inconsistency issues when they occur.
The new system procedure `SYSCS_DROP_OBSOLETE_TEMPORARY_TABLES(schemaName)` cleans up all obsolete temporary tables in schema `schemaName`. It works in the following steps:
1. get a copy of table descriptors in the …
> DB-10594 Add a system procedure to clean up obsolete temp tables

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/NaturalJoinIT.java
Fix natural right outer join 
During Parsing phase, we construct a HalfOuterJoinNode and if it is a right outer join, we set joinResultSet and rightOuterJoinUsingClause in every result column of top select nodes.
However, during optimization phase, we remove the original HalfOuterJoinNode to create a new one. The new one will get a resultSetNumber assigned to it. Since the original HalfOuterJoinNode was removed, we never assign a resultSetNumber to it.
However, the top SelectNode was never cleared of its reference to the original HalfOuterJoinNode, leading to issues in code generation.
```
drop table staff3;
drop table staff66;
create table staff3(EMPNUM   VARCHAR(3) NOT NULL, GRADE    DECIMAL(4));
INSERT INTO STAFF3 VALUES ('E2',10);
CREATE TABLE STAFF66 (SALARY DECIMAL(14,0),EMPNUM …
```
> DB-9348 Fix natural right outer join

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/ModifyColumnConstantOperation.java
DB-12224 changed the API for DataDictionary.getTableDescriptor, and DB-12158 still used the old API, so this is fixing this build error.
> DB-12350 fix build error in ModifyColumnConstantOperation (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/ModifyColumnConstantOperation.java
DB-12224 changed the API for DataDictionary.getTableDescriptor, and DB-12158 still used the old API, so this is fixing this build error.
> DB-12350 fix build error in ModifyColumnConstantOperation

- pipelines/spot-bugs/Jenkinsfile
Add an artifact check stage in order for a quick smoke test of whether all the versions can be built from a PR or not. If the artifacts can't be built, then the PR should be rejected.
This PR adds an additional stage to check if artifacts can be built or not. It runs the initial build check and then the spotbug stages in a single node. Then it dynamically generates the new stages depending on the branch. There is some duplicate needed since the new node cannot inherit the environment variables from the pipeline, so it needs to check the correct source_branch again along with doing another checkout. Once the spotbugs stage is completed, the artifact build stage is all run in parllel, so the normal case of dbaas3,dbaas3.1,cdh6.3.0,hdp3.1.0, and hdp3.1.5 are all run at the same time once …
> Add artifact stage (3.1)

- pipelines/spot-bugs/Jenkinsfile
Add an artifact check stage in order for a quick smoke test of whether all the versions can be built from a PR or not. If the artifacts can't be built, then the PR should be rejected.
This PR adds an additional stage to check if artifacts can be built or not. It runs the initial build check and then the spotbug stages in a single node. Then it dynamically generates the new stages depending on the branch. There is some duplicate needed since the new node cannot inherit the environment variables from the pipeline, so it needs to check the correct source_branch again along with doing another checkout. Once the spotbugs stage is completed, the artifact build stage is all run in parllel, so the normal case of dbaas3,dbaas3.1,cdh6.3.0,hdp3.1.0, and hdp3.1.5 are all run at the same time once …
> Add artifact stage (3.0)

- pipelines/spot-bugs/Jenkinsfile
Add an artifact check stage in order for a quick smoke test of whether all the versions can be built from a PR or not. If the artifacts can't be built, then the PR should be rejected.
This PR adds an additional stage to check if artifacts can be built or not. It runs the initial build check and then the spotbug stages in a single node. Then it dynamically generates the new stages depending on the branch. There is some duplicate needed since the new node cannot inherit the environment variables from the pipeline, so it needs to check the correct source_branch again along with doing another checkout. Once the spotbugs stage is completed, the artifact build stage is all run in parllel, so the normal case of dbaas3,dbaas3.1,cdh6.3.0,hdp3.1.0, and hdp3.1.5 are all run at the same time once …
> Add artifact stage (2.8)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/ModifyColumnConstantOperation.java
This change fixes an issue that in automatic view refreshing mode, views defined on top of other views sometimes are not refreshed properly.
3.1 PR: https://github.com/splicemachine/spliceengine/pull/5684
3.0 PR: https://github.com/splicemachine/spliceengine/pull/5685
Suppose we have views defined as the following:
```
create table T (c int, d int);
create view v as select * from T;
create view vv as select * from v;
```
Usually, when getting dependencies of table `T`, dependency manager returns a list of dependent items in their added order. Since view `VV` is defined after `V`, its dependencies to `T` and `V` are added after dependency from `V` to `T` is added. This should be the case because internally, dependency manager uses a `List` storing dependent items of an object. Also, `V` …
> DB-12352 Fix auto view refreshing mode for view on top of view

- hbase_sql/src/test/java/com/splicemachine/derby/utils/SqlshellIT.java
we test the current time against `\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d.\d\d\d\d\d\d` which is mostly correct,
however, if we’re unlucky and the current time is like `2021-07-19 17:55:24.500000`, it would be displayed
as `2021-07-19 17:55:24.5` , and we get a failed test. This fixes that.
> DB-12373 fix SqlshellIT.testCustomFormatsOption sporadic
