splicemachine/spliceengine

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
Just a simple dereference of OperationContext...
=> SPLICE-697 Dereference Operation Context

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OrderByColumn.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OrderByList.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SortOperationIT.java
Applying two derby patches to support order by error checking and simple execution of values clauses...
=> Splice 707 splice 708

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
Add warning message for restore, and print out any warnings when restore completes.
=> DB-5586: add warning message for restore

db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextService.java, db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java, splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java, splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java, splice_machine/src/main/java/com/splicemachine/derby/management/TransactionalSysTableWriter.java, splice_machine/src/main/java/com/splicemachine/derby/utils/DataDictionaryUtils.java
Close SpliceTransactionResourceImpl always after marshalling a
transaction and make sure to remove the ContextManager from the list of
active CMs
=> DB-5252 Fix ContextManager leak

hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSparkKryoRegistrator.java, hbase_sql/src/main/java/com/splicemachine/stream/ResultStreamer.java, hbase_sql/src/main/java/com/splicemachine/stream/StreamListenerServer.java, hbase_sql/src/main/java/com/splicemachine/stream/handlers/OpenHandler.java
- Added Kryo Pool in Result Streamer and Streamer listener.
I have added a OpenHandler and will do more cleaning  with the other classes as it get confusing to have class handling multiple handlers via anonymous classes
=> Fixed SPLICE 709 - Use Kryo pools in result streamer / stream listener

hbase_storage/pom.xml, hbase_storage/src/test/java/com/splicemachine/si/testsetup/HBaseSITestEnv.java
Removing DFS Cluster hang for HDP.
=> SPLICE-815 Fixing DFSCluster hang

hbase_storage/src/test/java/com/splicemachine/si/testsetup/HBaseSITestEnv.java
Adding a check for mapr since it does not handle starting zoo and hbase directly.
=> SPLICE-817 Using the old mechanism for MapR

pom.xml
=> SPLICE-760 Forcing JDK 1.8

splice_encoding/src/main/java/com/splicemachine/storage/index/SparseBitIndex.java, splice_encoding/src/test/java/com/splicemachine/storage/index/SparseBitIndexTest.java
Reverts splicemachine/spliceengine#71
=> Revert "SPLICE-816: Correcting error in SparseBitIndex"

hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
=> SPLICE-782: fix compiling errors for cdh5.7.2

splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIDriver.java
Improve logging in case an uncaught exception is thrown
=> SPLICE-839 Set default handler for uncaught exceptions

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/scanner/SITableScanner.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/scanner/TableScannerBuilder.java, splice_machine/src/main/java/com/splicemachine/derby/stream/stats/StatisticsScanner.java
Scans should not compute size unless it is a statistics run.
=> SPLICE-846 Remove Metrics Computation from Standard Scans

hbase_storage/src/main/java/com/splicemachine/storage/HLock.java
Tried to write an IT but I could not get Mockito to really run it through the Region Flow.  I think the challenge is that there is no no-arg constructor.  
This handles the hbase change from "waitFor boolean" in the lock logic to "readLock boolean."
=> SPLICE-857 Handling Versioned Lock Implementations

hbase_sql/src/main/java/com/splicemachine/hbase/MemstoreAwareObserver.java
When closing regions due to an abort we shouldn't block waiting for scanners to finish, since they might never be able to complete.
=> SPLICE-883 Don't block preClose() in case of abort

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, db-tools-ij/src/main/grammar/ij.jj
Transitioning from StringBuffer (Synchronized) to StringBuilder...
=> SPLICE-899 Transition to StringBuilder

db-client/src/main/java/com/splicemachine/db/client/net/NetCursor.java, db-client/src/main/java/com/splicemachine/db/client/net/Reply.java, db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java, db-engine/src/main/java/com/splicemachine/db/iapi/services/io/FormatableArrayHolder.java, db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLRowId.java
=> SPLICE-900 Removing Manual Array Copies

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
Removing _ identifer for JDK 1.9 ...
=> SPLICE-901 _ identifier not supported post JDK 1.8

db-client/src/main/java/com/splicemachine/db/jdbc/ClientDataSource40.java, db-engine/src/main/java/com/splicemachine/db/agg/Aggregator.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/Activation.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/AliasDescriptor.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/CatalogRowFactory.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/ConstraintDescriptorList.java, db-engine/src/main/java/com/splicemachine/db/iapi/types/ClobStreamHeaderGenerator.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryArithmeticOperatorNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryLogicalOperatorNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryOperatorNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CastNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CoalesceFunctionNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConcatenationOperatorNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConstantNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CreateTriggerNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CurrentDatetimeOperatorNode.java, db-engine/src/test/java/com/splicemachine/db/iapi/services/io/CompressedNumberTest.java, db-engine/src/test/java/com/splicemachine/db/iapi/services/io/DataInputUtilTest.java, hbase_sql/src/main/java/com/splicemachine/compactions/CompactionInputFormat.java, hbase_sql/src/main/java/com/splicemachine/compactions/CompactionRecordReader.java
=> SPLICE-902 Import Cleanup

hbase_sql/src/main/java/com/splicemachine/compactions/PlaceholderTask.java
This corrects the PlaceholderTasks' early cancellation race condition. See SPLICE-891 for more details about why things are done the way they are.
This occurs in the ITs for CDH5.7.2, so no additional tests are necessary (even if it were possible as written).
=> SPLICE-891: Correcting early cancellation race condition.

hbase_sql/src/test/java/com/splicemachine/olap/OlapClientTest.java
=> SPLICE-906 Fix flaky test

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/HregionDataSetProcessor.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java, hbase_sql/src/test/java/com/splicemachine/mrio/api/core/SplitRegionScannerIT.java, hbase_sql/src/test/java/com/splicemachine/mrio/api/core/SplitRegionScannerStressIT.java, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
=> SPLICE-886 Don't wait indefinetely for subpartitions

hbase_sql/src/main/java/com/splicemachine/olap/AsyncOlapNIOLayer.java, hbase_sql/src/main/java/com/splicemachine/olap/MappedJobRegistry.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapJobStatus.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapServer.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SIConfigurations.java
Tick time configurable + increase olap client timeout
=> SPLICE 838 Backport

hbase_sql/pom.xml
Fixing sql breakage in ide, with dynamic naming transitive dependencies are not included.
=> SPLICE-920 Fixing sql breakage in ide

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
Code Cleanup for Spark/Control Logic.  Still need to create a configurable parameter.
=> SPLICE-921 Cleanup Spark Logic Application Code

hbase_sql/src/main/java/com/splicemachine/hbase/BytesCopyTaskSplitter.java, hbase_sql/src/main/java/com/splicemachine/hbase/RegionSizeEndpoint.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/AbstractSMInputFormat.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SubregionSplitter.java, hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java, splice_protocol/src/main/protobuf/Splice.proto
=> SPLICE-910

db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLClob.java
As requested per John, fix also SQLClob.readExternal assumptions about .read() returning all needed bytes.
=> SPLICE-915 Fix SQLCLob.readExternal assumption of .read()

splice_machine/src/main/java/com/splicemachine/derby/stream/function/AntiJoinFunction.java
=> SPLICE-928 Code Cleanup

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/IndexConstantOperation.java
=> SPLICE-869 Make sure operation context is properly setup on index job

db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextService.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/BroadcastedActivation.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java, hbase_storage/src/main/java/com/splicemachine/storage/HScan.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/NestedLoopJoinOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/RowOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ScanOperation.java, splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlOperationContext.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJInnerJoinFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/OperationContext.java, splice_machine/src/test/java/com/splicemachine/foreignkeys/ForeignKey_AlterDropTable_IT.java
=> SPLICE-858: batch nested loop join

db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLClob.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/sequence/SpliceSequence.java, splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnOperationFactory.java
=> Splice 915 2.0

hbase_sql/src/main/java/com/splicemachine/derby/stream/compaction/SparkCompactionFunction.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java, pipeline_api/src/main/java/com/splicemachine/pipeline/api/RecordingContext.java, pipeline_api/src/main/java/com/splicemachine/pipeline/config/BaseWriteConfiguration.java, pipeline_api/src/test/java/com/splicemachine/pipeline/client/BulkWriteActionTest.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetWriter.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlOperationContext.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/output/ControlExportDataSetWriter.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/AntiJoinRestrictionFlatMapFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/FileFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/InnerJoinRestrictionFlatMapFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/MergeAllAggregatesFlatMapFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJAntiJoinFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJOneRowInnerJoinFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJOuterJoinFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/NormalizeFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/ProjectRestrictFlatMapFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/ScalarAggregateFlatMapFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/TableScanTupleFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/output/direct/DirectDataSetWriter.java
Removing Extra Object Creation.
=> SPLICE-940 Remove Extra List Creation for SingletonIterators

db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/CreateConstraintConstantAction.java, db-tools-testing/src/main/java/com/splicemachine/dbTesting/functionTests/util/ProcedureTest.java, db-tools-testing/src/main/java/com/splicemachine/dbTesting/junit/DropDatabaseSetup.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateConstraintConstantOperation.java
Automated Remove String.toString()
=> SPLICE-946 Remove String.toString(): Automated

db-client/src/main/java/com/splicemachine/db/client/am/EncryptionManager.java, db-client/src/main/java/com/splicemachine/db/client/net/NetCursor.java, db-client/src/main/java/com/splicemachine/db/client/net/Reply.java, db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java, db-drda/src/main/java/com/splicemachine/db/impl/drda/DecryptionManager.java, db-engine/src/main/java/com/splicemachine/db/iapi/services/io/FormatableArrayHolder.java, db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLRowId.java, db-engine/src/main/java/com/splicemachine/db/impl/services/jce/JCECipherFactory.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/TemporaryRowHolderResultSet.java, db-testing/src/test/java/com/splicemachine/dbTesting/functionTests/tests/tools/dblook_test.java, db-testing/src/test/java/com/splicemachine/dbTesting/functionTests/tests/upgradeTests/Version.java, db-testing/src/test/java/com/splicemachine/dbTesting/unitTests/store/T_AccessRow.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/IndexRowToBaseRowOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TemporaryRowHolderOperation.java
=> SPLICE-945 Manual Array Copy Cleanup: Automated

db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/depend/BasicDependency.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/depend/BasicDependencyManager.java
Invalidate statements when pushed out of the statement cache and store
only weak references on the DependencyManager
Tested against JDK 7.
=> SPLICE-950 Make activation classes eligible for GC

hbase_sql/src/test/java/com/splicemachine/olap/OlapClientTest.java
Reverts splicemachine/spliceengine#171
=> Revert "SPLICE-906 Fix flaky test"

db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java, db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
=> DB-5633: fix timestamp column for system tables

hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java, hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java, hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java, hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java, hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java
=> SPLICE-960 close parent scanner

hbase_sql/src/main/java/com/splicemachine/derby/impl/spark/WholeTextInputFormat.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/io/WholeTextInputFormatTest.java
Move test out of platform directory, it is generic
=> SPLICE-962 Create split per file in WholeTextInputFormat

splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Row_IT.java
=> SPLICE-964 Increase test time threshold to limit spurious build failures

assembly/mapr5.2.0/src/main/resources/bin/sqlshell.sh, assembly/mapr5.2.0/src/main/resources/conf/hbase-env.sh.patch, assembly/mapr5.2.0/src/main/resources/conf/hbase-env.sh.secure.patch, assembly/mapr5.2.0/src/main/resources/conf/hbase-site.xml.patch, assembly/mapr5.2.0/src/main/resources/conf/hbase-site.xml.secure.patch, assembly/mapr5.2.0/src/main/resources/conf/warden.conf.patch, assembly/mapr5.2.0/src/main/resources/conf/yarn-site.xml.patch, assembly/mapr5.2.0/src/main/resources/conf/yarn-site.xml.secure.patch, assembly/mapr5.2.0/src/main/resources/conf/zoo.cfg.patch, assembly/mapr5.2.0/src/main/resources/examples/conf/hbase-env.sh, assembly/mapr5.2.0/src/main/resources/examples/conf/hbase-site.xml, assembly/mapr5.2.0/src/main/resources/examples/conf/mapr-splice-hbase-config.sh, assembly/mapr5.2.0/src/main/resources/examples/scripts/splice-init-script, assembly/mapr5.2.0/src/main/resources/scripts/flatten.sh, assembly/mapr5.2.0/src/main/resources/scripts/install-hbase-env-sh.sh, assembly/mapr5.2.0/src/main/resources/scripts/install-hbase-site-xml.sh, assembly/mapr5.2.0/src/main/resources/scripts/install-sysctl-conf.sh, assembly/mapr5.2.0/src/main/resources/scripts/install-test.sql, assembly/mapr5.2.0/src/main/resources/scripts/install-warden-conf.sh, assembly/mapr5.2.0/src/main/resources/scripts/install-yarn-site-xml.sh, assembly/mapr5.2.0/src/main/resources/scripts/install-zookeeper-conf.sh, assembly/mapr5.2.0/src/main/resources/scripts/restart.sh, assembly/mapr5.2.0/src/main/resources/scripts/start-hbase.sh, assembly/mapr5.2.0/src/main/resources/scripts/stop-hbase.sh, platforms/mapr5.2.0/pom.xml, pom.xml
Adding MapR 5.2.0 platform support to Splice Machine.
=> SPLICE-963 : MapR 5.2.x support in Splice

db-engine/src/main/java/com/splicemachine/db/iapi/services/io/ArrayUtil.java
=> DB-5634: add utility methods to serialize byte array

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java, hbase_sql/src/main/java/com/splicemachine/mrio/MRConstants.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java, hbase_sql/src/main/java/com/splicemachine/stream/QueryJob.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/IndexConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/index/PopulateIndexJob.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/scanner/TableScannerBuilder.java, splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
Pending cleanup when we fix leaks in SparkExecutors
=> SPLICE-961 Release contextManagers in OlapServer

splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceDateFunctions.java
For a timestamp that contains nanosecond, but is not compatible with SQLTimestamp format, we can parse timestamp using Joda DateTimeFormatter for millisecond precision. Then obtain nanosecond from timestamp string and set nanosecond.
=> SPLICE-992: parse timestamp format 'yyyy-MM-dd HH.mm.ss.SSSSSS' correctly

hbase_sql/src/main/java/com/splicemachine/compactions/PlaceholderTask.java
Remove annoying exceptions from logs.
=> Splice 934 

splice_machine/src/main/java/com/splicemachine/derby/stream/function/MergeAllAggregatesFunction.java
2.0 Commit that speeds up TPCH query 1 by a few seconds.
=> SPLICE-1034 Removing expensive checks when possible, incremental move

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java
Remove auto-boxing of longs (Long.valueof).
=> SPLICE-1037 Convert to Spark LongAccumulator impl to remove auto-boxing

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/CreateTableWithDataIT.java
Adhering to Oracle Syntax as well for create table.
=> SPLICE-466 Make with data the default for create table as (Oracle style)

splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java, splice_machine/src/test/java/com/splicemachine/derby/impl/load/CaseSensitiveImportIT.java, splice_machine/src/test/test-data/import/valuesThree.txt
This corrects the regression introduced by SPLICE-983, and adds an IT to confirm
=> SPLICE-1049: Dealing with mixed-case columns in import correctly.

hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
Pulling up hbase.regionserver.kerberos.principal and hbase.regionserver.keytab.file from HBase configuration
and set spark.yarn.keytab and spark.yarn.principal for Spark
=>  fix DB-5653 branch 2

db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/AggregateDefinition.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/AggregateNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowResultSetNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WrappedAggregateFunctionNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/WindowFunctionInfo.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkPairDataSet.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkUtils.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkWindow.java, hbase_sql/src/test/java/com/splicemachine/mrio/api/core/DataFrameIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/WindowOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregator.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregatorImpl.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/OperationContext.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
Ignored tests with a decimal precision difference between previous implementation and Splice.
This is going to be fixed afterward.
=> Correct version of WIndow Functions on top of DataSet.

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java, hbase_sql/src/main/java/com/splicemachine/stream/RemoteQueryClientImpl.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/RowCountOperation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/RowCountOperationIT.java
=> SPLICE-985 Bypass RowCountOperation only when needed

pom.xml
=> SPLICE-1096 Fix dependency conflict

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CursorNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InsertNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/StatementNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WithStatementIT.java
Adding Parser Support for With Clauses in Inserts.
=> SPLICE-1026 With Clause Inserts

db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/CreateSchemaConstantAction.java, splice_machine/src/test/java/com/splicemachine/derby/utils/UserFunctionsIT.java
This fix will create a  new schema for a user during his creation.
=> FIX SPLICE 1030

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/VTIOperation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/VTIOperationIT.java
=> SPLICE-1109 Make VTI operations work with joins

hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HBasePipelineEnvironment.java, hbase_sql/pom.xml, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/S3IT.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java, hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HBaseSIEnvironment.java, mem_pipeline/src/main/java/com/splicemachine/pipeline/MPipelineEnv.java, mem_storage/src/main/java/com/splicemachine/si/MemSIEnvironment.java, splice_machine/src/main/java/com/splicemachine/derby/impl/load/ImportUtils.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java, splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java, splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java, splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIDriver.java, splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIEnvironment.java
Small Fix to File System abstraction to allow for access to Hadoop Compliant File Systems.  Added a small test for S3.
=> SPLICE-159 Supporting Hadoop Compliant File Systems

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/AggregateNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WrappedAggregateFunctionNode.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
Fixed for TPC-DS  nested aggregates in queries: 12,20,47,53,57,63,89,98 with Window Functions
=> SPLICE 969 -

splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsFunctions.java, splice_machine/src/test/java/com/splicemachine/derby/utils/StatisticsAdminIT.java
Careless mistake when computing the percentage.  Added test for coverage.
=> SPLICE-1138 Null Fraction Computational Error

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/FunctionIT.java
Adding Support for NVL (i.e. COALESCE)
=> SPLICE-576 Add Support for NVL

hbase_sql/src/main/java/com/splicemachine/stream/output/SpliceOutputCommitter.java, pipeline_api/src/main/java/com/splicemachine/pipeline/writehandler/PartitionWriteHandler.java, splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Row_IT.java
=> SPLICE-1129: make import transaction additive

hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HBasePipelineEnvironment.java
=> SPLICE-1162 Don't publish reference before finishing booting

db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLBoolean.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
Fix Boolean scans, quick test.
=> SPLICE-1167 Adding back booleans

splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/BaseSpliceTransaction.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/SpliceTransaction.java, splice_machine/src/main/java/com/splicemachine/pipeline/ErrorState.java, splice_si_api/src/main/java/com/splicemachine/si/impl/BaseTransaction.java, splice_si_api/src/main/java/com/splicemachine/si/impl/SavePointNotFoundException.java, splice_si_api/src/main/java/com/splicemachine/si/impl/Transaction.java, splice_si_api/src/main/java/com/splicemachine/si/impl/TransactionImpl.java, splice_si_api/src/main/java/com/splicemachine/si/impl/TransactionViewImpl.java, splice_si_api/src/test/java/com/splicemachine/si/SavepointsTest.java
Added some tests around savepoints
=> SPLICE-998 Move SpliceTransaction into SI module

utilities/src/main/java/com/splicemachine/collections/LongKeyedCache.java, utilities/src/test/java/com/splicemachine/collections/LongKeyedCacheTest.java
This caused transactional overhead because when full LongKeyedCache effectively only cached one element.
Tested on a cluster.
=> PLICE-1190 Fix LongKeyedCache eviction mechanism

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperation.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
Parallelize Union Operations on the control side.
=> SPLICE-1189 Parallelize Control Side Unions

splice_machine/src/main/java/com/splicemachine/derby/impl/load/ImportUtils.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportFile.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportPermissionCheck.java
Would like to support S3 for export command.  Unfortunately, I think it is a party foul to add S3 tests to github, plus it might get expensive.  :)
I am going to have QA test this individually.
=> SPLICE-1243 Adding Other FileSystem Support, QA to test

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DistinctGroupedAggregateOperationIT.java
Do not give wrong answers for multiple distinct aggregates instead error out well until we add the support for it.
=> SPLICE-1234: error out well for multiple distinct aggregates

hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinOperation.java
This fixes the inner join piece.  This will address Bob's immediate need.
=> SPLICE-1219 Fixes the inner join with restriction and adds test

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
Check for appropriate table formation.  Throw exception if regular table has location or stored as...
=> SPLICE-1203 Throw exception if not external with location or storage

hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java, hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java, hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java, hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java, hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/hbase/HBaseConnectionFactory.java, hbase_storage/src/main/java/com/splicemachine/access/HConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
Pull Request which was reverted due to build issues that have been fixed.
=> SPLICE-1216 Block Coding Configurability

db-drda/pom.xml, db-drda/src/main/java/com/splicemachine/db/impl/drda/DDMWriter.java, db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java, db-drda/src/main/java/com/splicemachine/db/impl/drda/Session.java
odbc server side snappy changes from server side.
=> Add snappy compression in DRDA layer (server side)

db-engine/src/main/java/com/splicemachine/db/impl/ast/RepeatedPredicateVisitor.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/JoinSelectionIT.java
Extract repetitive predicate from a DNF to enable hashable join strategy.
=> SPLICE-1143: extract repetive predicate from DNF

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
Adding a Null Handling Test for Parquet.
=> SPLICE-1254 Fixing Null Handling in Parquet

db-drda/src/main/java/com/splicemachine/db/impl/drda/DDMWriter.java
Removing Stringbuilder issue...  (Hot Spots)
=> SPLICE-1278 Fix StringBuilder Issue In Hot Path

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/IndexConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/index/PopulateIndexJob.java
Lowers the temperature on spark when you are creating an index after creating a table (ITS).
=> SPLICE-1251 Adding Control Side Option to populating indexes

db-engine/src/main/java/com/splicemachine/db/iapi/stats/PrimaryKeyStatisticsImpl.java, db-engine/src/main/java/com/splicemachine/db/iapi/stats/UniqueKeyStatisticsImpl.java
Simple String error during logging.  Using Findbugs...
=> SPLICE-1282 Fixing String Format Error

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinOperation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/BroadcastJoinIT.java
..another attempt to do clean merge and push the changes.
=> SPLICE-1262: fix the wrong answer in broadcastjoin with in-clause

hbase_storage/src/main/java/com/splicemachine/storage/HLock.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetWriter.java, splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
=> SPLICE-1177: Correct failed rows for import

hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/HEngineSqlEnv.java, hbase_sql/src/main/java/com/splicemachine/olap/AsyncOlapNIOLayer.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapStatusHandler.java, hbase_sql/src/test/java/com/splicemachine/olap/OlapClientTest.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SIConfigurations.java
=> SPLICE-1288 Retry a few times when status not available for OLAP job

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java, splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ScanSelectivityIT.java
Handling base predicate selection.  Very specific test case.
=> SPLICE-1294 Poor Costing when first part of PK is not =

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
This is the same change that was checked into the branch-2.0 but for master.
=> SPLICE-1130 - fix null pointer exception when using hints with VTI

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/dvd/LazyChar.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/dvd/LazyClob.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/dvd/LazyDataValueDescriptor.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/dvd/LazyDecimal.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/dvd/LazyDouble.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/dvd/LazyLongVarchar.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/dvd/LazyNumberDataValueDescriptor.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/dvd/LazyStringDataValueDescriptor.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/dvd/LazyTimestamp.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/dvd/LazyVarchar.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinCache.java, splice_machine/src/test/java/com/splicemachine/concurrency/ConcurrentBroadcastJoinIT.java, splice_machine/src/test/test-data/concurrent/script.sql
This caused race conditions when 2 threads tried to deserialize the same
DVD at the same time
The most important part is in LazyDataValueDescriptor.java on the forceDeserialization method.
=> DB-5701 Synchronize deserialization of LazyDVDs

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectivityUtil.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/HalfMergeSortJoinStrategy.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java
Reverts splicemachine/spliceengine#353
=> Revert "SPLICE-1208: fix mergeSortJoin overestimate by 3x"

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java
=> SPLICE-1209: pick up a remote cost per Kb

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
=> SPLICE-1210: remove dup of setRemoteCost

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java
=> SPLICE-1209: pick up a remote cost per Kb 

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectivityUtil.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/HalfMergeSortJoinStrategy.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/JoinSelectionIT.java
already merged-reverted change, just updating an IT after review and tpcds workload sanity run.
=> Splice 1208: fix mergeSortJoin overestimate by 3x

db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLTinyint.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TableScanOperationIT.java
Adding support for TinyInt.  It is already there in the code but was left out of the parser since DB2 once upon a time did not support it.
=> SPLICE-1324 Support Tony Danza or Tiny Dancer or TinyInt

db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java, db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAProtocolException.java, db-shared/src/main/java/com/splicemachine/db/iapi/reference/DRDAConstants.java, splice_machine/pom.xml, splice_machine/src/test/java/com/splicemachine/derby/client/TestUnknownClient.java, splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceNetConnection.java
Already reviewed/reverted change. Sending new pull request for merge. Updated failing IT and squashed all changes in one commits to track.
=> SPLICE-976: do not allow odbc and jdbc requests other than splice driver

assembly/common/src/main/resources/scripts/install-splice-symlinks.sh, assembly/pom.xml, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/OperationConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java, splice_machine/src/main/java/com/splicemachine/EngineDriver.java, splice_machine/src/main/java/com/splicemachine/derby/lifecycle/EngineLifecycleService.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJoinFunction.java
=> SPLICE-1325 branch 2.5

db-engine/src/main/java/com/splicemachine/db/iapi/db/ConsistencyChecker.java, db-engine/src/main/java/com/splicemachine/db/iapi/store/access/ConglomerateController.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DD_Version.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/TabInfoImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/IndexChanger.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/RIBulkChecker.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/RowChangerImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/TemporaryRowHolderImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/TemporaryRowHolderResultSet.java, mem_sql/src/main/resources/log4j.properties, splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchRefresher.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/TemporaryRowHolderImpl.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TemporaryRowHolderOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/PropertyConglomerate.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceController.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/btree/IndexController.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/hbase/HBaseController.java
SPLICE-1290: Again with Daniel's suggestions added.
=> SPLICE-1290 Adding Batch Writes to the dictionary

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/batchonce/BatchOnceOperation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/BatchOnceOperationIT.java
=> SPLICE-1349: serialize and initialize BatchOnceOperation correctly

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectivityUtil.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/HalfMergeSortJoinStrategy.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java, splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/JoinSelectionIT.java
backport from master to 2.5 branch
=> Splice 1208 branch 2.5

splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/OperationConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java, splice_machine/src/main/java/com/splicemachine/EngineDriver.java, splice_machine/src/main/java/com/splicemachine/derby/lifecycle/EngineLifecycleService.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJoinFunction.java
=> SPLICE 1325 : NLJoinFunction creates too many threads

hbase_sql/src/main/java/com/splicemachine/serializer/SpliceKryoSerializerInstance.java, pom.xml
This upgrade will unblock Jebril's work with null ordering.
=> SPLICE-1335 Upgrade to Spark 2.1.0

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeDerbyScanInformation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperatonIT.java
=> SPLICE-1323: add null check for probevalue

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/SpliceCreateTableOperation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/CreateTableWithDataIT.java
=> SPLICE-8: make CTAS work with case sensitive names

hbase_sql/src/main/java/com/splicemachine/stream/QueryJob.java, splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java, splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java, splice_machine/src/main/java/com/splicemachine/derby/serialization/SpliceObserverInstructions.java, splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
=> SPLICE-1329: Memory leak in SpliceObserverInstructions

db-engine/pom.xml
Upgrading to latest stats library...
=> SPLICE-1351 Upgrade Sketching Library from 0.8.1 - 0.8.4

hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java, splice_machine/src/main/java/com/splicemachine/procedures/external/CreateExternalTableJob.java
There is already units tests in ExterlTableIT.
=> SPLICE-1358 : CREATE EXTERNAL TABLE can failed with some specific users in hdfs,

db-drda/src/main/java/com/splicemachine/db/impl/drda/DDMWriter.java
=> SPLICE-1359 SanityManager.DEBUG messages create a lot of noise in derby.log

hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java, splice_machine/src/main/java/com/splicemachine/procedures/external/CreateExternalTableJob.java
=> SPLICE 1358 : backport to 2.5

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java
SPLICE-1355 : Changed syntax for pin / unpin
PIN TABLE [table_name];
UNPIN TABLE [table_name];
=> SPLICE-1355 : Changed syntax for pin / unpin

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java
SPLICE-1355 : Changed syntaxt for pin / unpin
PIN TABLE [table_name];
UNPIN TABLE [table_name];
=> SPLICE-1355 : Changed syntaxt for pin / unpin

db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextManager.java, splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
Synchronize access to internalConnection's contextManager.
=> SPLICE-1362 IndexOOB exceptions loading TPCC data

db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextManager.java, splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
=> SPLICE-1362 synchronize access to internalConnection's contextManager

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java, splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java, splice_machine/src/main/java/com/splicemachine/derby/utils/stats/StatsCollectionJob.java
=> FIX-SPLICE-1169 - backport to 2.5

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
=> DB-5743: fix table number to allow predicate push down

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumn.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/OuterJoinIT.java
=> SPLICE-737: getTableNumber should return -1 if it cannot be determined

splice_machine/src/main/java/com/splicemachine/derby/stream/control/BadRecordsRecorder.java, splice_machine/src/main/java/com/splicemachine/derby/stream/output/PermissiveInsertWriteConfiguration.java, splice_machine/src/main/java/com/splicemachine/derby/stream/output/insert/InsertPipelineWriter.java
Create ThreadLocal decoder and synchronize closes/writes to the log
file.
=> SPLICE-1375 Fix concurrency issues reporting failedRows

db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDescriptorGenerator.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/TableDescriptor.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSTABLESRowFactory.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreatePinConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropTableConstantOperation.java
Some typos fixes for pin tables
=> SPLICE-1406: Some typos fixes for pin tables - trivial

db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDescriptorGenerator.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/TableDescriptor.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSTABLESRowFactory.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreatePinConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropTableConstantOperation.java
Some typos fixes for pin tables
=> SPLICE-1406 backport branch 2.5

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropPinConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
Partially fixed the issue when the table wasn't pined to begin with. This will help to understand the underlying issue that causes the problem by removing one case bug.
=> SPLICE-1285 

splice_machine/src/main/java/com/splicemachine/derby/stream/control/BadRecordsRecorder.java
=> SPLICE-1374: bad file in S3

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, mem_storage/src/main/java/com/splicemachine/storage/MemFileSystem.java, splice_machine/src/main/java/com/splicemachine/derby/impl/load/ImportUtils.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportFile.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportPermissionCheck.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/output/ControlExportDataSetWriter.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportFileTest.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportOperationIT.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportPermissionCheckTest.java, splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIDriver.java
=> SPLICE-1353: export to S3

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectivityUtil.java
=> Splice-1211: open and close latency calculated twice for NLJ

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/NestedLoopJoinOperationIT.java
=> DB-5773 Remove sortedness from NLJ

splice_machine/src/main/java/com/splicemachine/procedures/external/CreateExternalTableJob.java
=> SPLICE-1369: store external table on S3

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropPinConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
Partially fixed the issue when the table wasn't pined to begin with. This will help to understand the underlying issue that causes the problem by removing one case bug.
=> SPLICE-1285 ; please merged - already approved

hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java, splice_machine/src/main/java/com/splicemachine/procedures/external/ExternalTableSystemProcedures.java
Corrected multiples issues:
1) remove 3th arg : CALL SYSCS_UTIL.SYSCS_REFRESH_EXTERNAL_TABLE('APP', 'myTable', rs);
2) check for table not found.
=> SPLICE-1387

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowResultSetNode.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
=> SPLICE-1411: resolve over clause expr when alias from inner query is used in Window fn

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java, splice_machine/src/main/java/com/splicemachine/procedures/external/CreateExternalTableJob.java
- Moved the logic of checking if a file exist outside of the job.
=> SPLICE-1258 branch 2.5

hbase_storage/src/test/java/com/splicemachine/si/testsetup/HBaseSITestEnv.java, mem_storage/src/main/java/com/splicemachine/si/impl/MemTxnStore.java, mem_storage/src/test/java/com/splicemachine/si/MemSITestEnv.java, splice_si_api/src/main/java/com/splicemachine/si/impl/ForwardingTxnView.java, splice_si_api/src/test/java/com/splicemachine/si/SITransactorInMemTest.java
Added IT for in mem sub transactions
=> SPLICE-1436 Fix mem profile after SPLICE-1222

hbase_storage/src/test/java/com/splicemachine/si/testsetup/HBaseSITestEnv.java, mem_storage/src/main/java/com/splicemachine/si/impl/MemTxnStore.java, mem_storage/src/test/java/com/splicemachine/si/MemSITestEnv.java, splice_si_api/src/main/java/com/splicemachine/si/impl/ForwardingTxnView.java, splice_si_api/src/test/java/com/splicemachine/si/SITransactorInMemTest.java
Added IT for in mem sub transactions
Forward port to master
=> SPLICE-1436 Fix mem profile after SPLICE-1222 (master)

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
Fix null pointer when pinning a external table
=> SPLICE-1142:Fix null pointer when pinning a external table

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
Fix null pointer when pinning a external table
=> SPLICE-1142: backport branch 2.5 Fix null pointer when pinning a external table

db-engine/src/main/java/com/splicemachine/db/impl/services/reflect/JarLoader.java, splice_machine/pom.xml, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/catalog/SqlJJarIT.java, sqlj-it-procs/pom.xml, sqlj-it-procs/src/main/java/org/splicetest/sqlj/PropertiesFileVTI.java
=> DB-5471 Allow more packages to be loaded from user code (branch 2.5)

db-engine/src/main/java/com/splicemachine/db/impl/services/reflect/JarLoader.java, splice_machine/pom.xml, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/catalog/SqlJJarIT.java, sqlj-it-procs/pom.xml, sqlj-it-procs/src/main/java/org/splicetest/sqlj/PropertiesFileVTI.java
I've inspected the packages we are allowing to be loaded with this change and couldn't find any obvious attack vectors, but I'm no security expert, please have a look.
=> DB-5471 Allow more packages to be loaded from user code

db-engine/src/main/java/com/splicemachine/db/impl/services/reflect/JarLoader.java, pom.xml, splice_machine/pom.xml, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/catalog/SqlJJarIT.java, sqlj-it-procs/pom.xml, sqlj-it-procs/src/main/java/org/splicetest/sqlj/PropertiesFileVTI.java
Includes fix for broken build on other branches.
=> DB-5471 Allow more packages to be loaded from user code (branch 2.0)

hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HBasePipelineEnvironment.java, hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HBaseSIEnvironment.java, hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java, mem_pipeline/src/main/java/com/splicemachine/pipeline/MPipelineEnv.java, mem_storage/src/main/java/com/splicemachine/si/MemSIEnvironment.java, mem_storage/src/main/java/com/splicemachine/storage/MemFileSystem.java, splice_access_api/src/main/java/com/splicemachine/access/api/DistributedFileSystem.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportFile.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/BadRecordsRecorder.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java, splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIDriver.java, splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIEnvironment.java, splice_si_api/src/test/java/com/splicemachine/si/impl/TestingFileSystem.java
Now it's OK to merge this one when it gets enough +1s.
=> DB-5469 Fix filesystem code (2.0)

hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HBasePipelineEnvironment.java, hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HBaseSIEnvironment.java, hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java, mem_pipeline/src/main/java/com/splicemachine/pipeline/MPipelineEnv.java, mem_storage/src/main/java/com/splicemachine/si/MemSIEnvironment.java, mem_storage/src/main/java/com/splicemachine/storage/MemFileSystem.java, splice_access_api/src/main/java/com/splicemachine/access/api/DistributedFileSystem.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/export/ExportFile.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/BadRecordsRecorder.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java, splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIDriver.java, splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIEnvironment.java, splice_si_api/src/test/java/com/splicemachine/si/impl/TestingFileSystem.java
=> DB-5469 Fix filesystem code (2.5)

hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropPinConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/DropPinJob.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/RemoteDropPinJob.java
Make sure the "unpinning" from spark happens on the OlapServer
Update system table when unpinning
=> SPLICE-1433 Fix unpin feature (branch 2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/TableConstantOperationIT.java
=> SPLICE-835 Mapping TEXT column creation to CLOB

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
Fail if location exists and it's a file
=> SPLICE-1446 Check schema for ext table only if there's data (2.5)

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
Fail if location exists and it's a file
=> SPLICE-1446 Check schema for ext table only if there's data (master)

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_storage/src/main/java/com/splicemachine/si/data/HExceptionFactory.java, splice_machine/src/main/java/com/splicemachine/pipeline/Exceptions.java
Protect against unexpected exceptions during parsing
=>  SPLICE-1461 Add null check on exception parsing (2.0)

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_storage/src/main/java/com/splicemachine/si/data/HExceptionFactory.java, splice_machine/src/main/java/com/splicemachine/pipeline/Exceptions.java
Protect against unexpected exceptions during parsing
=> SPLICE-1461 Add null check on exception parsing (2.5)

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_storage/src/main/java/com/splicemachine/si/data/HExceptionFactory.java, splice_machine/src/main/java/com/splicemachine/pipeline/Exceptions.java
Protect against unexpected exceptions during parsing
=> SPLICE-1461 Add null check on exception parsing (master)

hbase_sql/pom.xml
=> SPLICE-1462 Adding Mesos Scheduling Option to Splice Machine

db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java
This is what is slowing down explain plan generation.
=> SPLICE-1467 Accidental System.out.println inclusion

db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java
This is what is slowing down explain plan generation.
=> SPLICE-1467 Removing System.out.println inclusion

RELEASE-NOTES.md
This is to add RELEASE-NOTES.md under the root directory for 2.5 branch.
=> SPLICE-1447: Add 2.5 release notes

hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/IndexConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
Adding the ability to run stats on Array Types for external tables.  There was a serde issue.
=> SPLICE-1453 Fixing Calculating Stats on Array Types

hbase_sql/src/test/java/com/splicemachine/hbase/RowLockIT.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
=> SPLICE-1469 Set hbase.rowlock.wait.duration to 0 to avoid deadlock

hbase_sql/src/test/java/com/splicemachine/hbase/RowLockIT.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
=> SPLICE-1469 Set hbase.rowlock.wait.duration to 0 to avoid deadlock (2.0)

hbase_sql/src/test/java/com/splicemachine/hbase/RowLockIT.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
=> SPLICE-1469 Set hbase.rowlock.wait.duration to 0 to avoid deadlock (2.5)

splice_machine/src/main/java/com/splicemachine/derby/serialization/SpliceObserverInstructions.java, splice_machine/src/test/java/com/splicemachine/derby/serialization/ActivationSerializerTest.java
Allows for statements to be larger than utf serde bounds.
=> SPLICE-1478 Fixing Statement Limits

db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java, mem_sql/src/main/resources/log4j.properties
Allow N Tree Logging when you want to view trees during their different phases.
=> SPLICE-1480 Allow N Tree Logging

db-engine/src/main/java/com/splicemachine/db/iapi/error/StandardException.java, db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, splice_machine/src/test/java/com/splicemachine/derby/impl/load/ImportErrorIT.java
Add a generic error message to report exception from S3. Removed some duplicates message caused by previous bad merge.
=> SPLICE-1395: add a generic error message for import failure from S3

hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
Make Predicate Pushdown default for ORC.
=> SPLICE-1489 Make Predicate Pushdown defaulted for ORC

db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/InsertDataSetWriter.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java, splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/BadRecordsRecorder.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetWriter.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlOperationContext.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/OperationContext.java
=> SPLICE-1423: clean up import error messages for bad file

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OrderByColumn.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumn.java, splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Table_IT.java
=> SPLICE-77: order by column in subquery not projected should not be resolved

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OrderByColumn.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumn.java, splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Table_IT.java
=> SPLICE-77: order by column in subquery not projected should not be resolved (2.0)

hbase_pipeline/src/main/java/com/splicemachine/pipeline/SnappyPipelineCompressor.java
Workaround for HADOOP-12007
This is missing the pom.xml changes because I couldn't get it to work with my locally installed native libraries.
=> SPLICE-1526 Handle CodecPool manually to avoid leaking memory (2.0)

hbase_pipeline/src/main/java/com/splicemachine/pipeline/SnappyPipelineCompressor.java, hbase_sql/pom.xml
=> SPLICE-1526 Handle CodecPool manually to avoid leaking memory (2.5)

hbase_pipeline/src/main/java/com/splicemachine/pipeline/SnappyPipelineCompressor.java, hbase_sql/pom.xml
=> SPLICE-1526 Handle CodecPool manually to avoid leaking memory (master)

db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/TableDescriptor.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSTABLESRowFactory.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DeleteNode.java, db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java, mem_sql/src/main/java/com/splicemachine/derby/impl/sql/ControlOnlyDataSetProcessorFactory.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreatePinConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropPinConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropTableConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/DistributedIsCachedJob.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/GetIsCachedResult.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/IsCachedJob.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java, splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
-Removed pins from dictionary
-Return a error message if the user try to pin a table already pinned.
-Corrected the error message when the user try to delete a pin.
=> SPLICE-1430 and SPLICE-1487 ( branch 2.5 )

db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/TableDescriptor.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSTABLESRowFactory.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DeleteNode.java, db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java, mem_sql/src/main/java/com/splicemachine/derby/impl/sql/ControlOnlyDataSetProcessorFactory.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreatePinConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropPinConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropTableConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/DistributedIsCachedJob.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/GetIsCachedResult.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/pin/IsCachedJob.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java, splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
-Removed pins from dictionary ( pins are not persistent ) 
-Return a error message if the user try to pin a table already pinned.
-Corrected the error message when the user try to delete a pin.
=> SPLICE-1430 and SPLICE-1487

splice_machine/src/main/java/com/splicemachine/derby/utils/marshall/dvd/AbstractTimeDescriptorSerializer.java
ThreadLocal is made static final - one ThreadLocal object per process.
=> SPLICE-1531 ThreadLocal is used incorrectly in AbstractTimeDescriptorSerializer

splice_machine/src/main/java/com/splicemachine/derby/stream/function/RowAndIndexGenerator.java
Simple fix with noticeable performance improvement.
=> SPLICE-1544 RowAndIndexGenerator is re-initialized on every call

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListOperatorNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNodeList.java, splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/InListMultiprobeIT.java
=> Splice-1533: eliminate duplicates in the IN list (2.0)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListOperatorNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNodeList.java, splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/InListMultiprobeIT.java
=> Splice-1533: eliminate duplicates in the IN list (2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Level2OptimizerTrace.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceLevel2OptimizerImpl.java
modified:   db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Level2OptimizerTrace.java
modified:   db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
modified:   splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceLevel2OptimizerImpl.java
=> SPLICE-1555 Enable optimizer trace info for costing

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Level2OptimizerTrace.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceLevel2OptimizerImpl.java
modified:   db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Level2OptimizerTrace.java
modified:   db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
modified:   splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceLevel2OptimizerImpl.java
=> SPLICE-1555 Enable optimizer trace info for costing - port to 2.0

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListOperatorNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNodeList.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperation.java, splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/InListMultiprobeIT.java
backport to 2.5, already merged in master
=> SPLICE-1541,1543: fix IN-list issues with dynamic bindings and char column (2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListOperatorNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNodeList.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperation.java, splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/InListMultiprobeIT.java
backport to 2.0, already merged in master.
=> SPLICE-1541,1543: fix IN-list issues with dynamic bindings and char column (2.0)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ArrayOperatorNode.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/complextypes/SQLArrayIT.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/ArrayJoinIT.java
Make it work with hashable joins and don't reuse DVDs that get
overwritten
=> SPLICE-1540 Fix ArrayOperatoNode

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIT.java
splice property bulkImportDirectory should be case sensitive.
=> SPLICE-1559: bulkImportDirectory is case sensitive(2.0)

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java, splice_machine/src/main/java/com/splicemachine/derby/impl/storage/TableSplit.java
System procedures to compute split key and split table/index was not checked into master.
=> SPLICE-1482: fix system procedure to split table and index

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromVTI.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TimeTypeCompiler.java, hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/CostChoosingDataSetProcessorFactory.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java, hbase_sql/src/main/java/com/splicemachine/derby/vti/SpliceDatasetVTI.java, pom.xml, splice_spark/README.md, splice_spark/docs/info.txt, splice_spark/pom.xml, splice_spark/src/main/scala/com/splicemachine/spark/splicemachine/DefaultSource.scala, splice_spark/src/main/scala/com/splicemachine/spark/splicemachine/SpliceJDBCUtil.scala, splice_spark/src/main/scala/com/splicemachine/spark/splicemachine/SplicemachineContext.scala, splice_spark/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/SpliceRelation.scala, splice_spark/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/SplicemachineDialect.scala, splice_spark/src/main/spark1/com/splicemachine/spark/package.scala, splice_spark/src/main/spark2/com/splicemachine/spark/package.scala, splice_spark/src/test/resources/log4j.properties, splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceTest.scala, splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/SplicemachineContextTest.scala, splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/TestContext.scala
only implemented for 5.8.3 until I get through Jenkins.
Adds Crud Operations to be run from Spark Command Line or Zeppelin environments.
See DefaultSourceTest for example runs...
Hold on committing this until Monday at the earliest.  I want to watch it go through Jenkins the first time.  :)
=> SPLICE-1568 Core Spark Adapter Functionality with Maven Build

db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/ValueRow.java
Cache hashCode() value for ValueRow. Invalidate on any change to the object. Include in serde.
=> SPLICE-1575 ValueRow.hashCode() value should be cached

hbase_sql/hbase1.0.0.x/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java, hbase_sql/hbase1.0.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java, hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java, hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java, hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java, hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
Make sure coprocessor hooks set and clear flags for flushing and split.
Please also review pull request on ee branch.
=> DB-5912: fix incremental backup hang

db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/BasicPrivilegeInfo.java, db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/GrantRevokeConstantOperation.java, splice_machine/src/test/java/com/splicemachine/derby/security/AuthorizationIT.java, splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
Straightforward, when the user try to do a GRANT on a column, we first check to see which version the user used and return a error message in case of the open source version.
=> SPLICE-865 : Check if enterprise version is activated and if the user  try to use column privileges.

hbase_sql/src/main/java/com/splicemachine/stream/StreamListener.java, hbase_sql/src/test/java/com/splicemachine/stream/StreamableRDDTest_Failures.java
Bail out as soon as we get a Failure message to prevent a NPE
=> SPLICE-1586 Prevent NPE when Spark job fails

db-engine/src/main/java/com/splicemachine/db/iapi/stats/EffectivePartitionStatisticsImpl.java, db-engine/src/main/java/com/splicemachine/db/iapi/stats/PartitionStatisticsImpl.java, db-engine/src/main/java/com/splicemachine/db/iapi/stats/TableStatisticsImpl.java, splice_machine/src/main/java/com/splicemachine/derby/impl/stats/StoreCostControllerImpl.java, splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/StatsUsageIT.java
…re collected and we try to access column stats for estimation.
=> SPLICE-1584 fix IndexOutOfBound exception when not all column stats a…(2.5)

splice_machine/src/main/java/com/splicemachine/derby/stream/function/RowKeyStatisticsFunction.java
=> SPLICE-1605 Remove Extra Packages

hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/PipelineConfiguration.java, splice_spark/pom.xml, splice_spark/src/main/scala/com/splicemachine/spark/splicemachine/SplicemachineContext.scala, splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceTest.scala, splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/TestContext.scala
Taking Jun's work over the finish line.  Added native libs so snappy can be compressed on both sides.
=> SPLICE-1598 Fixing Spark Adapter Code

splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
code clean up for restore
Please also review pull requests from ee branch
=> DB-5920: restore cleanup(2.5)

splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
code clean up for restore
Please also review pull requests from ee branch
=> DB-5920: restore cleanup(2.0)

splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
code clean up for restore
Please also review pull requests from ee branch
=> DB-5920: restore cleanup

db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSSOURCECODERowFactory.java, splice_machine/src/test/java/com/splicemachine/pl/PL_SaveSourceCode_IT.java, splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Create_IT.java, splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Dependency_IT.java, splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Exec_Stored_Proc_IT.java, splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Row_IT.java, splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Row_Transition_IT.java, splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Statement_IT.java
Left out an important commit during rebase for PR#652.
Also, PR#652 asked to have "create=true;" removed from IT JDBC URL, which was copied from Trigger_*_IT.java files, so I updated those as well.  https://github.com/splicemachine/spliceengine/pull/652#discussion_r113553243
=> SPLICE-1600: Fix SYSSOURCECODE integration test

splice_si_api/src/main/java/com/splicemachine/si/impl/TxnUtils.java
Use the lowest significant bits.
=> SPLICE-1589 All transactions are processed by pre-created region 0

hbase_storage/src/main/java/com/splicemachine/storage/HGet.java, mem_storage/src/main/java/com/splicemachine/storage/MGet.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/OperationConfiguration.java, splice_access_api/src/main/java/com/splicemachine/storage/DataGet.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/sequence/SpliceSequence.java
Increase default allocation size for sequences
=> SPLICE-1622 Return only latest version for sequences

splice_machine/src/main/java/com/splicemachine/derby/stream/function/AbstractFileFunction.java
Port fix contributed by Brandon with minor correction.
=> SPLICE-1023 add more info in the message for data import error

splice_machine/src/main/java/com/splicemachine/derby/utils/Vacuum.java
Increase logging level if needed with
CALL SYSCS_UTIL.SYSCS_SET_LOGGER_LEVEL (
'com.splicemachine.derby.utils.Vacuum', 'TRACE');
=> DB-5933 Add logging to Vacuum process (2.5)

splice_machine/src/main/java/com/splicemachine/derby/utils/Vacuum.java
Increase logging level if needed with
CALL SYSCS_UTIL.SYSCS_SET_LOGGER_LEVEL (
'com.splicemachine.derby.utils.Vacuum', 'TRACE');
=> DB-5933 Add logging to Vacuum process

hbase_sql/src/main/java/com/splicemachine/stream/KryoDecoder.java, hbase_sql/src/main/java/com/splicemachine/stream/KryoEncoder.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/CallStatementOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/NoRowsOperation.java, splice_machine/src/main/java/com/splicemachine/derby/serialization/ActivationSerializer.java, splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java, splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsOperation.java
=> SPLICE-1479 Make stats run on the OlapServer (2.5)

db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CostEstimate.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Optimizable.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Optimizer.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CostEstimateImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/IndexToBaseRowNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SingleChildResultSetNode.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SimpleCostEstimate.java, splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/BroadcastJoinMemoryLimitIT.java
=> SPLICE-1640 apply memory limit check for consecutive outer broadcast …(2.5)

hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/LazyPartitionServer.java, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/RangedClientPartition.java, hbase_storage/src/main/java/com/splicemachine/access/hbase/HServer.java, hbase_storage/src/main/java/com/splicemachine/storage/RegionPartition.java
=> SPLICE-1443 Skip cutpoint that create empty partitions (2.5)

hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/LazyPartitionServer.java, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/RangedClientPartition.java, hbase_storage/src/main/java/com/splicemachine/access/hbase/HServer.java, hbase_storage/src/main/java/com/splicemachine/storage/RegionPartition.java
=> SPLICE-1443 Skip cutpoint that create empty partitions

db-client/src/main/java/com/splicemachine/db/client/am/Agent.java, db-client/src/main/java/com/splicemachine/db/client/am/CrossConverters.java, db-client/src/main/java/com/splicemachine/db/client/am/Cursor.java, db-client/src/main/java/com/splicemachine/db/client/am/Decimal.java, db-client/src/main/java/com/splicemachine/db/client/am/FloatingPoint.java, db-client/src/main/java/com/splicemachine/db/client/am/ResultSet.java, db-client/src/main/java/com/splicemachine/db/client/net/Reply.java, db-client/src/main/java/com/splicemachine/db/client/net/Request.java
Deleted instances of 'final' in db-client where there were redundant 'final' and 'private' statements.
=> SPLICE-1666 Cleanup redundant private final

db-client/src/main/java/com/splicemachine/db/client/am/LogicalConnection.java, db-client/src/main/java/com/splicemachine/db/client/am/stmtcache/StatementKeyFactory.java, db-client/src/main/java/com/splicemachine/db/client/net/NetConnectionReply.java
Removed a few unnecessary semicolons.
=> SPLICE-1667 Removing unnecessary semicolons

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
backports on 2.5 branch for external table stats collection issues.
=> SPLICE-1425, DB-5823 backports

hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/LazyPartitionServer.java, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/RangedClientPartition.java, hbase_storage/src/main/java/com/splicemachine/access/hbase/HServer.java, hbase_storage/src/main/java/com/splicemachine/storage/RegionPartition.java
Backport to 2.0, hadn't seen this error in 2.0 when I fixed it for the other branches
=> SPLICE-1443 Skip cutpoint that create empty partitions (2.0)

splice_machine/src/main/java/com/splicemachine/derby/stream/function/StatisticsFlatMapFunction.java, splice_machine/src/test/java/com/splicemachine/derby/utils/StatisticsAdminIT.java
…tion in the presence of empty partition and some column stats disabled
=> SPLICE-1684 fix stats collection logic for ArrayIndexOutOfBoundsExcep…(2.5)

db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/PartitionStatisticsDescriptor.java, db-engine/src/main/java/com/splicemachine/db/iapi/stats/EffectivePartitionStatisticsImpl.java, db-engine/src/main/java/com/splicemachine/db/iapi/stats/FakePartitionStatisticsImpl.java, db-engine/src/main/java/com/splicemachine/db/iapi/stats/PartitionStatistics.java, db-engine/src/main/java/com/splicemachine/db/iapi/stats/PartitionStatisticsImpl.java, db-engine/src/main/java/com/splicemachine/db/iapi/stats/TableStatisticsImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSTABLESTATISTICSRowFactory.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java, splice_machine/src/main/java/com/splicemachine/derby/impl/stats/StoreCostControllerImpl.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/StatisticsFlatMapFunction.java, splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java, splice_machine/src/test/java/com/splicemachine/derby/utils/StatisticsAdminIT.java
, and add upgrade logic for the system view systablestatistics definition change
=> SPLICE-1675 merge partition stats at the stats collection time (master)

hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSparkKryoRegistrator.java, splice_machine/src/main/java/com/splicemachine/SpliceKryoRegistry.java
Add ScanOperation and SplcieBaseOperation to Kryo
=> SPLICE-1696 Add ScanOperation and SplcieBaseOperation to Kryo

db-client/src/main/java/com/splicemachine/db/client/am/ResultSet.java, db-client/src/main/java/com/splicemachine/db/client/am/Statement.java, db-client/src/main/java/com/splicemachine/db/client/net/NetConnection.java, db-drda/src/main/java/com/splicemachine/db/impl/drda/NetworkServerControlImpl.java, db-drda/src/main/java/com/splicemachine/db/impl/tools/sysinfo/Main.java, db-engine/src/main/java/com/splicemachine/db/iapi/util/IdUtil.java, db-engine/src/main/java/com/splicemachine/db/impl/ast/RepeatedPredicateVisitor.java, db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedClob.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CreateAliasNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/MethodCallNode.java, db-engine/src/main/java/com/splicemachine/db/jdbc/EmbedPooledConnection.java, db-tools-ij/src/main/java/com/splicemachine/db/tools/dblook.java, db-tools-testing/src/main/java/com/splicemachine/dbTesting/functionTests/harness/RunList.java, db-tools-testing/src/main/java/com/splicemachine/dbTesting/functionTests/harness/RunTest.java, db-tools-testing/src/main/java/com/splicemachine/dbTesting/functionTests/harness/Sed.java, db-tools-testing/src/main/java/com/splicemachine/dbTesting/junit/DerbyDistribution.java, hbase_sql/src/main/java/com/splicemachine/derby/impl/io/HdfsDirFile.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/SpliceTableMapReduceUtil.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMSQLUtil.java, splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
Replace double quotes with isEmpty
=> SPLICE-1704 Replace double quotes with isEmpty

db-build/src/main/java/com/splicemachine/derbyBuild/propertyconfig.java, db-client/src/main/java/com/splicemachine/db/client/am/Clob.java, db-client/src/main/java/com/splicemachine/db/client/am/ClobOutputStream.java, db-client/src/main/java/com/splicemachine/db/client/am/DatabaseMetaData.java, db-client/src/main/java/com/splicemachine/db/jdbc/ClientBaseDataSource.java, db-drda/src/main/java/com/splicemachine/db/impl/tools/sysinfo/Main.java, db-engine/src/main/java/com/splicemachine/db/iapi/services/i18n/MessageService.java, db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLChar.java, db-engine/src/main/java/com/splicemachine/db/impl/io/BaseStorageFactory.java, db-engine/src/main/java/com/splicemachine/db/impl/jdbc/authentication/BasicAuthenticationServiceImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/services/bytecode/BCClass.java, db-engine/src/main/java/com/splicemachine/db/impl/services/bytecode/BCMethod.java, db-engine/src/main/java/com/splicemachine/db/impl/services/jce/JCECipherFactory.java, db-engine/src/main/java/com/splicemachine/db/impl/services/monitor/BaseMonitor.java, db-engine/src/main/java/com/splicemachine/db/impl/services/monitor/StorageFactoryService.java, db-engine/src/main/java/com/splicemachine/db/impl/services/reflect/DatabaseClasses.java, db-engine/src/main/java/com/splicemachine/db/impl/services/reflect/UpdateLoader.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DropAliasNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DropSequenceNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ExpressionClassBuilder.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/StaticMethodCallNode.java, db-engine/src/main/java/com/splicemachine/db/jdbc/ReferenceableDataSource.java, db-tools-testing/src/main/java/com/splicemachine/dbTesting/functionTests/util/SimpleProcedureTest.java, db-tools-testing/src/main/java/com/splicemachine/dbTesting/junit/SpawnedProcess.java, db-tools-testing/src/main/java/com/splicemachine/dbTesting/junit/SupportFilesSetup.java, db-tools-testing/src/main/java/com/splicemachine/dbTesting/junit/TestConfiguration.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceBaseFileResource.java, splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceStringFunctions.java, utilities/src/main/java/com/splicemachine/utils/StringUtils.java
=> SPLICE-1711 Replace concat with +

hbase_sql/src/main/java/com/splicemachine/orc/block/ColumnBlock.java
Unnecessary interface modifier
=> SPLICE-1713 Unnecessary interface modifier

db-engine/src/main/java/com/splicemachine/db/impl/services/jmx/JMXManagementService.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/BulkInsertDataSetWriter.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/RowKeyStatisticsFunction.java
Do not use KeySet where entryset will work (Performance)
=> SPLICE-1708 Do not use KeySet where entryset will work

db-engine/src/main/java/com/splicemachine/db/iapi/services/io/StoredFormatIds.java, hbase_sql/src/main/java/com/splicemachine/derby/utils/ZkUpgradeK2.java, hbase_sql/src/main/resources/META-INF/services/com.splicemachine.derby.utils.UpgradeK2, splice_access_api/src/main/java/com/splicemachine/access/api/DatabaseVersion.java, splice_access_api/src/main/java/com/splicemachine/tools/version/SimpleDatabaseVersion.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/Splice_DD_Version.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/ConglomeratesUpgradeScript.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceConglomerate.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/btree/IndexConglomerate.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/hbase/HBaseConglomerate.java, splice_machine/src/main/java/com/splicemachine/derby/utils/ConglomerateUtils.java, splice_machine/src/main/java/com/splicemachine/derby/utils/UpgradeK2.java
Upgrade SPLICE_CONGLOMERATES table, mark 2.0 version in ZK
=> SPLICE-774 Support upgrade to Janus (2.0)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumn.java, hbase_sql/src/main/java/com/splicemachine/orc/stream/OrcInputStream.java, hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, splice_machine/src/main/java/com/splicemachine/derby/serialization/ActivationSerializer.java, splice_si_api/src/main/java/com/splicemachine/si/impl/txn/AbstractTxn.java
Remove Tail Recursion in Hot Paths.
=> SPLICE-1707 Fix Tail Recursion Issues

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConditionalNode.java, db-testing/src/test/java/com/splicemachine/dbTesting/functionTests/tests/jdbc4/VerifySignatures.java, hbase_storage/src/test/java/com/splicemachine/access/client/MemstoreKeyValueScannerTest.java, splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyChildInterceptWriteHandler.java
=> SPLICE-1719 Bulk Operation vs. iteration

pipeline_api/src/main/java/com/splicemachine/pipeline/api/Constraint.java, pipeline_api/src/main/java/com/splicemachine/pipeline/constraint/UniqueConstraint.java, pipeline_api/src/main/java/com/splicemachine/pipeline/constraint/UniqueConstraintChecker.java, pipeline_api/src/main/java/com/splicemachine/pipeline/writehandler/ConstraintWriteHandler.java
=> DB-6008: suppress false constraint violation during retry(2.0)

hbase_sql/src/main/java/com/splicemachine/hbase/SpliceMasterObserver.java, hbase_storage/src/main/java/com/splicemachine/si/data/hbase/ZkUpgradeK2.java, hbase_storage/src/main/java/com/splicemachine/si/impl/CoprocessorTxnStore.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java, splice_si_api/src/main/java/com/splicemachine/si/api/txn/TxnStore.java, splice_si_api/src/test/java/com/splicemachine/si/impl/store/TestingTxnStore.java
=> SPLICE-774 Upgrade from 2.0: wait for master to clear upgrade znode

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DropViewNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropViewIT.java
Implements 'if exists' when dropping a view.
=> SPLICE-398 Support 'drop view if exists'

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, splice_machine/src/test/java/com/splicemachine/derby/impl/load/ImportErrorIT.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropTableIT.java
splice-1729 was merged to master already.
=> SPLICE-1729-2.5 Support 'drop table t_name if exists' for 2.5

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DropViewNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropViewIT.java
splice-398 was already merged into master
=> SPLICE-398-2.5 Support 'drop view if exists' for 2.5

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/GenericAggregateOperation.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/MergeAllAggregatesFlatMapFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/ScalarAggregateFlatMapFunction.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ScalarAggregateOperationIT.java
=> SPLICE-1601 fix wrong result for min/max/sum on empty table without g…(2.0)

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/GenericAggregateOperation.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/MergeAllAggregatesFlatMapFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/ScalarAggregateFlatMapFunction.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ScalarAggregateOperationIT.java
=> SPLICE-1601 fix wrong result for min/max/sum on empty table without g…(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BaseTypeCompiler.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperationIT.java
Varchar to Int type supported, Int to varchar not supported: Tests created and @ignored
=> SPLICE-1733 Support Type Conversion

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/GroupByNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java, hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSparkKryoRegistrator.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkPairDataSet.java, hbase_sql/src/test/java/com/splicemachine/hbase/DistinctAggregateOverMultiplePartitionsIT.java, splice_machine/src/main/java/com/splicemachine/SpliceKryoRegistry.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DistinctScalarAggregateOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/GenericAggregateOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/GroupedAggregateOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/framework/SpliceGenericAggregator.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/DistinctAggregateKeyCreation.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/DistinctAggregatesPrepareFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/MergeAllAggregatesFunctionForMixedRows.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/MergeNonDistinctAggregatesFunctionForMixedRows.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/StitchMixedRowFlatMapFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/StitchMixedRowFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/OperationContext.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DistinctGroupedAggregateOperationIT.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/MultipleDistinctAggregatesIT.java
Please refer to comment SPLICE-1512 for explanation of the implementation.
=> SPLICE-1512 Multiple distinct aggregates

splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnFilter.java
Backport to 2.5
* SPLICE-1692 Perform (anti)tombstone txn resolution only when needed
* SPLICE-1692 Simplify (anti)tombstones handling
=> SPLICE-1692 Perform (anti)tombstone txn resolution only when needed (2.5)

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainOperation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
=> Splice-1438: Fix the explain plan issue (2.5)

splice_machine/src/main/java/com/splicemachine/derby/utils/Vacuum.java
=> SPLICE-1744 Removing Dictionary Check

hbase_pipeline/src/main/java/com/splicemachine/pipeline/InitializationCompleted.java, hbase_sql/src/main/java/com/splicemachine/hbase/SpliceMasterObserver.java, hbase_sql/src/main/java/com/splicemachine/lifecycle/RegionServerLifecycle.java, splice_machine/src/main/java/com/splicemachine/EngineDriver.java, splice_machine/src/main/java/com/splicemachine/derby/lifecycle/NetworkLifecycleService.java
- Created a separate exception to signal successful initialization
- Properly handle more exceptions that should make us continue trying to create the init table
- Added null checks for failures during the boot process
=> SPLICE-1769 Improve distributed boot process

splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
Saw this when debugging another issue, these should be in the suite according to the bug statuses.
=> DB-3927 Uncommenting out Tests That Have Been Fixed

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/BroadcastJoinIT.java
=> DB-6068 fix wrong result for broadcast with implicit cast from int to…(2.5)

splice_machine/src/main/java/com/splicemachine/EngineDriver.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/IndexRowReader.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/IndexRowReaderBuilder.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
Unifies Thread Pool Execution.
=> SPLICE-1773 Unifying the thread pools

hbase_sql/pom.xml
=> SPLICE-930 Parallel 4 ITS, ran successfully on 5.8.3 in 40% less time

splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/BroadcastJoinMemoryLimitIT.java
=> SPLICE-1792 BroadcastJoinMemoryLimitIT must be executed serially

splice_machine/src/test/java/com/splicemachine/derby/security/AuthorizationIT.java
=> Splice 1791 v2.5 again

splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/BroadcastJoinMemoryLimitIT.java
Getting IT's to support parallel execution.
=> Splice 1792 v2.5 again

db-engine/src/main/java/com/splicemachine/db/catalog/types/TypeDescriptorImpl.java, db-engine/src/main/java/com/splicemachine/db/iapi/services/io/StoredFormatIds.java, hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java, hbase_sql/src/main/java/com/splicemachine/hbase/RegionServerLifecycleObserver.java, hbase_storage/src/main/java/com/splicemachine/si/data/hbase/ZkUpgrade.java, hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/TxnLifecycleEndpoint.java, hbase_storage/src/main/java/com/splicemachine/si/impl/CoprocessorTxnStore.java, hbase_storage/src/main/java/com/splicemachine/si/impl/region/RegionTxnStore.java, hbase_storage/src/main/java/com/splicemachine/si/impl/region/TxnDecoder.java, hbase_storage/src/main/java/com/splicemachine/si/impl/region/V2TxnDecoder.java, mem_storage/src/main/java/com/splicemachine/si/impl/MemTxnStore.java, splice_access_api/src/main/java/com/splicemachine/access/api/DatabaseVersion.java, splice_access_api/src/main/java/com/splicemachine/tools/version/SimpleDatabaseVersion.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/Splice_DD_Version.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptBase.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptFor260.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/btree/IndexConglomerate.java, splice_protocol/src/main/protobuf/Txn.proto, splice_si_api/src/main/java/com/splicemachine/si/api/txn/TxnStore.java, splice_si_api/src/main/java/com/splicemachine/si/api/txn/lifecycle/TxnLifecycleStore.java, splice_si_api/src/main/java/com/splicemachine/si/api/txn/lifecycle/TxnPartition.java, splice_si_api/src/main/java/com/splicemachine/si/impl/TxnUtils.java, splice_si_api/src/main/java/com/splicemachine/si/impl/data/StripedTxnLifecycleStore.java, splice_si_api/src/test/java/com/splicemachine/si/impl/store/TestingTxnStore.java
Merge into master to support upgrade from 2.5 to future release(2.6.1)
=> Splice-1578: upgrade from 2.5 to 2.6

db-engine/src/main/java/com/splicemachine/db/catalog/types/TypeDescriptorImpl.java, db-engine/src/main/java/com/splicemachine/db/iapi/services/io/StoredFormatIds.java, hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java, hbase_sql/src/main/java/com/splicemachine/hbase/RegionServerLifecycleObserver.java, hbase_storage/src/main/java/com/splicemachine/si/data/hbase/ZkUpgrade.java, hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/TxnLifecycleEndpoint.java, hbase_storage/src/main/java/com/splicemachine/si/impl/CoprocessorTxnStore.java, hbase_storage/src/main/java/com/splicemachine/si/impl/region/RegionTxnStore.java, hbase_storage/src/main/java/com/splicemachine/si/impl/region/TxnDecoder.java, hbase_storage/src/main/java/com/splicemachine/si/impl/region/V2TxnDecoder.java, mem_storage/src/main/java/com/splicemachine/si/impl/MemTxnStore.java, splice_access_api/src/main/java/com/splicemachine/access/api/DatabaseVersion.java, splice_access_api/src/main/java/com/splicemachine/tools/version/SimpleDatabaseVersion.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/Splice_DD_Version.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptBase.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptFor260.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/btree/IndexConglomerate.java, splice_protocol/src/main/protobuf/Txn.proto, splice_si_api/src/main/java/com/splicemachine/si/api/txn/TxnStore.java, splice_si_api/src/main/java/com/splicemachine/si/api/txn/lifecycle/TxnLifecycleStore.java, splice_si_api/src/main/java/com/splicemachine/si/api/txn/lifecycle/TxnPartition.java, splice_si_api/src/main/java/com/splicemachine/si/impl/TxnUtils.java, splice_si_api/src/main/java/com/splicemachine/si/impl/data/StripedTxnLifecycleStore.java, splice_si_api/src/test/java/com/splicemachine/si/impl/store/TestingTxnStore.java
Please refer to https://splice.atlassian.net/browse/SPLICE-1578
=> Splice-1578 Upgrade from 2.5 to 2.6

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_sql/hbase1.0.0.x/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java, hbase_sql/hbase1.1.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java, hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java, hbase_sql/hbase1.1.2/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java, hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java, hbase_sql/src/main/java/com/splicemachine/hbase/BackupBaseRegionObserver.java, hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java, hbase_sql/src/main/java/com/splicemachine/hbase/SpliceHFileCleaner.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java, hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionState.java, splice_machine/src/main/java/com/splicemachine/backup/BackupRestoreConstants.java, splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnFilter.java
=> DB-5934: restore a chain of backup(2.6)

db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java, splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java, splice_machine/src/test/java/com/splicemachine/derby/utils/StatisticsAdminIT.java
…ify the collect stats behavior
=> SPLICE-1756 introduce database property collectIndexStatsOnly to spec…(master)

db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java, splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java, splice_machine/src/test/java/com/splicemachine/derby/utils/StatisticsAdminIT.java
…ify the collect stats behavior
=> SPLICE-1756 introduce database property collectIndexStatsOnly to spec…(2.6)

db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java, splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java, splice_machine/src/test/java/com/splicemachine/derby/utils/StatisticsAdminIT.java
…ify the collect stats behavior
Please see details about the usage of this new database property in [SPLICE-1756](https://splice.atlassian.net/browse/SPLICE-1756).
=> SPLICE-1756 introduce database property collectIndexStatsOnly to spec…(2.5)

splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
…r for analyze table statement.
=> SPLICE-1737 fix value outside the range of the data type INTEGER erro…(2.5)

hbase_sql/src/main/java/com/splicemachine/hbase/BytesCopyTaskSplitter.java, hbase_sql/src/main/java/com/splicemachine/hbase/RegionSizeEndpoint.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java, hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java, splice_protocol/src/main/protobuf/Splice.proto
The prior commit would consistently fail on TPCH1.  This attempt uses the batch coprocessor service and is a bit higher level.  I had 3 successful TPCH1 runs...
=> SPLICE-1784 Trying to do cutpoints again

splice_machine/src/main/java/com/splicemachine/derby/stream/function/OffsetFunction.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/RowCountOperationIT.java
This has already been merged in master.
=> DB-6106 Fix limit on multiple partitions on Spark (2.6)

splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsAdmin.java
…r for analyze table statement.
=> SPLICE-1737 fix value outside the range of the data type INTEGER erro…(2.6)

hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
HBase Kerberos principal is in the format of user/_HOST@realm, where _HOST will be replaced with local host name by HBase. However, this does not work for Yarn application master when it renews a Kerberos credential, because it does not replace _HOST with host name.
=> DB-6057: replace _HOST with host name (2.5)

hbase_sql/src/main/java/com/splicemachine/orc/reader/ShortDictionaryStreamReader.java, hbase_sql/src/main/java/com/splicemachine/orc/reader/ShortDirectStreamReader.java, hbase_sql/src/main/java/com/splicemachine/orc/reader/ShortStreamReader.java, hbase_sql/src/main/java/com/splicemachine/orc/reader/StreamReaders.java, hbase_sql/src/main/java/com/splicemachine/orc/stream/LongStream.java, hbase_sql/src/main/java/com/splicemachine/orc/stream/LongStreamDwrf.java, hbase_sql/src/main/java/com/splicemachine/orc/stream/LongStreamV1.java, hbase_sql/src/main/java/com/splicemachine/orc/stream/LongStreamV2.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
Introduce a ShortStreamReader to handle the SHORT data type. Please see [SPLICE-1824](https://splice.atlassian.net/browse/SPLICE-1824) for details.
=> SPLICE-1824 NullPointer when collecting stats on ORC table

hbase_sql/src/main/java/com/splicemachine/olap/AbstractOlapHandler.java, hbase_sql/src/main/java/com/splicemachine/olap/AsyncOlapNIOLayer.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapCancelHandler.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapJobStatus.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapPipelineFactory.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapRequestHandler.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapServer.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapStatusHandler.java, hbase_sql/src/test/java/com/splicemachine/olap/OlapClientTest.java, mem_sql/src/main/java/com/splicemachine/derby/impl/sql/LocalOlapClient.java, splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/olap/OlapStatus.java, splice_protocol/src/main/protobuf/Olap.proto
This got merged into master and reverted due to a compilation failure in the mem profile.
This is the fixed mem profile build on jenkins: http://206.225.8.98:8080/job/spliceengine-branch/job/spliceengine-branch/352/
cdh5.8.3: http://206.225.8.98:8080/job/spliceengine-branch/job/spliceengine-branch/353/
=> SPLICE-1716 Reduce Olap job latency for short tasks

hbase_sql/src/main/java/com/splicemachine/orc/input/ColumnarBatchRow.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
Please see [SPLICE-1825](https://splice.atlassian.net/browse/SPLICE-1825) for analysis of the problem.
=> SPLICE-1825 fix wrong result with Date type for ORC table

hbase_sql/pom.xml, hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/HEngineSqlEnv.java, hbase_sql/src/main/java/com/splicemachine/hbase/SpliceMasterObserver.java, hbase_sql/src/main/java/com/splicemachine/olap/AsyncOlapNIOLayer.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapServerProvider.java, hbase_sql/src/test/java/com/splicemachine/olap/OlapClientTest.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java
Boot up all HMasters (active or backup) one at a time, so that they
don't step in each other's work
=> DB-5974 Reconnect to OlapServer in case of failure (2.6)

hbase_sql/pom.xml, hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/HEngineSqlEnv.java, hbase_sql/src/main/java/com/splicemachine/hbase/SpliceMasterObserver.java, hbase_sql/src/main/java/com/splicemachine/olap/AsyncOlapNIOLayer.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapServerProvider.java, hbase_sql/src/test/java/com/splicemachine/olap/OlapClientTest.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java
Boot up all HMasters (active or backup) one at a time, so that they
don't step in each other's work
=> DB-5974 Reconnect to OlapServer in case of failure (2.5)

db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/BaseDataDictionary.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/FunctionIT.java
beginning round to chosen decimal place function
=> SPLICE-949 add ROUND(double) and ROUND(double,int) functions

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/utils/AvroUtils.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/LocatedRowToRowAvroFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/RowToLocatedRowAvroFunction.java
support date type for avro external tables by converting it to a string type
=> SPLICE-1747 Support date type for avro tables

splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
Please also review code changes on ee branch
=> DB-6127: fix delete_old_backups

splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
Please also review code changes on ee branch
=> DB-6127: fix delete_old_backups(2.6)

hbase_sql/src/main/java/com/splicemachine/orc/OrcRecordReader.java, hbase_sql/src/main/java/com/splicemachine/orc/block/DateColumnBlock.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTablePartitionIT.java
… predicate,
also add logic to support selection from Date partition column
=> SPLICE-1853 fix wrong result with query to partitioned ORC table with…(2.6)

db-engine/src/main/java/com/splicemachine/db/iapi/stats/ColumnStatisticsMerge.java, hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSparkKryoRegistrator.java, hbase_sql/src/main/java/com/splicemachine/stream/ResultStreamer.java, hbase_sql/src/main/java/com/splicemachine/stream/StreamProtocol.java, splice_machine/src/main/java/com/splicemachine/SpliceKryoRegistry.java
Small Tweek for new pieces that were not registered with Kryo.
=> SPLICE-1845 Tweek Kryo Serde for Missing Elements

db-engine/src/main/java/com/splicemachine/db/iapi/types/DataType.java, hbase_sql/src/main/java/com/splicemachine/orc/metadata/DateStatistics.java, hbase_sql/src/main/java/com/splicemachine/orc/predicate/SpliceORCPredicate.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
also, add missing logic in partition pruning for smallint as partition column
=> SPLICE-1854 fix wrong result with ORC table and predicate on Date column

db-engine/src/main/java/com/splicemachine/db/iapi/types/DataType.java, hbase_sql/src/main/java/com/splicemachine/orc/metadata/DateStatistics.java, hbase_sql/src/main/java/com/splicemachine/orc/predicate/SpliceORCPredicate.java, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
also, add missing logic in partition pruning for smallint as partition column
=> SPLICE-1854 fix wrong result with ORC table and predicate on Date column(2.6)

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
=> DB-6167 fix maximum version to trigger the 2.0 to 2.5 upgrade script …(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/IndexColumnOrder.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkUtils.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/DerbyWindowContext.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregator.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregatorImpl.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowContext.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/ColumnComparator.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/MergeWindowFunction.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/OrderByIT.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
…or Window function.
More details are in [DB-6164](https://splicemachine.atlassian.net/browse/DB-6164).
=> DB-6164 honor Null ordering specification in Spark and Control path f…(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/IndexColumnOrder.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkUtils.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/DerbyWindowContext.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregator.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregatorImpl.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowContext.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/ColumnComparator.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/MergeWindowFunction.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/OrderByIT.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
=> DB-6164 honor Null ordering specification in Spark and Control path f…(2.6)

db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/TabInfoImpl.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceScan.java, splice_machine/src/main/java/com/splicemachine/derby/utils/marshall/EntryDataDecoder.java
=> SPLICE-1867 honor scan column list to avoid decoding column with seri…(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/TabInfoImpl.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceScan.java, splice_machine/src/main/java/com/splicemachine/derby/utils/marshall/EntryDataDecoder.java
=> SPLICE-1867 honor scan column list to avoid decoding column with seri…(2.6)

db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/IndexColumnOrder.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkUtils.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/DerbyWindowContext.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregator.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowAggregatorImpl.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/WindowContext.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/ColumnComparator.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/MergeWindowFunction.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/OrderByIT.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
…Spark and Control path for Window function
by reverting commit 758ac78deb592ac5bcba77377337fd3c8bfbe923.
=> DB-6164 re-apply DB-6164's fix: honor Null ordering specification in …(master)

hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/CostChoosingDataSetProcessorFactory.java, hbase_sql/src/main/java/com/splicemachine/stream/QueryJob.java, hbase_sql/src/main/java/com/splicemachine/stream/RemoteQueryClientImpl.java, hbase_sql/src/main/java/com/splicemachine/stream/RemoteQueryJob.java, hbase_sql/src/main/java/com/splicemachine/stream/StreamListenerServer.java, splice_access_api/src/main/java/com/splicemachine/access/util/NetworkUtils.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java, splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java, splice_machine/src/main/java/com/splicemachine/management/DatabaseAdministrator.java, splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java, splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdmin_OperationsIT.java
Added stored procedure to get session info and attached session info to Spark job id.
=> SPLICE-1760 Correlate Spark job id with user session

db-engine/src/main/java/com/splicemachine/db/iapi/types/DataTypeDescriptor.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UnionOperationIT.java
=> DB-6134 change resultant datatype to varchar if union of char types w…(2.5)

db-engine/src/main/java/com/splicemachine/db/iapi/types/DataTypeDescriptor.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UnionOperationIT.java
=> DB-6134 change resultant datatype to varchar if union of char types w…(2.6)

db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CostEstimate.java, db-engine/src/main/java/com/splicemachine/db/impl/ast/LimitOffsetVisitor.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CostEstimateImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SimpleCostEstimate.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
…sing predicate against key value.
=> SPLICE-1874 determine Spark path based on output row count computed u…(2.6)

db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CostEstimate.java, db-engine/src/main/java/com/splicemachine/db/impl/ast/LimitOffsetVisitor.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CostEstimateImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SimpleCostEstimate.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
…sing predicate against key value.
=> SPLICE-1874 determine Spark path based on output row count computed u…(2.5)

hbase_sql/src/main/java/com/splicemachine/hbase/BytesCopyTaskSplitter.java, hbase_sql/src/main/java/com/splicemachine/hbase/RegionSizeEndpoint.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/AbstractSMInputFormat.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java, hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java, splice_protocol/src/main/protobuf/Splice.proto
=> Splice 1784: Query does not scale on 4000 regions (2.6)

hbase_sql/src/main/java/com/splicemachine/hbase/BytesCopyTaskSplitter.java, hbase_sql/src/main/java/com/splicemachine/hbase/RegionSizeEndpoint.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/AbstractSMInputFormat.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java, hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java, splice_protocol/src/main/protobuf/Splice.proto
Merged to master, backport to 2.5
=> Splice 1784: Query does not scale on 4000 regions (2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ActivationClassBuilder.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
=> DB-6203 honor Spark dataset processor once picked, and fix regression…(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ActivationClassBuilder.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
=> DB-6203 honor Spark dataset processor once picked, and fix regression…(2.6)

hbase_sql/pom.xml
Add sparkHistory profile that launches a History server pointing to
hbase_sql/target/SpliceTestYarnPlatform
=> DB-6228 Enable Spark event log to debug jenkins runs

splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
Please review ee branch for more changes
=> DB-6230: run restore asynchronously

assembly/pom.xml
Similar change was done for 2.0 for certification
=> Db 6042-exclude restart and flatten scripts (2.5)

hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java, hbase_sql/src/main/resources/info-log4j.properties, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.2.0_cdh5.12/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
Raise exception if scanner is closed
=> DB-6228 Add logs around task failure in Spark

hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java, hbase_sql/src/main/resources/info-log4j.properties, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.2.0_cdh5.12/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
Raise exception if scanner is closed
=> DB-6228 Add logs around task failure in Spark (2.6)

hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java, hbase_sql/src/main/resources/info-log4j.properties, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
Raise exception if scanner is closed
=> DB-6228 Add logs around task failure in Spark (2.5)

mem_sql/src/main/java/com/splicemachine/derby/impl/sql/NoOpBackupManager.java, splice_machine/src/main/java/com/splicemachine/backup/BackupManager.java, splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- Make syscs_backup/restore_database synchronous.
- Asynchronous backup/restore renamed to syscs_backup/restore_database_async.
=> DB-6252: add back synchronous backup/restore

splice_machine/src/main/java/com/splicemachine/backup/BackupManager.java, splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- Make syscs_backup/restore_database synchronous.
- Asynchronous backup/restore renamed to syscs_backup/restore_database_async.
=> DB-6252: add back synchronous backup/restore(2.6)

mem_sql/src/main/java/com/splicemachine/derby/impl/sql/NoOpBackupManager.java, splice_machine/src/main/java/com/splicemachine/backup/BackupManager.java, splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- Make syscs_backup/restore_database synchronous.
- Asynchronous backup/restore renamed to syscs_backup/restore_database_async.
=> DB-6252: add back synchronous backup/restore(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/BasicPrivilegeInfo.java, db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/GrantRevokeConstantOperation.java, splice_machine/src/test/java/com/splicemachine/derby/security/AuthorizationIT.java, splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
Doing the missing backport onto branch-2.5, master and branch-2.6 are ok.
=> Splice-865: REVOKE after GRANT can throw NullPointerException (2.5)

splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/SpliceOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/merge/AbstractMergeJoinFlatMapFunction.java
Please see more details in SPLICE-1887.
=> SPLICE-1887 fix memory leak for merge join

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkPairDataSet.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkUtils.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SIConfigurations.java
It can be disabled setting splice.olap.shuffle.partitions to 0
=> SPLICE-1302 Add minimum parallelism for Spark shuffles

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkPairDataSet.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkUtils.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SIConfigurations.java
=> SPLICE-1302 Add minimum parallelism for Spark shuffles (2.6)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BasicPrivilegesNode.java
Missed a check earlier, please also see EE for IT.
=> DB-1908: SELECT permission available after granting of any other kind of permission

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BasicPrivilegesNode.java
Missed a check earlier, please also see EE for IT.
=> DB-1908: SELECT permission after granting of any other kind of permission (2.6)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BasicPrivilegesNode.java
Missed a check earlier, please also see EE for IT.
=> DB-1908: SELECT permission become available after granting of any other kind of permission (2.5)

assembly/pom.xml
keep master, 2.6 branch in sync with v2.0 and v2.5 for Cloudera certification
=> DB-6275: exclude flatten and restart scripts (master)

hbase_sql/src/main/java/com/splicemachine/mrio/api/core/AbstractSMInputFormat.java, hbase_sql/src/main/resources/info-log4j.properties, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java, hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java, hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java, hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java, hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java, hbase_storage/hbase1.1.0/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java, hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java, hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java, hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java, hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java, hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java, hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java, hbase_storage/hbase1.2.0_cdh5.12/src/main/java/com/splicemachine/access/client/MemStoreFlushAwareScanner.java, hbase_storage/hbase1.2.0_cdh5.12/src/main/java/com/splicemachine/access/client/MemstoreKeyValueScanner.java
There is too much logging and that's creating issues on Jenkins
=> DB-6274 Reduce logging on MemStoreAwareScanner

splice_machine/src/test/java/com/splicemachine/derby/impl/sql/catalog/SqlJJarIT.java
'SQLJARIT' was wrong, though ineffectual.
=> SPLICE-1922 Typo in SqlJJarIT

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MergeSortJoinOperation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/JoinOperationIT.java
=> SPLICE-1921 fix wrong result with sort merge inclusion join for spark…(2.5)

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MergeSortJoinOperation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/JoinOperationIT.java
=> SPLICE-1921 fix wrong result with sort merge inclusion join for spark…(2.6.1)

splice_si_api/src/main/java/com/splicemachine/si/api/server/Transactor.java, splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactor.java, splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactorUtil.java
Removes a transaction lookup for all dictionary writes (base tables and indexes)...
=> SPLICE-1925: Remove TXN Lookups from dictionary writes

hbase_sql/src/test/java/com/splicemachine/hbase/DefaultIndexBulkLoadIT.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DefaultIndexIT.java
…parate file under hbase_sql so it won't run for mem platform
=> DB-6248 move the bulkimport/bulkdelete test in DefaultIndexIT to a se…(2.5)

hbase_sql/src/test/java/com/splicemachine/hbase/DefaultIndexBulkLoadIT.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DefaultIndexIT.java
…parate file under hbase_sql so it won't run for mem platform
=> DB-6248 move the bulkimport/bulkdelete test in DefaultIndexIT to a se…(2.6.1)

hbase_sql/src/test/java/com/splicemachine/derby/transactions/ClusterDDLTestIT.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java, hbase_storage/src/main/java/com/splicemachine/si/impl/CoprocessorTxnStore.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SIConfigurations.java
This has already been reviewed and merged into master
=> DB-6267 Add parameter to ignore missing transactions from SPLICE_TXN (2.6)

hbase_sql/src/test/java/com/splicemachine/derby/transactions/ClusterDDLTestIT.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java, hbase_storage/src/main/java/com/splicemachine/si/impl/CoprocessorTxnStore.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SIConfigurations.java
This has already been approved and merged into master
=> DB-6267 Add parameter to ignore missing transactions from SPLICE_TXN (2.5)

hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
Please also review code changes on ee branch.
=> DB-6315: keep alive backup

splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampOracle.java
=> DB-6362 Large variance in simple select query execution time (2.5)

splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampOracle.java
=> DB-6362 Large variance in simple select query execution time (2.6)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromList.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HalfOuterJoinNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/subquery/FlatteningUtils.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/subquery/SubqueryFlattening.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/subquery/ssq/ScalarSubqueryFlatteningVisitor.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/subquery/ssq/ScalarSubqueryPredicate.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/subquery/ssq/ScalarSubqueryWhereVisitor.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJoinFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/OuterJoinRestrictionFlatMapFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/SpliceJoinFlatMapFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iterator/merge/AbstractMergeJoinIterator.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iterator/merge/MergeInnerJoinIterator.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iterator/merge/MergeOuterJoinIterator.java, splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_SSQ_IT.java, splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_SSQ_To_FromSubquery_IT.java
Please see [DB-6346](https://splicemachine.atlassian.net/browse/DB-6346) for the fix description.
=> DB-6346 allow more scenarios to qualify for CSSQ flattening

hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java, splice_spark/pom.xml, splice_spark/src/main/scala/com/splicemachine/spark/splicemachine/SplicemachineContext.scala, splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/SparkStreamingTest.scala, splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/TestStreamingContext.scala
Add ITs for Spark streaming using this feature
=> SPLICE-1948 Initialize Splice Spark context with user context

db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/RowOrdering.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnOrdering.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OrderByList.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RelationalOperator.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RowOrderingImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryComparisonOperatorNode.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/OrderByEliminationIT.java
Please see problem analysis and solution in [JIRA](https://splicemachine.atlassian.net/browse/DB-6016?focusedCommentId=51644&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-51644)
=> DB-6016 avoid sort if some of the index columns are bound with constant.

hbase_sql/src/test/java/com/splicemachine/kafka/TestKafkaCluster.java, pom.xml
updating the  branch with kafka 0.10.0 for cdh5.8.3 platform.
=> DB-6385: update branch with kafka 0.10.0 for cdh5.8.3 (2.5)

splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java, splice_machine/src/test/java/com/splicemachine/derby/impl/load/UpportIT.java
…ement genereated by MERGE_DATA_FROM_FILE
=> DB-6410 prepend schemaname to columns in PK conditions in update stat…(2.6.1)

splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java, splice_machine/src/test/java/com/splicemachine/derby/impl/load/UpportIT.java
…ement genereated by MERGE_DATA_FROM_FILE
=> DB-6410 prepend schemaname to columns in PK conditions in update stat…(2.5)

db-client/src/main/java/com/splicemachine/db/client/net/NetConnection.java, db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java, db-drda/src/main/java/com/splicemachine/db/impl/drda/RemoteUser.java, db-drda/src/main/java/com/splicemachine/db/impl/drda/RemoteUserKerberos.java, db-drda/src/main/java/com/splicemachine/db/impl/drda/RemoteUserPassword.java, db-drda/src/main/java/com/splicemachine/db/impl/drda/Session.java, hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HBasePipelineEnvironment.java, hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/HEngineSqlEnv.java, hbase_storage/src/main/java/com/splicemachine/hbase/ZkServiceDiscovery.java, hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HBaseSIEnvironment.java, mem_pipeline/src/main/java/com/splicemachine/pipeline/MPipelineEnv.java, mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MEngineSqlEnv.java, mem_storage/src/main/java/com/splicemachine/si/MemSIEnvironment.java, splice_access_api/src/main/java/com/splicemachine/access/api/ServiceDiscovery.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java, splice_encoding/src/main/java/com/splicemachine/encoding/Encoding.java, splice_machine/src/main/java/com/splicemachine/EngineDriver.java, splice_machine/src/main/java/com/splicemachine/SqlEnvironment.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java, splice_machine/src/main/java/com/splicemachine/derby/lifecycle/EngineSqlEnvironment.java, splice_machine/src/main/java/com/splicemachine/derby/lifecycle/NetworkLifecycleService.java, splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java, splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdmin_OperationsIT.java
More details on https://splicemachine.atlassian.net/browse/DB-6342
=> DB-6342 Monitor/kill running operations for all nodes

db-engine/src/main/java/com/splicemachine/db/impl/ast/RowLocationColumnVisitor.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/VirtualColumnNode.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/UpdateFromSubqueryIT.java
Please refer to [DB-6411](https://splicemachine.atlassian.net/browse/DB-6411?focusedCommentId=51812&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-51812) for fix details.
=> DB-6411 fix column misalignment for join update through mergesort join(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectivityUtil.java, splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/JoinSelectivityNoIndexesIT.java
DB-6412 Bound the outer join row count by the left outer table's row count
=> DB-6412 Bound the outer join row count by the left outer table's row count

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectivityUtil.java, splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/JoinSelectivityNoIndexesIT.java
=> DB-6412 Bound the outer join row count by the left outer table's row count (2.6.1)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/AddColumnWithDefaultIT.java
…with the right type (regression fix for SPLICE-1700)
=> DB-6438 populate default value for column of DATE type in defaultRow …(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/AddColumnWithDefaultIT.java
…with the right type (regression fix for SPLICE-1700)
=> DB-6438 populate default value for column of DATE type in defaultRow …(2.6.1)

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_sql/src/test/java/com/splicemachine/hbase/SpliceRegionAdminIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java, splice_machine/src/main/java/com/splicemachine/derby/impl/storage/SpliceRegionAdmin.java, splice_machine/src/main/java/com/splicemachine/derby/impl/storage/TableSplit.java, splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIT.java
Sanity check for system procedure  parameters to avoid NPE
=> DB-6416: parameter sanity check for region operations(2.5)

hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java, splice_spark/src/main/scala/com/splicemachine/spark/splicemachine/SplicemachineContext.scala, splice_spark/src/test/java/com/splice/custom/reader/ReaderWriterExample.java
With a fix for the TPCH1 regression
=> DB-6399 Broadcast Kerberos tokens to executors instead of keytabs

pom.xml
=> DB-6445 Cannot import from an s3 bucket on HDP

hbase_sql/src/test/java/com/splicemachine/hbase/SpliceRegionAdminIT.java, hbase_storage/src/main/java/com/splicemachine/access/hbase/H10PartitionAdmin.java, mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MEnginePartitionAdmin.java, mem_storage/src/main/java/com/splicemachine/storage/MPartitionFactory.java, splice_access_api/src/main/java/com/splicemachine/access/api/PartitionAdmin.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java, splice_machine/src/main/java/com/splicemachine/derby/impl/storage/SpliceRegionAdmin.java
To delete a region from hbase
1) Close the region
2) Purge HFiles from hdfs
3) Reopen the region 
4) Merge the region with its neighbor
=> DB-6146: delete region(2.5)

db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Optimizer.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/RowOrdering.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HalfOuterJoinNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RowOrderingImpl.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJoinFunction.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/OrderByEliminationIT.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/OuterJoinOrderByEliminationIT.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/NestedLoopJoinOperationIT.java
DB-6453 preserve left row order for batched nestedloop join
=> DB-6453 avoid sort for outer join when applicable

hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/RangedClientPartition.java, hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/storage/RangedClientPartition.java, hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/storage/RangedClientPartition.java, hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/storage/RangedClientPartition.java
Few ITs were failing due to this on hdp2.5.5 platform
=> DB-6456: add missing getEncodedName() method

db-engine/src/main/java/com/splicemachine/db/iapi/types/HBaseRowLocation.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java, splice_machine/src/main/java/com/splicemachine/SpliceKryoRegistry.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperation.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlOperationContext.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/FutureIterator.java, splice_machine/src/main/java/com/splicemachine/derby/stream/function/SetCurrentLocatedRowAndRowKeyFunction.java, splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
Execute Multi-probe and unions in parallel and do not materialize their iterators
=> SPLICE-1984 parallelize multi-probe and union operation(2.5)

hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java, splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
=> SPLICE-1983 OOM in Spark executors while running TPCH1 repeatedly (2.6)

hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java, splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
=> SPLICE-1983 OOM in Spark executors while running TPCH1 repeatedly (2.5)

assembly/hdp2.4.2/src/main/resources/scripts/restart.sh, assembly/hdp2.4.3/src/main/resources/scripts/restart.sh, assembly/hdp2.5.0/src/main/resources/scripts/restart.sh, assembly/hdp2.5.3/src/main/resources/scripts/restart.sh, assembly/hdp2.5.5/src/main/resources/scripts/restart.sh
SPLICE-1927 Amend pattern string for detecting splice machine ready to accept connections
=> SPLICE-1927 Amend pattern string for detecting splice machine ready to accept connections

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperatonIT.java
=> DB-6440 reduce lengthy lineage of transformation for MultiProbeTableS…(2.6.1)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java, hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperatonIT.java
…can operation
Please see comments in [DB-6440](https://splicemachine.atlassian.net/browse/DB-6440) for analysis and solution description.
=> DB-6440 reduce lengthy lineage of transformation for MultiProbeTableS…(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/ast/RSUtils.java, db-engine/src/main/java/com/splicemachine/db/impl/ast/RowLocationColumnVisitor.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/UpdateFromSubqueryIT.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UpdateOperationIT.java
Please see solution description in [SPLICE-1870](https://splice.atlassian.net/browse/SPLICE-1870).
=> SPLICE-1870 fix update through index lookup path (2.5)

db-engine/src/main/java/com/splicemachine/db/impl/ast/RSUtils.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/UpdateFromSubqueryIT.java
Please see [DB-6320](https://splicemachine.atlassian.net/browse/DB-6320) for analysis and solution description.
=> DB-6320 fix wrong update using merge join

db-engine/src/main/java/com/splicemachine/db/impl/ast/PlanPrinter.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainOperation.java
…explain
Please see [SPLICE-2004](https://splice.atlassian.net/browse/SPLICE-2004) for details and also test result.
=> SPLICE-2004 fix inconsistency between plan logged in log and that in the …(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/ast/PlanPrinter.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainOperation.java
=> SPLICE-2004 fix inconsistency between plan logged in log and that in …(2.6.1)

pipeline_api/src/main/java/com/splicemachine/lifecycle/DatabaseLifecycleManager.java
Shutdown the database lifecycle executor.
=> SPLICE-2012 HMaster doesn't exit after shutdown

pipeline_api/src/main/java/com/splicemachine/lifecycle/DatabaseLifecycleManager.java
Shutdown the database lifecycle executor.
=> SPLICE-2012 HMaster doesn't exit after shutdown (2.5)

pipeline_api/src/main/java/com/splicemachine/lifecycle/DatabaseLifecycleManager.java
Shutdown the database lifecycle executor
=> SPLICE-2012 HMaster doesn't exit after shutdown (2.6)

hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HPipelineExceptionFactory.java, hbase_pipeline/src/test/java/com/splicemachine/pipeline/testsetup/com/splicemachine/pipeline/tests/BulkWriteActionRetryTest.java, pipeline_api/src/main/java/com/splicemachine/pipeline/client/WriteResult.java
Retry on some host unreachable exception. HBase will reassign the region soon.
=> DB-6574: retry write workload on host unreachable exceptions

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeJoinStrategy.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/MergeJoinIT.java
Please see comment in [DB-6594](https://splicemachine.atlassian.net/browse/DB-6594?focusedCommentId=52851&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-52851) for a brief explanation.
=> DB-6594 fix illegal merge join

hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkExportDataSetWriter.java, splice_machine/src/main/java/com/splicemachine/derby/stream/control/output/ControlExportDataSetWriter.java
- Remove RDD cache
- Get written rows from task metrics.
=> DB-6582: improve export performance

hbase_sql/pom.xml, hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/HEngineSqlEnv.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapServerMaster.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapServerSubmitter.java, hbase_sql/src/test/java/com/splicemachine/hbase/OlapServerIT.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
Fix TPCH1G failure by increasing OlapServer memory
=> SPLICE-2032 Reenable OlapServerIT and increase robustness

hbase_sql/pom.xml, hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/HEngineSqlEnv.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapServerMaster.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapServerSubmitter.java, hbase_sql/src/test/java/com/splicemachine/hbase/OlapServerIT.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
Fix TPCH1G failure by increasing OlapServer memory
=> SPLICE-2032 Reenable OlapServerIT and increase robustness (2.5)

hbase_sql/pom.xml, hbase_sql/src/main/java/com/splicemachine/derby/lifecycle/HEngineSqlEnv.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapServerMaster.java, hbase_sql/src/main/java/com/splicemachine/olap/OlapServerSubmitter.java, hbase_sql/src/test/java/com/splicemachine/hbase/OlapServerIT.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
Fix TPCH1G failure by increasing OlapServer memory
=> SPLICE-2032 Reenable OlapServerIT and increase robustness (2.6)

splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/OperationManager.java, splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/OperationManagerImpl.java, splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/RunningOperation.java, splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/SpliceOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java, splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java, splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdmin_OperationsIT.java
Test case failure in previous PR was because of no Spark in MEM. In V2 we specified the test case in HBase by marking @Category(HBaseTest.class)
=> DB-6478 Fix error in IT test case and ignored it in MEM mode

hbase_sql/src/main/java/com/splicemachine/stream/SparkCompactionContext.java, hbase_sql/src/main/resources/info-log4j.properties, hbase_sql/src/test/java/com/splicemachine/derby/transactions/TransactionResolutionIT.java, hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/SIObserver.java, hbase_storage/src/main/java/com/splicemachine/si/impl/CoprocessorTxnStore.java, hbase_storage/src/main/java/com/splicemachine/si/impl/server/AbstractSICompactionScanner.java, hbase_storage/src/main/java/com/splicemachine/si/impl/server/CompactionContext.java, hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionState.java, hbase_storage/src/main/java/com/splicemachine/si/impl/server/SimpleCompactionContext.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/PipelineConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SIConfigurations.java, splice_machine/src/main/java/com/splicemachine/derby/lifecycle/EngineLifecycleService.java, splice_si_api/src/main/java/com/splicemachine/si/api/txn/TransactionMissing.java, splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIDriver.java
Take 2 with fix for restore (ignore missing transactions instead of raising NPE) and some ITs
=>  SPLICE-2008 Resolve transactions during flushes

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OrNode.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperationIT.java
=> DB-6600 Case When Not Matching or Clause (2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OrNode.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperationIT.java
=> DB-6600 Case When Not Matching or Clause

db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/NonCoveringIndexIT.java
=> DB-6345 fix query failure with non-covering index as right table of a…(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/NonCoveringIndexIT.java
=> DB-6345 fix query failure with non-covering index as right table of a…(2.6.1)

db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDescriptorGenerator.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/SchemaPermsDescriptor.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementSchemaPermission.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSSCHEMAPERMSRowFactory.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BasicPrivilegesNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CreatePinNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DropPinNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PrivilegeNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/BasicPrivilegeInfo.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/SchemaPrivilegeInfo.java, db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptForModifySchemaPermission.java, splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java, splice_machine/src/test/java/com/splicemachine/derby/security/SchemaPrivilegeIT.java, splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java, splice_protocol/src/main/protobuf/DDL.proto
SPLICE-1587 add authorization check for PIN table statement
SPLICE-1587 add IT
SPLICE-1587 add upgrade logic
=> SPLICE-1587 add modifyPriv for Schema level privilege(2.5)

db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDescriptorGenerator.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/SchemaPermsDescriptor.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementSchemaPermission.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSSCHEMAPERMSRowFactory.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BasicPrivilegesNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CreatePinNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DropPinNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PrivilegeNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj, db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/BasicPrivilegeInfo.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/SchemaPrivilegeInfo.java, db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/PinTableIT.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptForModifySchemaPermission.java, splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java, splice_machine/src/test/java/com/splicemachine/derby/security/SchemaPrivilegeIT.java, splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java, splice_protocol/src/main/protobuf/DDL.proto
SPLICE-1587 add authorization check for PIN table statement
SPLICE-1587 add IT
SPLICE-1587 add upgrade logic
Fix description is in [SPLICE-1587](https://splice.atlassian.net/browse/SPLICE-1587?focusedCommentId=27119&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-27119)
=> SPLICE-1587 add modifyPriv for Schema level privilege

db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextService.java, hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java, splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
Forward port from branch-2.5
Changes to ContextService.java are new as the content of the file was different from that in branch-2.5
=> DB-6541 User defined function does not work on spark

splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlOperationContext.java
Get a cached value when available.
=> SPLICE-2081 Excessive creation of Kryo instances

splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlOperationContext.java
=> SPLICE-2081 Excessive creation of Kryo instances (2.5)

splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlOperationContext.java
=> SPLICE-2081 Excessive creation of Kryo instances (2.7)

db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java, splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java, splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java, splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java, splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java, splice_machine/src/test/java/com/splicemachine/derby/security/SchemaPrivilegeIT.java, splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java, splice_protocol/src/main/protobuf/DDL.proto
DB-6685 address review comments by adding IT for multiple region servers and invalidate nameTdCache too
=> DB-6685 invalidate dictionary cache after update schema owner(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java, splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java, splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java, splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java, splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java, splice_machine/src/test/java/com/splicemachine/derby/security/SchemaPrivilegeIT.java, splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java, splice_protocol/src/main/protobuf/DDL.proto
DB-6685 address review comments by adding IT for multiple region servers and invalidate nameTdCache too
=> DB-6685 invalidate dictionary cache after update schema owner(2.7)

assembly/hdp2.6.3/src/main/resources/common-services/SPLICEMACHINE/2.5.1/service_advisor.py
Fixes install of HDP2.6.3 when OLAP Server is involved.
=> DB-6735 Fixing HDP2.6.3 build to support OLAP Server properly

hbase_sql/src/main/java/com/splicemachine/olap/OlapServerSubmitter.java
@dgomezferro I'm able to fix the Client cannot authenticate via:[TOKEN, KERBEROS] issue. With this fix Olap Server no longer fails with the exception. Please review
=> SPLICE-2067: Fix for Client cannot authenticate via:[TOKEN, KERBEROS]

kbsqlsh.sh
=> Refactored and stream-line: execute in one place.

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnDefinitionNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/AddColumnWithDefaultIT.java
… the column size of fixed-length char type
Please see comment in [SPLICE-2095](https://splice.atlassian.net/browse/SPLICE-2095) for problem and solution description
=> SPLICE-2095 pad default values with extra space if it is shorter than…(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnDefinitionNode.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/AddColumnWithDefaultIT.java
… the column size of fixed-length char type
=> SPLICE-2095 pad default values with extra space if it is shorter than…(2.7)

db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/OptimizerFactory.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerFactoryImpl.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceLevel2OptimizerFactoryImpl.java
=> SPLICE-1883 Add rowcount threshold parameter to determine Spark or Control

kbsqlsh.sh
=> SPLICE-1936: Refactored and stream-line: execute in one place.

splice_spark/src/main/spark2.1/com/splicemachine/spark/splicemachine/SplicemachineContext.scala, splice_spark/src/main/spark2.2/com/splicemachine/spark/splicemachine/SplicemachineContext.scala, splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceTest.scala, splice_spark/src/test/spark2.1/com/splicemachine/spark/splicemachine/TestContext.scala, splice_spark/src/test/spark2.2/com/splicemachine/spark/splicemachine/TestContext.scala
Adding stats and truncate to spark adapter.
=> SPLICE-2102: Adding stats and truncate to spark adapter.

splice_spark/src/main/spark2.1/com/splicemachine/spark/splicemachine/SplicemachineContext.scala, splice_spark/src/main/spark2.2/com/splicemachine/spark/splicemachine/SplicemachineContext.scala, splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceTest.scala, splice_spark/src/test/spark2.1/com/splicemachine/spark/splicemachine/TestContext.scala, splice_spark/src/test/spark2.2/com/splicemachine/spark/splicemachine/TestContext.scala
Already reviewed.  The tests are added back based on a later commit.  It was not caught til already merged.
=> SPLICE-2102 Stats and truncate functions, a bit of scaladoc writing

db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java, hbase_sql/src/test/java/com/splicemachine/derby/transactions/ClusterDDLTestIT.java, splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java, splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateRoleConstantOperation.java, splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java, splice_protocol/src/main/protobuf/DDL.proto
Fixing a scan per connection.  This should help IT's since they create a lot of connections.
=> SPLICE-2096 Remove Role Scan Hit

splice_machine/src/main/java/com/splicemachine/derby/utils/Vacuum.java
=> SPLICE-2109 Add log message in a finally clause to indicate the vacuu… (2.5)

splice_machine/src/main/java/com/splicemachine/derby/utils/Vacuum.java
=> SPLICE-2109 Add log message in a finally clause to indicate the vacuu… (2.7)

db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java, splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/GrantRoleConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/RevokeRoleConstantOperation.java, splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java, splice_machine/src/test/java/com/splicemachine/derby/security/DefaultRoleIT.java, splice_protocol/src/main/protobuf/DDL.proto
Please see comment in [dB-6670](https://splicemachine.atlassian.net/browse/DB-6670?focusedCommentId=53547&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-53547)
=> DB-6670 cache role grant permissions(2.5)

hbase_sql/src/main/java/com/splicemachine/olap/OlapServerSubmitter.java
=> SPLCIE-2070:Default to HMaster principal/keytab for OlapServer when they are not explicitly set(2.7)

db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/RoutinePermsDescriptor.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/Procedure.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSROUTINEPERMSRowFactory.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptForModifySchemaPermissionAndDefaultRole.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptToCleanSysRoutinePerms.java
also clean obsolete rows in sysroutineperms if any
code is pretty much the same as branch-2.7.
=> SPLICE-2120 update SYS.SYSROUTINEPERMS when upgrading system procedures

assembly/hdp2.6.3/src/main/resources/common-services/SPLICEMACHINE/2.5.1/service_advisor.py
Already in branch-2.5, porting to master/2.7
=> DB-6735: Fixing HDP2.6.3 build to support OLAP Server properly 

assembly/hdp2.6.3/src/main/resources/common-services/SPLICEMACHINE/2.5.1/service_advisor.py
Already in branch-2.5, porting to master/2.7
=> DB-6735: Fixing HDP2.6.3 build to support OLAP Server properly (2.7)

hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSparkKryoRegistrator.java, hbase_sql/src/test/java/com/splicemachine/derby/utils/marshall/SparkValueRowSerializerTest.java
…tests
Based on the error @mzweben saw running a query from Spark.
=> SPLICE-2106 Fixing Transient Kryo Registrator and adding a few serde tests (2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/StaticMethodCallNode.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/FunctionIT.java
…ault schema
You may use this [link](https://github.com/splicemachine/spliceengine/pull/1641/files?w=1) to filter out white space difference.
=> DB-6839 fix NPE when calling system functions from a user without def…(2.5)

db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/StaticMethodCallNode.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/FunctionIT.java
…ault schema
Please use this [link](https://github.com/splicemachine/spliceengine/pull/1642/files?w=1) to filter out whitespace differences.
=> DB-6839 fix NPE when calling system functions from a user without def…(2.7)

hbase_storage/hbase1.0.0.x/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.0.0/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.1/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.2.2.6/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.2/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.1.8/src/main/java/com/splicemachine/storage/SplitRegionScanner.java, hbase_storage/hbase1.2.0_cdh5.12/src/main/java/com/splicemachine/storage/SplitRegionScanner.java
I forgot to apply this change to all hbase-1.* platforms, it was only applied to hbase-1.2.0
=> DB-6872 Set hbase.rootdir in all platforms

db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
Please review a related PR in ee branch
=> DB-6815: bulk insert into sys.sysbackupitems(2.5)

mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MemDatabase.java, pipeline_api/src/main/java/com/splicemachine/pipeline/PipelineDriver.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/PipelineConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
Already in branch-2.5. Forward port to master.
=> DB-6833 Set Max Dependent and Independent write threads directly

mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MemDatabase.java, pipeline_api/src/main/java/com/splicemachine/pipeline/PipelineDriver.java, splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/PipelineConfiguration.java, splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
Already merged to branch-2.5. Forward port to 2.7 branch.
=> DB-6833 Set Max Dependent and Independent write threads directly (2.7)

splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateViewConstantOperation.java, splice_machine/src/test/java/com/splicemachine/derby/security/AuthorizationIT.java
…olumn level permissions on views
port change from branch-2.5 to branch-2.7
=> SPLICE-2134 Fixing Column Sequencing for views, issue shows up with c…(2.7)

db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java, db-engine/src/main/java/com/splicemachine/db/iapi/db/Database.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionFactory.java, db-engine/src/main/java/com/splicemachine/db/impl/db/BasicDatabase.java, db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedPreparedStatement.java, db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionFactory.java, db-engine/src/main/java/com/splicemachine/db/jdbc/InternalDriver.java, db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java, splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java, splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
Adding IP Address to Language Connection Context for use by Audit features.
=> Splice 2140 Adding Client IP Address for Audit Functionality 2.5

db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java, db-engine/src/main/java/com/splicemachine/db/iapi/db/Database.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionFactory.java, db-engine/src/main/java/com/splicemachine/db/impl/db/BasicDatabase.java, db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionFactory.java, db-engine/src/main/java/com/splicemachine/db/jdbc/InternalDriver.java, db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java, splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java, splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
SPLICE-2140 Cleanup Accidental Space
Remove Assertion which breaks during the initial boot
port change from branch-2.5 to branch-2.7
=> SPLICE-2140 Adding IP Address for Client, needed for future audit work(2.7)

db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java, db-engine/src/main/java/com/splicemachine/db/iapi/db/Database.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java, db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionFactory.java, db-engine/src/main/java/com/splicemachine/db/impl/db/BasicDatabase.java, db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionFactory.java, db-engine/src/main/java/com/splicemachine/db/jdbc/InternalDriver.java, db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java, splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java, splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
SPLICE-2140 Cleanup Accidental Space
Remove Assertion which breaks during the initial boot
Port change from branch-2.5 to master
=> SPLICE-2140 Adding IP Address for Client, needed for future audit work

hbase_sql/src/test/java/com/splicemachine/test/SpliceTestYarnPlatform.java, platforms/hdp2.5.5/docs/HDP-installation.md
Only need to set this property on standalone and HDP platform.
=> DB-6570 Set fs.s3a.impl in SpliceTestYarnPlatform

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateRoleConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DDLConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropRoleConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/GrantRevokeConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/GrantRoleConstantOperation.java, splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/RevokeRoleConstantOperation.java
Error Message handling for Apache Sentry.
=> DB-6691 Apache Sentry Implementation(2.5)

db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java, db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
Add an error message. For actual code changes, please review ee branch
=> DB-5676: check disk space for backup/restore

hbase_sql/src/main/java/com/splicemachine/olap/OlapServerSubmitter.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestYarnPlatform.java
Defaults to splice.spark.yarn.queue, or default if that's not set
=> DB-6829 Add parameter to configure Olap Server yarn queue

hbase_sql/src/main/java/com/splicemachine/olap/OlapServerSubmitter.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestYarnPlatform.java
Defaults to splice.spark.yarn.queue, or default if that's not set
=> DB-6829 Add parameter to configure Olap Server yarn queue (2.5)

hbase_sql/src/main/java/com/splicemachine/olap/OlapServerSubmitter.java, hbase_sql/src/test/java/com/splicemachine/test/SpliceTestYarnPlatform.java
Defaults to splice.spark.yarn.queue, or default if that's not set
=> DB-6829 Add parameter to configure Olap Server yarn queue (2.7)

db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLClob.java, db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BaseTypeCompiler.java, splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/StringTypesToNumericTypeConversion.java
Text to Numeric Conversion in Splice...
=> DB-6940 Text to Numeric Conversion in Splice(2.5)

splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java, splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java, splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/PropertyConglomerate.java
=> SPLICE-2108 Can't disable logging statements (2.7)
