splicemachine/spliceengine

- splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/PropertyConglomerate.java
> SPLICE-2108 Can't disable logging statements (2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLClob.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/StringTypesToNumericTypeConversionIT.java
> DB-6940 Text to Numeric Conversion in Splice(2.7)

- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLClob.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/StringTypesToNumericTypeConversionIT.java
Port change from branch-2.5 to master
> DB-6940 Text to Numeric Conversion in Splice

- splice_machine/src/test/java/com/splicemachine/derby/security/DefaultRoleIT.java
> SPLICE-2157 fix DefaultRoleIT to make the defaultRole value compariso…(2.5)

- splice_machine/src/test/java/com/splicemachine/derby/security/DefaultRoleIT.java
> SPLICE-2157 fix DefaultRoleIT to make the defaultRole value compariso…(2.7)

- db-engine/src/main/java/com/splicemachine/db/iapi/services/property/PropertyUtil.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Visitable.java
- db-engine/src/main/java/com/splicemachine/db/iapi/util/JBitSet.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/ColumnCollectingVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DMLStatementNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromVTI.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectionPruningVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumnList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SetOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TableOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/VirtualColumnNode.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ProjectionPruningIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/StatisticsAdminIT.java
- splice_protocol/src/main/protobuf/DDL.proto
…isabled as a database property to control the projection pruning optimization
Please see comment in [DB-6768](https://splicemachine.atlassian.net/browse/DB-6768?focusedCommentId=54148&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-54148) for solution description.
> DB-6768 projection pruning, and add derby.database.projectionPruningD…(2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/services/property/PropertyUtil.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Visitable.java
- db-engine/src/main/java/com/splicemachine/db/iapi/util/JBitSet.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/ColumnCollectingVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DMLStatementNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromVTI.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectionPruningVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumnList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SetOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TableOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/VirtualColumnNode.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ProjectionPruningIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/StatisticsAdminIT.java
- splice_protocol/src/main/protobuf/DDL.proto
…isabled as a database property to control the projection pruning optimization
> DB-6768 projection pruning, and add derby.database.projectionPruningD…(2.7)

- hbase_storage/src/main/java/com/splicemachine/access/hbase/HFilesystemAdmin.java
- hbase_storage/src/main/java/org/apache/hadoop/hdfs/HDFSUtil.java
- hbase_storage/src/main/java/org/apache/hadoop/hdfs/ProxiedDFSClient.java
I removed HTrace calls to make it compatible with hdp and mapr builds
> DB-6892 Proxied decrypt key

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/callbuffer/PipingCallBuffer.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/client/BulkWriteAction.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/AuthenticationConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
- splice_machine/src/main/java/com/splicemachine/client/SpliceClient.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/store/IgnoreTxnSupplier.java
> DB-6996 Close table on PipingCallBuffer

- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/PropertyConglomerate.java
Process startParameters always, not just when a new database is created.
> SPLICE-2108 Can't disable logging statements redux

- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/PropertyConglomerate.java
> SPLICE-2108 Can't disable logging statements redux (2.7)

- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/PropertyConglomerate.java
> SPLICE-2108 Can't disable logging statements redux (2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BasicPrivilegesNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/GenericPrivilegeInfo.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/RoutinePrivilegeInfo.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/SchemaPrivilegeInfo.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/TablePrivilegeInfo.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/GrantRevokeConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/CreateSchemaIT.java
- splice_protocol/src/main/protobuf/DDL.proto
Please see [DB-6217](https://splicemachine.atlassian.net/browse/DB-6217) for solution description.
IT is in EE branch.
> DB-6217 add support for grant all column permissions

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/sequence/SpliceSequenceIT.java
- splice_machine/src/test/java/com/splicemachine/test_dao/SchemaDAO.java
port change from branch-2.5 to branch-2.7
> SPLICE-2171 Issue Granting Privileges to Sequences(2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/sequence/SpliceSequenceIT.java
- splice_machine/src/test/java/com/splicemachine/test_dao/SchemaDAO.java
port change from branch-2.5 to master.
> SPLICE-2171 Issue Granting Privileges to Sequences

- splice_spark/src/main/spark2.1/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark2.2/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceTest.scala
…k Adapter.
This will allow the duplicate primary key entries to be captured...
> SPLICE-2167 Support statusDirectory and Bad Records Count in the Spar…(2.5)

- splice_spark/src/main/spark2.1/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/main/spark2.2/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/DefaultSourceTest.scala
…k Adapter.
port the change from branch-2.5 to branch-2.7
> SPLICE-2167 Support statusDirectory and Bad Records Count in the Spar…(2.7)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/FirstLastValueFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
… with Frame clause for control path
> DB-7012 fix First_Value ingoreNulls logic, fix First_value/Last_Value…(2.5)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/FirstLastValueFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
… with Frame clause for control path
> DB-7012 fix First_Value ingoreNulls logic, fix First_value/Last_Value…(2.7)

- assembly/standalone/template/bin/functions.sh
Add LOG4J_PATH to java command in function.sh. This is for standalone package.
> DB-7033 Unknown arguments. start-splice.sh (2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ProjectionPruningIT.java
…ction pruning optimization is enabled.
> DB-7052 do not call pullVirtualIsReferenced() for JoinNode when proje…(2.7)

- platforms/std/docs/STD-installation.md
Fixed anchor link to CentOS/RedHat installation steps
> Anchor link fix (2.7)

- platforms/std/docs/STD-installation.md
Fixed CentOS/Red Hat link in installation doc
> Fixed anchor link (2.5)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
This is a follow up for PR #1872
> DB-6821 Check logger status before log and cache formatted statement

- hbase_sql/pom.xml
> DB-6931 Import from S3 failed on HDP 2.5.5 (2.7)

- hbase_sql/pom.xml
> DB-6931 Import from S3 failed on HDP 2.5.5

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromVTI.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
- splice_machine/src/test/java/com/splicemachine/customer/Price.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceUDTIT.java
Please see comments in [DB-6913](https://splicemachine.atlassian.net/browse/DB-6913?focusedCommentId=54566&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-54566) for solution description.
> DB-6913 Fix NullPointerException in aggregate queries with UDFs.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultSetNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TableOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Table_IT.java
Please see analysis in [DB-7104](https://splicemachine.atlassian.net/browse/DB-7104)
> DB-7104 fix size inconsistent for JBitSet in predicates

- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/SpliceOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DerbyScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/IndexRowToBaseRowOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeDerbyScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ScanOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/iapi/ScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/merge/AbstractMergeJoinFlatMapFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/Scans.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/MergeJoinIT.java
Please see [SPLICE-1996](https://splice.atlassian.net/browse/SPLICE-1996) for analysis and solution detail.
> SPLICE-1996 fix merge join starting key for right table scan

- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextService.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/SpliceOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJoinFunction.java
Synchronize SpliceBaseOperation.closeables, fix contextManager usage and close TransactionResourceImpl when exception is raised during prepare
> SPLICE-2185 Fix KillOperationIT

- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextService.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java
- hbase_sql/src/test/java/com/splicemachine/hbase/KillOperationIT.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/SpliceOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJoinFunction.java
Synchronize SpliceBaseOperation.closeables, fix contextManager usage and close TransactionResourceImpl when exception is raised during prepare
> SPLICE-2185 Fix KillOperationIT (2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextService.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/SpliceOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJoinFunction.java
Synchronize SpliceBaseOperation.closeables, fix contextManager usage and close TransactionResourceImpl when exception is raised during prepare
> SPLICE-2185 Fix KillOperationIT (2.7)

- db-engine/src/main/java/com/splicemachine/db/iapi/db/Database.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionFactory.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/SQLSessionContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementColumnPermission.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementPermission.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementSchemaPermission.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementTablePermission.java
- db-engine/src/main/java/com/splicemachine/db/impl/db/BasicDatabase.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericAuthorizer.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionFactory.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/SQLSessionContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/BasicPrivilegeInfo.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/DDLConstantAction.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/GenericPrivilegeInfo.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/PrivilegeInfo.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/RoutinePrivilegeInfo.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/SchemaPrivilegeInfo.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/TablePrivilegeInfo.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/OperationManagerImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/GrantRoleConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/RevokeRoleConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
This is a second submission of a previous PR #1781 with review comments addressed.
> DB-6889 support multiple groups for ldap user -- second submission

- db-engine/src/main/java/com/splicemachine/db/iapi/ast/ISpliceVisitor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/Statement.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/C_NodeTypes.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/SessionProperties.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/execute/ExecPreparedStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/AbstractSpliceVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericPreparedStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/C_NodeNames.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SetSessionPropertyNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SpecialFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/SessionPropertiesImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/GenericConstantActionFactory.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceNodeFactoryImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/SpliceGenericConstantActionFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/SetSessionPropertyConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SessionPropertyIT.java
Please see solution description [DB-7011](https://splicemachine.atlassian.net/browse/DB-7011)
> DB-7011 support session parameters

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UpdateNode.java
- splice_machine/src/main/java/com/splicemachine/derby/serialization/ActivationSerializer.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UpdateOperationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/NestedLoopJoinOperationIT.java
…class, also remove logic to bind expression twice for UpdateNode.
> DB-7115 save value of the flag materialized in Ser/De for Activation …(2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UpdateNode.java
- splice_machine/src/main/java/com/splicemachine/derby/serialization/ActivationSerializer.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UpdateOperationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/NestedLoopJoinOperationIT.java
Reverts splicemachine/spliceengine#1975
> Revert "DB-7115 save value of the flag materialized in Ser/De for Activation …(2.7)"

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UpdateNode.java
- splice_machine/src/main/java/com/splicemachine/derby/serialization/ActivationSerializer.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/UpdateOperationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/NestedLoopJoinOperationIT.java
…class, also remove logic to bind expression twice for UpdateNode.
> DB-7115 save value of the flag materialized in Ser/De for Activation …(2.5)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SessionPropertyIT.java
Please refer to [DB-7162](https://splicemachine.atlassian.net/browse/DB-7162) for problem and solution.
> DB-7162 fix syntax issue for "values current session_property" statement

- hbase_sql/hbase1.1.1/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2.2.6/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.8/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/compaction/SparkCompactionFunction.java
Fixes Compaction Locality:  Tested on srv91 with a single executor.  After compaction, a 13 region table had a locality of 1.0 for each region.
> splice-2173 Fixing Compaction Locality

- assembly/hdp2.6.3/build/var/lib/ambari-server/resources/common-services/SPLICEMACHINE/2.5.1/metainfo.xml
- assembly/hdp2.6.3/src/main/resources/common-services/SPLICEMACHINE/2.5.1/metainfo.xml
- assembly/hdp2.6.3/src/main/resources/common-services/SPLICEMACHINE/2.5.1/package/scripts/params.py
remove zeppelin and hive dependency from ambari service install
> DB-7171-2.7 remove zeppelin and hive dependency from ambari service install

- assembly/hdp2.6.3/build/var/lib/ambari-server/resources/common-services/SPLICEMACHINE/2.5.1/metainfo.xml
- assembly/hdp2.6.3/src/main/resources/common-services/SPLICEMACHINE/2.5.1/metainfo.xml
- assembly/hdp2.6.3/src/main/resources/common-services/SPLICEMACHINE/2.5.1/package/scripts/params.py
remove zeppelin and hive dependency from ambari service install
> DB-7171-2.5 remove zeppelin and hive dependency from ambari service install

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/ViewConstantOperationIT.java
Please see comment from [DB-7185](https://splicemachine.atlassian.net/browse/DB-7185) for details.
> DB-7185 check NULL key before looking up in the dictionary cache

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/SchemaPermsDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/GrantRevokeConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/security/PermissionIT.java
- splice_protocol/src/main/protobuf/DDL.proto
, and only invalidate dependency for revoke statement
Please see [SPLICE-2201](https://splice.atlassian.net/browse/SPLICE-2201) for analysis. 
Please also review [PR#244](https://github.com/splicemachine/spliceengine-ee/pull/244) in ee branch which is just test case update.
> SPLICE-2201 populate permision's UUID for grant privilege statement

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/SchemaPermsDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/GrantRevokeConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/security/PermissionIT.java
- splice_protocol/src/main/protobuf/DDL.proto
, and only invalidate dependency for revoke statement
> SPLICE-2201 populate permision's UUID for grant privilege statement(2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/SchemaPermsDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/GrantRevokeConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/security/PermissionIT.java
- splice_protocol/src/main/protobuf/DDL.proto
, and only invalidate dependency for revoke statement
> SPLICE-2201 populate permision's UUID for grant privilege statement(2.7)

- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupRestoreConstants.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchRefresher.java
- splice_si_api/src/main/java/com/splicemachine/si/api/txn/TxnLifecycleManager.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/ClientTxnLifecycleManager.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/ForwardingLifecycleManager.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/UnsupportedLifecycleManager.java
Please refer [DB-7139](https://splicemachine.atlassian.net/browse/DB-7139) for details
> DB-7139: Backup/restore - not use distcp to copy files

- assembly/pom.xml
add c3p0 related jars to hdp rpm
> DB-7234:add c3p0 related jars to hdp rpm

- assembly/pom.xml
add c3p0 related jars to hdp rpm
> DB-7234: add c3p0 related jars to hdp rpm (2.5)

- assembly/pom.xml
add c3p0 related jars to hdp rpm
> DB-7234: add c3p0 related jars to hdp rpm (2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowResultSetNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
…entiating same column from multiple instances of the same table.
> DB-7230 fix column mapping in the presence of window function, differ…(2.5)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowResultSetNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
…entiating same column from multiple instances of the same table.
> DB-7230 fix column mapping in the presence of window function, differ…(2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TableElementList.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
The fix is for 2.5 only. Partitioning works for master and 2.7
> DB-7255: fix external table partitioning

- db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLDate.java
This is an old issue, I forgot to send PR to 2.5/2.7.
> SPLICE-2110 Fix date format that returned from connection (2.5)

- db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLDate.java
This is an old issue, I forgot to send PR to 2.5/2.7.
> SPLICE-2110 Fix date format that returned from connection (2.7)

- assembly/common/src/main/resources/bin/sqlshell.sh
make username quoting the default, to be more friendly with ldap usernames like first.last@company.com
> DB-7214 (2.5) - always quote usernames

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementColumnPermission.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementPermission.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementSchemaPermission.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementTablePermission.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSPERMSRowFactory.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/DDLConstantAction.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/GrantRoleConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/RevokeRoleConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/security/DefaultRoleIT.java
- splice_machine/src/test/java/com/splicemachine/derby/security/PermissionIT.java
> DB-7247 Ignore grantor when looking up role grant description as we n…(2.7)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementColumnPermission.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementPermission.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementSchemaPermission.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementTablePermission.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSPERMSRowFactory.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/DDLConstantAction.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/GrantRoleConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/RevokeRoleConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/security/DefaultRoleIT.java
- splice_machine/src/test/java/com/splicemachine/derby/security/PermissionIT.java
> DB-7247 Ignore grantor when looking up role grant description as we n…(2.5)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- splice_machine/src/test/java/com/splicemachine/derby/security/DefaultRoleIT.java
- splice_machine/src/test/java/com/splicemachine/derby/security/PermissionIT.java
> SPLICE-2218 do not collect privilege requirement information for nest…(2.5)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- splice_machine/src/test/java/com/splicemachine/derby/security/DefaultRoleIT.java
- splice_machine/src/test/java/com/splicemachine/derby/security/PermissionIT.java
> SPLICE-2218 do not collect privilege requirement information for nest…(2.7)

- platforms/hdp2.6.1/docs/HDP-installation.md
- platforms/hdp2.6.3/docs/HDP-installation.md
- platforms/hdp2.6.4/docs/HDP-installation.md
DB-7165 Add notes about click recommend button manually.
DB-7260 Add Spark 2 dependency.
> DB-7165, DB-7260 Fix HDP install documentation

- platforms/hdp2.6.1/docs/HDP-installation.md
- platforms/hdp2.6.3/docs/HDP-installation.md
- platforms/hdp2.6.4/docs/HDP-installation.md
DB-7165 Add notes about click recommend button manually.
DB-7260 Add Spark 2 dependency.
> DB-7165, DB-7260 Fix HDP install documentation (2.5)

- platforms/hdp2.6.1/docs/HDP-installation.md
- platforms/hdp2.6.3/docs/HDP-installation.md
- platforms/hdp2.6.4/docs/HDP-installation.md
DB-7165 Add notes about click recommend button manually.
DB-7260 Add Spark 2 dependency.
> DB-7165, DB-7260 Fix HDP install documentation (2.7)

- assembly/hdp2.6.4/src/main/resources/common-services/SPLICEMACHINE/2.5.1/service_advisor.py
DB-7299:fix ambari service hdp version problem:change hdp version to 2.6.4.0-91
> DB-7299:fix ambari service hdp version problem:change hdp version to 2.6.4.0-91

- assembly/common/src/main/resources/bin/sqlshell.sh
add an option '-U' to encapsulate a new future to quote usernames
> DB-7296: remove the behavior to always quote usernames (2.7)

- assembly/common/src/main/resources/bin/sqlshell.sh
add an option '-U' to encapsulate a new future to quote usernames
> DB-7296: remove the behavior to always quote usernames (2.5)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ProjectionPruningIT.java
…ased on the isReferenced flag for previously missing scenarios.
> DB-7293 add logic to prune ProjectRestrictNode's result column list b…(2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ProjectionPruningIT.java
…ased on the isReferenced flag for previously missing scenarios.
> DB-7293 add logic to prune ProjectRestrictNode's result column list b…(2.5)

- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
Reverts splicemachine/spliceengine#2149
> DB-7298: Do not allow incremental backup if SpliceHFileCleaner is not configured(2.7)

- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
Refer [DB-7298](https://splicemachine.atlassian.net/browse/DB-7298) for an explanation. Please also review code changes on ee branch
> DB-7298: Do not allow incremental backup if SpliceHFileCleaner is not configured

- db-engine/src/main/java/com/splicemachine/db/iapi/services/loader/ClassInspector.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/MethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/StaticMethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/pyprocedure/PyCodeUtil.java
- hbase_sql/src/test/java/com/splicemachine/derby/transactions/PyFunctionIT.java
- hbase_sql/src/test/java/com/splicemachine/derby/transactions/PyProcedureIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/PyRoutineWrapper.java
> SPLICE-2204: Added support for Python user-defined function that returns(2.7)

- hbase_sql/src/main/java/com/splicemachine/orc/predicate/SpliceORCPredicate.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTablePartitionIT.java
…ate on non-partitioning columns
> SPLICE-2244 fix ORC partition pruning logic in the presence of predic…(2.7)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
- splice_machine/src/test/java/com/splicemachine/customer/Price.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceUDTIT.java
> DB-7483 backing out context manager related change of DB-6913 to avoi…(2.5)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
- splice_machine/src/test/java/com/splicemachine/customer/Price.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceUDTIT.java
> DB-7483 backing out context manager related change of DB-6913 to avoi…(2.7)

- assembly/common/src/main/resources/bin/sqlshell.sh
- assembly/pom.xml
- db-tools-ij/pom.xml
- db-tools-ij/src/main/grammar/ij.jj
- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/utilMain.java
Also, backport the suggested SPLICE-1348 changes
> DBAAS-1583 Build sqlshell artifact (2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/InListMultiprobeIT.java
…tion phase, and fix wrong result
> DB-7446 treat inlist with expression as regular OrList at code genera…(2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/InListMultiprobeIT.java
…tion phase, and fix wrong result
> DB-7446 treat inlist with expression as regular OrList at code genera…(2.5)

- utilities/pom.xml
> SPLICE-2254 Shaded snappy-java fails to load native library

- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
> DB-7498 fix roleIsSettable() to take into consideration roles granted…(2.5)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
> DB-7498 fix roleIsSettable() to take into consideration roles granted…(2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ArrayOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CastNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JavaToSQLValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/MethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLToJavaValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/JoinWithFunctionIT.java
Please see analysis in [DB-7402](https://splicemachine.atlassian.net/browse/DB-7402)
> DB-7402 fix NPE for join conditions with expression

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
The test result: http://206.225.8.98:8080/job/spliceengine-branch/job/spliceengine-branch/default/1247/console
> DB-7460 Re-enable ExternalTableIT.testParquetMergeSchema

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumnList.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ProjectionPruningIT.java
> DB-7515 do not set result column's isReferenced field when flattening…(2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromSubquery.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumnList.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ProjectionPruningIT.java
> DB-7515 do not set result column's isReferenced field when flattening…(2.5)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/SumAggregator.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
See [DB-7554](https://splicemachine.atlassian.net/browse/DB-7554) for details.
> DB-7554 Fix SUM in window function.

- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLTimestamp.java
See [SPLICE-201](https://splice.atlassian.net/browse/SPLICE-201) for details.
> SPLICE-201 Use shared thread local Calendar in SQLTimestamp for performance.

- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLTimestamp.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TimestampIT.java
See [SPLICE-2200](https://splice.atlassian.net/browse/SPLICE-2200) for details.
> SPLICE-2200 Fix nil'ed out fractional seconds by TIMESTAMPADD function.

- db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CastNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JavaToSQLValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/MethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLToJavaValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/JoinWithFunctionIT.java
> DB-7543 restore fix of DB-7402 and fix NPE for expression with SQL fu…(2.5)

- db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ArrayOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CastNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JavaToSQLValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/MethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLToJavaValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/JoinWithFunctionIT.java
> DB-7543 restore fix of DB-7402 and fix NPE for expression with SQL fu…(2.7)

- assembly/pom.xml
A bug was fixed where the replace token was not detecting the new modified values and therefore did not replace the token with the new value.
> DB-7563 Add Xenial support and fix parcel.json replace bug

- assembly/pom.xml
A bug was fixed where the replace token was not detecting the new modified values and therefore did not replace the token with the new value.
> DB-7563 Add Xenial support and fix parcel.json replace bug (2.7)

- hbase_sql/hbase1.1.1/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.1/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.6/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2.2.6/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.8/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.8/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupJobStatus.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
- hbase_storage/src/main/java/com/splicemachine/hbase/CellUtils.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/AbstractSICompactionScanner.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionState.java
- mem_sql/src/main/java/com/splicemachine/derby/impl/sql/NoOpBackupManager.java
- platform_it/pom.xml
- splice_access_api/src/main/java/com/splicemachine/access/configuration/HBaseConfiguration.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupManager.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_protocol/src/main/protobuf/Splice.proto
Please refer to [DB-7179](https://splicemachine.atlassian.net/browse/DB-7179) for details.
> DB-7179: full backup/restore for tables

- assembly/standalone/template/bin/functions.sh
Fixes a bug with using Spark in standalone versions
> DBAAS-1845 Fix hbase-site.xml loading for standalone

- platforms/std/docs/STD-installation.md
Need to add the /bin parent folder to these two file paths.
> Update file path to scripts (2.7)

- platforms/hdp2.6.1/docs/HDP-manual-installation.md
DB-7588:add manual installation guide to platform hdp2.6.1
> DB-7588:add manual installation guide to platform hdp2.6.1

- platforms/hdp2.6.1/docs/HDP-manual-installation.md
add manual installation guide to platform hdp2.6.1
> DB-7588: add manual installation guide to platform hdp2.6.1 (2.5)

- platforms/hdp2.6.1/docs/HDP-manual-installation.md
add manual installation guide to hdp 2.6.1 platform
> DB-7588: add manual installation guide to hdp 2.6.1 platform (2.7)

- hbase_sql/src/main/java/com/splicemachine/orc/OrcRecordReader.java
- hbase_sql/src/main/java/com/splicemachine/orc/StripeReader.java
Please see [SPLICE-2275](https://splice.atlassian.net/browse/SPLICE-2275) for problem description and solution.
Existing test cases in ExternalTablePartitionIT and ExternalTableIT can cover the fix code.
> SPLICE-2275 fix includedOrcColumns in StripeReader

- platform_it/pom.xml
Created this ticket since we don't use the standalone tarball created and it is currently causing issues in Jenkins (creating the tarball step).
> DBAAS-1927 Remove standalone execution

- splice_machine/src/main/java/com/splicemachine/derby/stream/function/merge/AbstractMergeJoinFlatMapFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/MergeJoinIT.java
> DB-7583 Adjust right start key of merge join based on first read left row (2.7)

- pom.xml
Fixes the failing hdp2.6.1 jenkins module.
> DB-7698 Fix missing scala_util module (2.5)

- splice_machine/src/main/java/com/splicemachine/derby/utils/Vacuum.java
Please review code changes on ee branch as well.
> DB-7692: stop vacuum during database restore

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/SchemaPermsDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementColumnPermission.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DDdependableFinder.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/TabInfoImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/CreateConstraintConstantAction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptToRemoveFKDependencyOnPrivileges.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateConstraintConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DDLConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/catalog/SqlJJarIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/ConstraintConstantOperationIT.java
- sqlj-it-procs/src/main/java/org/splicetest/sqlj/SqlJTestProcs.java
> DB-7603 do not add dependency of FK constraint on role or permission …(2.7)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/SchemaPermsDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementColumnPermission.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DDdependableFinder.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/TabInfoImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/CreateConstraintConstantAction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptToRemoveFKDependencyOnPrivileges.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateConstraintConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DDLConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/catalog/SqlJJarIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/ConstraintConstantOperationIT.java
- sqlj-it-procs/src/main/java/org/splicetest/sqlj/SqlJTestProcs.java
> DB-7603 do not add dependency of FK constraint on role or permission …(2.5)

- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextService.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkOperationContext.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMSQLUtil.java
- splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/ActivationHolder.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlOperationContext.java
- splice_machine/src/test/java/com/splicemachine/customer/Price.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceUDTIT.java
Backport from master (already integrated).
> DB-6913 Query fails when output of CONVERT_TO_DATE is used in GROUP BY clause (2.7)

- db-engine/src/main/java/com/splicemachine/db/iapi/util/IdUtil.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/authentication/AuthenticationServiceBase.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/authentication/NativeAuthenticationServiceImpl.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Attribute.java
- hbase_storage/pom.xml
- mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MemDatabase.java
- mem_storage/src/main/java/com/splicemachine/si/MemSIEnvironment.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/AuthenticationConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/test/java/com/splicemachine/derby/security/AuthenticationIT.java
For an explanation of the changes check out:
https://splicemachine.atlassian.net/browse/DB-7632?focusedCommentId=58525&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-58525
Please review the -ee repo as well: https://github.com/splicemachine/spliceengine-ee/pull/313
> DB-7632 Add impersonation during authentication

- platform_it/pom.xml
> SPLICE-2282 hbase_sql ITs are not run

- hbase_sql/hbase1.1.1/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.2.2.6/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.1.8/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupBaseRegionObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupRestoreConstants.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
1. keeps track of compaction and split
2. do not block on flush
Please also review ee branch
> DB-6871: incremental backup improvements

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ArrayConstantNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryListOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CastNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CoalesceFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConditionalNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConstantNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CurrentDatetimeOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JavaToSQLValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/MethodCallNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ParameterNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SQLToJavaValueNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SpecialFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNodeList.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/InListMultiprobeIT.java
- sqlj-it-procs/src/main/java/org/splicetest/sqlj/SqlJTestProcs.java
Please see solution description in [DB-7482](https://splicemachine.atlassian.net/browse/DB-7482)
> DB-7482 support multi-probe scan for inlist with expressions

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeDerbyScanInformation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/InListMultiprobeIT.java
> DB-7778 populate a qualifier's orderable before the start of multi-pr…(2.7)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/stream/QueryJob.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
> SPLICE-82 Remove ThreadLocal and clearBroadcastedOperation() from SparkDataSetProcessor

- hbase_sql/pom.xml
- platform_it/pom.xml
Move to hbase_sql, ran 1384,1385 spliceengine-branch builds
>  DB-7794 Remove spark_avro from platform_it

- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLInteger.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLSmallint.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLTinyint.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/TypeId.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryComparisonOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CharTypeCompiler.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/AutoCastIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/BroadcastJoinIT.java
Allow numeric expressions to be compared with CHAR and VARCHAR expressions, for example:
select * from t1 where numeric_column = '12345';
More details in [DB-7817](https://splicemachine.atlassian.net/browse/DB-7817)
> DB-7817 Autocast char to decimal.

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/C_NodeTypes.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLChar.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/StringDataValue.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceNodeFactoryImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceStringFunctionsIT.java
Please refer to [DB-7875](https://splicemachine.atlassian.net/browse/DB-7875) for details.
> DB-7875 support repeat() function for String

- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ShowCreateTableIT.java
jenkins please test branch @cdh5.12.2
> DB-7980 Order constraints in show create table result

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/C_NodeTypes.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/authentication/AuthenticationServiceBase.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/authentication/NativeAuthenticationServiceImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SpecialFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MemDatabase.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/AuthenticationConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceNodeFactoryImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/security/AuthenticationIT.java
Please see comment from [DB-7870](
https://splicemachine.atlassian.net/browse/DB-7870?focusedCommentId=59600&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-59600) for details.
Please also review [PR](https://github.com/splicemachine/spliceengine-ee/pull/343) in the EE branch.
> DB-7870 allow user mapping for Kerberos and Native authentication

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/subquery/CorrelatedColumnPredicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/subquery/exists/ExistsSubqueryPredicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/subquery/exists/ExistsSubqueryWhereVisitor.java
- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSparkKryoRegistrator.java
- splice_machine/src/main/java/com/splicemachine/SpliceKryoRegistry.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MergeSortJoinOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iterator/merge/AbstractMergeJoinIterator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iterator/merge/MergeAntiJoinIterator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iterator/merge/MergeInnerJoinIterator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iterator/merge/MergeOuterJoinIterator.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/JoinSelectivityNoIndexesIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/NestedLoopJoinSelectivityIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicateSimplificationIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/UnsatTreePruningIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/MergeJoinIT.java
- splice_machine/src/test/java/com/splicemachine/subquery/SubqueryITUtil.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_ExistsNotExists_InnerJoin_IT.java
…e table as inner (anti) join
and fix a wrong result for merge join in the presence of null.
> DB-7976 flatten non-aggregate correlated exists/not exists with singl…(2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SelectivityIT.java
…r equality condition of type "col=expr"
> DB-8041 Use average rows per value as estimation for qualified row fo…(2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java
- hbase_sql/src/test/java/com/splicemachine/hbase/CostEstimationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
> DB-8061 fix reference selectivity and the project restrict cost in ex…(2.7)

- db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAProtocolException.java
- splice_machine/src/test/java/com/splicemachine/db/impl/drda/DRDAProtocolExceptionTest.java
> SPLICE-1399 Fixed typo in error message

- db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/RSUtils.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BaseTableNumbersVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SetOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/NestedLoopJoinOperationIT.java
> DB-8200 fix NPE and wrong result for nested loop join with UNION oper…(2.7)

- db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAProtocolException.java
- splice_machine/src/test/java/com/splicemachine/db/impl/drda/DRDAProtocolExceptionTest.java
Already merged changes to master.
> SPLICE-1399 Fixed typo in error message (2.7)

- hbase_sql/src/main/java/com/splicemachine/hbase/BytesCopyTaskSplitter.java
- hbase_sql/src/main/java/com/splicemachine/hbase/RegionSizeEndpoint.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/AbstractSMInputFormat.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SubregionSplitter.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/RegionSplitsIT.java
- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
- splice_protocol/src/main/protobuf/Splice.proto
This JIRA fixes uneven splits when region sizes are imbalanced.
See [DB-8195](https://splicemachine.atlassian.net/browse/DB-8195).
> DB-8195 Calculate average split size for the splits=n hint.

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/C_NodeTypes.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/authentication/AuthenticationServiceBase.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/authentication/NativeAuthenticationServiceImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SpecialFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- mem_sql/src/main/java/com/splicemachine/derby/lifecycle/MemDatabase.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/AuthenticationConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceNodeFactoryImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/security/AuthenticationIT.java
> DB-7870 allow user mapping for Kerberos and Native authentication (2.7)

- hbase_sql/src/main/java/com/splicemachine/hbase/BytesCopyTaskSplitter.java
- hbase_sql/src/main/java/com/splicemachine/hbase/RegionSizeEndpoint.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/AbstractSMInputFormat.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/HBaseSubregionSplitter.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SMRecordReaderImpl.java
- hbase_sql/src/main/java/com/splicemachine/mrio/api/core/SubregionSplitter.java
- hbase_sql/src/test/java/com/splicemachine/mrio/api/core/RegionSplitsIT.java
- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
- splice_protocol/src/main/protobuf/Splice.proto
* DB-8195 Calculate average split size for the splits=n hint.
* DB-8195 Get region sizes in parallel instead of using a serial record reader.
> DB-8195 Calculate average split size for the splits=n hint. (2.7)

- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
Found two places that would benefit from code reuse (and used it as an opportunity to contribute to the project).
> [MINOR] (Re)use

- db-shared/src/main/resources/com/splicemachine/db/info/DBMS.properties
- db-shared/src/main/resources/com/splicemachine/db/info/dnc.properties
- db-shared/src/main/resources/com/splicemachine/db/info/net.properties
- db-shared/src/main/resources/com/splicemachine/db/info/tools.properties
Reverts splicemachine/spliceengine#2740
> Revert "DB-8296 Roll back changes to DRDA maintenance code to re-enable ODBC"

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnionNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicatePushToUnionIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
Please refer to [DB-8036](https://splicemachine.atlassian.net/browse/DB-8036) for details.
> DB-8036 allow more predicates to be pushed down into unions

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/C_NodeTypes.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLChar.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/StringDataValue.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SpliceNodeFactoryImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TernaryOperationIT.java
SPLICE-2343: Support builtin scalar function LEFT used by MicroStrategy. Essentially LEFT() with padding option.
@changli6 @dgomezferro @msirek @jyuanca
> Splice-2343 Support builtin scalar function LEFT used by MicroStrategy

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/JoinWithFunctionIT.java
Please see [DB-8382](https://splicemachine.atlassian.net/browse/DB-8382?oldIssueView=true) for analysis.
> DB-8382 use tablenumber to find relevant columns

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/subquery/aggregate/AggregateSubqueryPredicate.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HBaseBulkLoadIndexIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/TPCHIT.java
- splice_machine/src/test/java/com/splicemachine/subquery/SubqueryITUtil.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_Aggregate_IT.java
> DB-8480 do not flatten non-correlated scalar aggregate subquery(2.7)

- splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/UpportIT.java
…ment for merge_data_from_file
> DB-8559 do not include PK column in the setcolumnlist of update state…(2.7)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/execute/ResultSetFactory.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/ListDataType.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLVarchar.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNodeList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/BaseActivation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/CrossJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/SpliceGenericResultSetFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DerbyScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeDerbyScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicatePushToUnionIT.java
…rchar values, and fix predicate pushed down to union for char columns
> DB-8534 do not ignore trailing spaces when removing duplicates for va…(2.8)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/execute/ResultSetFactory.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/ListDataType.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLVarchar.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNodeList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/BaseActivation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/CrossJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/SpliceGenericResultSetFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DerbyScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeDerbyScanInformation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicatePushToUnionIT.java
…rchar values, and fix predicate pushed down to union for char columns
> DB-8534 do not ignore trailing spaces when removing duplicates for va…(3.0)

- db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptBase.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
- splice_protocol/src/main/protobuf/DDL.proto
Reverts splicemachine/spliceengine#2841
> Revert "DB-8570: invalidate dictionary cache after updating system procedures(2.8)"

- db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptBase.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
- splice_protocol/src/main/protobuf/DDL.proto
Reverts splicemachine/spliceengine#2840
> Revert "DB-8570: invalidate dictionary cache after updating system procedures (2.7)"

- db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptBase.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
- splice_protocol/src/main/protobuf/DDL.proto
Reverts splicemachine/spliceengine#2843
> Revert "DB-8570: invalidate dictionary cache after updating system procedures(3.0)"

- db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptBase.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
- splice_protocol/src/main/protobuf/DDL.proto
Reverts splicemachine/spliceengine#2842
> Revert "DB-8570: invalidate dictionary cache after updating system procedures"

- db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptBase.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
- splice_protocol/src/main/protobuf/DDL.proto
Reverts splicemachine/spliceengine#2851
> Revert "Revert "DB-8570: invalidate dictionary cache after updating system procedures(2.8)""

- db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptBase.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
- splice_protocol/src/main/protobuf/DDL.proto
Reverts splicemachine/spliceengine#2852
> Revert "Revert "DB-8570: invalidate dictionary cache after updating system procedures (2.7)""

- db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptBase.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
- splice_protocol/src/main/protobuf/DDL.proto
Reverts splicemachine/spliceengine#2853
> Revert "Revert "DB-8570: invalidate dictionary cache after updating system procedures(3.0)""

- db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryCache.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DefaultSystemProcedureGenerator.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptBase.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
- splice_protocol/src/main/protobuf/DDL.proto
Reverts splicemachine/spliceengine#2854
> Revert "Revert "DB-8570: invalidate dictionary cache after updating system procedures""

- hbase_sql/hbase1.1.1/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2.2.6-129/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2.2.6/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.8/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactorBase.java
With this commit, we only factor out the functions of
SpliceDefaultCompactor which are absolutely identical accross all
hbase_sql/hbase<...> versions.
A later commit may be necessary to factor out the meaty part as well.
> DB-8714 Factor out common SpliceDefaultCompactor functions (2.8)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/OptimizablePredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- hbase_sql/src/test/java/com/splicemachine/hbase/CostEstimationIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/CrossJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SimpleCostEstimate.java
…hableJoinStrategy, also fix an explain bug.
> DB-8715 do not consider join predicate as scan start/stop key for Has…(3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/OptimizablePredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- hbase_sql/src/test/java/com/splicemachine/hbase/CostEstimationIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/CrossJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SimpleCostEstimate.java
…hableJoinStrategy, also fix an explain bug.
> DB-8715 do not consider join predicate as scan start/stop key for Has…(2.8)

- hbase_sql/src/main/java/com/splicemachine/olap/OlapServerMaster.java
Make sure we have the right tokens all along
I'll be doing some more manual testing tomorrow
> DB-8749 Use the same user for all communications to the RM

- hbase_sql/src/main/java/com/splicemachine/olap/OlapServerMaster.java
Make sure we have the right tokens all along
> DB-8749 Use the same user for all communications to the RM (2.8)

- hbase_sql/src/main/java/com/splicemachine/olap/OlapServerMaster.java
Make sure we have the right tokens all along
> DB-8749 Use the same user for all communications to the RM (3.0)

- hbase_sql/src/main/java/com/splicemachine/olap/OlapServerMaster.java
Make sure we have the right tokens all along
> DB-8749 Use the same user for all communications to the RM (2.7)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RowResultSetNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperationIT.java
> DB-8785 trigger binding for RowResultSetNode with subquery under Inse…(2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RowResultSetNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperationIT.java
> DB-8785 trigger binding for RowResultSetNode with subquery under Inse…(3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSCONGLOMERATESRowFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptToUpdateViewForSYSCONGLOMERATEINSCHEMAS.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/TableSplit.java
- splice_machine/src/test/java/com/splicemachine/derby/security/MetaDataAccessControlIT.java
…t the column CONGLOMERATENAME
> DB-8779 update the system view SYSCONGLOMERATEINSCHEMAS to project ou…(2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSCONGLOMERATESRowFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptToUpdateViewForSYSCONGLOMERATEINSCHEMAS.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/TableSplit.java
- splice_machine/src/test/java/com/splicemachine/derby/security/MetaDataAccessControlIT.java
…t the column CONGLOMERATENAME
> DB-8779 update the system view SYSCONGLOMERATEINSCHEMAS to project ou…(3.0)

- pom.xml
Make splicemachine the first repo to search for dependencies
> DB-8817 Reverse repo search order

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_Values_IT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_OneRow_IT.java
> DB-8140 do not flatten non-correlated subquery that returns at most o…(3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_Values_IT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_OneRow_IT.java
> DB-8140 do not flatten non-correlated subquery that returns at most o…(2.8)

- mem_sql/src/main/java/com/splicemachine/derby/impl/sql/NoOpBackupManager.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupManager.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
Code changes include:
- Fix null pointer exception
- Add validate_schema_backup
Please also review code changes on ee branch
> DB-8755: fix validate_table_backup

- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceDateFunctionsTest.java
Fixes failing tests in SpliceDateFunctionsTest.testTimeFormats.  Apparently there is no such thing as a Time with a time zone such as PDT or PST.  The presence of the DT (daylight time) or ST (standard time) implies a DateTime value.  So, when we build a time such as "12 o'clock PM, Pacific Daylight Time", to insert into the database, for example, the only way we can construct it is to associate it with a DateTime, which is always the current system DateTime.  For this example, If the current system DateTime uses daylight savings in the Pacific time zone, then the time will be in PDT.  If the current system DateTime uses standard time in the Pacific time zone, then the time will be in PST. 
Due to all this, we can't compare a PDT or PST Time against a UTC Time, because the results will …
> DB-8856 Make testTimeFormats not dependent on system timezone.

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/sqlgrammar.jj
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/TableConstantOperationIT.java
Make TEXT a non-reserved key word
> DB-8791: Support column named TEXT

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/RequiredRowOrdering.java
- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/SortCostController.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OrderByList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OrderByNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/TempSortController.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/JoinOrderIT.java
Please see [DB-8144](https://splicemachine.atlassian.net/browse/DB-8144?focusedCommentId=63580&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-63580) for detailed explanations.
> DB-8144 properly deduct sort cost from plan cost during join planning

- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java
…nversion" for ranger authorization
> DB-7517 introduce a parameter "splice.ranger.usersync.username.caseco…(2.7)

- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java
…nversion" for ranger authorization
> DB-7517 introduce a parameter "splice.ranger.usersync.username.caseco…(2.8)

- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java
…nversion" for ranger authorization
> DB-7517 introduce a parameter "splice.ranger.usersync.username.caseco…(3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/execute/ExecRow.java
- db-engine/src/main/java/com/splicemachine/db/iapi/stats/StatsBoundaryDataValueDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/DataValueDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/HBaseRowLocation.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/ListDataType.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLArray.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLBinary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLBoolean.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLChar.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLDate.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLDecimal.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLDouble.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLInteger.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLLongint.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLReal.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLRef.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLRowId.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLSmallint.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLTime.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLTimestamp.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLTinyint.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/UserType.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/XML.java
- db-engine/src/main/java/com/splicemachine/db/impl/store/access/conglomerate/GenericConglomerate.java
Back out API changes that break upgrade
> DB-8888: upgrade form 2.8 to 3.0

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropAliasConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/CreateAliasIT.java
> DB-8854 clear the corresponding nameTdCache entry after drop synonym/…(2.8)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/DropAliasConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/CreateAliasIT.java
> DB-8854 clear the corresponding nameTdCache entry after drop synonym/…(3.0)

- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TableScanOperationIT.java
This PR is for testing ^= operator (DB-8931) on different data types.
> DB-8957 Not Equals Operators ^= Verification

- hbase_storage/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionUtil.java
This problem is specific to 3.0. Please see details in [DB-8867](https://splicemachine.atlassian.net/browse/DB-8867?focusedCommentId=63679&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-63679).
> DB-8867 fix wrong casting in trace info to avoid NoElementException

- assembly/hdp2.6.3/src/main/resources/common-services/SPLICEMACHINE/2.5.1/service_advisor.py
- db-tools-ij/src/main/grammar/ij.jj
The fix was in ij, so no testcase / ITs were added. Testing steps were in [DB-8118](https://splicemachine.atlassian.net/browse/DB-8118)
> DB-8118 SYNONYM tables don't show "describe" information correctly

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorToString.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictSparkExpressionIT.java
…f function in native spark execution
> DB-9026 Map subtraction expression of two date type values to datedif…(3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorToString.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictSparkExpressionIT.java
…f function in native spark execution
> DB-9026 Map subtraction expression of two date type values to datedif…(2.8)

- hbase_sql/src/main/java/com/splicemachine/olap/OlapServerMaster.java
Logic stays the same for non kerberized clusters, for kerberized clusters we recover the old logic (two different users, one to interact with Yarn and another to submit the Spark app)
> DB-8915 Fix Kerberos on Olap Server

- splice_access_api/src/main/java/com/splicemachine/access/configuration/SQLConfiguration.java
- splice_encoding/src/main/java/com/splicemachine/utils/kryo/ExternalizableSerializer.java
- splice_machine/src/main/java/com/splicemachine/SpliceKryoRegistry.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/IndexRowReader.java
- splice_machine/src/main/java/com/splicemachine/derby/serialization/ActivationSerializer.java
- splice_machine/src/main/java/com/splicemachine/derby/serialization/SpliceObserverInstructions.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlOperationContext.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/NLJoinFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iterator/GetNLJoinAntiIterator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iterator/GetNLJoinInnerIterator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iterator/GetNLJoinIterator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iterator/GetNLJoinLeftOuterIterator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iterator/GetNLJoinOneRowIterator.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/kryo/DataValueDescriptorSerializer.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/kryo/ListDataTypeSerializer.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/kryo/SimpleObjectSerializer.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ProjectionPruningIT.java
- start-splice-cluster
@msirek noticed this wasn't merged in branch-2.8
> DB-8214 Improve OperationContext cloning and perform it in parallel (2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/UserDefinedAggregator.java
- splice_machine/src/main/java/com/splicemachine/tools/StringConcat.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceUDTIT.java
It seems we are not serializing these objects to disk, so I wasn't able to test the upgrade logic. If you can come up with an scenario where we'd store them on disk let me know.
> DB-9068 Use Java serialization for user defined aggregates

- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/UserDefinedAggregator.java
- splice_machine/src/main/java/com/splicemachine/tools/StringConcat.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceUDTIT.java
Kryo won't have the classes registered and would fail
> DB-9068 Use Java serialization for user defined aggregates (2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/UserDefinedAggregator.java
- splice_machine/src/main/java/com/splicemachine/tools/StringConcat.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceUDTIT.java
Kryo won't have the classes registered and would fail
> DB-9068 Use Java serialization for user defined aggregates (3.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/MaxMinAggregator.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
> DB-8976 ignore nulls when updating the accumulated value for minmax w…(2.8)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/MaxMinAggregator.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
> DB-8976 ignore nulls when updating the accumulated value for minmax w…(3.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/MaxMinAggregator.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
> DB-8976 ignore nulls when updating the accumulated value for minmax w…(2.7)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/NestedLoopLeftOuterJoinOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/IndexRowToBaseRowOperationIT.java
> DB-9134 Add implementation of getRightEmptyRow() for nestedloop left …(2.8)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/NestedLoopLeftOuterJoinOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/IndexRowToBaseRowOperationIT.java
> DB-9134 Add implementation of getRightEmptyRow() for nestedloop left …(3.0)

- db-client/src/main/java/com/splicemachine/db/client/am/SQLExceptionFactory40.java
- db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/MessageId.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/test/java/com/splicemachine/hbase/KillOperationIT.java
- splice_machine/src/main/java/com/splicemachine/pipeline/ErrorState.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdmin_OperationsIT.java
- splice_machine/src/test/java/com/splicemachine/jdbc/JdbcApiIT.java
> DB-9098 Raise SQLTimeoutException on query cancellation

- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SplitRegionRowCountOperationIT.java
- pom.xml
- remote_it/pom.xml
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceNetConnection.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_Join_IT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_OneRow_IT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Table_IT.java
Running ITs against a remote database:
mvn -Pit -Dsplice.jdbc.host=srv132 verify
mvn -Pit,ee -Dsplice.jdbc.url="jdbc:splice://jdbc-oleg-eks-test3.eks.splicemachine-dev.io:1527/splicedb;ssl=basic" verify
> DB-9133 Run Splice Machine DB ITs on K8s Cloud Cluster

- splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/load/HdfsImportIT.java
> DB-8114: allow both double-quoted and unquoted column name in import column list

- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
> DB-7619: do not backup schema with no tables

- db-client/src/main/java/com/splicemachine/db/client/am/PreparedStatement.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/ConcatableDataValue.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLBinary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLChar.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/StringDataValue.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CharTypeCompiler.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TernaryFunctionForBitDataIT.java
DB-9179 allow char for bit data for locate
DB-9179 allow implicit String to bytes conversion at client
> DB-9179 support cast from char to char for bit data(2.8)

- db-client/src/main/java/com/splicemachine/db/client/am/PreparedStatement.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/ConcatableDataValue.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLBinary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/SQLChar.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/StringDataValue.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CharTypeCompiler.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TernaryOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TernaryFunctionForBitDataIT.java
DB-9179 allow char for bit data for locate
DB-9179 allow implicit String to bytes conversion at client
> DB-9179 support cast from char to char for bit data(3.0)

- hbase_sql/pom.xml
- hbase_sql/src/test/java/com/splicemachine/olap/OlapClientTest.java
- remote_it/pom.xml
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SparkExplainIT.java
See also a PR for spliceengine-ee
> Port IT fixes to branch-3.0

- pipelines/spot-bugs/Jenkinsfile
Opening the PR's for the other branches, I realized the logic shell logic doesn't execute and it just trims "HEAD". Switched over to groovy logic. Though it doesn't have any effect on master, it's just to match the other branchs' Jenkinsfile.
> DB-9162 Switch to groovy logic

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorToString.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SparkStringPadOperator.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/JoinOperationCharJoinPredicateIT.java
> DB-9198 pad fixed length char columns of different length when they a…(2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorToString.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SparkStringPadOperator.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/JoinOperationCharJoinPredicateIT.java
> DB-9198 pad fixed length char columns of different length when they a…(3.0)

- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/OperationManagerImpl.java
> DB-9326 java.util.UUID.randomUUID() creates thread contention

- pipelines/spot-bugs/Jenkinsfile
Fix checking out of spliceengine-ee branches to fix failing spotbugs jenkins job
> Fix wrong spliceengine-ee checkout

- pipelines/spot-bugs/Jenkinsfile
Fix checking out of spliceengine-ee branches to fix failing spotbugs jenkins job
> Fix wrong spliceengine-ee checkout (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
> DB-9259 Fix spotbugs errors in DataDictionaryImpl.java (2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
> DB-9259 Fix spotbugs errors in DataDictionaryImpl.java (3.0)

- hbase_storage/src/main/java/com/splicemachine/storage/ClientPartition.java
- pom.xml
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
> DB-9323 SpliceAdminIT fails with NPE (3.0)

- hbase_storage/src/main/java/com/splicemachine/storage/ClientPartition.java
- pom.xml
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
Reworking deprecated APIs makes the test stable.
Also added _-DskipUT_ flag to skip unit tests.
> DB-9323 SpliceAdminIT fails with NPE

- hbase_storage/hbase1.1.1/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/hbase1.1.2.2.5/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/hbase1.1.2.2.6-129/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/hbase1.1.2.2.6/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/hbase1.1.8/src/main/java/com/splicemachine/storage/ClientPartition.java
- hbase_storage/hbase1.2.0/src/main/java/com/splicemachine/storage/ClientPartition.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/callbuffer/PipingCallBuffer.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/writehandler/PartitionWriteHandler.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/writehandler/RoutingWriteHandler.java
> SPLICE-1806 NullPointerException in the PipingCallBuffer (2.8)

- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceMasterObserver.java
- hbase_sql/src/main/java/com/splicemachine/lifecycle/MasterLifecycle.java
- platform_it/pom.xml
- platform_it/src/main/resources/hadoop-metrics2-hbase.properties
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
Make sure we create ZK structure before trying to access it
Some other small memory usage reductions on metrics
> DB-9386 Increase heap size for standalone 

- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceMasterObserver.java
- hbase_sql/src/main/java/com/splicemachine/lifecycle/MasterLifecycle.java
- platform_it/pom.xml
- platform_it/src/main/resources/hadoop-metrics2-hbase.properties
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
Make sure we create ZK structure before trying to access it
> DB-9386 Increase heap size for standalone  (3.0)

- db-engine/pom.xml
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/CrossJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/CrossJoinIT.java
> DB-9401 avoid costing control execution path in the presence of cross…(2.8)

- db-engine/pom.xml
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/CrossJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/CrossJoinIT.java
> DB-9401 avoid costing control execution path in the presence of cross…(3.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
field executed removed as nowhere used
> DB-9156 startTime, badRecords, returnedRows added to reset()

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/AccessPath.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/AccessPathImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromVTI.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/GroupByNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/LastIndexKeyOperationIT.java
…ible only for the control execution
> DB-9457 Consider SpecialMaxScan during costing stage and make it elig…(3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/AccessPath.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/AccessPathImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromVTI.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/GroupByNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/LastIndexKeyOperationIT.java
…ible only for the control execution
> DB-9457 Consider SpecialMaxScan during costing stage and make it elig…(2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
> DB-9388 write complete update row when updating the sys.sysstatements…(3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
> DB-9388 write complete update row when updating the sys.sysstatements…(2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/execute/RunningOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SessionPropertyIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/LastIndexKeyOperationIT.java
DB-9447 Relable Control->OLTP, Spark->OLAP in explain and get_running_operations
DB-9447 fix spotbugs
> DB-9447 Relabel Engine in EXPLAIN plans

- pom.xml
Fixes `mvn clean install -Pcore,cdh6.3.0`
> DB-9537 Reorder standalone module

- hbase_sql/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/MemstoreAwareObserver.java
- hbase_sql/src/main/java/com/splicemachine/olap/AsyncOlapNIOLayer.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/DummyScanner.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/SIObserver.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/AbstractSICompactionScanner.java
Fix compaction leaks
OlapFutures get their own timer thread now
> DB-9397 Fix resource leaks after IT run

- hbase_sql/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/MemstoreAwareObserver.java
- hbase_sql/src/main/java/com/splicemachine/olap/AsyncOlapNIOLayer.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/DummyScanner.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/SIObserver.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/AbstractSICompactionScanner.java
Fix compaction leaks
OlapFutures get their own timer thread now
> DB-9397 Fix resource leaks after IT run (3.0)

- hbase_sql/src/main/java/com/splicemachine/olap/AsyncOlapNIOLayer.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/AbstractSICompactionScanner.java
Fix compaction leaks
OlapFutures get their own timer thread now
> DB-9397 Fix resource leaks after IT run (2.8)

- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SparkExplainIT.java
…ntly for different spark versions.
> DB-9648 Make SparkExplainIT.testMixtureOfOuterJoins() behave consiste…(3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/SessionProperties.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/SessionPropertiesImpl.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/BroadcastJoinMemoryLimitIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicatePushToUnionIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicateTransitiveClosureIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
… broadcast join memory limit check if hinted
DB-9601 introduce session property
> DB-9601 apply TC on predicates pushed from outside view/dt, also skip…(2.8)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/SessionProperties.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ColumnReference.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/SessionPropertiesImpl.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/BroadcastJoinMemoryLimitIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicatePushToUnionIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicateTransitiveClosureIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
… broadcast join memory limit check if hinted
DB-9601 introduce session property
> DB-9601 apply TC on predicates pushed from outside view/dt, also skip…(3.0)

- hbase_sql/src/main/java/com/splicemachine/olap/OlapServerMaster.java
- hbase_sql/src/main/java/com/splicemachine/olap/OlapServerSubmitter.java
- splice_protocol/src/main/protobuf/Olap.proto
Restart OlapServer if software version changed
> DB-9665 Clear ZNode for OlapServer app watcher

- hbase_sql/src/main/java/com/splicemachine/olap/OlapServerMaster.java
- hbase_sql/src/main/java/com/splicemachine/olap/OlapServerSubmitter.java
- splice_protocol/src/main/protobuf/Olap.proto
Restart OlapServer if software version changed
> DB-9665 Clear ZNode for OlapServer app watcher (3.0)

- assembly/hdp3.1.0/src/main/resources/common-services/SPLICEMACHINE/2.5.1/package/scripts/params.py
Fix for  `Configuration parameter 'stack_version' was not found in configurations dictionary!`
> DB-9730 HDP API change for params.py

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/SessionProperties.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InsertNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/SessionPropertiesImpl.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/IndexConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SessionPropertyIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
Note that useOLAP is *added*. useSpark=X still works.
> DB-9572 add useOLAP=X as query and session config/hint

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/SessionProperties.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/TransactionResourceImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InsertNode.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SessionPropertyIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
Note that useOLAP is added. useSpark=X still works.
> DB-9572 add useOLAP=X as query and session config/hint (3.0)

- hbase_storage/src/main/java/com/splicemachine/storage/HPut.java
- hbase_storage/src/main/java/com/splicemachine/storage/RLServer.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/callbuffer/PartitionBuffer.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/callbuffer/ServerCallBuffer.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/client/BulkWrite.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/writehandler/RoutingWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/pipeline/IndexWriteHandler.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactor.java
Fix itself is in this commit: https://github.com/splicemachine/spliceengine/pull/3763/commits/a2cbe66c21a35388838d486d49dd88e033e75e28
> DB-9789 Fix RoutingWriteHandler error handling

- hbase_sql/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/SIObserver.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionState.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionStateMutate.java
- hbase_storage/src/main/java/com/splicemachine/storage/ClientPartition.java
> Debug dictionary(3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/SessionProperties.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/SessionPropertiesImpl.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- hbase_sql/src/main/java/com/splicemachine/derby/impl/SpliceSpark.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/stream/QueryJob.java
- hbase_sql/src/main/java/com/splicemachine/stream/RemoteQueryClientImpl.java
- hbase_sql/src/main/java/com/splicemachine/stream/RemoteQueryJob.java
- hbase_sql/src/main/java/com/splicemachine/stream/StreamableRDD.java
Same PR as https://github.com/splicemachine/spliceengine/pull/3668 with @jyuanca's fix for NSDS
Thanks @yxia92 and @jyuanca !
> DB-8190 DB-9604 Make Spark fetch and shuffle partitions configurable 

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/OrderByEliminationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/JoinSelectionIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/FlattenedOuterJoinIT.java
…sing outer join condition to eliminate order by columns.
> DB-9669 avoid pushing outer join condition to left table, and avoid u…(2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/compile/OrderByEliminationIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/JoinSelectionIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/FlattenedOuterJoinIT.java
…sing outer join condition to eliminate order by columns.
> DB-9669 avoid pushing outer join condition to left table, and avoid u…(3.0)

- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_When_Clause_IT.java
> DB-9870 fix intermittent IT failure in Trigger_When_Clause_IT. testSi…(3.0)

- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/CreateTableTypeHelper.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
also DB-7348 truncate CHAR/VARCHAR from external tables
> DB-9682 SELECT on external table needs to check number of columns returned

- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/CreateTableTypeHelper.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
also DB-7348 truncate CHAR/VARCHAR from external tables
> DB-9682 SELECT on external table needs to check number of columns returned (2.8)

- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/CreateTableTypeHelper.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
also DB-7348 truncate CHAR/VARCHAR from external tables
> DB-9682 SELECT on external table needs to check number of columns returned (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSCOLUMNSRowFactory.java
- db-tools-ij/src/main/grammar/ij.jj
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ShowCreateTableIT.java
> DB-9807 use info in tabledescriptor to colllect the ddl info for "sho…(3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/SYSCOLUMNSRowFactory.java
- db-tools-ij/src/main/grammar/ij.jj
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ShowCreateTableIT.java
> DB-9807 use info in tabledescriptor to colllect the ddl info for "sho… (2.8)

- hbase_sql/src/main/java/com/splicemachine/hbase/BackupEndpointObserver.java
- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
Please also review code changes on ee branch
> DB-9989: fix the logic to tell whether a backup is cancelled

- hbase_sql/hbase1.1.1/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.13/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2.2.5/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2.2.6-129/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.2.2.6/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.1.8/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/hbase1.2.0/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactorBase.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/AbstractSICompactionScanner.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionState.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionStateMutate.java
- hbase_storage/src/test/java/com/splicemachine/si/impl/server/SICompactionStateMutateTest.java
- hbase_storage/src/test/java/com/splicemachine/si/impl/server/SITestUtils.java
This is a rewrite of PR #3994 targeting different HBase versions.
> DB-9554 check for cancellation requests during long-running compactions (2.8).

- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/SessionPropertyIT.java
> DB-10054 Disable jump mode test in SessionPropertyIT.TestTableLimitForExhaustiveSearchSessionProperty

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/LeadLagFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowDefinitionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowReferenceNode.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkWindow.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/AvgAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/CountAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/FirstLastValueFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/LeadLagFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/MaxMinAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/SpliceGenericWindowFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/SumAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/window/BaseFrameBuffer.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/window/PhysicalGroupFrameBuffer.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionWithFrameIT.java
> DB-8049 handle begin or end rows for window function properly

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/LeadLagFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowDefinitionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowReferenceNode.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkWindow.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/AvgAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/CountAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/FirstLastValueFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/LeadLagFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/MaxMinAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/SpliceGenericWindowFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/SumAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/window/BaseFrameBuffer.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/window/PhysicalGroupFrameBuffer.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionWithFrameIT.java
> DB-8049 handle begin or end rows for window function properly (2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/LeadLagFunctionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowDefinitionNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/WindowReferenceNode.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkWindow.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/AvgAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/CountAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/FirstLastValueFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/LeadLagFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/MaxMinAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/SpliceGenericWindowFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/window/function/SumAggregator.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/window/BaseFrameBuffer.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/window/PhysicalGroupFrameBuffer.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/WindowFunctionWithFrameIT.java
> DB-8049 handle begin or end rows for window function properly (3.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/CachedOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/AnyOperationIT.java
- splice_machine/src/test/test-data/test_data/AnyOperationIT.sql
> DB-10245 set current row in CachedOperation for scenarios where rowco…(3.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/CachedOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/AnyOperationIT.java
- splice_machine/src/test/test-data/test_data/AnyOperationIT.sql
> DB-10245 set current row in CachedOperation for scenarios where rowco…(2.8)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsOperation.java
Reverts splicemachine/spliceengine#4111
> Revert "DB-10231 better CSV format support in external tables"

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsOperation.java
Reverts splicemachine/spliceengine#4121
> Revert "DB-10231 better CSV format support in external tables (2.8)"

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkScanSetBuilder.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/DataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ForwardingDataSetProcessor.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/StatisticsOperation.java
Reverts splicemachine/spliceengine#4120
> Revert "DB-10231 better CSV format support in external tables (3.0)"

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/FlattenedOuterJoinIT.java
…outer join to where clause when checking for unssatisfiable block
> DB-10018 skip outer join conditions that are released from flattened …(2.8)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/FlattenedOuterJoinIT.java
…outer join to where clause when checking for unssatisfiable block
> DB-10018 skip outer join conditions that are released from flattened …(3.0)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSet.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSet.java
consisting of changes DB-9770 (fix) and DB-10267 (speed improvement)
> DB-9770/DB-10267 Fix External Table Row Counts after cross-join insert

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/AlterTableConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/TruncateTableIT.java
> DB-10351 fix columnOrdering array for unique index when truncating a …(3.0)

- splice_machine/src/main/java/com/splicemachine/derby/stream/function/FileFunction.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/function/StreamFileFunction.java
Should I be checking for _null_ anywhere in the dereferencing chain?
> DB-8896 fix ‘no current connection’ exception

- hbase_sql/pom.xml
- hbase_storage/pom.xml
- pom.xml
- splice_aws/pom.xml
Reverts splicemachine/spliceengine#4225
> Revert "DB-10068 NSDS: Update with DateType column throws class not found exception - Spark 3.0 only"

- db-tools-ij/src/main/grammar/ij.jj
- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/ijCommands.java
- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/ijResultSetResult.java
- db-tools-ij/src/main/java/com/splicemachine/db/impl/tools/ij/utilMain.java
- db-tools-ij/src/main/java/com/splicemachine/db/tools/JDBCDisplayUtil.java
check commit 1 for functional change,
commit 2 is refactoring
> DB-10373 sqlshell buildin commands adhere to maximumdisplaywidth

- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceMasterObserver.java
- hbase_storage/src/main/java/com/splicemachine/timestamp/hbase/HBaseTimestampHostProvider.java
- hbase_storage/src/main/java/com/splicemachine/timestamp/hbase/ZkTimestampSource.java
- splice_access_api/src/main/java/com/splicemachine/access/api/SConfiguration.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/ConfigurationBuilder.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SConfigurationImpl.java
- splice_access_api/src/main/java/com/splicemachine/access/configuration/SIConfigurations.java
- splice_protocol/src/main/protobuf/Timestamp.proto
- splice_timestamp_api/pom.xml
- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/BatchedTimestampClient.java
- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/ClientCallback.java
- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampBaseHandler.java
- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampClient.java
- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampConnection.java
- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampOracle.java
- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampPipelineFactoryLite.java
- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampQueue.java
- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampServer.java
- splice_timestamp_api/src/main/java/com/splicemachine/timestamp/impl/TimestampServerHandler.java
- splice_timestamp_api/src/test/java/com/splicemachine/timestamp/impl/TimestampClientTest.java
DB-7371 Port Timestamp Client/Server to Netty 4
> DB-9330 Add option for batched newTimestamp RPCs (3.0)

- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ShowCreateTableIT.java
> DB-10460 fix default value for bit data type in show_create_table sta…(3.0)

- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
fixes failed test com.splicemachine.derby.impl.sql.execute.actions.TempTableIT#testSystemProceduresOnTempTable
> DB-10506 fix SET_PURGE_DELETED_ROWS using unset minRetentionPeriod

- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
fixes failed test com.splicemachine.derby.impl.sql.execute.actions.TempTableIT#testSystemProceduresOnTempTable
> DB-10506 fix SET_PURGE_DELETED_ROWS using unset minRetentionPeriod (3.0)

- pipeline_api/src/main/java/com/splicemachine/pipeline/config/BaseWriteConfiguration.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/config/CountingWriteConfiguration.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/config/SharedWriteConfiguration.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/config/UpdatingWriteConfiguration.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/constraint/ConstraintContext.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/contextfactory/ListWriteFactoryGroup.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/contextfactory/LocalWriteContextFactory.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/contextfactory/SetWriteFactoryGroup.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/contextfactory/WriteFactoryGroup.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/traffic/SynchronousWriteControl.java
- pipeline_api/src/main/java/com/splicemachine/pipeline/writehandler/RoutingWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateConstraintConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/pipeline/DerbyContextFactoryLoader.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/FKWriteFactoryHolder.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyChildInterceptWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyParentInterceptWriteFactory.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyParentInterceptWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyViolationProcessor.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/actions/ActionFactory.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/actions/OnDeleteAbstractAction.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/actions/OnDeleteNoAction.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/actions/OnDeleteSetNullOrCascade.java
- splice_machine/src/main/java/com/splicemachine/protobuf/ProtoUtil.java
- splice_machine/src/test/java/com/splicemachine/foreignkeys/ForeignKeyActionIT.java
- splice_machine/src/test/java/com/splicemachine/foreignkeys/ForeignKeyAlterDropTableIT.java
- splice_protocol/src/main/protobuf/DDL.proto
This PR un-reverts the original DB-9010 PR with a fix for write-write conflict exception parsing.
> DB-9010 implement FK ON DELETE CASCADE

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/LastIndexKeyOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ScanOperation.java
fixes a problems caused by DB-10328 -> DB-10253 -> REVERT DB-10328
> DB-10544 fix missing serialization items in LastIndexKeyOperation / ScanOperation

- .github/CODEOWNERS
- pipelines/spot-bugs/Jenkinsfile
Update Jenkinsfile and codeowners for branch-3.1
> Update Jenkinsfile for 3.1

- pipelines/spot-bugs/Jenkinsfile
Updated spotbugs for branch-3.1.
> Update pipeline (3.1)

- hbase_storage/src/main/java/com/splicemachine/hbase/ZkUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/btree/IndexConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/ConglomerateUtils.java
> DB-10448: improve restore performance(3.1)

- hbase_storage/src/main/java/com/splicemachine/hbase/ZkUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/btree/IndexConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/ConglomerateUtils.java
> DB-10448: improve restore performance(3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/types/DataTypeDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/TypeId.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryComparisonOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ComparisonForBitDataIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TernaryFunctionForBitDataIT.java
> DB-10527 support for the comparison between bit data type and regular…(3.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/types/DataTypeDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/types/TypeId.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryComparisonOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ComparisonForBitDataIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TernaryFunctionForBitDataIT.java
> DB-10527 support for the comparison between bit data type and regular…(3.0)

- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SelectTimeTravelIT.java
The test is written incorrectly, it was using a lower-precision `TIMESTAMP` (from `SpliceDateTimeFormatter.defaultTimestampFormatString = "yyyy-MM-dd HH:mm:ss"`) causing time travel algorithm to return incorrect results when `INSERT` transactions share the same sub-second time.
To solve this problem, we now use the server time (`values current_timestamp`) with a high enough precision to probe the time travel results.
> DB-10620 fix sporadically-failing SelectTimeTravelIT

- hbase_sql/src/main/java/com/splicemachine/hbase/ReplicationUtils.java
- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceCompactionUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/index/IndexTransformer.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/CheckTableJob.java
- splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/DataDictionaryUtils.java
- splice_machine/src/main/java/com/splicemachine/pipeline/DerbyContextFactoryLoader.java
Reverts splicemachine/spliceengine#4350
> Revert "DB-10562 Refactor SpliceTransactionResourceImpl.getMarshallTransaction "

- hbase_sql/src/main/java/com/splicemachine/compactions/SpliceDefaultCompactor.java
- hbase_sql/src/main/java/com/splicemachine/hbase/ReplicationUtils.java
- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceCompactionUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/CheckTableJob.java
- splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/DataDictionaryUtils.java
- splice_machine/src/main/java/com/splicemachine/pipeline/DerbyContextFactoryLoader.java
Reverts splicemachine/spliceengine#4351
> Revert "DB-10562 Refactor SpliceTransactionResourceImpl.getMarshallTransaction (3.0)"

- hbase_sql/src/main/java/com/splicemachine/hbase/ReplicationUtils.java
- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceCompactionUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/index/IndexTransformer.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/storage/CheckTableJob.java
- splice_machine/src/main/java/com/splicemachine/derby/jdbc/SpliceTransactionResourceImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/DataDictionaryUtils.java
- splice_machine/src/main/java/com/splicemachine/pipeline/DerbyContextFactoryLoader.java
Reverts splicemachine/spliceengine#4352
> Revert "DB-10562 Refactor SpliceTransactionResourceImpl.getMarshallTransaction (3.1)"

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Table_IT.java
… generation phase as code generation for the same tree could happen twice
> DB-10686 do not remove inlist condition after being processed in code…(3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Table_IT.java
… generation phase as code generation for the same tree could happen twice
> DB-10686 do not remove inlist condition after being processed in code…(3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DDLStatementNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/FromFinalTableIT.java
Adds support for aliases/synonyms in FROM FINAL TABLE queries.
> DB-10525 Support aliases in FROM FINAL TABLE clause.

- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/SIObserver.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionState.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionStateMutate.java
- hbase_storage/src/main/java/com/splicemachine/storage/ClientPartition.java
Log WAL replay and compaction removals, run compactions on region server
DB-9827 Lower WAL replay logs to DEBUG level
> DB-9622 Add logging to ClientPartition for DataDictionary writes

- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/SIObserver.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionState.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/server/SICompactionStateMutate.java
- hbase_storage/src/main/java/com/splicemachine/storage/ClientPartition.java
Log WAL replay and compaction removals, run compactions on region server
DB-9827 Lower WAL replay logs to DEBUG level
> DB-9622 Add logging to ClientPartition for DataDictionary writes(3.1)

- hbase_sql/src/test/java/com/splicemachine/derby/utils/VacuumIT.java
- remote_it/pom.xml
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
Fixed dependencies, compilation, execution. Excluded new ITs not runnable in remote mode.
Running ITs against a cluster:
`mvn -Pit,ee -Dsplice.jdbc.url="jdbc:splice://<host>:1527/splicedb" clean verify`
> DB-10786 Remote ITs are broken 

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkExternalTableUtil.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableUnitTests.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- mem_storage/src/main/java/com/splicemachine/storage/MemFileSystem.java
- splice_access_api/src/main/java/com/splicemachine/access/api/FileInfo.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/StoreCostControllerImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/ResultHelper.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/DistributedGetSchemaExternalJob.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/GetSchemaExternalResult.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdmin_OperationsIT.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/TestingFileSystem.java
DB-10455 add LIST_DIRECTORY function
DB-10922 adding SYS_UTILS.ANALYZE_EXTERNAL_TABLE
e.g. 
`call SYSCS_UTIL.LIST_DIRECTORY('/tmp');`
and
`call SYSCS_UTIL.ANALYZE_EXTERNAL_TABLE('.... spliceengine/splice_machine/src/test/test-data/parquet_sample_one')`
> DB-10455 add LIST_DIRECTORY and ANALYZE_EXTERNAL_TABLE

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkExternalTableUtil.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableUnitTests.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- mem_storage/src/main/java/com/splicemachine/storage/MemFileSystem.java
- splice_access_api/src/main/java/com/splicemachine/access/api/FileInfo.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/StoreCostControllerImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/ResultHelper.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/DistributedGetSchemaExternalJob.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/GetSchemaExternalResult.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdmin_OperationsIT.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/TestingFileSystem.java
DB-10455 add LIST_DIRECTORY function
DB-10922 adding SYS_UTILS.ANALYZE_EXTERNAL_TABLE
e.g. 
`call SYSCS_UTIL.LIST_DIRECTORY('/tmp');`
and
`call SYSCS_UTIL.ANALYZE_EXTERNAL_TABLE('.... spliceengine/splice_machine/src/test/test-data/parquet_sample_one')`
> DB-10455 add LIST_DIRECTORY and ANALYZE_EXTERNAL_TABLE (3.1)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkExternalTableUtil.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableUnitTests.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- mem_storage/src/main/java/com/splicemachine/storage/MemFileSystem.java
- splice_access_api/src/main/java/com/splicemachine/access/api/FileInfo.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/StoreCostControllerImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/ResultHelper.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/DistributedGetSchemaExternalJob.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/GetSchemaExternalResult.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdmin_OperationsIT.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/TestingFileSystem.java
DB-10455 add LIST_DIRECTORY function
DB-10922 adding SYS_UTILS.ANALYZE_EXTERNAL_TABLE
e.g. 
`call SYSCS_UTIL.LIST_DIRECTORY('/tmp');`
and
`call SYSCS_UTIL.ANALYZE_EXTERNAL_TABLE('.... spliceengine/splice_machine/src/test/test-data/parquet_sample_one')`
> DB-10455 add LIST_DIRECTORY and ANALYZE_EXTERNAL_TABLE (3.0)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkDataSetProcessor.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/SparkExternalTableUtil.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableIT.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExternalTableUnitTests.java
- hbase_storage/src/main/java/com/splicemachine/storage/HNIOFileSystem.java
- mem_storage/src/main/java/com/splicemachine/storage/MemFileSystem.java
- splice_access_api/src/main/java/com/splicemachine/access/api/FileInfo.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/load/HdfsImport.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/CreateTableConstantOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/stats/StoreCostControllerImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/utils/ExternalTableUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/ResultHelper.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/DistributedGetSchemaExternalJob.java
- splice_machine/src/main/java/com/splicemachine/procedures/external/GetSchemaExternalResult.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdmin_OperationsIT.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/TestingFileSystem.java
DB-10455 add LIST_DIRECTORY function
DB-10922 adding SYS_UTILS.ANALYZE_EXTERNAL_TABLE
e.g. 
`call SYSCS_UTIL.LIST_DIRECTORY('/tmp');`
and
`call SYSCS_UTIL.ANALYZE_EXTERNAL_TABLE('.... spliceengine/splice_machine/src/test/test-data/parquet_sample_one')`
> DB-10455 add LIST_DIRECTORY and ANALYZE_EXTERNAL_TABLE (2.8)

- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceMasterObserver.java
- hbase_storage/src/main/java/com/splicemachine/access/hbase/HPartitionCreator.java
- platform_it/pom.xml
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
Reduce HMaster timeout for faster procedure execution
> DB-11075 Make standalone durable

- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceMasterObserver.java
- hbase_storage/src/main/java/com/splicemachine/access/hbase/HPartitionCreator.java
- platform_it/pom.xml
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
Reduce HMaster timeout for faster procedure execution
> DB-11075 Make standalone durable (3.1)

- hbase_sql/src/main/java/com/splicemachine/hbase/SpliceMasterObserver.java
- hbase_storage/src/main/java/com/splicemachine/access/hbase/HPartitionCreator.java
- platform_it/pom.xml
- platform_it/src/test/java/com/splicemachine/test/SpliceTestPlatformConfig.java
Reduce HMaster timeout for faster procedure execution
> DB-11075 Make standalone durable (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
This is to re-merge DB-10773, including DB-11084 which fixes a performance regression in query plans with hinted joins.
> DB-10773+DB-11084 Honor joinStrategy hints on the target table of an UPDATE (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
This is to re-merge DB-10773, including DB-11084 which fixes a performance regression in query plans with hinted joins.
> DB-10773+DB-11084 Honor joinStrategy hints on the target table of an UPDATE (3.1)

- splice_spark/src/main/spark3.0/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/TestContext.scala
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/column_case/TestContext.scala
- splice_spark/src/test/scala/com/splicemachine/spark/splicemachine/triggers/TestContext.scala
- splice_spark/src/test/spark2.1/com/splicemachine/spark/splicemachine/ThisVersionSpecificItems.scala
- splice_spark/src/test/spark2.2/com/splicemachine/spark/splicemachine/ThisVersionSpecificItems.scala
- splice_spark/src/test/spark2.3/com/splicemachine/spark/splicemachine/ThisVersionSpecificItems.scala
- splice_spark/src/test/spark2.4/com/splicemachine/spark/splicemachine/ThisVersionSpecificItems.scala
- splice_spark/src/test/spark3.0/com/splicemachine/spark/splicemachine/ThisVersionSpecificItems.scala
NSDS v1 updated.
NSDS v2 already had the right logic.
> DB-10336 NSDS Spark 3.0 Add Missing Logic

- db-drda/src/main/properties/metadata.properties
Tests exist in ForeignKeyMetadataIT.
> DB-10942 Hint getCrossReference and getImportedKeys metadata queries

- db-engine/src/main/java/com/splicemachine/db/catalog/types/RoutineAliasInfo.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/StaticMethodCallNode.java
- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
Reverts splicemachine/spliceengine#4418
> Revert "DB-9656 better error output for nonmatching parameters in CALL"

- utilities/pom.xml
Reverts splicemachine/spliceengine#4933
> Revert "DB-11031 Cleanup shading in utilities"

- utilities/pom.xml
Reverts splicemachine/spliceengine#4934
> Revert "DB-11031 Cleanup shading in utilities (3.1)"

- utilities/pom.xml
Reverts splicemachine/spliceengine#4935
> Revert "DB-11031 Cleanup shading in utilities (3.0)"

- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java
Before the fix, preserveLineEndings didn't use parallel readings in SpliceFileVTI. This is because we use another
code path which would not preserve line endings. This is correct, however If we have oneLineRecords, it doesn't make sense to preserve line endings, since we don't read the line endings into the data (for this, we would need multiline-line varchars). So the case oneLineRecords we can set preserveLineEndings to false, which then allows parallel reads in this case.
So, simple solution is to set preserveLineEndings to false if we have oneLineRecords (in Code).
Workaround for customer is to do this manually with global options.
This is a performance improvement, see https://splicemachine.atlassian.net/browse/DB-11412 .
> DB-11412 disable preserveLineEndings if oneLineRecords is set

- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java
Before the fix, preserveLineEndings didn't use parallel readings in SpliceFileVTI. This is because we use another
code path which would not preserve line endings. This is correct, however If we have oneLineRecords, it doesn't make sense to preserve line endings, since we don't read the line endings into the data (for this, we would need multiline-line varchars). So the case oneLineRecords we can set preserveLineEndings to false, which then allows parallel reads in this case.
So, simple solution is to set preserveLineEndings to false if we have oneLineRecords (in Code).
Workaround for customer is to do this manually with global options.
This is a performance improvement, see https://splicemachine.atlassian.net/browse/DB-11412 .
> DB-11412 disable preserveLineEndings if oneLineRecords is set (3.0)

- splice_machine/src/main/java/com/splicemachine/derby/vti/SpliceFileVTI.java
Before the fix, preserveLineEndings didn't use parallel readings in SpliceFileVTI. This is because we use another
code path which would not preserve line endings. This is correct, however If we have oneLineRecords, it doesn't make sense to preserve line endings, since we don't read the line endings into the data (for this, we would need multiline-line varchars). So the case oneLineRecords we can set preserveLineEndings to false, which then allows parallel reads in this case.
So, simple solution is to set preserveLineEndings to false if we have oneLineRecords (in Code).
Workaround for customer is to do this manually with global options.
This is a performance improvement, see https://splicemachine.atlassian.net/browse/DB-11412 .
> DB-11412 disable preserveLineEndings if oneLineRecords is set (3.1)

- db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAStatement.java
- db-engine/src/main/java/com/splicemachine/db/catalog/SystemProcedures.java
- db-engine/src/main/java/com/splicemachine/db/iapi/error/PublicAPI.java
- db-engine/src/main/java/com/splicemachine/db/iapi/error/StandardException.java
- db-engine/src/main/java/com/splicemachine/db/iapi/services/context/ContextManager.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/StatementPermission.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchRefresher.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/NormalizeOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
Under some circumstances, the Server Connection gets in an erroneous state, and the connection to the client is dropped. Symptoms are one of the following:
When executing a query through sqlshell (or other JDBC shells):
- `ERROR 08006: Insufficient data while reading from the network - expected a minimum of 6 bytes and received only 0 bytes.  The connection has been terminated.`
- `ERROR 08006: A network protocol error was encountered and the connection has been terminated: the requested command encountered an unarchitected and implementation-specific condition for which there was no architected message (additional information may be available in the derby.log file on the server)`
- `ERROR 08003: DERBY SQL error: SQLCODE: -1, SQLSTATE: 08003, SQLERRMC: No current connection.`
This fix …
> DB-10382 fix exception paths (2.8)

- hbase_sql/src/main/java/com/splicemachine/ddl/ZooKeeperDDLWatchChecker.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/AsynchronousDDLWatcher.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchChecker.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchRefresher.java
> DB-11133: persist DDL demarcation point to zookeeper(3.1)

- hbase_sql/src/main/java/com/splicemachine/ddl/ZooKeeperDDLWatchChecker.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/AsynchronousDDLWatcher.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchChecker.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchRefresher.java
> DB-11133: persist DDL demarcation point to zookeeper(3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/types/ProtobufUtils.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/AvgAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/DecimalBufferedSumAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/DoubleBufferedSumAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/LongBufferedSumAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/MaxMinAggregator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/SumAggregator.java
- db-engine/src/main/protobuf/Derby.proto
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/DB2VarcharCompatibilityIT.java
> DB-11636: fix avg aggregator regression(3.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/SessionProperties.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/SessionPropertiesImpl.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/BroadcastJoinIT.java
> DB-11641 Only disable NLJ on Spark if it enables no index access (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeStoredObjects.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/ConglomerateUtils.java
>  DB-11644: improve dictionary serialization upgrade(3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeStoredObjects.java
Fix an upgrade failure from 3.1.0.2004 to 3.2.0.2004.
3.1.0.2004 should have run a script to upgrade data diction serialization. When it is being upgraded to 3.2.0.2004, master server tries to run the script again. The script tried to read the data dictionary objects in old format and immediately fails.
Upgrade post 3.1.0.2003 database to post 3.2.0.2003
> DB-11676: skip serialization upgrade if it's done on a lower release

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/SessionProperties.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromBaseTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/SessionPropertiesImpl.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/IndexPrefixIterationIT.java
- splice_machine/src/test/test-data/subquery/IndexPrefixIterationTestTables.sql
Port DB-11675 to the optimizer branch
> DB-11675 Fix NPE in IndexLookup: SPLICE-2399 regression

- hbase_sql/src/main/java/com/splicemachine/olap/OlapServerMaster.java
Corrects the calculation of maxExecutorCores on cloud clusters.
On Kubernetes, rmClient is null in OlapServerMaster, so we cannot find the number of nodes from that source.  Also, there is no YARN, so the max memory allocation: yarn.scheduler.maximum-allocation-mb is not set.  
The fix is to derive the number of "nodes" from the number of spark executor instances because cloud uses one instance per pod.  Also, use spark.kubernetes.executor.request.memory as the memory size as Kubernetes tries to honor this value.
Create a large table on a cloud cluster and select from it using the hint --splice-properties splits=24
or a higher number of splits.
The explain should show a parallelTasks value of 24.
> DB-11052 Correct calulation of MaxExecutorCores on cloud clusters

- db-engine/src/main/java/com/splicemachine/db/iapi/ast/ISpliceVisitor.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Visitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/AggregateVectorCleaner.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/RepeatedPredicateVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/ast/SpliceDerbyVisitorAdapter.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/GroupedAggregateOperationIT.java
> DB-11613 Fix NPE in aggregate queries with repeated predicates (3.1)

- db-client/src/main/java/com/splicemachine/db/client/net/CodePoint.java
- db-client/src/main/java/com/splicemachine/db/client/net/NetConnection.java
- db-client/src/main/java/com/splicemachine/db/client/net/NetConnectionReply.java
- db-client/src/main/java/com/splicemachine/db/client/net/NetConnectionRequest.java
- db-drda/src/main/java/com/splicemachine/db/impl/drda/CodePoint.java
- db-drda/src/main/java/com/splicemachine/db/impl/drda/DRDAConnThread.java
- db-drda/src/main/java/com/splicemachine/db/impl/drda/Database.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedConnection.java
> DB-11046 SSO: DRDA PLGINOVR implementation; username is taken from token

- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/TransactionController.java
- db-engine/src/main/java/com/splicemachine/db/impl/db/BasicDatabase.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_access_api/src/main/java/com/splicemachine/access/api/PartitionAdmin.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeConglomerateTable.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeStoredObjects.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeUtils.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/PropertyConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/SpliceTransactionManager.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/ConglomerateUtils.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceCatalogUpgradeScriptsTest.java
> DB-11684: recover from data dictionary serialization upgrade failure(3.1)

- assembly/pom.xml
> DB-11815 Add JWT jars to common dependencies to enable deployment (3.1)

- assembly/pom.xml
> DB-11815 Add JWT jars to common dependencies to enable deployment (3.0)

- platforms/hbck/README.md
Short Description
Add README.md document only
Long Description
Add a small readme with how to build and some quick usage. Doesn't need a pipeline in this branch, so it's only a documentation update.
How to test
N/A
> DB-11739 Add hbck README.md (3.1)

- platforms/hbck/README.md
Short Description
Add README.md document only
Long Description
Add a small readme with how to build and some quick usage. Doesn't need a pipeline in this branch, so it's only a documentation update.
How to test
N/A
> DB-11739 Add hbck README.md (3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/services/io/DataInputUtil.java
> DB-11818: fix table/schema backup stats backward compatibility(3.1)

- db-shared/src/main/java/com/splicemachine/db/shared/common/reference/SQLState.java
- db-tools-i18n/src/main/resources/com/splicemachine/db/loc/messages.xml
- splice_machine/src/main/java/com/splicemachine/backup/BackupManager.java
- splice_machine/src/main/java/com/splicemachine/backup/BackupSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_protocol/src/main/protobuf/Backup.proto
> DB-11690: backup metadata(3.1)

- splice_machine/src/test/java/com/splicemachine/benchmark/FeatureStoreBenchmark.java
- splice_machine/src/test/java/com/splicemachine/benchmark/TriggerBenchmark.java
- splice_machine/src/test/java/com/splicemachine/test/Benchmark.java
> DB-11809 Implement Feature Store benchmark

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptForTriggerMultipleStatements.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeScriptForTriggerWhenClause.java
Refactor upgrade code to add and populate new columns to system tables
This is an extract of code from DB-10193 that I'd like to make available before DB-10193 is merged.
> DB-11891 Refactor upgrade scripts to add and populate new columns

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CreateIndexNode.java
- hbase_sql/src/test/java/com/splicemachine/hbase/CheckTableIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/actions/index/IndexIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DefaultIndexIT.java
See https://github.com/splicemachine/spliceengine/pull/5392
> DB-11224 Don't set exclude null/default flags of an index when they have no effect (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/procedures/StatisticsProcedures.java
ddl notifications are partitioned during COLLECT_SCHEMA_STATISTICS. Previously, a large list of table descriptor ids was sent in one call. 
When COLLECT_SCHEMA_STATISTICS analyzes a big schema with many tables, it could cause a DDL coordination timeout. The problem happens when the massage with ddlChangeType: ALTER_STATS has many table descriptor ids. To avoid this issue, the new method ddlNotificationInPartitions splits the list of table descriptors into smaller partitions with the size given in partitionSize.
Create a schema with big amount of tables, some thousands, and call  COLLECT_SCHEMA_STATISTICS. It's also possible to decrease the environment variable splice.ddl.maxWaitSeconds to have a higher probability to get a timeout.
> DB-10494 DDL coordination timed out when analyze schema with many tables

- hbase_sql/src/main/java/com/splicemachine/ddl/ZooKeeperDDLWatchChecker.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/AsynchronousDDLController.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchRefresher.java
> DB-11985 Improve ZK DDL Refresh logging (3.1)

- hbase_sql/src/main/java/com/splicemachine/ddl/ZooKeeperDDLWatchChecker.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/AsynchronousDDLController.java
- splice_machine/src/main/java/com/splicemachine/derby/ddl/DDLWatchRefresher.java
> DB-11985 Improve ZK DDL Refresh logging (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/BaseDataDictionary.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/FailuresSparkIT.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/RollbackTxnFilter.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/SIFilterPacked.java
- hbase_storage/src/main/java/com/splicemachine/storage/RangedClientPartition.java
- hbase_storage/src/main/java/com/splicemachine/storage/RegionPartition.java
- hbase_storage/src/main/java/com/splicemachine/storage/SkeletonHBaseClientPartition.java
- hbase_storage/src/test/java/com/splicemachine/si/impl/SynchronousReadResolverTest.java
- mem_storage/src/main/java/com/splicemachine/si/impl/TxnPartition.java
- mem_storage/src/main/java/com/splicemachine/storage/MPartition.java
- mem_storage/src/test/java/com/splicemachine/si/MemSITestEnv.java
- splice_access_api/src/main/java/com/splicemachine/storage/Partition.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyChildInterceptWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/actions/OnDeleteAbstractAction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/WriteWriteRollbackIT.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnFilter.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/TxnRegion.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/server/ConflictRollForward.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactor.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/store/CompletedTxnCacheSupplier.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/txn/SITransactionReadController.java
- splice_si_api/src/test/java/com/splicemachine/si/SITransactorTest.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/SimpleTxnFilterTest.java
> DB-11534: Filter out rolled back txn during WW-conflict detection(3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/BaseDataDictionary.java
- hbase_sql/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/FailuresSparkIT.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/RollbackTxnFilter.java
- hbase_storage/src/main/java/com/splicemachine/si/impl/SIFilterPacked.java
- hbase_storage/src/main/java/com/splicemachine/storage/RangedClientPartition.java
- hbase_storage/src/main/java/com/splicemachine/storage/RegionPartition.java
- hbase_storage/src/main/java/com/splicemachine/storage/SkeletonHBaseClientPartition.java
- hbase_storage/src/test/java/com/splicemachine/si/impl/SynchronousReadResolverTest.java
- mem_storage/src/main/java/com/splicemachine/si/impl/TxnPartition.java
- mem_storage/src/main/java/com/splicemachine/storage/MPartition.java
- mem_storage/src/test/java/com/splicemachine/si/MemSITestEnv.java
- splice_access_api/src/main/java/com/splicemachine/storage/Partition.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/ForeignKeyChildInterceptWriteHandler.java
- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/actions/OnDeleteAbstractAction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/actions/WriteWriteRollbackIT.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/SimpleTxnFilter.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/TxnRegion.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/server/ConflictRollForward.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactor.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/txn/SITransactionReadController.java
- splice_si_api/src/test/java/com/splicemachine/si/SITransactorTest.java
- splice_si_api/src/test/java/com/splicemachine/si/impl/SimpleTxnFilterTest.java
> DB-11534: Filter out rolled back txn during WW-conflict detection(3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/DataDictionary.java
- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/ScanController.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/TabInfoImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/sequence/SpliceSequence.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceScan.java
> DB-11856: upgrade SPLICE_SEQUENCE table(3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/costing/v1/V1ScanCostEstimator.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/costing/v2/V2ScanCostEstimator.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/IndexLookupCostEstimationIT.java
This change fixes unfair comparison between PK access path and index access path when estimated rows to be scanned is zero.
The problem is a combination of two:
- gf.gf#='ccce30bb-530c-11ea-a885-005056b28b7b' gives 0 rows according to statistics
- PK access goes to estimateOneRowCost() without calculating scan selectivity
In the end, the cost of index access path using XPK_INCL_DUP_GFLL is estimated using 0 rows, while the cost of primary key access path is estimated using 1 row. For this reason, PK access path has higher cost.
The fix is to use 1 row to estimate scan cost in generateCost() when estimated row count is smaller than 1. Important thing is that we use 1 row only in estimating cost, but not really overwriting 1 row in all cases. Specifically, raw row count is critical in …
> DB-11979 Use one row to estimate scan cost when row count is zero

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/execute/ResultSetFactory.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/SpliceGenericResultSetFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperationIT.java
> DB-11764 TOSCA rich client test - query complexity (3.1)

- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
> DB-12075: null check for namespace(3.1)

- hbase_sql/src/main/java/com/splicemachine/hbase/BackupUtils.java
> DB-12075: null check for namespace(3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/db/InternalDatabase.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/conn/LanguageConnectionContext.java
- db-engine/src/main/java/com/splicemachine/db/iapi/store/access/TransactionController.java
- db-engine/src/main/java/com/splicemachine/db/impl/db/BasicDatabase.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BaseJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/NativeSparkDataSet.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/SimpleCostEstimate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/BroadcastJoinOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DMLWriteOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/BaseSpliceTransaction.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/HBaseStore.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/SpliceInternalTransactionManager.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/SpliceTransactionFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/SpliceTransactionManager.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/control/ControlDataSetWriter.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/FromFinalTableIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SparkExplainIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/CrossJoinIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/FullOuterJoinIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Referencing_Clause_IT.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/BaseTransaction.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/Transaction.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/TransactionImpl.java
Backport the following Jiras required by DB-11580:
DB-11865 Enable native spark broadcast join with non-equijoin predicates
DB-10579 Use truly nested transactions for triggers.
> DB-11865 + DB-10579 backport (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/IndexPrefixIterationIT.java
- splice_machine/src/test/test-data/subquery/IndexPrefixIterationTestTables.sql
See https://github.com/splicemachine/spliceengine/pull/5471.
> DB-12064 Fix NPE in code generation for index prefix iteration mode (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/IndexPrefixIterationIT.java
- splice_machine/src/test/test-data/subquery/IndexPrefixIterationTestTables.sql
See https://github.com/splicemachine/spliceengine/pull/5471.
> DB-12064 Fix NPE in code generation for index prefix iteration mode (optimizer)

- db-client/src/main/java/com/splicemachine/db/jdbc/ClientDriver.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceNetConnection.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
- splice_machine/src/test/java/com/splicemachine/derby/transactions/TransactionAdminIT.java
Support a connection property autoCommit
> DB-11566: support jdbc url property autoCommit

- db-client/src/main/java/com/splicemachine/db/jdbc/ClientDriver.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceNetConnection.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceWatcher.java
- splice_machine/src/test/java/com/splicemachine/derby/transactions/TransactionAdminIT.java
> DB-11566: support jdbc url property autoCommit(3.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/services/property/PropertyUtil.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- hbase_sql/src/main/java/com/splicemachine/derby/impl/sql/ZkPropertyManager.java
- mem_sql/src/main/java/com/splicemachine/derby/impl/sql/DirectPropertyManager.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/PropertyManager.java
- splice_machine/src/main/java/com/splicemachine/derby/iapi/sql/PropertyManagerService.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/SpliceService.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/PropertyConglomerate.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdminIT.java
> DB-11966: set selectivityEstimationIncludingSkewedDefault for all servers(3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DMLStatementNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNodeList.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- pom.xml
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/NullPredicateIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicateSimplificationIT.java
Reverts splicemachine/spliceengine#5474
> Revert "DB-12077 Evaluate null constant restriction to false during execution "

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/OptimizablePredicate.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/Optimizer.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FullOuterJoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HalfOuterJoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/IntersectOrExceptNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OptimizerImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/TableOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnionNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/MergeSortJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/OuterJoinIT.java
Reverts splicemachine/spliceengine#5481
> Revert "DB-11523 sort merge join infeasible for correlated subq. join condition"

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/compile/CompilerContext.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/CompilerContextImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/DMLStatementNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/JoinNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SelectNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueNodeList.java
- db-shared/src/main/java/com/splicemachine/db/iapi/reference/Property.java
- pom.xml
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/NullPredicateIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicateSimplificationIT.java
Restoring https://github.com/splicemachine/spliceengine/pull/5474 after reverting.
> DB-12077 Evaluate null constant restriction to false during execution

- splice_machine/src/test/java/com/splicemachine/benchmark/FeatureStoreBenchmark.java
- splice_machine/src/test/java/com/splicemachine/benchmark/FeatureStoreTriggerBenchmark.java
- splice_machine/src/test/java/com/splicemachine/test/Benchmark.java
This is a micro-benchmark for measuring Feature Store trigger update performance.
The micro-benchmark is based on SQL scripts provided in JIRA. Two modes of updates are implemented: batched updates from a staging table, concurrent single updates from multiple connections. 
Two approaches in how updates are applied and propagated:
- insert into the history table triggers update of the feature table
- insert/update of the feature table triggers insert into the history table
> DB-12032 a micro-benchmark for Feature Store trigger updates

- hbase_sql/src/main/java/com/splicemachine/stream/RemoteQueryClientImpl.java
- hbase_sql/src/main/java/com/splicemachine/stream/StreamListener.java
- mem_sql/src/main/java/com/splicemachine/derby/impl/sql/ControlOnlyDataSetProcessorFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/RemoteQueryClient.java
See https://github.com/splicemachine/spliceengine/pull/5493.
> DB-10980 Wait for real exception when an OLAP job fails (3.1)

- hbase_sql/src/main/java/com/splicemachine/stream/RemoteQueryClientImpl.java
- hbase_sql/src/main/java/com/splicemachine/stream/StreamListener.java
- mem_sql/src/main/java/com/splicemachine/derby/impl/sql/ControlOnlyDataSetProcessorFactory.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/SpliceBaseOperation.java
- splice_machine/src/main/java/com/splicemachine/derby/stream/iapi/RemoteQueryClient.java
See https://github.com/splicemachine/spliceengine/pull/5493.
> DB-10980 Wait for real exception when an OLAP job fails (3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/IndexRowGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RelationalOperator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryComparisonOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/HashableJoinIT.java
> DB-12085 Fix isQualifier() for index conglomerates (3.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/IndexRowGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RelationalOperator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryComparisonOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/HashableJoinIT.java
> DB-12085 Fix isQualifier() for index conglomerates (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ParseException.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ParserImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Token.java
- findbugs-exclude-filter.xml
- hbase_sql/src/test/java/com/splicemachine/derby/utils/SqlshellIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropTableIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropViewIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/TruncateFunctionIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
improve error messages with more detailed description what's wrong with the SQL
SQL with errors:
```
CREATE TABLE MY_TABLE (
L_ORDERKEY BIGINT NOT NULL,
L_PARTKEY INTEGER NOT DECIMAL,
L_SUPPKEY INTEGER NOT NULL,
L_LINENUMBER INTEGER NOT NULL,
L_QUANTITY DECIMAL(15,2),
L_EXTENDEDPRICE DECIMAL(15,2),
L_DISCOUNT DECIMAL(15,2)
);
```
Error Message before
```
ERROR 42X01: Syntax error: Encountered "DECIMAL" at line 3, column 23.
```
New Error Message
```
ERROR 42X01: Syntax error: Encountered "DECIMAL" at line 3, column 23.
Was expecting:
    "null" ...
    
1: CREATE TABLE MY_TABLE (
2: L_ORDERKEY BIGINT NOT NULL,
3: L_PARTKEY INTEGER NOT DECIMAL,
                         ^^^^^^^---------
4: L_SUPPKEY INTEGER NOT NULL,
5: L_LINENUMBER INTEGER NOT NULL,
6:L_QUANTITY DECIMAL(15,2),
```
> DB-12097 better SQL errors

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/IndexRowGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RelationalOperator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryComparisonOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/HashableJoinIT.java
Reverts splicemachine/spliceengine#5506
> Revert "DB-12085 Fix isQualifier() for index conglomerates (3.1)"

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/IndexRowGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RelationalOperator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryComparisonOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/HashableJoinIT.java
Reverts splicemachine/spliceengine#5507
> Revert "DB-12085 Fix isQualifier() for index conglomerates (3.0)"

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/IndexRowGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RelationalOperator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryComparisonOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/HashableJoinIT.java
> DB-12085 Redo Fix isQualifier() for index conglomerates (3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/IndexRowGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RelationalOperator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryComparisonOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/HashableJoinIT.java
> DB-12085 Redo Fix isQualifier() for index conglomerates (3.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/IndexRowGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/OperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/Predicate.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/PredicateList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/RelationalOperator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryComparisonOperatorNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/HashableJoinIT.java
> DB-12085 Fix isQualifier() for index conglomerates

- db-engine/src/main/java/com/splicemachine/db/catalog/types/IndexDescriptorImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/IndexExpressionBindingVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/actions/index/IndexIT.java
See https://github.com/splicemachine/spliceengine/pull/5535.
> DB-12140 Fix index on expressions logic for UnaryDateTimestampOperatorNode (3.0)

- db-engine/src/main/java/com/splicemachine/db/catalog/types/IndexDescriptorImpl.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/IndexExpressionBindingVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ScanCostFunction.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/actions/index/IndexIT.java
See https://github.com/splicemachine/spliceengine/pull/5535.
> DB-12140 Fix index on expressions logic for UnaryDateTimestampOperatorNode (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceDataDictionary.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeUtils.java
> DB-12116: batch write to SPLICE_CONGLOMERATE_SI during upgrade(3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeUtils.java
> DB-12116: batch write to SPLICE_CONGLOMERATE_SI during upgrade(3.0)

- splice_machine/src/test/java/com/splicemachine/benchmark/FeatureStoreBenchmark.java
A different variant of FeatureStoreBenchmark queries was proposed to ensure more parallelism in multi-table PK lookups. This PR adds that variant to the benchmark.  
In a table with 10 columns, select columns c2, c4, c6, c8, c10, with 100 columns: c20, c40, c60, c80, c100 and with 1000: c200, c400, c600, c800, c1000.
```
SELECT max(t1_c2), ... max(t2_c20), ... max(t3_c200), ... FROM (
SELECT T1.c1 t1_c1, ... cast(NULL as int) t2_c20, ..., cast(NULL as int) t3_c200, ... FROM T1 WHERE (T1.<primaryKey>, ...) = (<random value>, ...)
UNION ALL
SELECT cast(NULL as int) t1_c1, ... T2.c20 t2_c20, ... cast(NULL as int) t3_c200, ... FROM T2 WHERE (T2.<primaryKey>, ...) = (<random value>, ...)
... )
```
Run FeatureStoreBenchmark as an integration test either in standalone or cluster environment.
> DB-11809 FeatureStoreBenchmark: implemented queries based on UNION

- hbase_sql/src/test/java/com/splicemachine/hbase/CheckTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceTableAdmin.java
> DB-12130: quote schema and table names for check_table(3.0)

- hbase_sql/src/test/java/com/splicemachine/hbase/CheckTableIT.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceTableAdmin.java
> DB-12130: quote schema and table names for check_table(3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/TriggerExecutionContext.java
- splice_machine/src/main/java/com/splicemachine/derby/catalog/TriggerNewTransitionRows.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/NestedLoopJoinStrategy.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/TriggerRowHolderImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/TriggerHandler.java
- splice_machine/src/test/java/com/splicemachine/triggers/Trigger_Referencing_Clause_IT.java
> DB-12109 Favor NLJ for PK joins with the trigger VTI (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ShowCreateTableIT.java
> DB-12159: generate constraints in a deterministic order(3.0)

- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/ShowCreateTableIT.java
> DB-12159: generate constraints in a deterministic order(3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SQLWarningIT.java
See https://github.com/splicemachine/spliceengine/pull/5574.
> DB-11106 Defer executing code that could cause a warning in ProjectRestrictOperation (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/ProjectRestrictOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SQLWarningIT.java
See https://github.com/splicemachine/spliceengine/pull/5574.
> DB-11106 Defer executing code that could cause a warning in ProjectRestrictOperation (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryListOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumnList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueTupleNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ValueTupleIT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_InList_IT.java
See https://github.com/splicemachine/spliceengine/pull/5589.
> DB-11420 DB-10555 Fix multi-column IN subquery issues (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryListOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumnList.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/SubqueryNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ValueTupleNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ValueTupleIT.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_InList_IT.java
See https://github.com/splicemachine/spliceengine/pull/5589.
> DB-11420 DB-10555 Fix multi-column IN subquery issues (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/actions/index/IndexIT.java
See https://github.com/splicemachine/spliceengine/pull/5579.
> DB-10800 Make hashable joins infeasible for non-covering IoEs (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/HashableJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/actions/index/IndexIT.java
See https://github.com/splicemachine/spliceengine/pull/5579.
> DB-10800 Make hashable joins infeasible for non-covering IoEs (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ExplainNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/GroupByNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
See https://github.com/splicemachine/spliceengine/pull/5593.
> DB-10439 Improve no stats report from explain statement (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ExplainNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromTable.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/GroupByNode.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/ExplainPlanIT.java
See https://github.com/splicemachine/spliceengine/pull/5593.
> DB-10439 Improve no stats report from explain statement (3.0)

- db-engine/src/main/java/com/splicemachine/db/iapi/types/NumberDataValue.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/GenericStatement.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryArithmeticOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/BinaryRelationalOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConcatenationOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConditionalNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ConstantNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NotNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/NumericConstantNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryArithmeticOperatorNode.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UntypedNullConstantNode.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/ConstantFoldingIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicateSimplificationIT.java
- splice_machine/src/test/java/com/splicemachine/db/impl/sql/compile/PredicateTransitiveClosureIT.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/MultiProbeTableScanOperatonIT.java
- splice_machine/src/test/java/com/splicemachine/derby/test/framework/SpliceUnitTest.java
- splice_machine/src/test/java/com/splicemachine/subquery/Subquery_Flattening_InList_IT.java
Contains DB-12051 and DB-12225
> DB-12051 & DB-12225 Constant folding

- db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/BroadcastJoinStrategy.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/BroadcastJoinIT.java
See https://github.com/splicemachine/spliceengine/pull/5610.
> DB-12057 Cost broadcast join for left outer join with no hash key (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/ast/JoinConditionVisitor.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ProjectRestrictNode.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/costing/v1/V1BroadcastJoinCostEstimation.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/compile/costing/v2/V2BroadcastJoinCostEstimation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/joins/BroadcastJoinIT.java
See https://github.com/splicemachine/spliceengine/pull/5610.
The commit for optimizer branch is an extended version of the commit on master because it needs to fix the same issue for v2 cost model, too.
> DB-12057 Cost broadcast join for left outer join with no hash key (optimizer)

- db-engine/src/main/java/com/splicemachine/db/iapi/db/InternalDatabase.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedConnection.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/AdapterPipelineEnvironment.java
- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HBasePipelineEnvironment.java
- hbase_storage/src/main/java/com/splicemachine/hbase/SessionsWatcherImpl.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/AdapterSIEnvironment.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HActiveSessionsTaskFactory.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HBaseSIEnvironment.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HGetActiveSessionsTask.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/SpliceRSRpcServices.java
- mem_pipeline/src/main/java/com/splicemachine/pipeline/MPipelineEnv.java
- mem_storage/src/main/java/com/splicemachine/si/MemSIEnvironment.java
- mem_storage/src/main/java/com/splicemachine/storage/MSessionsWatcherImpl.java
- splice_access_api/src/main/java/com/splicemachine/access/api/ActiveSessionsTaskFactory.java
- splice_access_api/src/main/java/com/splicemachine/access/api/GetActiveSessionsTask.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdmin_GetActiveSessionsIT.java
- splice_protocol/src/main/protobuf/Splice.proto
- splice_si_api/src/main/java/com/splicemachine/si/api/session/SessionsWatcher.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIDriver.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIEnvironment.java
See https://github.com/splicemachine/spliceengine/pull/5624.
> DB-12222 Track all active sessions (3.1)

- db-engine/src/main/java/com/splicemachine/db/iapi/db/InternalDatabase.java
- db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedConnection.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/AdapterPipelineEnvironment.java
- hbase_pipeline/src/main/java/com/splicemachine/derby/hbase/HBasePipelineEnvironment.java
- hbase_storage/src/main/java/com/splicemachine/hbase/SessionsWatcherImpl.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/AdapterSIEnvironment.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HActiveSessionsTaskFactory.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HBaseSIEnvironment.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/HGetActiveSessionsTask.java
- hbase_storage/src/main/java/com/splicemachine/si/data/hbase/coprocessor/SpliceRSRpcServices.java
- mem_pipeline/src/main/java/com/splicemachine/pipeline/MPipelineEnv.java
- mem_storage/src/main/java/com/splicemachine/si/MemSIEnvironment.java
- mem_storage/src/main/java/com/splicemachine/storage/MSessionsWatcherImpl.java
- splice_access_api/src/main/java/com/splicemachine/access/api/ActiveSessionsTaskFactory.java
- splice_access_api/src/main/java/com/splicemachine/access/api/GetActiveSessionsTask.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/db/SpliceDatabase.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceAdmin_GetActiveSessionsIT.java
- splice_protocol/src/main/protobuf/Splice.proto
- splice_si_api/src/main/java/com/splicemachine/si/api/session/SessionsWatcher.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIDriver.java
- splice_si_api/src/main/java/com/splicemachine/si/impl/driver/SIEnvironment.java
See https://github.com/splicemachine/spliceengine/pull/5624.
> DB-12222 Track all active sessions (3.0)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/FromList.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropColumnIT.java
[spliceengine master](https://github.com/splicemachine/spliceengine/pull/5648)
[spliceengine branch-3.1](https://github.com/splicemachine/spliceengine/pull/5649)
> DB-12305 Fix DB-9898 regression after using storage cols in ColRefs (3.1)

- hbase_sql/src/main/java/com/splicemachine/derby/stream/spark/KafkaReadFunction.java
> DB-12291: close consumer when reading from Kafka fails

- hbase_sql/src/main/java/com/splicemachine/mrio/api/hive/SMHiveRecordWriter.java
Close result set if insert operation went wrong
No particular tests to run on top of our usual integration tests.
[spliceengine master](https://github.com/splicemachine/spliceengine/pull/5636)
[spliceengine branch-3.0](https://github.com/splicemachine/spliceengine/pull/5637)
[spliceengine branch-3.1](https://github.com/splicemachine/spliceengine/pull/5638)
> DB-12131 Close result set in case of exception 

- hbase_sql/src/main/java/com/splicemachine/mrio/api/hive/SMHiveRecordWriter.java
[spliceengine master](https://github.com/splicemachine/spliceengine/pull/5636)
[spliceengine branch-3.0](https://github.com/splicemachine/spliceengine/pull/5637)
[spliceengine branch-3.1](https://github.com/splicemachine/spliceengine/pull/5638)
> DB-12131 Close result set in case of exception (3.0)

- hbase_sql/src/main/java/com/splicemachine/mrio/api/hive/SMHiveRecordWriter.java
[spliceengine master](https://github.com/splicemachine/spliceengine/pull/5636)
[spliceengine branch-3.0](https://github.com/splicemachine/spliceengine/pull/5637)
[spliceengine branch-3.1](https://github.com/splicemachine/spliceengine/pull/5638)
> DB-12131 Close result set in case of exception (3.1)

- db-engine/src/main/java/com/splicemachine/db/catalog/IndexDescriptor.java
- db-engine/src/main/java/com/splicemachine/db/catalog/types/IndexDescriptorImpl.java
- db-engine/src/main/java/com/splicemachine/db/iapi/sql/dictionary/IndexRowGenerator.java
- db-engine/src/main/java/com/splicemachine/db/impl/sql/catalog/DataDictionaryImpl.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/SpliceCatalogUpgradeScripts.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/upgrade/UpgradeFixIndexDescriptors.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/base/SpliceConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/btree/IndexConglomerate.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/store/access/hbase/HBaseConglomerate.java
- splice_machine/src/test/java/com/splicemachine/derby/utils/SpliceCatalogUpgradeScriptsTest.java
[spliceengine master](https://github.com/splicemachine/spliceengine/pull/5658)
[spliceengine branch-3.1](https://github.com/splicemachine/spliceengine/pull/5659)
> DB-12323 Fix upgrade regression introduced by DB-9898 (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/ModifyColumnConstantOperation.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/DropColumnIT.java
> DB-12306: fix a drop column regression - drop columns doesn't drop related trigger(3.1)

- hbase_sql/src/test/java/com/splicemachine/hbase/KillOperationIT.java
instead of waiting exactly one second, then check SYSCS_GET_RUNNING_OPERATIONS for the operation that was submitted, we now wait 100 x 200 ms and check, which should increase robustness against situations where the submission of the task takes a bit longer.
> DB-11551 make KillOperationIT more robust

- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
See https://github.com/splicemachine/spliceengine/pull/5639.
> DB-10594 Add a system procedure to clean up obsolete temp tables (3.1)

- db-engine/src/main/java/com/splicemachine/db/impl/sql/conn/GenericLanguageConnectionContext.java
- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/SpliceSystemProcedures.java
- splice_machine/src/main/java/com/splicemachine/derby/utils/SpliceAdmin.java
See https://github.com/splicemachine/spliceengine/pull/5639.
> DB-10594 Add a system procedure to clean up obsolete temp tables (3.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/ModifyColumnConstantOperation.java
See https://github.com/splicemachine/spliceengine/pull/5683.
> DB-12352 Fix auto view refreshing mode for view on top of view (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/actions/ModifyColumnConstantOperation.java
See https://github.com/splicemachine/spliceengine/pull/5683.
> DB-12352 Fix auto view refreshing mode for view on top of view (3.0)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/sequence/AbstractSequence.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/GeneratedColumnIT.java
See https://github.com/splicemachine/spliceengine/pull/5677.
> DB-8936 Fix potential gaps in sequence generation (3.1)

- splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/sequence/AbstractSequence.java
- splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/GeneratedColumnIT.java
Reverts splicemachine/spliceengine#5678
> Revert "DB-8936 Fix potential gaps in sequence generation (3.1)"

- splice_machine/src/main/java/com/splicemachine/pipeline/foreignkey/actions/OnDeleteAbstractAction.java
This PR attempts to fix a sporadic that might be caused by unboxing null value. Also, we add `SanityManager` checks to document preconditions in order to get a clear error message should the sporadic appear again.
> DB-11138 remove unused method parameter and use SanityManager checks.
